### ISSUE TITLE
Two missing fields from the ULP Status Window

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#101]
From Ticket #T013 - 2 - b
    Missing "Turn In Date" field.

From Ticket #T013 - 2 - f - iii
    Missing "Closed Date" field.

Both of these fields are currently in the database but are not displayed to the application. I thought we removed 2 text fields from the tab and when I looked up the old commits, it appears to be the 'EONumber' and 'DeptInState' combo-box. So as far as I can tell the placement of these fields were just overlooked.

**Comment by parkjohnston** [comment]
This is a interesting ticket, the text box for Closed Date does not exist in ANY DB or ANY system.  It is completely made up and has taken 1 hour to research.  It will be moved to a new ticket to talk about enhancement.

**Comment by parkjohnston** [comment]
Appears the issue is from the ULP case closed report...they dont have a date closed, so the report is not giving any value

**Comment by parkjohnston** [comment]
d770454a99b0f5ac90d3857f38f4ba257166f0b1 -- added turn in date, other field is not added
