### ISSUE TITLE
Missing Closed Date

### ISSUE THREAD

**Issue by parkjohnston** [CurrentlyNotSet/SERB#102]
This field is not missing, but is an addition that will need to be an enhancement so that they can properly run the requested ULP Bulk Case Close Report.  Right now the best that can be done to resolve the issue to disable the ULP Bulk Case Close Report

**Comment by altrdgenetics** [comment]
the date that the use for all of the close cases report is based off of the final board date. We checked the old emails and the code in the application. This was a misunderstanding of the user and a lack of Justin explaining to the user how it is supposed to work (justin provided the requirements for the bulk close).
