### ISSUE TITLE
ORG/CSC Number box

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#108]
SERB wants to have that functionality to rightclick on the number and type one in manually. This functionality currently exists and will verify the number. 

We attempted to explain that the function currently exists but have moved... apparently that was not good enough. They want it EXACTLY like they had in the old system even though it goes against the SOW about keeping all of the sections having the same style for easier transitioning.

**Comment by parkjohnston** [comment]
e91e6d7643f71ae7b2722d5c3e155cf1f5312e2f

**Comment by anthonyperk** [comment]
Functionality Confirmed
