### ISSUE TITLE
DB modification of Activity Table for MailLog

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#111]
Needs a BIT column added to the activity table for items that are docketed.

The MailLog only shows the items that are docketed in the old system based off of the date called "MailLogDate" in the old system. This needs to be added in so it only shows the items that are docketed. All associated SQL calls need to be modified to support this as well.

If the item was Docketed = TRUE
any other activity Entry = FALSE

**Comment by altrdgenetics** [comment]
new DB field for activity table 'mailLog'

**Comment by parkjohnston** [comment]
completed

**Comment by anthonyperk** [comment]
Confirmed
