### ISSUE TITLE
BUN search functionality different between REP and ULP

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#113]
NOTE: This might be coded correctly, this is just an observation that I noticed between the two:

ULP Section -> Status Tab -> BU Number textbox:
Process to bring up the search panel is not the same as REP (double left click in ULP Status Tab vs. doulbe left/double right click in REP Information Tab.  Single right click asks the user if they want to clear the selection).

**Comment by parkjohnston** [comment]
Clear data was wrong in ULP...removed

Updated REP to match ulp where a double right click brings up the window.
