### ISSUE TITLE
Modify auto-select for MED bios (FF vs Conciliator Panel)

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#118]
the auto selection for MED BIOS needs tweaked.  When generating the Fact Finder Panel or Conciliator Panel, the BIOS will load both Fact Finder AND Conciliators (if both FF and Concil tables are generated).  Please separate Fact Finders from Conciliators.

**Comment by altrdgenetics** [comment]
added

**Comment by anthonyperk** [comment]
Functionality Confirmed
