### ISSUE TITLE
Font sizing issues

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#12]
The tabs, recommendations, investigation reveals, and statement have the smaller text to them. Text sizing should match the change that happened to the Notes tab.

**Comment by parkjohnston** [comment]
Marked as enhancement as this is continued change from the initial application

**Comment by parkjohnston** [comment]
e44bc15374e971fcb527910785118315af02baf1

Resolved

**Comment by parkjohnston** [comment]
2 Hours
