### ISSUE TITLE
Report Button disabled on MED, REP, ULP

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#128]
MED, ULP, REP Tabs: After launching the app, Reports button is enabled for all sections.  If I switch between the MED, ULP, REP Tabs, the button remains active and usable.  If I switch to ORG, CSC, CMDS, or Hearings tab (and dont choose anything in those sections), then click back to REP, MED, or ULP, the Reports button becomes disabled/grayed out.  Reports button on ORG, CSC, CMDS, and Hearings tab always remain active.  No error thrown in CMD window.

Another example: if I switch from ULP to ORG, load an ORG, then switch back to ULP, the report button stays active.

**Comment by parkjohnston** [comment]
Found the issue to be the way that the buttons active state was handled
