### ISSUE TITLE
Case Search

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#13]
The main search box of case search is not loading information properly. 

ex. if I search "hon" for "Hon. Allen G. Perk" nothing shows up. Same goes for "Perk". 

If I do a single letter like "A" which is in "Parker A. Johnston" I am able to find a single case. But that does not seem to work with any other letters.

**Comment by parkjohnston** [comment]
Found the issue to be the handling of case sensitivity of the typed letters.  No results causes a null pointer to be returned.

**Comment by parkjohnston** [comment]
d13c661db431ccc5b71babb62c53127ea52d258c

Resolved
