### ISSUE TITLE
REP bookmark additions

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#143]
(T025)  Add the following bookmarks to REP section:

COUNTBALLOTSDATE
COUNTBALLOTSTIME
NONPROFESSIONAL_INCLUDED
LONGMEETDATE
CCREPAREA - Same functionality as DIRECCList
EXCLUDED - Exists already

**Comment by altrdgenetics** [comment]
added in the missing ones, also boarddate from ticket 25 exists in the system
