### ISSUE TITLE
Activity table resorting on its own

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#145]
In CMDS -> Activity Tab, the activity's will reorder themselves after an activity is double clicked on, and the activity detail panel is closed out.

Example: 2017-RED-02-0013 has 3 activities in it.  If you double click on the second activity, and then close out of the Activity Detail window, the first and second activity reorder themselves.  I am sure this is due to them having the same date and time stamp, could an additional order by ID as well help this?

**Comment by parkjohnston** [comment]
bingo! resolved.
