### ISSUE TITLE
CSC Letters addition

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#146]
CSC/Civitas need to have letters and letter generation functionality added

CSC: Annual Report - 60 Day notice.docx (Letter)
Annual Report - Past Due Notice.docx (Letter)
CSCReport.pdf (Quest)

**Comment by altrdgenetics** [comment]
Anthony added in the reports, I verified that the single letter works without issues. there was an issue about the template location due to full spelling of section vs. initials.
