### ISSUE TITLE
Directives and Misc REP documents functionality change

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#147]
REP Section: Directives and Misc Documents (From Parallel meeting):

The functionality for Directives and Misc documents will need to be changed.  Directives and Misc will need to 'skip' the letter generation panel and be generated without the ability to send the file to an outside party or add attachments.  They will NOT have a file linked to their history entry (the history entry will just state that specific file was generated).  Directives will be scanned into the system once signed by the board (that history entry WILL have a link to the signed copy)

**Comment by altrdgenetics** [comment]
as an update to this as of yesterday

- Directives & Misc
no generation window, no file link in the history

- memos
no generation window, DOES have a link in the history

**Comment by altrdgenetics** [comment]
finished this feature
