### ISSUE TITLE
Docketing to auto select person assigned to the case

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#149]
Docketing tab -> File Button -> Scan/Email/Media Filing Panel:

The "To:" field should auto populate to the person assigned to the case that is entered into the "Case Number(s):" field at the top of the panel.  If the file is to be docketed to multiple cases, choose the assigned person for the first case entered into the "Case Number(s):" field.

**Comment by parkjohnston** [comment]
Justin,
 
·         When an email is docketed, we are going to auto populate the TO drop down based on the LRS/Investigator/etc in each section for the person assigned per case.  Could you please provide use with the location in each section that we should use to populate this data?
In the ULP section, auto assign the TO: field to the Status > Investigator field. If Status > ALJ field is populated choose this instead. An email should be sent to the assigned ALJ only.
 
In the REP section, auto assign the TO: field to the Information > Current Owner field. If Board Status > Hearing Person Assigned field is populated choose this instead. An email should be sent to the assigned ALJ (Hearing Person) only.
 
In the MED section, the TO: would auto assign to Mary Laurent. There is not a field for who is assigned to the MED case. I thought we decided in a meeting to add this field to MED.  There is also not a field for assigning an ALJ in this section (which is not currently needed).
 
In the ORG section, the TO: field is pulling from who is assigned to work on ORG. No email sending needed.
In the CIVITAS section, the TO: field is pulling from who is assigned to work on ORG. No email sending needed.
 
In the CMDS section, auto assign the TO: field to the Case Information > ALJ field.  Also send an email to the assigned ALJ.
 
·         When an email is docketed we are going to send an email to the assigned person as well, should that just be to the user that is in the TO combo box? Would this be the same for all sections?
 
With these questions answered we can completed the docket system.
 
Thanks.
 
 
Anthony Perk
Network and Systems Engineer
XLNsystems
614-947-3607

**Comment by parkjohnston** [comment]
above email provides what Justin was initially asking for.

**Comment by altrdgenetics** [comment]
per the meeting today it was decided that the clerks office will have the extra step when initially creating the case they will have to manually assign a person to the case. Justin reitterated what we were going for with nothing being hard coded.  This is now a non-issue, they were just testing on a case without an assigned user.
