### ISSUE TITLE
Add "IN - " / "OUT - " to the activity entry of a docketed file

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#150]
Docketing to all sections -> Activity tab:

When docketing a file, the activity entry should have an "IN - " or "OUT - " at the beginning of the activity.  Possibly add a "IN - " / "OUT - " drop down in the Scan Filing/File Email/File Media panel indicating IN or OUT.

**Comment by parkjohnston** [comment]
IN OUT drop down when it is filed, not on a per line basis

**Comment by altrdgenetics** [comment]
that is correct
