### ISSUE TITLE
CMDS Advanced Case Search

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#152]
Jim - Needs the Appellant Rep and Appellee Rep added to CMDS advanced case search. They could search these parties in the old system so this is missing existing functionality. 

don't forget:
- DB table column additions
- gui table additions in search
- party table catches to update DB table.

**Comment by parkjohnston** [comment]
updated DB locally with new columns, need to have import tool updated and ran now
