### ISSUE TITLE
Admin panel "god mode"

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#161]
When looking at hte latest activity table entries the ORG/CSC entries are not formated correctly for the "caseNumber". it is using the other sections format and has 'null-ORG-null-####'

**Comment by parkjohnston** [comment]
What is the issue. Will need better detail than provided.

**Comment by parkjohnston** [comment]
May understand it now...read it several times

**Comment by parkjohnston** [comment]
new is CSC: ## or ORG: ## or full case number
