### ISSUE TITLE
Bargining unit auto populate on new certifications

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#176]
The current system auto populates the employer Number... and name????

not sure how it autopopulates name on a new BU but whatever. match existing functionality.

**Comment by parkjohnston** [comment]
over stated the problem on the ticket, breaks down to be much simpler.  They have to search for an employer number and then the data we know is populated.

**Comment by parkjohnston** [comment]
I also feel that this ticket is in need of a discussion, comparing new search with what they want. 

@altrdgenetics  lets chat about it
