### ISSUE TITLE
Change AddressBlock bookmark (again)

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#178]
Please change the bookmark to reflect the additions from the meeting

**Comment by altrdgenetics** [comment]
got it squared, hopefully this works


NAME:
[First Name][M][Last][, Suffix][, Prof Designation][, Job Title]
[Company Name]

ADDRESS BLOCK:
[Address 1]
[Address 2]
[Address 3]
[City][State][Zip]
