### ISSUE TITLE
CMDS Email type dropdown

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#183]
CMDS needs an additional type dropdown to reflect the sub type (similar to the new activity panel).  This CURRENTLY EXISTS in 2.0

**Comment by parkjohnston** [comment]
Why were these not caught in any alpha testing

**Comment by altrdgenetics** [comment]
does each attachment follow the same process as the CMDS add activity... that was the question

**Comment by altrdgenetics** [comment]
Found the answer... the answer is yes, it does follow the same path for each of the attachments as if it is an activity

XLNPBR: DialogEmailArchive.java

DialogEmailArchive.moreInformation(...) (ln:434)

It has the list of 'each letter' that we are o so familiar with.

**Comment by parkjohnston** [comment]
In process...redoing the tables based on type was posing an issue at first, but moved past that to parsing data to fit the larger overall set of questions...goal is wednesday night release

**Comment by parkjohnston** [comment]
Not properly pulling the right column, debugging this morning, was hard to do on a plane, easy fix

**Comment by parkjohnston** [comment]
found an issue with going between any section and then to CMDS.  Just the typical updating for single types of cases

**Comment by parkjohnston** [comment]
XLN server hit a wall while trying to test this...cant verify...will try again in the morning but app is taking 30-60 seconds to load anything

**Comment by parkjohnston** [comment]
Mirrored 2.0, but would like to see the process change for better UX, but they can ask for an enhancement.  Time to make them pay up for all these changes
