### ISSUE TITLE
(PT007) Case Log Report

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#191]
Ticket Text:

> The File > New Case Log is missing from the new system. This report lists all the MED, REP, and ULP Cases with a file date between a date range. Grouped by section.

**Comment by parkjohnston** [comment]
I need this report....

I can add the header link but don't do the report

**Comment by anthonyperk** [comment]
I will be creating the report

**Comment by parkjohnston** [comment]
Does this happen to be done? 

Dont want to release the button without the report

**Comment by anthonyperk** [comment]
No it is not, should be done tomorrow

On Feb 28, 2017, at 6:20 PM, Parker Johnston <notifications@github.com<mailto:notifications@github.com>> wrote:


Does this happen to be done?

Dont want to release the button without the report

-

**Comment by altrdgenetics** [comment]
I added in the link to the menu item that Parker put in to the system. However now the report fails to locate a subreport

**Comment by anthonyperk** [comment]
Report is added to the database, and the files are in the G:/SERB/Reporting/ALL folder.  Please enable the code for the next release.
