### ISSUE TITLE
(PT008) ORG docketing issues

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#195]
Please see the attached ticket

Slack Error messages from Licia

**Comment by parkjohnston** [comment]
[SMDS 3.0 PT008.pdf](https://github.com/CurrentlyNotSet/SERB/files/809134/SMDS.3.0.PT008.pdf)

**Comment by parkjohnston** [comment]
Fixed issues 1 and 2

**Comment by parkjohnston** [comment]
fixed the ORG name to be display only
