### ISSUE TITLE
(PT009) ORG/CSC Docketing window

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#196]
**This is a place holder till it is decided what we are going to do billing wise and functionality wise.**

In 2.0 they entered information on which org through a drop down list of the org names spelled out. Now in 3.0 they type in ORG#, to allow for multiple "case" docketing. This ticket also goes against the "it would be nice to see the name as well" request for an ORG NAME field that we just fixed in PT008. Need clarification from Allen as well as getting a straight answer from Justin about what is exactly to be done and what will be the outcome financially.

![image](https://cloud.githubusercontent.com/assets/24595073/23480853/6f5bf386-fe97-11e6-85fe-882b3960ed81.png)

![image](https://cloud.githubusercontent.com/assets/24595073/23480857/7343f39a-fe97-11e6-8f3f-ffef82c6e0c6.png)

![image](https://cloud.githubusercontent.com/assets/24595073/23480860/76292ca6-fe97-11e6-997a-e901c2f18ee9.png)

**Comment by altrdgenetics** [comment]
We talked to justin on a phone call... he understands out position and will get back to us on what they are going to want. 

This goes against the multicase filing and the unified panels. He said he was going to check on if they could add the ORG Number to outgoing/incoming documents to eliminate the need for name searching.

**Comment by parkjohnston** [comment]
any movement on this....

**Comment by altrdgenetics** [comment]
no movement... all questions are still outstanding at this point in time.

**Comment by altrdgenetics** [comment]
>XLN Team,
>
>Please proceed with programming to add an ORG/CSC name drop down. In both sections (email and >docketing) the users only docket to one specific ORG/CSC number at a time. This functionality was present >in the 2.0 application and needs to be available in the 3.0 application.
>
>Thank you,
>Justin Brown

**Comment by parkjohnston** [comment]
This is in process...should be ready for Wednesday release

**Comment by parkjohnston** [comment]
found a non handled exception before release was cut, have since resolved the issue.

**Comment by parkjohnston** [comment]
this is good to ship this evening

**Comment by parkjohnston** [comment]
Enhancement...2 hours total, required changes in Email, Scan and Media, plus had to be custom done for two sections
