### ISSUE TITLE
(PT010) - Name Bookmark change

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#198]
name and address block/ email signature block:

For users in CMDS and CSC, place "State Personnel Board of Review" between Job title and Address 1.

For Users in all other sections, place "State Employment Relations Board" between Job title and Address 1.

![image](https://cloud.githubusercontent.com/assets/24595073/23480875/81f63538-fe97-11e6-925d-cd13198cd164.png)

**Comment by altrdgenetics** [comment]
> Anthony,
 
Sorry if this was vague.
 
Yes this information would go in the signature line of the letter queue for outgoing emails.
 
Thank you,
 
Justin Brown

**Comment by altrdgenetics** [comment]
fixed this.... took 30min
