### ISSUE TITLE
(PT011) - Section Symbol not printing in some templates

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#199]
ULP Agenda -> Minute Summary:

The Minutes summary is not picking up the bookmark for the Section Symbol (§), it only displays a black diamond with a ?.  This could be happening with other templates.

![image](https://cloud.githubusercontent.com/assets/24595073/23480890/8d24895a-fe97-11e6-8b17-d1805bf63d00.png)

**Comment by altrdgenetics** [comment]
non issue... only a problem on outdated Office 2007. Below the minimum requirements for SOW

**Comment by anthonyperk** [comment]
Re-ran in Office 2016, issue still persists

![image](https://cloud.githubusercontent.com/assets/24595073/23553965/0c4b0952-fff1-11e6-836d-ce3bdd9fa20f.png)

**Comment by altrdgenetics** [comment]
issue must be with the UTF-8 that java uses and whatever Word2016 currently uses. The section Symbol for this report was actually hardcoded string in the system as part of a built out text. Manually adding the U code instead of the symbol itself solved the issue
