### ISSUE TITLE
(PT018) REP Agenda 'BLURB'

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#200]
**On The REP Agenda . BLURB template when populated the alignment is off for item 11. But when I look at the template it looks correct for this bookmark. Your assistance is appreciated. I also noticed that the “R” will fully show as I adjust the zoom. Using Board meeting date 3/9/17. The same issue occurs on many of the lines on the Long Agenda. The short agenda does not have the Recommendation listed so there are not any issues on it.**

![image](https://cloud.githubusercontent.com/assets/8847344/23480795/3c0c816c-fe97-11e6-8295-a94b5200e022.png)

**Comment by altrdgenetics** [comment]
Anthony has tested this on our W10 machine w/ Office 2016. We were not able to reproduce the issue. Justin only tested it on windows 7. This appears to be a template layout issue and not our responsibility, however we still do need to test it on the W7 machine

**Comment by altrdgenetics** [comment]
this is a template layout issue

**Comment by anthonyperk** [comment]
Due to spacing issues with A10 (#10) in the Blurb.docx template, the next item (#11) was misaligned.  This has been corrected in the file Blurb-FIXED.docx in the G:\SERB\Template\REP folder, but will not be live until signed off.

**Comment by anthonyperk** [comment]
Emailed Justin about the fix, renamed the old file to Blurb-OLD.docx
