### ISSUE TITLE
(PT013) - Advanced Search issue

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#202]
User attempted to search for party name (Sherri Fowler).  When the user types "Sherri", a whole list of names comes up.  When the user types "Sherri " with the space, not all Sherri's are shown.  There might be an issue with how the advanced search looks through the Rolodex

![image](https://cloud.githubusercontent.com/assets/24595073/23480920/a2239f08-fe97-11e6-8a5c-7d799748832c.png)

**Comment by altrdgenetics** [comment]
completed by adding a few more search options to the if statement match
