### ISSUE TITLE
(PT014) - Type dropdown lengthened

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#203]
Please make the Docketing Document Type Dropdown taller so that many more entries can be seen at once.  This will drastically speed up docketing for users.

![image](https://cloud.githubusercontent.com/assets/24595073/23480520/377d55e6-fe96-11e6-9719-14a2ddaef81e.png)

**Comment by parkjohnston** [comment]
changed to 10
