### ISSUE TITLE
(PT016) Tab Selections

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#204]
**When going from case to case under the Board Status Tab the current system (2.0) stays in the preceding tab. However, the new system (3.0) switches to the Activity Tab. I need it to stay in the tab I was under in the previous case.**

![image](https://cloud.githubusercontent.com/assets/8847344/23480823/50cf0296-fe97-11e6-9261-c4a914f32c2e.png)

Not sure who this actually came from but it is showing REP section in the screenshot attached to the panel, Seeing the distorted image my guess would be Angela.

**Comment by parkjohnston** [comment]
Why is this a bug?

**Comment by parkjohnston** [comment]
Will will be an enhancement at cost and will be a lot of work. 

This was 80+ builds later and is NOW an issue....not acceptable from there

**Comment by altrdgenetics** [comment]
Email recieved today

>Thank you for the list below…
>Please proceed with the enhancement for ticket 174. This can be completed after the migration is completed (Low Priority). I am awaiting the green light from Angela and the list for the enhancement for ticket 165.

**Comment by parkjohnston** [comment]
Do we have a billing number of hours, or should I put something together?

**Comment by altrdgenetics** [comment]
This is on hold till after go live, sounds like they want it. If it is going to be more than 2hrs of work will probably wanna tell them upfront the cost.

**Comment by parkjohnston** [comment]
would have to try this out on a single tab to get a number of hours...i see it being over 2 as it will be a lot of testing.

**Comment by parkjohnston** [comment]
This is starting on a branch for 3.1 release 

A milestone has been created and will remain open with no end date.  

All 3.1 items will be enhancements.  

3.0.# will be nightly builds pushed out as needed for bugs

**Comment by parkjohnston** [comment]
Will be doing a single section first (ULP) to determine time fro others to provide quote

**Comment by parkjohnston** [comment]
Total time is 2 hours (for all sections)

Continuing to work, but have evaluated the enhamcenet

**Comment by parkjohnston** [comment]
This is in beta....waiting for feedback from Justin on testing.
