### ISSUE TITLE
(PT020) - Report Due Date in ULP auto-populate

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#205]
The Report Due Date should automatically be populated for 5-months out when the File Date is completed by the Clerk’s Office

![image](https://cloud.githubusercontent.com/assets/24595073/23480620/9403c016-fe96-11e6-9994-51cad67c70c5.png)

![image](https://cloud.githubusercontent.com/assets/24595073/23480630/9750b508-fe96-11e6-9ca3-e19cc947bf2a.png)

**Comment by parkjohnston** [comment]
had to update this in new case creation and on text box change

**Comment by parkjohnston** [comment]
currently have this handling weekends, does that need to happen?

**Comment by anthonyperk** [comment]
Email justin, waiting on response

**Comment by anthonyperk** [comment]
From justin: 

If it falls on a weekend, thats fine.  As long as the user has the ability to change.  It is an addition of 5 months (do not worry about exact days, just add 5 to the moth number)

**Comment by parkjohnston** [comment]
Thanks, closing shortly
