### ISSUE TITLE
(PT012) - Renaming of file in Activity Entry (same as T028 #1 or Git #181)

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#207]
When user changes the Type in docketing, the activity does not reflect the change.  This is the same as T028-1 (Github #183)

![image](https://cloud.githubusercontent.com/assets/24595073/23481029/0e5f4d66-fe98-11e6-9e10-a0ea95a29f54.png)

![image](https://cloud.githubusercontent.com/assets/24595073/23481037/11b45736-fe98-11e6-8b06-55ce2136170f.png)

**Comment by parkjohnston** [comment]
Justin needs to start checking tickets and see if they are duplicate.  Getting these is wasting time

**Comment by parkjohnston** [comment]
Only allows for those with types defined to be changed, which should be only items coming in via docket.
