### ISSUE TITLE
(PT024) ORG items missing... Justin is resubmitting tickets

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#211]
FROM LICIA

ORG question 4
Feb. 21, 2017 RESUBMIT: 3/1/2017
Resubmit Issue: Documents have been added, but there are still missing documents (in current system, but still not in the new system)
ORG # 1121 Current system

![image](https://cloud.githubusercontent.com/assets/8847344/23485351/12748acc-fea9-11e6-883e-9dd67d6d134e.png)

Documents in the system dated 2008, 2009, 2005, 2003 and 2001 (highlighted in blue)

ORG # 1121 NEW system

![image](https://cloud.githubusercontent.com/assets/8847344/23485370/2234ecc2-fea9-11e6-881a-ab0ed6ddd221.png)
*Only goes back as far as 2010…the above documents not in the system.
---------------------------------------------------------------------------------------------------------

**Comment by altrdgenetics** [comment]
these entries do not exist in the ORGHistory Table.... Checked count from OLD to NEW, 25rows match.

They are coming from somewhere else.

**Comment by altrdgenetics** [comment]
So there was a batch import July 27th @ 8:50am....

**Comment by anthonyperk** [comment]
emailed Justin regarding the missing entries.  entries should be in the database now

**Comment by altrdgenetics** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/8847344/23525007/fb0906c6-ff5a-11e6-92d5-6a269856d2d4.png)
