### ISSUE TITLE
(PT025) ORG sort order of parties

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#212]
ORG question 5
Feb. 21, 2017
Resubmit: 3/1/2017 (new issue)
Issue: For officers only (not representative) - is there a way to automatically sort order by the officer type under Type?
i.e. President, VP, Treasurer, Secretary, then any other type
New system:
-appears to add them in the order you delete/add a new party

![image](https://cloud.githubusercontent.com/assets/8847344/23485431/646cdd5c-fea9-11e6-91a7-541762bbc44d.png)

Current system:
Sorted by Officer Title
![image](https://cloud.githubusercontent.com/assets/8847344/23485446/6e4064c0-fea9-11e6-943c-7790b4fa1805.png)
President on top
Vice President 2nd
Treasurer 3rd
Secretary 4th

**Comment by parkjohnston** [comment]
It could be done, easy...may just do it later (if we have quick down time)

**Comment by parkjohnston** [comment]
Initial comment was based on name, we could do party (again would be at a downtime)

**Comment by altrdgenetics** [comment]
if it is just a sort order within the Officers Block.... I figured out the code to do it for SQL... so no additional cleanup on the system

```
SELECT * FROM 
caseparty 
WHERE casetype = 'org' AND caseNumber = '1201' 
ORDER BY caserelation DESC,
CASE 	WHEN jobTitle = 'President' THEN '1'
		WHEN jobTitle LIKE '%Vice President' THEN '2'
		WHEN jobTitle LIKE '%Treasurer%' THEN '3'
		WHEN jobTitle LIKE '%Secretart%' THEN '4'
 ELSE jobTitle END ASC
```

**Comment by altrdgenetics** [comment]
emailed Justin asking for clarification on how they want it laid out.....

Like every other section or keeping the REP/Officer seperation.

**Comment by anthonyperk** [comment]
Please add the enhancement as listed above

**Comment by anthonyperk** [comment]
also change %Secretart% to %Secretary%

**Comment by altrdgenetics** [comment]
Email received today from Justin. This one is 174 on justins list.

    Thank you for the list below…
    Please proceed with the enhancement for ticket 174. This can be completed after the migration is completed (Low Priority). I am awaiting the green light from Angela and the list for the enhancement for ticket 165.

**Comment by altrdgenetics** [comment]
So the list needs to stay like it is, so split between REP and Officers. And then order the Officers under that.

**Comment by altrdgenetics** [comment]
added in the SQL statement and got this ready to go.
