### ISSUE TITLE
(PT026) 'ORG Non-Compliance Report - Detail'  issue

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#213]
FROM LICIA 

ORG question 11: ORG REPORT – All Org Non-Compliance Report - Detail
EEO NON-COMPLIANCE REPORT - Detail (using parameters: Sept 2016): NEW system
![image](https://cloud.githubusercontent.com/assets/8847344/23485501/a19c2f66-fea9-11e6-8b40-a9be1ceaf015.png)

Employee Org Non-Compliance Report - Detail – OLD system
![image](https://cloud.githubusercontent.com/assets/8847344/23485508/a7a2d1c6-fea9-11e6-8933-aa80a407d5a8.png)

Issue 1) Layout – should default to landscape
![image](https://cloud.githubusercontent.com/assets/8847344/23485521/b1161164-fea9-11e6-9a64-a698b418b3a3.png)

Issue 2) Reports do not match:
New report has 469 records, for parameters Sept 2016.
![image](https://cloud.githubusercontent.com/assets/8847344/23485533/beb2477a-fea9-11e6-9b36-d21b799f9b50.png)
Old report has 80 records, for parameters Sept 2016
![image](https://cloud.githubusercontent.com/assets/8847344/23485542/c69329b4-fea9-11e6-887b-4d92826831c6.png)
EXAMPLE:
New report has ORG 2433 listed, but it shouldn’t be:
Last filings of AR and FS were for 12/31/2015. The FYE 2016 reports are not due until May 2017…ORG due in December shouldn’t be on this report.
![image](https://cloud.githubusercontent.com/assets/8847344/23485547/cf5faf2c-fea9-11e6-93cd-4aed036441d8.png)

**Comment by anthonyperk** [comment]
The report is now pulling the correct information, Andrew has also changed the parameter code to pass the month name as a string and not a number.

**Comment by anthonyperk** [comment]
Licia seems to be good with this report, I will close the ticket
