### ISSUE TITLE
(PT029) -  Search/ Add New Party Windows

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#215]
When adding a new party to a case, the user may need to create a new party. When doing this, the user creates the party, but then it does not add to the case, the user must “find” the party from the search party screen, before they can actually load it to the case.
Also, when the party is “Pro Se” in the old system the user could press the button and it would duplicate the party into the proper fields. Would it be possible to Duplicate the party and allow the user to give it a new party type?

![image](https://cloud.githubusercontent.com/assets/8847344/23485677/7584e39a-feaa-11e6-905b-7ac2a3c7f321.png)

**Comment by parkjohnston** [comment]
It does this already....

**Comment by anthonyperk** [comment]
Re Pro-Se in SMDS 2.0:

Moth MED and REP sections have the ability to add a party as Pro-Se.  This functionality will need to be added to 3.0

**Comment by altrdgenetics** [comment]
if(((Global.activeSection.contains("ULP"))
                && !jComboBox1.getSelectedItem().toString().trim().contains("REP")
                && !jComboBox1.getSelectedItem().toString().trim().contains("Complainant"))
                ||(Global.activeSection.contains("REP")
                && !jComboBox1.getSelectedItem().toString().trim().contains("REP"))
                ||(Global.activeSection.contains("MED")
                && !jComboBox1.getSelectedItem().toString().trim().contains("REP"))
                ) {
            setVisible(false);
            new ProSeSelectionPanel((JFrame) Global.root.getParent(), rootPaneCheckingEnabled, jComboBox1.getSelectedItem().toString().trim(), id, name);
        }

**Comment by altrdgenetics** [comment]
code for if statement if they ask for it for all sections

**Comment by anthonyperk** [comment]
Justin confirmed that ULP is the only section that uses Pro-Se

**Comment by altrdgenetics** [comment]
this information was correct, justin did not understand. We will probably get a new ticket wanting them to send the new party info to the search textbox

**Comment by anthonyperk** [comment]
Justin has requested the functionality from Andrew's last comment

**Comment by altrdgenetics** [comment]
Add Party -> Party Search window -> Add New Party. 

After adding hitting the save button on add new party, Transfer the [FIRSTNAME] SPACE [LASTNAME] to the search bar to "pre search" that party that the user JUST added.

Caveat, check company name if first and last names are blank of course.
