### ISSUE TITLE
(PT031) REP Bookmark issue

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#217]
For the REP directives, I need the ability to populate two bookmarks based upon the person who is generating the directive.
I am currently using the following two bookmarks which pull the name of the person assigned to the case. I am currently testing the “AC Amend Merger or Affilation.docx” template.
[[NAME]]
[[TITLE]]
For case 2016-REP-11-0109 the following would appear. Debra is assigned to the case.
Debra Prots Investigator
If Angela is generating the directive, her information needs to appear in this area. In the old system there were not any bookmarks for this field. Angela’s name was typed on every template.
Do these bookmarks already exist? If not please create the two new bookmarks.

**Comment by altrdgenetics** [comment]
This code grabs current user of the case ATM

```
User user = null;
        if (caseInfo.currentOwnerID > 0) {
            user = User.findUserByID(caseInfo.currentOwnerID); //Need to get user by ID
        }
```


```
//LRS Worker 
            if (user != null) {
                processBookmark.process("NAME" + (i == 0 ? "" : i), StringUtilities.buildFullName(user.firstName, user.middleInitial, user.lastName), Document);  
                processBookmark.process("TITLE" + (i == 0 ? "" : i), user.jobTitle, Document); 
                processBookmark.process("PHONE" + (i == 0 ? "" : i), user.workPhone, Document);
                processBookmark.process("EMAIL" + (i == 0 ? "" : i), user.emailAddress, Document);
            }
```

**Comment by altrdgenetics** [comment]
instead of currentowner of the case do they want it to be logged in user?

**Comment by anthonyperk** [comment]
Justin's Response:

Anthony, 

I will want new books. Maybe something like

<<LOGGEDINUSER>>
<<LOGGEDINUSERTITLE>>

**Comment by altrdgenetics** [comment]
created globally using provided text, available for all sections SERB & PBR sides.
