### ISSUE TITLE
(PT031) - ALJNAME bookmark not populating

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#218]
In CMDS Tab the ALJNAME bookmark is populating blank even if there is an ALJ assigned to the case.
CMDS Documents > Continuances > Continuances Granted Letter

![image](https://cloud.githubusercontent.com/assets/24595073/23523771/3129f760-ff56-11e6-8869-8d63002c92a1.png)

![image](https://cloud.githubusercontent.com/assets/24595073/23523777/345c9c26-ff56-11e6-8dc6-2ab683a01d68.png)

**Comment by altrdgenetics** [comment]
was pulling Mediator not ALJName... got it fixed
