### ISSUE TITLE
REP Status tab, needs textboxes disabled

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#22]
Issues with two text boxes on initial load that are editable. They stay editable until the update button it hit once. After that they function as they should.

![screenshot 127](https://cloud.githubusercontent.com/assets/8847344/15458107/c7e35cb4-2063-11e6-8f60-cc4e60733b15.png)

**Comment by parkjohnston** [comment]
Resolved

b75ad46d455f8681195751b5dbfce3dcc6db3fab
