### ISSUE TITLE
(PT035) -- Hearing Section Issues

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#221]
The following are issues with Hearings Section:
1) hearings Section Reports are not listed correctly

2) Hearings Tab: Add Mediation: On this screen the save button is grayed out until all fields are completed. Please change it so that users can save without needing to complete all the fields. Users add this info as users receive it- not always at the same time.

3) Also, the mediator names should be in this drop down, not the investigators.
![image](https://cloud.githubusercontent.com/assets/24595073/23529280/0894ee44-ff6b-11e6-81b0-5d5aed37292b.png)

4) The word mediation is spelled wrong on the activity entries

![image](https://cloud.githubusercontent.com/assets/8847344/23557407/f8aaf012-fffd-11e6-9457-fa518aafe62a.png)

5) Hearings Tab: The ALJ Assigned drop down should show the ALJs, not the Investigators.

![image](https://cloud.githubusercontent.com/assets/8847344/23557421/04f6bf86-fffe-11e6-9f60-69ae37fa3462.png)

**Comment by anthonyperk** [comment]
Anthony comment: I know that there are 4 issues in this ticket, however since they are all about the Hearings tab, and should be pretty straight forward, I kept them in one ticket instead of asking for 4 separate tickets.  PT036 is being asked to resubmitted as individual tickets

**Comment by parkjohnston** [comment]
We need to follow a process and return tickets like this as invalid and stop them from sending shit like this. 

As he was told in a meeting. One ticket one issue. 

We need to hold him to a process and not let XLN lose power if the situation. We need to keep an upper hand and control the process.  Not only for our sanity, but for the general health of this project. We can't keep waiting to update grouped tickets as closed when we have other aspects closed. 

Moving forward we need to kill things like this and have them be one ticket one issue for overall project benefit.

**Comment by parkjohnston** [comment]
More proof that the "multi issues" will not work

I could close this ticket, but it is waiting on report changes so therefore it is having to stay open and be bounced around to several people, something that is NOT beneficial to making money or having the cards closed out in a timely manner.  

XLN needs to set the tone the for quicker response time to issues we need to have a single issue on a ticket

**Comment by altrdgenetics** [comment]
I have the reports Added in yesterday.... there was an issue with the naming convention....

code looked for 'HRG' and DB had 'Hearing'

**Comment by altrdgenetics** [comment]
finished #4 on this ticket

**Comment by altrdgenetics** [comment]
#2  Need to know bare minimum of information required to insert data... we will not allow entirely blank dialogs to be inserted.

#3 & #5 for joining all of the 'user' tables into one we ask if the CMDS & Hearing ALJ/investigators were the same thing using different terms in respective departments and could use the same Checkbox. We were told yes. Now it appears as NO, can we get clarifcation on that. (hearingPeople table is what these items referencing)

**Comment by altrdgenetics** [comment]
we received information in an email to be able to complete a few of these....

3)
The minimum fields are PC/PreD, Mediator, Date Assigned. Please leave Mediation Date and Outcome not required. (They come later).


The mediator names should be generated from the Mediators Table. Any active “State” Mediator. (First + Last Name)

5)
I just submitted a similar ticket PT048 regarding this as well for ALJs in all the other sections, I missed this tab. Please correct this item as discussed in PT048.

**Comment by altrdgenetics** [comment]
for 3 only one that we had extra in the required list was mediation date, this is now fixed

**Comment by altrdgenetics** [comment]
I will also need to adjust my import for that since we are grabbing ID instead of name.

**Comment by parkjohnston** [comment]
What am i needing to do with this?

**Comment by parkjohnston** [comment]
Completed the second half of number 3

**Comment by parkjohnston** [comment]
What section is the ALJs? ULP?

**Comment by parkjohnston** [comment]
I would suggest that we maybe ask for a breakdown of like: 

ALJ == section 
Mediotors == section 

Since they are using terms that we have no idea what they are really wanting since they do not overlap with other tab names.

**Comment by altrdgenetics** [comment]
changed over the mediators to the State mediator as requested as well as all of the supporting panels, Add/ Update, and loading the table on the main tab.

**Comment by altrdgenetics** [comment]
5 does load ALJ... this one is fine.
