### ISSUE TITLE
(PT032) - ALJNAME not populating

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#224]
ALJNAME bookmark not populating in 

CMDS Documents -> Board Order -> Continuance -> Continuances Granted Letter

**Comment by anthonyperk** [comment]
Due to [Appellee2Name] field populating a blank when no Appellee2 is present, the bookmark [ALJNAME] is moved to the left of the document (under [AppelleeName]) when generated

![image](https://cloud.githubusercontent.com/assets/24595073/23555655/c14d83d8-fff7-11e6-9bd3-f604df3ca084.png)

![image](https://cloud.githubusercontent.com/assets/24595073/23555675/d22d4fd0-fff7-11e6-9416-902b12da7416.png)

**Comment by altrdgenetics** [comment]
shifting of the text is not our problem, that is a template layout problem with the spacing/tabbing of the text.
