### ISSUE TITLE
(PT038) -- Activity Report not generating for ORGs

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#225]
Since the Activity Report needs a full case number, butting in an ORG number will not satisfy the credentials on the "Required Report Information" panel

![image](https://cloud.githubusercontent.com/assets/24595073/23557672/c78d5adc-fffe-11e6-80e5-65c8f9b06575.png)

**Comment by altrdgenetics** [comment]
removed the ALL reports from ORG and CSC....
