### ISSUE TITLE
(PT039) -- All Active Orgs Detail Report – All Organizations report do not match numbers

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#226]
Current name: All active Detail Report – All ORGS
*Does not match, 1 record off….new has 2288 records, current has 2289 records

NEW
![image](https://cloud.githubusercontent.com/assets/24595073/23557853/851c59cc-ffff-11e6-8447-a59d56900c3e.png)
CURRENT
![image](https://cloud.githubusercontent.com/assets/24595073/23557857/87a90d48-ffff-11e6-9690-50e22434e872.png)

**Comment by anthonyperk** [comment]
ORG number 743 (Austintown Education Assn) is missing from the new database

**Comment by altrdgenetics** [comment]
sommemmeeeeee how, this org was missed in the migration to SERB... It exists in our XLNCMS and SERB DB downstairs and also exists in the SERB-Dev on SERB machine... but it was not in SERB on their side. I manually imported that single case and its rep.

**Comment by altrdgenetics** [comment]
because DB... it is live as we speak
