### ISSUE TITLE
(PT041-42) - (ORG) - All Orgs Noncompliance – All Months records do not match

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#228]
New report: All Orgs Noncompliance – All Months
Current report: All Orgs Noncompliance Report – all months

New (Parameters used: Sept 2016)
![image](https://cloud.githubusercontent.com/assets/24595073/23557952/ddef8074-ffff-11e6-952e-26980ab4d2e5.png)
Current (Parameters used: Sept 2016)
![image](https://cloud.githubusercontent.com/assets/24595073/23557957/e3d1a936-ffff-11e6-97ee-3f4efdacd2d9.png)

Reports generated do not match:
New system – 469 records
![image](https://cloud.githubusercontent.com/assets/24595073/23557966/e9a3fb3e-ffff-11e6-9443-78ac4ea0bdde.png)
Current system – 80 records
![image](https://cloud.githubusercontent.com/assets/24595073/23557971/ef9b9970-ffff-11e6-9cd8-51553e4b11f6.png)

**Comment by anthonyperk** [comment]
Report has changed to reflect the correct query, however Licia will need to test in so we can make sure it works correctly.

**Comment by altrdgenetics** [comment]
This report is in question. It appears to be a duplicate. Justin will meet with Licia at some point and decide if this report is even needed anymore. Still waiting on that.

**Comment by altrdgenetics** [comment]
Email From Justin:

> We do want to keep this report.
> This report is identical to the other report except that it will also show noncompliance orgs for previous months. Is there a way for you to continue to do that?  I see the code utilized a SQL passthrough on the old report so without seeing that code I am not going to be able to help any further. I am sure there is some kind of loop that counts back the previous 11 months.  Please let me know if you need to discuss this further.

**Comment by altrdgenetics** [comment]
Justin Approves hardcoding this report into the application.

**Comment by altrdgenetics** [comment]
I have worked on the hardcoding and Think I have it squared away. need to have anything test it

**Comment by altrdgenetics** [comment]
report needs to be changed out on SERBside but Anthony will do that at release
