### ISSUE TITLE
(PT042) -- Duplicate Please Ignore

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#229]
New report: All Orgs Noncompliance – All Months
Current report: All Orgs Noncompliance Report – all months
JUSTIN – I’m not sure what this report is supposed to calculate, but they don’t match.
New system: parameter May 2016
![image](https://cloud.githubusercontent.com/assets/24595073/23558002/0cede226-0000-11e7-8790-0ead848e985e.png)
Current system: parameter May 2016
![image](https://cloud.githubusercontent.com/assets/24595073/23558010/1304a348-0000-11e7-843f-119667d1a0e2.png)

New system report: 99 records (For starters, AFT and ATU aren’t one the current report)
![image](https://cloud.githubusercontent.com/assets/24595073/23558022/1d812346-0000-11e7-8102-de2f449f5875.png)
Current system report: 79 records
![image](https://cloud.githubusercontent.com/assets/24595073/23558028/24819518-0000-11e7-96f8-cfb2de35c435.png)

**Comment by parkjohnston** [comment]
Put the duplicate ticket number here as a link and close the card

use the pound sign and then github issue number 

#

**Comment by anthonyperk** [comment]
Duplicate of #228
