### ISSUE TITLE
(PT048) - ALJ / Investigator dropdowns....

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#235]
The drop down for Investigator and ALJ in the ULP section contains the same list of names. They pull from the Investigator checkmark in the users table. I believe this checkmark should be renamed ALJ.

![image](https://cloud.githubusercontent.com/assets/8847344/23565851/45f18e84-001d-11e7-9329-d706ab345973.png)

The Investigator list should be populating just like the coding for the Rep Current Owner, which is based upon who has the “REP Worker” checkmark in the users table. The ULP Investigator should be populating with the Users who have the “ULP Worker” Checkmark.

After re-reviewing the REP Dropdown I discovered the current owner contains both REP workers and ALJs. Can you update this dropdown to include the anyone with the “REP Worker” Checkmark and “newly renamed ALJ Checkmark”?

Below is an example of the ULP screen in the new system.

![image](https://cloud.githubusercontent.com/assets/8847344/23565860/565d5974-001d-11e7-9c4d-0ea1fb35786b.png)

Below is the ALJ drop down in the CMDS system.

![image](https://cloud.githubusercontent.com/assets/8847344/23565868/611e54f8-001d-11e7-8e2c-603711d01ad5.png)

**Comment by altrdgenetics** [comment]
We had previously submitted a email to Justin about Hearing Section dropdowns, GitHub issue #221. More specifically item 3 on that ticket. We did not receive clarification regarding that and have since received this ticket. I will be marking this with the question tag till we get the answer on that, as it appears Justin is not reading his incoming emails nor knows what he wants.

**Comment by parkjohnston** [comment]
I agree about leaving it a question, but lets follow up with him also on the fact it would be helpful to XLN that we have a break down of:

ALJ == section, etc

He is using words that we have NO idea about and expects us to be working with SERB for years.

**Comment by parkjohnston** [comment]
Clicked comment and close by accident

Also I can fix this in a few sections after we get that.  Picked it up and just let me know the result of the email

**Comment by altrdgenetics** [comment]
After talking to Justin today I have checked the comboboxes

ULP -> Status -> Investigator - > ULPWORKER Load only

REP -> Information -> Current Owner -> REPWORKER & ALJ


this has been completed
