### ISSUE TITLE
(PT049) -- Unable to locate certian CMDS Reports

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#238]
CMDS Reports > I get the following error:

![image](https://cloud.githubusercontent.com/assets/24595073/23616811/f6b023f6-0258-11e7-8276-cbdeb3210094.png)

Activity Report
Mail Log 
Party Information 
Cases Appealed to a Higher Court 
Appealed to a Higher Court – Year 
Appealed to a Higher Court – Type

**Comment by anthonyperk** [comment]
Activity Report - Part of SMDS's Reports as type 'ALL', not in CMDS's reporting folder

Mail Log - Part of SMDS's Reports as type 'ALL', not in CMDS's reporting folder

Party Information - Part of SMDS's Reports as type 'ALL', not in CMDS's reporting folder

Cases Appealed to a Higher Court - File Name listed as 'Appealed to a Higher Court.jasper', should be 'Appealed to Higher Court.jasper'.  This is changed in their database

Appealed to a Higher Court – Year - File Name listed as 'Appealed to a Higher Court – Year.jasper', should be 'Appealed to Higher Court – Year.jasper'.  This is changed in their database

Appealed to a Higher Court – Type - File Name listed as 'Appealed to a Higher Court – Type.jasper', should be 'Appealed to Higher Court – Type.jasper'.  This is changed in their database

**Comment by altrdgenetics** [comment]
The 'All' reports errored out because i was defining a object and then looking for null, not letting the object start out as null.
