### ISSUE TITLE
(PT051) -- Generate Report button will not enable unless you select 2 differnet Activity Types

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#240]
The generate button is greyed out until I select a different drop down item and come back to it. May be able to fix by simply putting a blank line 1 in drop down. On most of the drop downs that I tested. 

Below are two examples:
![image](https://cloud.githubusercontent.com/assets/24595073/23617605/9fdeb206-025b-11e7-93d5-781b0009097a.png)

![image](https://cloud.githubusercontent.com/assets/24595073/23617611/a4f2eba4-025b-11e7-9195-b803fed2dafb.png)

**Comment by anthonyperk** [comment]
Users will have to select the activity type, enter a year, then go back to the activity type and select a different one in order for the Generate Report button to enable

**Comment by altrdgenetics** [comment]
the combobox string window had a missing listener on the textbox and also the count on index for the combobox was off by one, caused the first entry to be flagged as invalid. The second example had the same combobox issue. This all came when we stopped using the BLANK lines and now have the 'ALL' wildcard choice.

**Comment by anthonyperk** [comment]
Generate Report button does enable
