### ISSUE TITLE
(PT052)(PT053)(PT055)(PT056)(PT057)(PT058) - Single Case Number prompt for CMDS reports not working

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#241]
![image](https://cloud.githubusercontent.com/assets/24595073/23618458/5f5ab056-025e-11e7-89ef-8e7169c4fcf5.png)

**Comment by anthonyperk** [comment]
Code not looking for CMDS case types

**Comment by altrdgenetics** [comment]
I fixed this by using global active section to narrow down the case table and created a different case validation method based off of the section that the user is in.

**Comment by parkjohnston** [comment]
Case validation was already created for all sections
