### ISSUE TITLE
(PT055)(PT056)(PT057) -- Reports prompt for case number when it didnt in 2.0

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#242]
The report prompt appears but unable to generate.
There is no Dialog Box in Old System – user only presses generate to see the report.

![image](https://cloud.githubusercontent.com/assets/24595073/23618790/802d4dd8-025f-11e7-9679-ab231392711c.png)

**Comment by anthonyperk** [comment]
In 2.0, the system grabbed the currently loaded case and passed that case number to the report.  Now the report is asking for any case number.  Automatically entering the case number into the Required Report Information panel is an enhancement.  Will ask Justin about this

**Comment by parkjohnston** [comment]
Throwing out the topic of, did we used to limit the report button to working with a case selected? which would allow that to happen, but now we allow it to be when nothing is selected.

**Comment by altrdgenetics** [comment]
No, the Letters/Document Button is Case Dependent. The Report button is case independent. In the old system the reports were buried under the tabs and looking at CMDS 2.0 application there is not a way after initial log in to the system to NOT have a case number loaded in the system.

The way to do this would be to preload a casenumber if one is entered, but that would also mean that any report that would have this parameter window would be forced into it as well. Need a final answer from Justin.

**Comment by altrdgenetics** [comment]
they want us to pre-populate the textbox

**Comment by altrdgenetics** [comment]
completed this. If the global caseNumber is active... it pulls from that and pre-populates the textbox.
