### ISSUE TITLE
Next available CMDS case number is still overwriting all sections next available case number

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#245]
When a new CMDS case is created, the next available CMDS case number is written to CMDS AND REP, MED, and ULP, causing them all to have the same next case number

**Comment by altrdgenetics** [comment]
fixed this issue and Anthony tested it. The one thing I found is that Parker had changed the Get method to support CMDS back in 02/22 but did not change the set or adding of new casenumber where no year exist yet.
