### ISSUE TITLE
(PT061) -- Remove Assistants as a migrated party

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#247]
The type Petition Rep Assistant appeared on an imported case. It is not an option in the type drop down. There is another example in a different case where the Employer Rep Assistant title is used.
![image](https://cloud.githubusercontent.com/assets/24595073/23627954/b7d7db1a-0280-11e7-9b53-f704297aed5e.png)

**Comment by anthonyperk** [comment]
From Justin:

In the example provided in the ticket for case 2016-REP-11-0109 It listed an assistant in the new system. This was not in the case in the old system. We do not want the party type of Assistant. We were not sure where that label came from or how it appeared on that case. That is why we submitted the ticket.

**Comment by altrdgenetics** [comment]
this is an enhancement, clarification on the ticket yeilded they wanted it removed from the migration. This of course is after having the system to use for 2 months... this is now an enhancement.

**Comment by altrdgenetics** [comment]
fixed, 1hr charge.
