### ISSUE TITLE
(PT063) -- ALL Letters -> New Registration Past Due grayed out

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#249]
ALL Letters – New Registration Past Due
New System: Cannot generate the letter, grayed out.
-Would it be based on FY ending during the current month? i.e. now it state’s March?
![image](https://cloud.githubusercontent.com/assets/24595073/23628751/59c90d3e-0283-11e7-8385-09564120187b.png)

Current system:
Based on the system’s calculations:
![image](https://cloud.githubusercontent.com/assets/24595073/23628757/5ce3c590-0283-11e7-89c7-ce763beea571.png)

**Comment by altrdgenetics** [comment]
The button wont be enabled, this has already been submitted as PT028 (#214)
