### ISSUE TITLE
(PT064) -- Tickler 10 days missing an ORG

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#250]
All Letters – Tickler 10 days
Issue – Processing Error - Missing ORG on list to send letter
Issue – Letter will not generate; only “clocks”
New System: Only has 1 ORG (1527), what about ORG 2460 (also FY end Oct 2016, due March 15, 2017) but not listed.
![image](https://cloud.githubusercontent.com/assets/24595073/23629073/84256068-0284-11e7-9b20-b87822edb9f1.png)

Current System:
![image](https://cloud.githubusercontent.com/assets/24595073/23629082/89a0d108-0284-11e7-9586-d15923a4f9cc.png)

Current System Enlarged:
![image](https://cloud.githubusercontent.com/assets/24595073/23629095/93ea2902-0284-11e7-82f9-95d4fa387cba.png)

Looking at ORG 2460 in the new system, no AR or FS, and due date March 15th, so it should get a letter.
![image](https://cloud.githubusercontent.com/assets/24595073/23629173/d392da36-0284-11e7-91bc-e8ec8ed44395.png)

2nd issue: The letter will not generate, it gets stuck “clocking”
![image](https://cloud.githubusercontent.com/assets/24595073/23629179/db0fcab2-0284-11e7-85dc-c6b2313d889e.png)

**Comment by altrdgenetics** [comment]
SERB 2.0 Code:

```
if (currentData.getDd().DocumentFileName.contains("45")) {

    cal.set(Calendar.DAY_OF_MONTH, 15);
    cal.add(Calendar.MONTH, 1);
    cal.add(Calendar.MONTH, -5);

    FYEMonthMatch = String.format("%02d", cal.get(Calendar.MONTH) + 1);
    FYEMonthName = cal.getDisplayName(Calendar.MONTH, Calendar.LONG, Locale.ENGLISH);

    currentData.setMatchString("45");

    FileYearMatch = Global.getSdfYear().format(cal.getTimeInMillis());
} else if (currentData.getDd().DocumentFileName.contains("10")) {

    cal.set(Calendar.DAY_OF_MONTH, 15);
    cal.add(Calendar.MONTH, -5);

    FYEMonthMatch = String.format("%02d", cal.get(Calendar.MONTH) + 1);
    FYEMonthName = cal.getDisplayName(Calendar.MONTH, Calendar.LONG, Locale.ENGLISH);

    currentData.setMatchString("10");

    FileYearMatch = Global.getSdfYear().format(cal.getTimeInMillis());
} else if (currentData.getDd().DocumentFileName.contains("31")) {

    cal.set(Calendar.DAY_OF_MONTH, 15);
    cal.add(Calendar.MONTH, -5);
    cal.add(Calendar.MONTH, -1);

    FYEMonthMatch = String.format("%02d", cal.get(Calendar.MONTH) + 1);
    FYEMonthName = cal.getDisplayName(Calendar.MONTH, Calendar.LONG, Locale.ENGLISH);

    currentData.setMatchString("31");

    FileYearMatch = Global.getSdfYear().format(cal.getTimeInMillis());
} else {
    return;
}
```

**Comment by altrdgenetics** [comment]
SERB 3.0 Code:

`switch (letterComboBox.getSelectedItem().toString()) {
            case "Tickler 45 days":
                cal.set(Calendar.DAY_OF_MONTH, 15);
                cal.add(Calendar.MONTH, 1);
                cal.add(Calendar.MONTH, -5);
                processOverdueNumbers(cal);
                break;
            case "Tickler 10 days":
                cal.set(Calendar.DAY_OF_MONTH, 15);
                cal.add(Calendar.MONTH, -5);
                processOverdueNumbers(cal);
                break;
            case "Tickler 31 days overdue":
                cal.set(Calendar.DAY_OF_MONTH, 15);
                cal.add(Calendar.MONTH, -5);
                cal.add(Calendar.MONTH, -1);
                processOverdueNumbers(cal);
                break;
            default:
                orgCaseList = ORGCase.getOrgCasesAllLettersDefault();
                break;
        }`

**Comment by altrdgenetics** [comment]
Wonderful.... The issue tied with this one was due to the fact that I had '= null' not 'IS NULL'
