### ISSUE TITLE
(PT065) -- All Letters – Tickler 31 days does not match number of letters

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#251]
All Letters – Tickler 31 days overdue
Issue – Processing Error – Generation of letters does not match (1 ORG, but number of letters differs)
Issue – Letter will not generate; only “clocks”
New System
-Sending 2 via postal mail (both for ORG 943)
![image](https://cloud.githubusercontent.com/assets/24595073/23629222/0588ebde-0285-11e7-8469-7dd6235f4c96.png)

Current System
-Sending 1 via postal mail (for ORG 943)
Enlarged:
![image](https://cloud.githubusercontent.com/assets/24595073/23629236/103db46a-0285-11e7-9321-62046090df2a.png)
![image](https://cloud.githubusercontent.com/assets/24595073/23629237/124ff100-0285-11e7-997b-93eca9ff16a0.png)

In the current system, the REP and the ORG have the same address (and neither have an email), so it only generates one postal letter). *If the REP and the ORG had the same address, but one had an email, it would generate 2 letters (one email and a second postal letter to the one w/out the email address).
Current system:
ORG REP address is 27 Euclid Ave; Columbus, OH 43201 (no email address)
![image](https://cloud.githubusercontent.com/assets/24595073/23629249/1976de12-0285-11e7-9cb2-048b71563b0d.png)

ORG address is 27 Euclid Ave; Columbus, OH 43201 (no email address)
![image](https://cloud.githubusercontent.com/assets/24595073/23629255/20142b3a-0285-11e7-8ea9-cee537ca4bb1.png)

New system:
ORG REP address is 27 Euclid Ave; Columbus, OH 43201 (no email address)
![image](https://cloud.githubusercontent.com/assets/24595073/23629260/25a5e764-0285-11e7-89d3-0f4ff9ed006b.png)

ORG address is 27 Euclid Ave; Columbus, OH 43201 (no email address)
![image](https://cloud.githubusercontent.com/assets/24595073/23629272/2d408b14-0285-11e7-9dc2-f0a838c90ee3.png)

Both are the same with no email address for either, should only do 1 letter.
ISSUE – DOES NOT GENERATE TICKLER 31 days overdue LETTER, ONLY CLOCKS
![image](https://cloud.githubusercontent.com/assets/24595073/23629278/368d7560-0285-11e7-9b67-3f6b23a04386.png)

**Comment by altrdgenetics** [comment]
two issues were found with this... So the letters would generate but would not show a confirmation dialog that they had completed, added one in. Also missed the check for org address and rep address match.
