### ISSUE TITLE
(PT066) -- All Letters - Ticker 45 Days not generating

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#252]
All Letters – Tickler 45 days
Issue – Processing Error – Generation of letters does not match (1 ORG, but number of letters differs)
Issue – Letter will not generate; only “clocks”
![image](https://cloud.githubusercontent.com/assets/24595073/23630619/c172f9bc-0289-11e7-98e5-a2575cd8a18a.png)

**Comment by anthonyperk** [comment]
Need clarification from Justin about what exactly the issue is.  Would this be the same as #251

**Comment by altrdgenetics** [comment]
related to others
