### ISSUE TITLE
(PT067) -- Possible Renaming of ORG Letters

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#253]
**All Letters – names**

Issue: Might be helpful to include date you send letter in letter name.

Tickler 10 days = Tickler 10 days (send 5th of every month)
Tickler 31 days overdue = Tickler 31 days overdue (send 15th of every month)
Tickler 45 days = Tickler 45 days (send 1st of every month)

**Comment by altrdgenetics** [comment]
not sure what he is asking for here....  Document descriptions can be changed in the DB now, and there **IS** an admin panel for this.
