### ISSUE TITLE
(PT076) Auto assign to ALJ on CMDS Docketing

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#261]
CMDS Email and Scan docketing.
The to: field should auto fill with the ALJ assigned to the case.

![image](https://cloud.githubusercontent.com/assets/8847344/23710134/a27f98d8-03e9-11e7-866b-7c9a71f49192.png)

![image](https://cloud.githubusercontent.com/assets/8847344/23710138/a5021630-03e9-11e7-98ad-9bfc50716b5d.png)

![image](https://cloud.githubusercontent.com/assets/8847344/23710142/a735d2a2-03e9-11e7-973e-c06edef1da67.png)

**Comment by parkjohnston** [comment]
Not an issue, works as requested in a previous ticket.  

A case number is required, which is not shown in any of the above documentation.
