### ISSUE TITLE
(PT079) -- DIRECCList addition for CMDS

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#265]
For CMDS I need a CC Bookmark that includes all parties to the case in the following format. This is only used on the Appeals form.

FName MI. LName, Suffix, Prof Designation, Company, [Party Type] 
Address 1, address 2, Address 3, City, State, Zip,

FName MI. LName, Suffix, Prof Designation, Company, [Party Type] 
Address 1, address 2, Address 3, City, State, Zip,

FName MI. LName, Suffix, Prof Designation, Company, [Party Type] 
Address 1, address 2, Address 3, City, State, Zip,

FName MI. LName, Suffix, Prof Designation, Company, [Party Type] 
Address 1, address 2, Address 3, City, State, Zip,

Which is similar to how it appeared on the previous letter shown below.

![image](https://cloud.githubusercontent.com/assets/8847344/23719622/1cf2ca8e-040a-11e7-8695-28301faaf6a0.png)

**Comment by altrdgenetics** [comment]
there was already CCList and ccListAddress in use as bookmarks. Used the "CCDIREList" as the bookmark and created as it is asked for here with the line seperation between party and address.
