### ISSUE TITLE
(PT080) -- "Questions" changes for letter Lack of Jurisdiction over Parties -> Appellant FTA

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#266]
For the following letter…
![image](https://cloud.githubusercontent.com/assets/24595073/23718618/2c45fd2a-0406-11e7-85ad-129090af9ded.png)

For clarity please revise the text to “What Date was the Notice of Hearing Served on Appellant”
![image](https://cloud.githubusercontent.com/assets/24595073/23718631/38fff7dc-0406-11e7-850c-179f0c370a60.png)

**Comment by altrdgenetics** [comment]
in the database the Column used for this is CMDSDocuments.hearingTime and this is not the only document that the column is used on. If adjusted it would affect all other reports as well, do we really want to change it to have a party name dependent title? 

![2screenshot](https://cloud.githubusercontent.com/assets/8847344/23719841/d6234542-040a-11e7-83d3-3cca7015ff38.png)

**Comment by altrdgenetics** [comment]
screw it, ill just change it and if they want it different later they can pay for it.
