### ISSUE TITLE
(PT081) -- "Questions" changes for letter Lack of Jurisdiction over Parties ->Metropolitan Housing Authority Employees

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#267]
For the following letter…
![image](https://cloud.githubusercontent.com/assets/24595073/23718685/7ab19474-0406-11e7-940d-d286442367cb.png)

The prompt below is not needed. It does not populate any bookmarks on this letter. The letter is gender neutral.
![image](https://cloud.githubusercontent.com/assets/24595073/23718693/83fcd82c-0406-11e7-8b94-0af23af9b20c.png)

**Comment by altrdgenetics** [comment]
just remove the checkbox. should be able to do so on the admin panel.

**Comment by anthonyperk** [comment]
Prompt removed on SERB DB and Downstairs DB
