### ISSUE TITLE
(PT082) -- "Questions" changes for letter Lack of Jurisdiction over Parties ->Collective Bargaining Employees

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#268]
For the following letter...
![image](https://cloud.githubusercontent.com/assets/24595073/23718730/aebb02d2-0406-11e7-8e8b-3b48640bb5a8.png)

The Type should be a drop down containing “Removal”, “Reduction”, “Suspension”, “Other”
The Memorandum Contra drop down should contain, “Filed” and “Did Not File”
Typo on fill-in box for “Classificationt Title.”
![image](https://cloud.githubusercontent.com/assets/24595073/23718735/b7d82f8e-0406-11e7-9f3c-d83c24cc217d.png)

**Comment by altrdgenetics** [comment]
fixed the miss spelling.

The others do exist in 2.0

**Comment by altrdgenetics** [comment]
fixed the memorandum contra

**Comment by altrdgenetics** [comment]
fixed the action was appealed. that used the field 'ActionAppealed' in the DB
