### ISSUE TITLE
(PT083) - (CMDS) - "Questions" changes for letter Lack of Jurisdiction over Parties ->Collective Bargaining Employees

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#269]
For the following letter...
![image](https://cloud.githubusercontent.com/assets/24595073/23718759/d6369e2a-0406-11e7-83a6-6df6bab627fa.png)

Typo on fill-in box for “Classificationt Title.”
Add drop down on fill-in menu for the type of employment action that took place – “Removal” or “Reduction”
![image](https://cloud.githubusercontent.com/assets/24595073/23718780/e0afccfa-0406-11e7-8a70-6a5352b974d9.png)

When the classification date populates the letter please spell out the date. March 3, 2017.
Information contained in the record indicates that Appellant was appointed as 12312, Classification Number 122, on 03/16/2017. I further find that this classification has been assigned a 1232probationary period.

**Comment by altrdgenetics** [comment]
classification title is duplicate and already been fixed

**Comment by altrdgenetics** [comment]
I can not find "employment action" in the old code. This appears to be a new item, which would mean new DB field and supporting panel updates

**Comment by altrdgenetics** [comment]
justin will look into, employment action is the same as the miss spelled one

**Comment by altrdgenetics** [comment]
Justin still has not looked into this as of today

**Comment by altrdgenetics** [comment]
Justin still needs to meet with Jennette as of today's meeting. He was hoping to get an answer later today.

**Comment by altrdgenetics** [comment]
FROM JUSTIN EMAIL:

> I have further clarified this issue and below is what is needed.
> 
> -          A new question (I don’t think one exists yet) 
> -          “Type of employment action that took place?”
> -          Answer: drop down containing “removal” and “reduction
> -          Bookmark to populate [employmentactionappealed] or similar (new)
> 
> Text from the template:
> 
> This matter came on for consideration upon Appellant’s filing of an appeal with this Board.  Information contained in the record indicates that Appellant was a probationary employee at the time of the employment action appealed.

**Comment by altrdgenetics** [comment]
asked for approval on 4/03 for the adding of the question to the DB since it will require DB modification... no response yet

**Comment by altrdgenetics** [comment]
Sent Email To Justin Reminding him we have a outstanding question on this ticket.

**Comment by anthonyperk** [comment]
Email From Justin:

> PT083       - Waiting on confirmation of database change
> Please close this ticket… do not proceed.
