### ISSUE TITLE
(PT085) -- Issue switching to the Hearings tab from another tab

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#271]
There seems to be a pointer file error when jumping to the SERB Hearings Tab. Ray got it earlier and I just got it but I cannot seem to pinpoint at what step.

**Comment by parkjohnston** [comment]
What are you referencing??

He is trying to open files....

**Comment by anthonyperk** [comment]
I will get clarification

**Comment by anthonyperk** [comment]
From Justin:

Anthony, 

It had to do with going from a case in CMDS to the SERB hearings tab. Then I did an advanced search. Both Ray and I were researching the SMDS advanced search and not being able to search by Party Name. Then bouncing back to CMDS tab. unfortunately when it happened I attempted to recreate it and I was not able to. I was hoping you had received an error in your log that would better pinpoint.

**Comment by anthonyperk** [comment]
we got nothing out of the ordinary from SLACK

**Comment by parkjohnston** [comment]
It could have been a null pointer on their other search ticket PT086, but i dont see a reason to keep this open.

**Comment by parkjohnston** [comment]
Will leave open until the other is completed. #272

**Comment by anthonyperk** [comment]
I agree.  He cant recreate it, and NULL pointers dont seem to be as devastating in 3.0 as they were in 2.0
