### ISSUE TITLE
(PT086) -- Unable to search by party in Hearings Advanced search

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#272]
SERB Hearings Advanced Search. I am unable to search by the parties.
![image](https://cloud.githubusercontent.com/assets/24595073/23721122/d32023ca-040e-11e7-9722-2c0b5b37e8db.png)

**Comment by anthonyperk** [comment]
not sure how this will work since there are multiple parties in a case

**Comment by parkjohnston** [comment]
in progress

**Comment by parkjohnston** [comment]
im dumb! that is all :)

**Comment by parkjohnston** [comment]
Found my issue....not working on the correct case that was being passed, but XLN server speed is locked up. Nightly again around 10

**Comment by parkjohnston** [comment]
will test to release in morning
