### ISSUE TITLE
(PT087) -- Add 'Joint' to "Which Party Required a Continuance" dropdown

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#273]
For the Board Orders & Letters > Continuances Please add “Joint” to the drop down.

![image](https://cloud.githubusercontent.com/assets/24595073/23721230/1eb57984-040f-11e7-93d9-61279c38e064.png)

**Comment by altrdgenetics** [comment]
easy, done... this is techinically not in the old system... We can add this to the freebie list for them
