### ISSUE TITLE
(PT088) -- bookmakr in "Continuance Denied" letter not generating

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#274]
When the Party field is populated this field does not populate the RequestingPartyC bookmark. I have also tried RequestingParty and RequestingPartyNOS.
This appears for the Continuance Letters.
Also add “Joint” to the Party drop down box. For the continuance letters.

![image](https://cloud.githubusercontent.com/assets/24595073/23721332/5cc0e7fe-040f-11e7-8ebe-02fa1490fc88.png)

![image](https://cloud.githubusercontent.com/assets/24595073/23721341/63564bcc-040f-11e7-8419-7b8cf4d2beb2.png)

**Comment by altrdgenetics** [comment]
this is a bug.... this is the one that we keep seeing in slack notififcations
