### ISSUE TITLE
(PT090)  --  Exclude (<<unit descriptions>>) in MED parties

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#276]
In the Mediation Section, Mary will add a brief unit description to some of the cases to help identify them. Currently this information is also updating in the Rolodex. Would it be possible to omit everything in ( example ) parenthesis from updating back to the rolodex?
So instead of updating “Fraternal Order of Police, Lodge #166 (Police Officers)” in the rolodex
It would update “Fraternal Order of Police, Lodge #166”
At a minimum I would like this ability for the MED section. I am not sure if it is used elsewhere.

![image](https://cloud.githubusercontent.com/assets/24595073/23722002/acd99608-0411-11e7-91fa-21f285fe3a16.png)

**Comment by altrdgenetics** [comment]
Emailed Justin

> Justin,

> 
> This change is an all or nothing as far as updating parties is concerned. And personally I believe it is a very dangerous request. Silently blanket stripping out party information could mean losing important data.  As it stands now there are 4k instances where those characters are in use in part of the name somewhere and some of them are not used as a "personal note" but as the shorthand description for the party example of is :"Central Ohio Transit Authority (COTA)". Which we believe would be immensely useful for searching.
> 
> I want to bring this to your attention, please advice on if we should continue with this request.
> 
> 
> - Andrew

**Comment by altrdgenetics** [comment]
if we are to proceed here is a link to stripping out multiple deep parenthesis

https://stackoverflow.com/questions/19136161/how-to-remove-all-the-and-text-within-it-in-java-string

**Comment by altrdgenetics** [comment]
> Andrew,
>  
> I agree with you that this is a very dangerous approach and Erin and I agree not to proceed. We will proceed as is and if this becomes an actual issue in the future we will address it then.
>  
> I appreciate your guidance and example.
> Thank you,
>  
> Justin Brown


Will be marking this as Wont Fix
