### ISSUE TITLE
(PT091)  --  CMDS "Letter Template" does not generate address bookmark

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#277]
For the following CMDS Letter it asks for the address but does not populate it on the template

![image](https://cloud.githubusercontent.com/assets/24595073/23726880/eda81044-0423-11e7-8703-d6244b67721c.png)

![image](https://cloud.githubusercontent.com/assets/24595073/23726883/f086f654-0423-11e7-9f9c-8f1a79a57c15.png)

**Comment by altrdgenetics** [comment]
needed to have the default... was missing that. the issue was also caused when "other" is selected in the dropdown and it would use the name field instead of the send to dropdown
