### ISSUE TITLE
(PT092)  --  Bookmark generation issue for "Redaction Memo"

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#278]
For the following CMDS Letter
Template Name: PO-MIS-Redaction Memo.docx
I have created the <<bookmark>> spacers, but need your assistance with populating the names to the bookmarks. Some of them are not working and others are missing from my list. Your assistance with this one is appreciated.

![image](https://cloud.githubusercontent.com/assets/24595073/23726904/055a17c8-0424-11e7-84e4-b642c43cb3d8.png)

![image](https://cloud.githubusercontent.com/assets/24595073/23726909/0834b228-0424-11e7-9475-b3fab36f7bfb.png)

**Comment by altrdgenetics** [comment]
emailed justin about what he is trying to do... does he just not know the fields?

**Comment by altrdgenetics** [comment]
justin will do
