### ISSUE TITLE
(PT094)  --  RequestingParty bookmark generation issue

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#280]
When the RequestingParty bookmark populates for Appellant, it is using a lowercase “a” when it populates the bookmark.
Also the Party dropdown should contain “Appellant” and “Appellee”

![image](https://cloud.githubusercontent.com/assets/24595073/23726971/44247cfa-0424-11e7-8cb0-becad76763d7.png)

**Comment by altrdgenetics** [comment]
no apostrophe and keep it as it shows in the combobox
