### ISSUE TITLE
(PT095)  --  MediationConfDates bookmark generation issue

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#281]
MediationConfDates bookmark is not populating. It should pull from Scheduled “MC” hearing types.
BO and Letters > Notices > Mediation Conference Notice
MediationConfernceNotice.docx

![image](https://cloud.githubusercontent.com/assets/24595073/23727015/664b22f2-0424-11e7-8d1d-ece5c5dccbfe.png)

**Comment by altrdgenetics** [comment]
i got all of the other hearing types in as well, was only missing TC. The other ones might be named differently bookmark wise.
