### ISSUE TITLE
(PT096)  --  Multi bookmark issue in Court Cost Statement letter

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#282]
The following nine bookmarks do not populate and I did not see them on my list. These are for the following template. There is not a current prompt for these in the new system.

![image](https://cloud.githubusercontent.com/assets/24595073/23727036/830a4954-0424-11e7-86dd-24cafb6ed2a1.png)

Template: CourtCostStatement.docx
CourtCaseNumber
NameofCourtAppealedTo
CostofTranscript
CostofDocumentCopies
CostofSH
[PersonPaying
DatePaid
AmountPaid
Balance

**Comment by altrdgenetics** [comment]
This ticket is invalid... Half of those bookmarks do not generate in the old system



![image](https://cloud.githubusercontent.com/assets/8847344/23728512/3e4b414a-042b-11e7-9a5c-e0264ed2e94c.png)

**Comment by altrdgenetics** [comment]
we emailed justin telling him this does not function and this is the response email..


> FYI… Shane is out today. I will follow up with him next week on this.  Please put this ticket on hold.
>  
> Thank you,
>  
> Justin Brown




> Justin,
>  
> I don’t actually use that document.  Shane would be the one using it (not sure if he does actually use it or not).  The bookmarks below would not be something that would populate- the user would need to type them into the Word document.  Hope this helps.
>  
> Erin
