### ISSUE TITLE
(PT097)  --  Salutation bookmark issue in ULP (warning, very bitchy, trigger warning)

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#283]
![image](https://cloud.githubusercontent.com/assets/24595073/23727521/65f4e822-0426-11e7-820c-efa02999be9f.png)

3-8-17 – Salutation is now pulling too much information – Should NOT include the Organization/Employer Name in the text. EVERY TIME one fix is made to a letter – another error appears. This is the 4th parallel test I’ve done over the last 3 weeks on just the Letters. Contrary to Justin’s March 2nd email Item #1 to Angela that all this would only be correct in 2016 Office – it has been correct when using 2007/2010 Office as far back as 2-9-17, as shown in the examples listed below.
(See previous of examples below where in Version 3.0 that the Salutation is correct)

![image](https://cloud.githubusercontent.com/assets/24595073/23727535/71ba90bc-0426-11e7-97c6-4b5b73d978dd.png)
3-8-17 – This example is from the tickets submitted for Version 3.0 on 2-22-17 which shows that the Salutation is correct

![image](https://cloud.githubusercontent.com/assets/24595073/23727554/7b40c714-0426-11e7-91bf-d892317841ea.png)
3-8-17 – This example is from the tickets submitted for Version 3.0 on 2-28-17 which shows that the Salutation is correct

**Comment by altrdgenetics** [comment]
im not touching nothing till we get a final ruling on this... Justin and Chris have been emailed.

**Comment by altrdgenetics** [comment]
med gets a custom set of bookmarks for generating names.
