### ISSUE TITLE
(PT098)  --  Mail Log Viewer should only show Incoming documents (less bitchy)

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#284]
![image](https://cloud.githubusercontent.com/assets/24595073/23727573/95f2410a-0426-11e7-9511-63374456831a.png)
3-8-17 – Outgoing documents should NOT be on the Mail Log – only Incoming documents should appear. Outgoing items do not appear on the Mail Log in Version 2.0 (See example below)

![image](https://cloud.githubusercontent.com/assets/24595073/23727581/9eaa99f0-0426-11e7-960f-51a239dc0325.png)
3-8-17 – Only Incoming items appear on the Mail Log in Version 2.0

**Comment by altrdgenetics** [comment]
emailed justin... this ticket is a lie.


![maillog](https://cloud.githubusercontent.com/assets/8847344/23763416/84459f46-04c7-11e7-8a83-40a3429c3ada.png)

**Comment by altrdgenetics** [comment]
this turned out to be a bug. when sending postal was using the "addactivitytodocket" method
