### ISSUE TITLE
(PT103) - Null Pointer error

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#291]
![image](https://cloud.githubusercontent.com/assets/8847344/23772170/0405d488-04e8-11e7-998d-f6bb1b57dba5.png)

![image](https://cloud.githubusercontent.com/assets/8847344/23772174/07938550-04e8-11e7-9ed3-3854c35b0baa.png)

**Comment by parkjohnston** [comment]
tried everything humanly possible and could not reproduce.  If it happens again we need WAY more details.

**Comment by parkjohnston** [comment]
found the issue....super odd
