### ISSUE TITLE
(PT104)  --  Locked File when generating "Registration Report Letter - EMAIL"

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#292]
When closing cases where the election results were certified, I need to send Registration Letters to the newly elected unions. So I go to Documents and Click on the “Document” button. I then go to letter to select the Registration Letter. I click the “Generate” button.
.
<<insert steps that dont matter>>
.
.
![image](https://cloud.githubusercontent.com/assets/24595073/23777384/326d7c26-0502-11e7-8a25-96298de7f417.png)

I had to select the read only option as it was the only way I could view the document, but that has to be fixed.

When the document is generated:
1.The e-mail where the letter is being sent does not populate
2.The author of the letter is incorrect. The investigator of the case is not always the one generating the letter. We discussed having the person who generates the document appear.
![image](https://cloud.githubusercontent.com/assets/24595073/23777386/3fc9ed96-0502-11e7-8eec-9ff565a49487.png)

**Comment by anthonyperk** [comment]
1)  I tested and did NOT get a file locked, so she would have had to had it open or WORD open in the background from a failed operation.

2) The Emails are not generating, however the bookmark [IEOCONTACTEMAIL] should be [IEOCONTACT], same for the other two emails

3) [BdMeetingDate] is not in my list of REP bookmarks, I think that should be [BORADMEETDATE]

**Comment by altrdgenetics** [comment]
added in the email bookmarks

**Comment by altrdgenetics** [comment]
couldnt replicate other issues
