### ISSUE TITLE
(PT105)  --  Should not be able to delete REP Certifications

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#293]
We should never be permitted to delete a certification. We can make active or inactive, but not delete

![image](https://cloud.githubusercontent.com/assets/24595073/23777752/bd08dfb8-0504-11e7-8aa1-14aa0517aacf.png)

**Comment by parkjohnston** [comment]
This is not actually deleting it, they are marked as inactive in the DB...this is a non issue. 

Wording on the button is delete not just remove...DUMB

**Comment by altrdgenetics** [comment]
they want the delete button just gone
