### ISSUE TITLE
(PT106)  --  Cert advanced search pre-populate will not allow on that search

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#294]
When Creating a new Certification, I put in the Employer ID Number and all certifications populate under that Employer ID Number.
![image](https://cloud.githubusercontent.com/assets/24595073/23777765/d0138518-0504-11e7-8b07-5eb7f3390f9b.png)

I then select the Certification that I want
![image](https://cloud.githubusercontent.com/assets/24595073/23777778/db65bc60-0504-11e7-9dd8-f229aa15278d.png)

When I close out the certification box, I am returned to the original SEARCH box, but when I hit enter, nothing happens and I have to type the same Employer ID Number again to go back
![image](https://cloud.githubusercontent.com/assets/24595073/23777788/e6c1f45c-0504-11e7-973e-0ddb1ba39a5b.png)

**Comment by parkjohnston** [comment]
not sure this is a bug or them just wanting actions changed.
