### ISSUE TITLE
(PT107)  --  Auto Populate in the Cert advanced search 'issue'

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#295]
When creating a new certification, I enter the Employer ID Number and then click “Create”
![image](https://cloud.githubusercontent.com/assets/24595073/23777853/21c25d30-0505-11e7-8ead-113ef382a115.png)

The Employer Name and ID Number should auto-populate as it does in the current system.
![image](https://cloud.githubusercontent.com/assets/24595073/23777860/2b5189fc-0505-11e7-9764-7cc646c9e432.png)

**Comment by anthonyperk** [comment]
This isnt how the functionality works at all....  I will talk to Angela tomorrow

**Comment by altrdgenetics** [comment]
talked to justin and well... he will have to look into it. we cant get it to work like the ticket said

**Comment by altrdgenetics** [comment]
Justin still has not looked into this as of today

**Comment by parkjohnston** [comment]
Any movement here either? 

Just trying to build out a 3.0.7 release roadmap.

Again, I know it is out of our control...

**Comment by altrdgenetics** [comment]
FROM JUSTIN:

> 
Angela has agreed to the process that we discussed over the phone for the creation of new BU numbers.  Please proceed with auto filling the employer number, employer name, and county fields when there is an employer number in the search box (as shown below). I confirmed using the employer number only for the creation of new BUs

I completed this while talking to him on the phone about it.
