### ISSUE TITLE
(PT108)  --  Author generation and Poling Period population issue

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#296]
The Letter is not indicating the author of the document as previously discussed.
The document is not pulling the polling period.
![image](https://cloud.githubusercontent.com/assets/24595073/23777896/745ff96c-0505-11e7-9d51-f959135efb1b.png)

**Comment by altrdgenetics** [comment]
what and where is this so called author?

**Comment by altrdgenetics** [comment]
![screenshot 39](https://cloud.githubusercontent.com/assets/8847344/23779668/c432efee-050f-11e7-8b66-f8ce63c168d4.png)

no polling dates for this case in the database

**Comment by altrdgenetics** [comment]
author is non isue.. should be logged in user, its a bad bookmark and they admitted they "had to look into the polling date"
