### ISSUE TITLE
(PT109)  --  'Who Prevailed' and 'Time of Tally' info missing in REP

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#297]
Information in current system was not properly transferred to new system.
[2016-REP-08-0078]
--Who prevailed
--Time of Tally

2.0  vs.  3.0
![image](https://cloud.githubusercontent.com/assets/24595073/23777926/a09fff04-0505-11e7-91f9-e88d5714a242.png)

Another Example:
Information in current system was not properly transferred to new system.
[2016-REP-09-0087]
![image](https://cloud.githubusercontent.com/assets/24595073/23777941/b72d6a18-0505-11e7-8aff-185684278002.png)

(she adds more examples of the same missing stuff)

**Comment by altrdgenetics** [comment]
Screenshots are not readable.....

**Comment by altrdgenetics** [comment]
for....

ballotsCountTime -> bad import all is null
resultWHoPrevailed -> items are blank... probably need to insert all parties first and then get a pull from that since it is INTS

**Comment by altrdgenetics** [comment]
got the ballot count time in the system now. Was doing timestamp instead of just time

**Comment by altrdgenetics** [comment]
got the who prevailed to the best of the ability.
