### ISSUE TITLE
(PT111)  --  Order of Files question

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#299]
What is the order of the documents filed in the Activity Tab. Should be in same date order from oldest to most recent as it is in the Activities Tab.
![image](https://cloud.githubusercontent.com/assets/24595073/23778067/52faee8e-0506-11e7-9e98-64a98aada9ac.png)

**Comment by altrdgenetics** [comment]
no sort order... by ID only.

**Comment by altrdgenetics** [comment]
added it just to clear it out....
