### ISSUE TITLE
ULP Parties tab issue

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#30]
once you navigate away from the parties tab, the button in the location of "Add Party" (# 2 i think, the one right below "New Case" button) does not change to match the new tab that it is on. It will enable the fields for being editable but will also bring up the search parties window as if it thinks it is still on the parties tab. Upon closing the search party window an invalid case number box shows up and gives the option for case search or close. The case number that was populated was the old case number from the ULP section even though you are in a different section.

Example cases, 2015-ULP-12-0273 on initial load. Button error occurs on 2016-REP-01-0002.

after exiting out of the improper windows and hitting the save button again an null pointer error occurs.

The issue does not occur in REP parties 

![screenshot 6](https://cloud.githubusercontent.com/assets/8847344/15751482/44ef5918-28b8-11e6-99ca-dd5ac7bf1333.png)

**Comment by parkjohnston** [comment]
de51a9964d6362bac27612a252cfa97ce24884de
