### ISSUE TITLE
(PT112)  --  Bookmark issues in MISC documents

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#300]
SOI
Not pulling from the Alpha List Field:
![image](https://cloud.githubusercontent.com/assets/8847344/23779210/196c760e-050d-11e7-8e93-6937d2db5864.png)

Cannot generate document with WORD open.

**Comment by altrdgenetics** [comment]
which document is this.... the ticket does not say and both SOI documents in REP Misc do not have what this screenshot is.

**Comment by altrdgenetics** [comment]
found it.... it is not SOI.... it is RC2 and there is no Alpha Field list... what kind of crack rocks are they smoking

![image](https://cloud.githubusercontent.com/assets/8847344/23779395/42ff4252-050e-11e7-9ce2-6626c5f5d0eb.png)

**Comment by altrdgenetics** [comment]
"ALPHALISTDATE" is the new bookmark name
