### ISSUE TITLE
(PT113)  --  Changing Activity Entry type issue (AGAIN)

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#301]
Still cannot change information in the activity section. This is a mandatory function for the investigation section as it allows us to properly label items such as exhibits or attachments in a manner that we can determine the document without opening each and every document looking for the one we want. We have had to change the identity of the filing, especially with documents that are filed not using our forms.

For testing purposes only I was changing IN-RC to Petition for Decertification. I clicked “save” and it did not change.

![image](https://cloud.githubusercontent.com/assets/24595073/23778179/bc6c9296-0506-11e7-9945-acb48b72a54d.png)

**Comment by anthonyperk** [comment]
ZOMG WHERE IS MY FUCTIONALITYYYYYYYY

**Comment by parkjohnston** [comment]
Please see #181 or #194 or 8 other tickets

**Comment by parkjohnston** [comment]
This is out there, but will ONLY working on new items forward. 

We did not have these certain columns in the old system.

**Comment by parkjohnston** [comment]
Released in beta 19

**Comment by altrdgenetics** [comment]
THIS WORKS AND I PERSONALLY TESTED THIS
