### ISSUE TITLE
(PT115)  --  Add confirmation when sending a letter

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#303]
In the Letter Queue highlight the document.
![image](https://cloud.githubusercontent.com/assets/24595073/23778421/02c8f558-0508-11e7-8c8f-c776ecf4a29f.png)

Click “Send”. Then everything disappears. We do not get a confirmation pop up box like we get in the current system. We need a confirmation pop-up box.
![image](https://cloud.githubusercontent.com/assets/24595073/23778423/055f4b0a-0508-11e7-9f60-b0fde274dc07.png)

**Comment by anthonyperk** [comment]
this was talked about in the meeting

**Comment by altrdgenetics** [comment]
this is already done...
