### ISSUE TITLE
(Pre-GoLive Test)  --  'View File' button active on activities without document link in ORG Section (Minor)

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#307]
build 3.0b21.jar

In ORG Section, double clicking on an activity entry that doesnt have a document associated with it still shows a 'View File' button in the Activity Detail Panel.  When 'View File' is clicked, it brings up that ORGs folder.

![image](https://cloud.githubusercontent.com/assets/24595073/23824672/918d4bea-0648-11e7-83cd-3f8dd128b3d0.png)

![image](https://cloud.githubusercontent.com/assets/24595073/23824674/9b9d69a8-0648-11e7-90fd-fa8c844daa20.png)

no errors were thrown

**Comment by parkjohnston** [comment]
import tool put blanks instead of nulls....add in catches to handle both.
