### ISSUE TITLE
(PT119)  --  Annual Case Dismissals Report issues

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#308]
“Annual Case Dismissals” Report
Date Range 01/01/2017 - 3/12/2017 Record Count should be 36
1) Displays duplicate case numbers (2016-ULP-11-0269, 2016-ULP-11-0273)
2) Displays case 2016-ULP-11-0265 which does not have a dismissal board meeting date displaying on the report (This case number does not display on the old report).
3) The following three cases show on the old report but not on the new one. 2016-ULP-04-0069, 2016-ULP-07-0163, 2016-ULP-08-0181

**Comment by parkjohnston** [comment]
-Added an ‘AND BoardMeeting.boardmeetingdate IS NOT NULL’ to the query
-Migration issue with Board Meeting Dates, this has been fixed and also effected other reports

**Comment by anthonyperk** [comment]
-Added an ‘AND BoardMeeting.boardmeetingdate IS NOT NULL’ to the query
-Migration issue with Board Meeting Dates, this has been fixed and also effected other reports
