### ISSUE TITLE
(PT120)  -ULP-  Allegations Statement Report Issue

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#309]
Allegations Statement
Date Range 1/1/2017 – 3/12/2017 criteria used “a” Record Count should be 50
1) This report displayed no cases that contain “null” in the allegation statement. I believe the criteria field is not being passed into the report

**Comment by anthonyperk** [comment]
The report should run, however something isn’t getting handed off to the report.  I am looking into it

**Comment by altrdgenetics** [comment]
got my half figured out, was pointing to the ID hashput method instead of the String one
