### ISSUE TITLE
(PT124)  --  Annual Case Filings Tracking Charging and Charged Party report issue

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#313]
Annual Case Filings Tracking Charging and Charged Party
Date 1/1/2017 3/1/2017
1. The recommendation field is not importing correctly [B@120ab60] onto the report for case 2017-ULP-02-0045, This also showed this way in the old system. It just imported over the same way.
2. In Case 2017-ULP-01-0021 there are funny characters in the recommendation box. (Three instances) Also in case 2017-ULP-01-0010
3. The charging party rep when displayed in the report needs to include a fuller contact card
a. Fname MI Lname, Suffix, Professional Designation
b. (This format should be used on all party Reps in all reports how do you want to tackle this?)

**Comment by anthonyperk** [comment]
- Changed the party names to include MI, Suffix, and Professional Designation
- Find and replace of [unicode characters] with an actual apostrophe
- Find and replace of [unicode characters] with an §

**Comment by anthonyperk** [comment]
Re-opened for Andrew

**Comment by altrdgenetics** [comment]
SQL REPLACE CODE:

```
UPDATE ULPCase SET 
statement = REPLACE(statement, 'â€œ', '');

UPDATE ULPCase SET 
recommendation = REPLACE(recommendation, 'â€œ', '');

UPDATE ULPCase SET 
investigationReveals = REPLACE(investigationReveals, 'â€œ', '');

UPDATE ULPCase SET 
note = REPLACE(note, 'â€œ', '');
```
