### ISSUE TITLE
REP Details Panel (alignment offset)

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#32]
Professional /Non Professional boxes are offset and do not line up in the grid pattern to match Bargaining Unit IN / EX .

![screenshot 7](https://cloud.githubusercontent.com/assets/8847344/15751928/edcb5202-28b9-11e6-8e39-952e1969b017.png)

**Comment by parkjohnston** [comment]
@altrdgenetics just how it appeared...is lined up within the application layout. 

Will leave open until I have time to look at it and fidget.

**Comment by parkjohnston** [comment]
d5212166a6aa7d5b138efb6a21478b158aabe337
