### ISSUE TITLE
(PT135)  --  Parsing Error Concern

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#324]
Parsing Error Concern? 
Case 2016-REP-09-0087
In the case below the name does not appear correctly in the case? Discovered this when comparing reports from new and old system, the name shows incorrectly on the new report.

![image](https://cloud.githubusercontent.com/assets/24595073/23862027/4adb3dce-07e2-11e7-9323-901060a5f92a.png)

**Comment by altrdgenetics** [comment]
i moved the prefix over with the first name. The rule for this was find all of the ones that have prefix that do not end with a period. There was a few others that were brought over like Mayor and Sheriff. But they are adjusted.
