### ISSUE TITLE
(PROD2)  --  CMDS docketed file issue

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#327]
In CMDS, when a file is docketed into the system, the File is named using the second of the two type dropdowns (EX: 1489421012548_Motion To Continue.pdf)  where as the activity file extention lists the file using both types (EX : 1489421012548_J - Motion To Continue.pdf)

**Comment by anthonyperk** [comment]
This has been confirmed from Di.  She is correctly docketing the files, however the files are being named one way and the file path is being named a different way (as stated above)

**Comment by parkjohnston** [comment]
its being a fickle little bitch

**Comment by parkjohnston** [comment]
jackpot..finally found the issue was passing type not type2...DUMB
