### ISSUE TITLE
(PROD3)  --  CMDS Letter generation issue

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#328]
CMDS Tab -> Documents Button -> Report and Recommendation -> Lack of Jurisdiction over Parties -> Appellant FTA
Case: 2017-RED-02-0011

When generating this letter, WORD will either hang in the background, or it the small 'File Locked' box will appear in the background.  The letter will not FULLY generate either way (opening a read-only copy will populate some bookmarks but not others).

**Comment by altrdgenetics** [comment]
there was an issue on null object, not nulls inside of the object, just the entire object being not set.
