### ISSUE TITLE
(PROD5)  --  CMDS Hearings tab Date/Times are not imported correctly

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#330]
CMDS – 2017-RED-02-0011:

The “hearings” tab shows the PH date as 4/1/17.  The PH was REALLY today 3/13/17 – notice that was sent out 2/22/17 reflects this date and the calendar entry showed up on the right day.  Any idea how/why it is showing up with a different date on the hearings tab?  I am crossing my fingers that this is an isolated weird incident.

**Comment by anthonyperk** [comment]
This is correct in the 2.0 system/database, however importing of the 2 string columns was flubbed and was incorrectly merged.

**Comment by altrdgenetics** [comment]
this is fixed now. parsing of string to date was the issue here. Luckily all of the dates were setup in the same format for these columns so some assumptions could be made from a column by column basis.
