### ISSUE TITLE
(PROD1)  --  Document timestamp format change

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#331]
All Timestamped Documents:

The timestamp in the documents shows military time. The Timestamp also does not show the day of the week 

3.0 example: 03/10/2017 16:44:20 PM SERB
2.0 example: Tue, 22 Dec 2015  11:10:21   AM - SERB

NOTE: keep the date as MM/DD/YYYY

**Comment by altrdgenetics** [comment]
adjusted the datetime
