### ISSUE TITLE
(PROD7)  --  File Email "To:" field autopopulate

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#333]
When filing an Email, IF an ALJ is assigned to the case, the To: field should auto-populate to the ALJ that is assigned.

EX: 2016-REP-11-0107
Sarah Cole is the current owner of case (she is an ALJ), and because of that, the To: field should auto-populate with her name (current dropdown has REP workers)

**Comment by parkjohnston** [comment]
This has been open and closed several times. Everything was done in accordance to the list Justin provided which was approved

**Comment by parkjohnston** [comment]
#149

**Comment by parkjohnston** [comment]
the code for this works 100% it is a user role issue.

Sarah Cole is not a rep section worker and does not appear in the field to combo, so how can something be selected that is not there....

marking as a non-issue

**Comment by altrdgenetics** [comment]
2.0 Code, does not use REPWorker table.

```
    public void loadCurrentOwnerVec(){
            REPCurrentOwnerData rep = new REPCurrentOwnerData();
            lrsVec = rep.getaljDataRecordSet(Global.getLogger(), Global.getDba(), Global.getREPCurrentOwnerTableName(), "Active = '1'", "Name ASC", 0, 0);
    }

    public void loadCurrentOwnerCombo(){
        REPCurrentOwnerData alj;
        UlpLRSData lrs;

        long count = lrsVec.getCount();
        long index = 0;

        lrsVec.seek(1, true);
        //action = false;
        REPCaseInformationUpdate.getCurrentOwner().removeAllItems();
        REPCaseInformationUpdate.getCurrentOwner().addItem("");
        while (index < count) {
            alj = (REPCurrentOwnerData) lrsVec.read(true);
            REPCaseInformationUpdate.getCurrentOwner().addItem(alj.Name);
            index++;
        }
    }
```

**Comment by parkjohnston** [comment]
DUMB old system....
