### ISSUE TITLE
(PT139)  --  Party migration issue (duplicate Employer Assistant)

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#335]
2016-REP-09-0082
Data transfer error from SMDS 2.0 (Employer – it duplicated the assistant)
See example below.
![image](https://cloud.githubusercontent.com/assets/24595073/23876944/4b2ae34a-0816-11e7-80c0-8f202cc091d4.png)

**Comment by altrdgenetics** [comment]
this was cleaned up already.... issue with the migration and the reuse of objects. Needed to encapsulate all objects differently to achive the desired result.
