### ISSUE TITLE
(PT140)  --  Inactive Election Report issue

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#336]
Inactive Election Report
Date Range 01/01/2016 - 3/12/2017 Record Count should be 1 not 17.
1. The report title is spelled wrong please change to “Inactive Election Report” on the report header.
2. Case 2016-REP-10-0103 is missing from the report

**Comment by anthonyperk** [comment]
-Header Spelled Correctly
-2.0 Looking for CaseActive column, doesnt seem to be in 3.0.  Ask Andrew

**Comment by altrdgenetics** [comment]
Talked about in the meeting, We do not necessarily need to add that column back in. Brought up that the active report does not use that column... but the inactive one does. They are aware that this is still in progress

**Comment by altrdgenetics** [comment]
JUSTIN EMAIL:

> Anthony is still investigating, one of the fields was deemed not needed in 3.0, however the report was using it in 2.0… May not be needed
> 
> Report filters:
> 
> -          Tally count date (Start and end date parameters)
> 
> -          Final Board Meeting Date (populated)

**Comment by anthonyperk** [comment]
This has been fixed:

WHERE
   (REPCase.ballotsCountDate BETWEEN  $P{begin date}  AND  $P{end date}  )
   AND REPCase.finalBoardDate IS NOT NULL

Also tweaked the Tally Date field to show the whole date
