### ISSUE TITLE
(PT141)  --  Investigator Active Cases Status Report issues

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#337]
Investigator Activity Cases Status Report
1. The User dropdown contains more than REP workers.
2. The record count does not match the 2.0 report. See example. It should match the old report.

**Comment by anthonyperk** [comment]
Will not run for me during test, this is because it uses the UserID parameter, when it should use the SectionUserID parameter.  Will test with Andrew

**Comment by altrdgenetics** [comment]
anthony is smoking the crack rock, and im doing meth....
