### ISSUE TITLE
(PROD008) - Detailed Activity View Load issue

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#338]
On crazy old items that have the UserID as SYSTEM (think intelliview import). There is no link to the usertable to it fails to load the information due to the join in the SQL statement.

**Comment by parkjohnston** [comment]
Example case number?

Suggested result: if returns a failed join just put a blank?

**Comment by parkjohnston** [comment]
if(((DefaultComboBoxModel)box.getModel()).getIndexOf(toAdd) < 0) {
  box.addItem(toAdd );
}

**Comment by parkjohnston** [comment]
Reopening due to a bug that was found affecting about 2-3% of entries...which is A LOT of entries in the grand picture. 

It is something that is a bit edge case, but needs to be fixed
