### ISSUE TITLE
Popup window location

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#34]
I just noticed this on the popup windows if the application is on monitor #2 the popup for adding new whatever will show up on monitor #1 in the default location (like location = null) instead of center on top of root panel.

**Comment by parkjohnston** [comment]
@altrdgenetics What window?

**Comment by altrdgenetics** [comment]
Cancel Dialog, party information (from party table)

**Comment by parkjohnston** [comment]
This issue closed, but all remain open as all dialogs will need to be checked at some point to ensure all handled properly
