### ISSUE TITLE
(PROD011) - Email notification when new email is docketed

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#341]
Staff Email notifications.
When the clerk’s office docket a case, an email notification should be sent to the Administrative Law Judge, if one is assigned. Currently, the REP and ULP staff are getting this notification. I believe this is happening because they were originally in the same list. Only staff assigned to a case with the ALJ Checkbox (in the users table) should be sent an email notification.

![image](https://cloud.githubusercontent.com/assets/8847344/23961083/3162241c-0980-11e7-9e89-993ea56dcfdf.png)

For REP Cases….
Current owner with ALJ Checkbox populated

![image](https://cloud.githubusercontent.com/assets/8847344/23961089/37c20e1c-0980-11e7-8e9e-2b2d83b5177d.png)

For ULP Cases … Users listed in the ALJ drop down box (have the ALJ checkbox populated) See image on next page.

![image](https://cloud.githubusercontent.com/assets/8847344/23961096/3dbcaad4-0980-11e7-958a-eeafa2e79249.png)

For CMDS, The ALJ listed in the ALJ drop down box.

![image](https://cloud.githubusercontent.com/assets/8847344/23961104/45c47afe-0980-11e7-95c0-cf7acc3b7358.png)

**Comment by parkjohnston** [comment]
This may override other information we have been given, but will review past information

**Comment by parkjohnston** [comment]
this is also incorrect...Justin has no idea how the system works....not saying we are not at fault, we are, but he is making up statements about what works and what does not

**Comment by parkjohnston** [comment]
The below text is what we were provided from Justin, was written into an email that XLN sent. 

This email is an direct contradiction of the above information.  

REP: 

Stated below to go to hearing person only, but above is stated to be current owner?

ULP:

Is fairly stated.

We need an actual answer before i fix this for no reason.

Justin,

· When an email is docketed, we are going to auto populate the TO drop down based on the LRS/Investigator/etc in each section for the person assigned per case. Could you please provide use with the location in each section that we should use to populate this data?

In the ULP section, auto assign the TO: field to the Status > Investigator field. If Status > ALJ field is populated choose this instead. An email should be sent to the assigned ALJ only.

In the REP section, auto assign the TO: field to the Information > Current Owner field. If Board Status > Hearing Person Assigned field is populated choose this instead. An email should be sent to the assigned ALJ (Hearing Person) only.

In the MED section, the TO: would auto assign to Mary Laurent. There is not a field for who is assigned to the MED case. I thought we decided in a meeting to add this field to MED. There is also not a field for assigning an ALJ in this section (which is not currently needed).

In the ORG section, the TO: field is pulling from who is assigned to work on ORG. No email sending needed.
In the CIVITAS section, the TO: field is pulling from who is assigned to work on ORG. No email sending needed.

In the CMDS section, auto assign the TO: field to the Case Information > ALJ field. Also send an email to the assigned ALJ.

· When an email is docketed we are going to send an email to the assigned person as well, should that just be to the user that is in the TO combo box? Would this be the same for all sections?

With these questions answered we can completed the docket system.

Thanks.

Anthony Perk
Network and Systems Engineer
XLNsystems
614-947-3607

**Comment by parkjohnston** [comment]
Any feedback? Would like to have answer so we can get this in for monday...i know that it is out of our hands

**Comment by parkjohnston** [comment]
Are we still waiting???

Really getting slowed down by lack of response from SERB

**Comment by altrdgenetics** [comment]
We got an email about this... Email oldest on top. Replied asking for clarification referencing earlier comments.


> Angela,
>  
> Regarding the outlook email notifications when items are docketed into REP and ULP cases, this was a programming error by XLN. The notification emails were only to be sent to Administrative Law Judges when they were assigned to the REP or ULP case. A ticket was submitted to XLN early last week to correct this error.
>  
> If you need to discuss further, please let me know.
>  
> Thank you, 
> Justin Brown


> Okay,
>  
> I wanted to make sure, however, that we do not lose the ability to get the alerts whenever a new REP case is created as we had before. 
>  
> Angela Phelps-White


> XLN Team,
>  
> I wanted to share the concern below with you and to confirm that this functionality is already built into the SMDS 3.0 application
>  
> Thank you,
> Justin Brown

**Comment by parkjohnston** [comment]
This is not an issues with XLN programming as stated in the first listed email, it was a lack of him understanding what he sent us.  We are now wrongly being blamed for his work....we need to fix that statement

**Comment by altrdgenetics** [comment]
ONLY CHANGE FROM ORIGINAL DOCUMENT BASED OFF OF EMAILS

```
For REP Cases…. 
OLD: Current owner with ALJ Checkbox populated 
Revised: Hearing Person Assigned field
```

**Comment by parkjohnston** [comment]
Will implement and then have to change it 10 more times :)
