### ISSUE TITLE
(PROD014) - Org Docketing - Org name no longer displaying in dropdown (dup???)

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#344]
Issue: The Org Name no longer displays
In ORG docketing, 3.0 was fixed so that when you entered the ORG Number (1615), then the ORG Name would automatically display.
This function is no longer available. When you type in 1615, there is now a drop down box for Item 1 – Item 4.

![image](https://cloud.githubusercontent.com/assets/8847344/23961247/b952e91a-0980-11e7-9320-82e6017aa43c.png)

It should display “Utility Workers Union of America Local 351.

![image](https://cloud.githubusercontent.com/assets/8847344/23961253/bec20156-0980-11e7-9bd9-9db054192d50.png)

**Comment by parkjohnston** [comment]
Interesting that it would just stop working...

**Comment by parkjohnston** [comment]
Will openly admit that the code that was working for this was ONLY in email so this is an incorrect statement that it ever worked.  It only ever worked for EMAIL
