### ISSUE TITLE
CMDS Add Activity Truncation

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#349]
User: erin.e.conn
Class Name: parker.serb.sql.Activity
Method Name: addCMDSActivty
Exception Type: SQLServerException
Exception Short: com.microsoft.sqlserver.jdbc.SQLServerException: String or binary data would be truncated.

**Comment by parkjohnston** [comment]
We need more data on this...cant fix it without knowing what types/file name etc, she was trying to add.  Will keep searching, but really need her input/help

**Comment by altrdgenetics** [comment]
So talking to erin to get more information about the filing of the CMDS cases. When entering in casenumber this was not tied to the group number of the case. So what happend is she entered in multiple numbers into the casenumber field in the docketemail.

Looking at the save information it looks like it is pulling from global case number and not the casenumber of the case from the docket loop... will keep looking to see if i can find any additional information

**Comment by altrdgenetics** [comment]
Also with that being said looking at the System Error Table I see a message with that addCMDSActivity exception....

User: erin.e.conn
Class Name: parker.serb.sql.CMDSCase
Method Name: getGroupNumber
Exception Type: SQLServerException
Exception Short: com.microsoft.sqlserver.jdbc.SQLServerException: The result set has no current row.

**Comment by parkjohnston** [comment]
This should be good to go....would like to release it and see what happens...may be small tweaks here and there.
