### ISSUE TITLE
(PROD016)  --  Activity Delete button visibility issue

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#351]
Issue: The MED Section delete button visibility I believe is not working correctly. If I switch to a different section and back to med it works fine as I click on the tabs. But if I go to detail view and back to activity tab it disappears and stays hidden.

![image](https://cloud.githubusercontent.com/assets/24595073/23966831/3433095a-0993-11e7-9f9b-04a8d067162b.png)

**Comment by anthonyperk** [comment]
Jeannette had a similar issue on CMDS where the DELETE button was not visible no matter what you did.  I switched her to the SERB.jar from Alpha.jar for the hell of it and the DELETE button was visible again.

**Comment by parkjohnston** [comment]
Should be resolved....will continue to monitor all edge cases users manage to find.
