### ISSUE TITLE
(PROD017)  --  Newspaper Rejection Letter not to pre-populate the TO: field

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#352]
Issue: The MED Section letters. Mary has one letter that does not go to any of the parties. It is the Newspaper Rejection Letter. We accidentally sent it to both parties today. Yes this is a training area… Can this letter be hard coded not to prepopulate the parties “to:” field? Or does that go against the way it is coded?

![image](https://cloud.githubusercontent.com/assets/24595073/23967068/f1941cd2-0993-11e7-8113-61d287159190.png)

**Comment by altrdgenetics** [comment]
During discussion of the Letter Generation process it was specifically asked FOR MED ONLY to auto select "TO:"...  We can of course remove that, at a cost.

**Comment by parkjohnston** [comment]
dumb shits...

**Comment by altrdgenetics** [comment]
Justin wants this one specific file to not auto populate to anyone

**Comment by altrdgenetics** [comment]
he also wanted it to grab based on id so he can tweak the wording of the row

**Comment by altrdgenetics** [comment]
30min of work
