### ISSUE TITLE
Docketing attachments for CMDS Email on groups

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#355]
FileService.docketCMDSEmailAttachment(...);   

This does not currently support copying the attachment to many cases within a group. It will only docket to the cases manually typed in. NEEDS CMDS GroupNumber Support

**Comment by altrdgenetics** [comment]
this was found by doing research for #349

**Comment by parkjohnston** [comment]
continuing this effort...WAY TO MANY LINES TO UPDATE for the CMDS handling of everything.

Other ticket for groups took a long while

**Comment by parkjohnston** [comment]
have attachments in test...

Bresco again hit a wall and can't get up or down anything without 30-60 seconds to load.

**Comment by parkjohnston** [comment]
Will try again in the morning, before closing.

This is important want to get it out...NEED to get it out

**Comment by parkjohnston** [comment]
This always worked, but was a result of the groups not properly working...resolving #349 had fixed this
