### ISSUE TITLE
Last Case loaded not automatically loading (from default section) when re-launching the application

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#356]
When you are in your default section, and have a loaded case, and exit the application, the application does not reload the last case loaded automatically.

**Comment by altrdgenetics** [comment]
Somewhere between setDefulatTab() and setHeaderCard() method the casenumber nulls out on inital load. By the time it gets to setHeaderCard() validate casenumber it is 'null-null-null-null'

```

public RootPanel() {
        initComponents();
        setIconImage( new ImageIcon(getClass().getResource("/SERBSeal.png")).getImage() );
        addListeners();
        Global.root = this;
        User.findAppliedRoles();
        enableTabs();
        setDefaultTab();
        Global.activeSection = jTabbedPane1.getTitleAt(jTabbedPane1.getSelectedIndex());
        User.updateLogInInformation();
        setHeaderCard();
        enableButtons();
        letterQueueThread();
        Global.activeUser.activeLogIn = true;
        setLocationRelativeTo(null);
        setVisible(true);
    }
```

**Comment by altrdgenetics** [comment]
ok so it is only in the setHeaderCard() method. At the start of the method with a println the casenumber for global is correct, then once it goes into the switch statement it fails out on the null.
