### ISSUE TITLE
Party Type Dialog

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#36]
When adding a party to a case the Party Type is not centered in the application when it loads (location == null). 

Also there is an overhang of text on names too long. see attached image.

![screenshot 39](https://cloud.githubusercontent.com/assets/8847344/16735254/6deb7da8-4756-11e6-822a-2d16e0600674.png)

**Comment by parkjohnston** [comment]
Due to employer names (companyName) being used the names tended to over flow tradition name length.  Data change over time...properly handled now
