### ISSUE TITLE
Detailed CMDS activity entries

### ISSUE THREAD

**Issue by parkjohnston** [CurrentlyNotSet/SERB#360]
Need to provide the ability to allow users to update CMDS docket entries.

**Comment by parkjohnston** [comment]
have this in flight...will be ready next release.

Really sucks how different CMDS is compared to 95% of the rest of the application

**Comment by parkjohnston** [comment]
Need to update CMDS activity from docket to store "type"

**Comment by parkjohnston** [comment]
and need to update for several more things as well 

From
To

**Comment by parkjohnston** [comment]
comment is always be blank as following CMDS practices, it gets merged into the longer text

**Comment by parkjohnston** [comment]
They will bitch about aspects of this, but it is all done for certain reasons to fit updated controls.

Hopefully they dont bitch :)

**Comment by anthonyperk** [comment]
Tried this in the latest build (3/20/2017) and the dropdowns exist, however they (Category and Description) are not editable when I click on the Update button.

**Comment by parkjohnston** [comment]
Was the item filed through docket?

If it was not then they should NOT be able to be used as the information
was not gathered to determine type and category.

**Comment by parkjohnston** [comment]
This is understanding how the system works, not just that things are not enabled...it is that way for a reason

**Comment by anthonyperk** [comment]
In 2.0, the system gave the user the ability to change the "Entry Type" and "Entry Description" for (what looks like) any activity entry (even System generated Activities/Histories like 'Initial Case Preparation')

![image](https://cloud.githubusercontent.com/assets/24595073/24151803/25d6cca2-0e20-11e7-8c77-1c7c696e6120.png)
As well as things that are docketed

However 3.0 will not allow for changes for any Activity, even activities that have been docketed
![image](https://cloud.githubusercontent.com/assets/24595073/24151999/b3bf094e-0e20-11e7-8008-b5bec9810d53.png)

Also, it is missing the comments box that used to be there in previous releases:
![image](https://cloud.githubusercontent.com/assets/24595073/24152066/f5fc5e92-0e20-11e7-98c4-22295f8694ce.png)

I understand and agree that in 3.0 users shouldn't have the ability to change the types/information for things that are system generated, however it looks like nothing is able to have their types changed in the latest release.

**Comment by parkjohnston** [comment]
Try something that was docketed....

**Comment by parkjohnston** [comment]
The detail box you are showing is in fact wrong. Please ensure you are running the most updated version

**Comment by parkjohnston** [comment]
Also in all CMDS areas. Comments are not used. It is Extra text which should not need updating. 

If they are messing up that bad in the clerks office they need training not us building a system to hide their errors
