### ISSUE TITLE
Docketing Section

### ISSUE THREAD

**Issue by parkjohnston** [CurrentlyNotSet/SERB#365]
Not sure if this is expected, but sections in docket are ending up the following:

![screen shot 2017-03-18 at 9 28 21 am](https://cloud.githubusercontent.com/assets/3246562/24072446/53ebf852-0bbd-11e7-91e9-d3fc5e2f0a1a.png)

**Comment by parkjohnston** [comment]
Just caught my eye and if it should be that way just close it out...just dont want them to be missing stuff!

**Comment by altrdgenetics** [comment]
Parker... Not a bug its a feature. the ERRO section is the XLN test section. We currently use that to send the crash emails. But since it is not tied to anyone else, I am also using as my IN/OUT section test so it does not get tied to anyone else. The email it is associated with is Test.Docket@...

**Comment by parkjohnston** [comment]
Sounds good...just wanted to make sure that it is not an issue...sorry!
