### ISSUE TITLE
ALL - Buttons

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#368]
The buttons do not enable properly when creating a new case unless on activity tab

Part of the '(PT016) Tab Selections #204' ticket

**Comment by altrdgenetics** [comment]
this is the same as "CSC - CSC Information tab. #367" Closing out that ticket as a duplicate as this is the META ticket.

**Comment by parkjohnston** [comment]
Should be easy to implement..just have to change ~10 lines a section 

CMDS is done
