### ISSUE TITLE
(PROD019)  --  Job title being loaded into Prof. Designation

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#369]
Issue: When a new party is created. The user populates the job title with “superintendent” (as an example). When the party is added to the case, the job title is populating the Prof. Designation field.

![image](https://cloud.githubusercontent.com/assets/24595073/24117753/cf50645e-0d81-11e7-909e-8bb575e8ca7d.png)

**Comment by parkjohnston** [comment]
this relates back to them wanting the order changed, but not wanting the SQL for certain things changed.

Working on it
