### ISSUE TITLE
Issue with original Fact Finder not being placed.

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#37]
There is a null pointer that shows up with. Everything on the panel was updated in one go. So the save button needed to save all of that information. I do not know, maybe it is a server overload for the SQL statement calls. I believe this is the same issue with conciliator tab.

![screenshot 45 - copy](https://cloud.githubusercontent.com/assets/8847344/17403824/603f731a-5a27-11e6-8231-ad77a1eac068.png)
![screenshot 45](https://cloud.githubusercontent.com/assets/8847344/17403825/604f5f64-5a27-11e6-98c9-3a8da08f344c.png)

**Comment by parkjohnston** [comment]
The overall bug here was not for the described issue..it was actually for a missing line in the detailed entires
