### ISSUE TITLE
(PROD021)  --  Email too large notification

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#371]
In SMDS 2.0 the public records screen displayed the file size of the files to assist users with keeping files under the email limit. The new application does not display the file size. Please add this column to the Public Records view.
Also add the prompt to notify the user that the email is too big to email. It may be wise to keep the limit at 24 MB even though our system can handle larger due to the receiver not being able to handle larger attachments. Do you have a recommendation?

![image](https://cloud.githubusercontent.com/assets/24595073/24120648/bcc50fba-0d8b-11e7-89fe-8136665a4f0a.png)

![image](https://cloud.githubusercontent.com/assets/24595073/24120653/c0b9b2d8-0d8b-11e7-9436-255115e30c6d.png)

**Comment by parkjohnston** [comment]
related to #363

**Comment by altrdgenetics** [comment]
I have added this feature back into the public records table. It did not actually function properly before.
