### ISSUE TITLE
Unparsable Date error - CMDSResponseDueDateDialog

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#374]
User: erin.e.conn
Class Name: parker.serb.CMDS.CMDSResponseDueDateDialog
Method Name: jButton2ActionPerformed
Exception Type: ParseException
Exception Short: java.text.ParseException: Unparseable date: ""

**Comment by parkjohnston** [comment]
in progress

**Comment by parkjohnston** [comment]
Simple testing required when back to my laptop

**Comment by parkjohnston** [comment]
found a larger issue when a new CMDS case is created it was not set to open...corrected that
