### ISSUE TITLE
(PROD024)  --  Time format in body of Calendar Invite 

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#375]
Issue:
Jim submitted a ticket on my desk on 3/14 regarding the CMDS calendar invites. The time is correct for the start and end time, however in the body of the calendar invite it is using military time. I am unable to confirm if this is still an issue without creating another hearing.
“There has been a PH scheduled for 2017-IDS-03-0017 on 4/12/2017 at **14:00:00** PM”

**Comment by altrdgenetics** [comment]
This is on the email server side

**Comment by altrdgenetics** [comment]
simple formatter change, H -> h
