### ISSUE TITLE
(PROD025)  --  DatePOSent bookmark to be spelled out

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#377]
The [DatePOSent] bookmark on the “Reinstatement 2nd to be mailed PO Letter” needs to be spelled out.
![image](https://cloud.githubusercontent.com/assets/24595073/24167347/d0396dd6-0e4c-11e7-9477-34d980fc96e0.png)

**Comment by altrdgenetics** [comment]
finished this
