### ISSUE TITLE
(PROD026)  --  FF Report Due Date filed missing from Fact Finder Panel in MED

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#378]
The FF Report Due Date field is missing from SMDS 3.0. It should auto populate 14 calendar days, but allow the user to adjust if falls on a holiday. This field should populate the [FACTFINDERREPORTDUEDATE] bookmark.
New System
![image](https://cloud.githubusercontent.com/assets/24595073/24167442/25466d6a-0e4d-11e7-82bf-ef0aff83bfc7.png)

Old System
![image](https://cloud.githubusercontent.com/assets/24595073/24167446/29edcc5a-0e4d-11e7-88c1-db1a69e7b05a.png)

**Comment by altrdgenetics** [comment]
> Justin,
> 
> I am aware that the field is no longer available to the user in 3.0. The Issue of [FACTFINDERREPORTDUEDATE] not generating on templates was brought to our attention last Monday. During that time I looked into the issue and sat down with Mary and discussed the field.  I thought that field might have been what is called 'FF Report Issue Date'. She has told me that this is a different field all together and is not the same one, due to its location of surrounding fields.
> 
> The conclusion that we came to was to take the 'Appointment Date' and calculate it 14 days out (moving forward on weekends to the following Monday) in the code when generating the letters and it was not necessary to have it as a displayed/editable field shown on the application. I brought up the concerns of holidays and said that she could change them in the template after it has been generated but she said she rarely had the 14 days fall on a holiday.
> 
> With that being said, is this a request to put that field back onto the screen and be visible to the user overriding the discussion and agreement I had with Mary last Monday?
> 
> - Andrew

**Comment by altrdgenetics** [comment]
Received from Justin:

> XLN Team,
> 
> I spoke with Mary and Tammy. They agree with you to proceed with the 14 day calculation instead of having the field in the database. This was brought to my attention today because she believed it was not calculating 14 days.
> 
> When I tested case 2015-MED-09-0945 The appointment date was 8/15/2016…. The Due Date in the letter was 8/19/2016 (4 days)…
> 
> Bookmark: [FACTFINDERREPORTDUEDATE]
> 
> The conclusion that we came to was to take the 'Appointment Date' and calculate it 14 days out (moving forward on weekends to the following Monday) (Since we work Mon-Fri there would not be a weekend appointment) in the code when generating the letters and it was not necessary to have it as a displayed/editable field shown on the application. I brought up the concerns of holidays and said that she could change them in the template after it has been generated but she said she rarely had the 14 days fall on a holiday.
> 
> Example
> Appointment Date: 3/21/2017
> Report Due Date: 4/4/2017

**Comment by altrdgenetics** [comment]
Turns out When i was adding the days... I didnt not his the ONE key hard enough, the code did show 4 days in advance.
