### ISSUE TITLE
(PROD028)  --  Fact Finder/Conciliator issues

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#380]
Mary sent out a Fact-Finder Appointment letter for Case 2016-MED-09-1073. The Fact-Finder did not get CC’d on the outgoing email. The Fact-Finder also did not appear in the CC list on the letter. The system also needs to account for when a replacement Fact-Finder is issued.
Letters Affected: Fact-Finder Appointment Letter, Fact-Finder Appointment SERB (Discretionary)
After Pulling up this case I discovered that The Fact Finder Selection is blank. There may be an issue with this staying populated after the save. I am also not sure if this affects the statement above.
![image](https://cloud.githubusercontent.com/assets/24595073/24167526/70e57be4-0e4d-11e7-90b6-ad60d9f0503a.png)

Mary sent out a Conciliator Appointment letter for Case 2015-MED-09-0945. The Conciliator did not get CC’d on the outgoing email. The Conciliator also did not appear in the CC list on the letter. The system also needs to account for when a replacement Conciliator is issued.
Letters Affected: Conciliation Appointment Letter, Conciliation Appointment Letter SERB (Discretionary)
After Pulling up this case I discovered that the Conciliator Selection is blank. There may be an issue with this staying populated after the save. I am also not sure if this affects the statement above.
![image](https://cloud.githubusercontent.com/assets/24595073/24167540/78a42d30-0e4d-11e7-8e0e-807f8aca36bf.png)

**Comment by altrdgenetics** [comment]
this was not discussed during the letter Generation/Queue meetings, this is new functionality and not built into original quote. Will need specifics from Justin.

**Comment by parkjohnston** [comment]
Sorry for the confusion in picking this up...was testing it last night as i misunderstood the issue...thought it was a bug with stuff saving, but alas it was not!

**Comment by anthonyperk** [comment]
The Letters for this ticket are:

MED Appointment Letter
Fact Finder Appointment Letter
Fact Finder Appointment Letter MAD
Conciliator Appointment Letter
Conciliator Appointment Letter MAD

The 2 Fact Finder letters get the current selected Fact Finder in the bookmark, and the Conciliator letters get the current selected Conciliator

**Comment by altrdgenetics** [comment]
```
Party’s to CC by letter type

CC Mediator – Mediator Appointment Letter (SERB and FMCS)

CC Fact-Finder – Fact Finder Appt Letter, Fact Finder Appt Letter MAD (FF or Replacement FF)

CC Conciliator – Conciliator Appt Letter, Conciliator Appt Letter MAD (Concil or Replacement Concil)
```

**Comment by altrdgenetics** [comment]
Finished: 3hrs
