### ISSUE TITLE
Admin Panel  --  Issue with Parameters dropdown not containing all of the parameters

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#386]
The parameters dropdown in the Edit Document panel (Admin Panel -> SMDS Documents Button -> Edit Document panel) does not contain parameters such as 'begin date, end date, SectionUserID'.  When an admin changes something in the Edit Document panel, the dropdown entry for the missing parameter/group of parameters isnt there so it NULLs the entry.  

![image](https://cloud.githubusercontent.com/assets/24595073/24268729/26af5cd6-0fe5-11e7-922d-0da46b294be1.png)

**Comment by altrdgenetics** [comment]
updated the list from the parameters in the switch statement
