### ISSUE TITLE
BU search panel

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#387]
When creating a new BU there seems to be an issue on saving where the table does not update properly to reflect the new BU. It was not visible after adding / or reset the search... cant remember. havent tested it again since the issue was spotted during a meeting as a demo.

**Comment by parkjohnston** [comment]
tried to replicate this on information given, but can't seem to make it work.  Only thing i am away is that they are trying to enter it without a unit number?

**Comment by parkjohnston** [comment]
kept testing and on the information given could not get it..marked as invalid, but please change should something be needed.

Starting to wonder if it was a network issue, looking at all of the other timeouts that occurred yesterday.

**Comment by altrdgenetics** [comment]
So I was completely wrong about the location of the error. It occurred on the double click of the BU, instead of loading the information and performing the search it just loaded the default list making the user "search" again by typing something.
