### ISSUE TITLE
(PROD038) - (REP) - 'Activity Action editing ability'

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#401]
Issue: The Docketing activity entries are not appearing on the activity tab the way that the end users would like them to appear. The end users also do not have the ability to change the activity entries using a “freehand” document description type. A “Freehand” document description type is a document type that does not appear in the exisiting drop downs. This is useful for document types that are not common enough to appear in the dropdown.

**Issue 1) Docketing Tab – Freehand entries**
In the example below, The investigation staff would like the comments appended to the activity entry as they did in the SMDS 2.0 application.
They would like it to say “IN – Filed Exhibit B” instead of how they are shown below in two separate columns.

![image](https://cloud.githubusercontent.com/assets/8847344/24520548/de313bba-1556-11e7-817d-eae26e69052e.png)
Below is another example…
![image](https://cloud.githubusercontent.com/assets/8847344/24520555/e73b782e-1556-11e7-8f59-5ee20d86063f.png)
Please see continued details on following page….

In order to do this properly, I propose the following enhancements to the docketing functionality for both email and scan for all sections.
A) Make the docketing screen wider and the “type” column wider so that it can display the full spelled out type description (if there is room). If there is not enough room continue to use the type code. Once the type selection is made the user would have the ability to append text to the document type entry. This is called the “Type Appended Comment” column (see below). Please change the column name if a more suitable column name is thought of.
a. Example: Select “Exhibit” and user could add the “ B” to read “Exhibit B”
This field does have an unknown limited number of characters. The document name in the case file would have the same name in the G: Drive. “Exhibit B.pdf”
NOTE: Currently the files in the G: Drive are being named with the docketing “code” and not the “history description”. How will this be handled for “other” types of document types that are submitted via freehand? We want to keep it consistent.
Filename example on G: drive…. “NTN.pdf” not “Notice to Negotiate.pdf” XLN Concern: If we move to allow for the freehand typing of the activity field we will have the same issue that currently exists with old imported activities. Any activity that had their action retyped will no longer be able to automatically reflect any “activity type” changes made.
b. The comments field would still be available for additional comments about the document.
The comments field allows more characters than the type filed does. The comments section allows for senetences of text.
When “Other” is selected could the system omit “Other” text from the activity entry? The filename could would use the code “O”.

![image](https://cloud.githubusercontent.com/assets/8847344/24520576/f182463c-1556-11e7-9ebf-295bf5398e62.png)

**Issue 2) Activity Tab – Freehand entries**
The staff want the ability to “freehand” the document type (if it does not appear in the list) to change the Activity tab history entry. Staff change the activity entry that was docketed in the Clerks office if the document was docketed in error, or if there is a more specific document name for that document. This is also used when an unusual filing or motion type was filed.
In the field below, the user would select Update, Then change the type using the drop down. If the item is not in the drop down they would choose the drop down type “Other”, the User could change the entry by typing it in by freehand (just like the Clerks office in the example above). When “Other” is selected could the system omit “Other” text from the activity entry? The filename could would use the code “O”.
a. Example: Select “Exhibit” and user could add the “ B” to read “Exhibit B”
This field does have an unknown limited number of characters. The document name in the case file would have the “doc type code” + “Type Appended Comment” in the G: drive.
“14900730120670_EXH_B.pdf”
Another example:
“14900730120670_MOT_To_Withdraw.pdf”
b. The comments field would still be available for additional comments about the document.
The comments field allows more characters than the type filed does. The comments section allows for senetences of text.
c. The Action: field (which is what the history entry would look like), would also need the ability to be updated (by freehand). Changing this field would not change the linked document name on the G: drive.

![image](https://cloud.githubusercontent.com/assets/8847344/24520601/037d8f4a-1557-11e7-98c3-a11c722264c8.png)

Keep in mind the outgoing public records attachments display the filename as it appears in the G: drive. We should take this in consideration when naming the files.
![image](https://cloud.githubusercontent.com/assets/8847344/24520608/09325f60-1557-11e7-88e2-0d6d8058b9b3.png)

**Issue 3) Activity Tab – Link to open documents (location on screen)**
Would it be possible to move the “link to open the document” from the right part of the activity tab to the left part of the screen, as shown in the “mock” example below?
The purpose for this location change is to make it closer to all of the buttons. The user generally will have their mouse point closer to the left side of the screen verses the right side of the screen. This will decrease the amount of mouse movement to open the attached files.
![image](https://cloud.githubusercontent.com/assets/8847344/24520617/113f64e6-1557-11e7-9b97-4cd0fa5973f1.png)

**Comment by altrdgenetics** [comment]
We finally discussed this issue with SERB and it will be compromized on to the point where we are not putting in additional fields in the DB. Instead we will be 'gluing' lots of fields together 'to the user'. I have to get a modified proposal based on today's discussion back to SERB and they will approve it. Then we will be go on preforming the changes.

**Comment by parkjohnston** [comment]
This was how it was initial in CMDS before we spilt that all apart...just
as reference.

I would REMOVE the ability to really update types and such, just a warning

**Comment by altrdgenetics** [comment]
So in the mess end of last week we got an email... I thought we were solid, guess not:

> XLN Team,
>  
> Can we chat to confirm that I understand this correctly?  I would like confirm understanding then seek final approval so that you can move forward with this.
>  
> Thank you,
>  
> Justin Brown

**Comment by altrdgenetics** [comment]
Sent Email To Justin Reminding him we have a outstanding question on this ticket.

**Comment by altrdgenetics** [comment]
FROM JUSTIN:

PROD038 - Waiting on approval
This item has been approved to proceed as of this AM.

**Comment by altrdgenetics** [comment]
finished this out.
