### ISSUE TITLE
(PROD039) - New Case Notification for REP Cases.

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#402]
2) PROD 039
Both Debra and Angela should be receiving email notifications when new REP cases are added into SMDS 3.0. This is to expedite the process because the timeline begins the moment the case is received.
Can you add a checkmark in the user’s table as shown below to allow the ability to quickly change who receives this notification as personnel changes or vacations occur.
In SMDS 2.0 I believe this was hard coded into the system.

![image](https://cloud.githubusercontent.com/assets/8847344/24520716/71f355d6-1557-11e7-85b2-a24820c4c6c6.png)

**Comment by altrdgenetics** [comment]
This was left out of the system because it was not told to us when requesting what items should the users be notified on. Chris AND Justin questioned if this needs to go in since it will be a paid request. Citing they should be checking the mail log daily anyways and this 'convenience feature' is something that management should not really be paying for since it is a personal preference.

The question I had is since this will require DB modification does any other section require or would benefit from this as I only want to do a DB change on a production system ONCE. Justin will get back to us.

**Comment by altrdgenetics** [comment]
Angela would like new case email notifications for both REP and ULP sections. She is Ok with the solution below rather than multiple people being notified of a new case.

Would it be possible to generate a “new case” email notification to the selected staff in the dropdown when Clerks office assigns the current owner for the first time. From null to staff member?

The same functionality would be used for the ULP section when investigator is populated from null to staff member. 

The clerks office is instructed to always assign the REP and ULP cases to Angela and then she assigns the case to an investigator.

**Comment by parkjohnston** [comment]
Email...which i will forward states differently

**Comment by altrdgenetics** [comment]
still waiting on that email....

**Comment by parkjohnston** [comment]
Just got ready to send it now and re read it...the email i have is strictly for the auto assignment of TO on docket...it was asking what the process for NEW cases was.  

My bad...I do misread the email. 

#fail

**Comment by altrdgenetics** [comment]
Email to Justin:

> This would be possible. What I can't do is first time only, What would have to happen is any time the field goes from NULL => ID. So if you update the current owner to blank (NULL),  hit save, then hit update again and change the drop-down to a new user, then that new user would get the notification. If it goes from User to User, there would be no notification. Would this be acceptable?
> 
> - Andrew

**Comment by altrdgenetics** [comment]
> Yes this would be acceptable.  Rarely would it go from user to null to user. 
> 
> Thanks,
> 
> Justin Brown
