### ISSUE TITLE
(PROD047) - CMDS Docketing to multiple cases issue

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#407]
Issue:
Please let XLN know that docketing to 2 cases at one time is still not working in CMDS. It seems to be ok in other sections.
She did not specify if it was email or scan.

**Comment by parkjohnston** [comment]
This has me a bit worried about what the actual hell they are typing in.....

Looking into it now, I know it is marked as a question, but now i am just wondering what shit they are really trying to do.  Bored and inquisitive mind...

**Comment by parkjohnston** [comment]
Will NOT be putting it on a release, unless I can figure it out (if it is actually an issue)

**Comment by altrdgenetics** [comment]
Email From Justin:

> Erin experienced the issue docketing an email filing to these two case:
> 2016-REM-06-0115, 2016-REM-07-0146
