### ISSUE TITLE
(PROD044) - NEW CMDS reports

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#408]
Adding three new reports to CMOS Tab to eliminate the need for MS Access to generate stats.

**Report Name: Stats - Board Orders Issued**
From Case Table ~ All Board Orders sent between date range in prompt.
Group By: Result, sort oldest Board Order sent on top.
Group Count Total: for each record in each group.
Total Records Total: at end of report
Fields to display:
Case #
Open Date
Board Order Sent Date
Result

**Report Name: Stats - New Appeals Received**
From Case Table ~ All New Cases filed (open date) between date range prompts
Group By: Case Type, sort by file date, oldest on top
Group Count Total: for each record in each group.
Total Records Total: at end of report
Fields to display:
Case #
Open Date
Case Type

**Report Name: Stats - Days of Hearing Activity**
From Case History Table -7 All activity entries with Type Pwhere history entry date between date
prompts
Sort by case number, then by history entry date oldest to newest
Fields to display:
Case #
Activity Entry Date
Category
Action

**Comment by anthonyperk** [comment]
These three reports have been added to the database and the files are in the CMDS folder.  2.5 hours
