### ISSUE TITLE
(PROD043) - (REP) - Multiple applications running

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#409]
I received the request below from Angela. I just wanted to share with you and see what type of options we have regarding allowing this functionality.
I had the ability to have more than one window open of SMDS in 2.0. It appears that this is another functionality that I have lost. Is it possible to get that ability in 3.0. It was useful for me to have two windows open when performing my duties, especially since I have two screens.
Angela
Angela,
The SMDS 3.0 system is designed to allow a single user login session. I will look into the ability for multiple concurrent login sessions.
The only hesitation I can see with multiple concurrent sessions is the possibility to key data into the wrong case if two cases are open at the same time. Do have any concerns about that possibility? All staff would have this capability if we would proceed with allowing multiple concurrent login sessions. I also need to find out if there are any other possible concerns with allowing this capability.
Justin

**Comment by altrdgenetics** [comment]
We talked to Justin on the phone about this. We told him that there is no way that it could happen with the way the login system works and that he would have to give the users a second login.

He asked to talk about it again at a later time, it is the only reason why I am entertaining the idea of this ticket being open still.

**Comment by altrdgenetics** [comment]
Sent Email To Justin Reminding him we have a outstanding question on this ticket.

**Comment by anthonyperk** [comment]
Email from Justin:

> PROD043 - Not problem, did you still wish to discuss or can we close ticket?
> Please close
