### ISSUE TITLE
(PROD048)  --  Error on opening files in Mail Log

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#411]
Viewing files from the mail log do not open when in the ORG and Civil Service Sections. The mail log works in all other sections.
![image](https://cloud.githubusercontent.com/assets/24595073/24562205/fd6a075c-1617-11e7-8e8b-0fd8f3473da6.png)
![image](https://cloud.githubusercontent.com/assets/24595073/24562207/ff1f954e-1617-11e7-94fb-cc9f6119ab43.png)

**Comment by altrdgenetics** [comment]
fixed this. was grabbing wrong column. Instead of ORG Number + filename it was both filename
