### ISSUE TITLE
(PROD050) - Update and advance search issue.

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#413]
Jim was able to do an advanced search for “Wadin” to get this case to load and upon load it defaults to the notes tab and greys out all the tabs.
I was able to create this by being in update mode on another case, then right click case number, advanced search and load another case. Please disable the advanced search until the user saves their work before proceeding to search for another case.

![image](https://cloud.githubusercontent.com/assets/8847344/24614437/2f8c786c-1859-11e7-83a5-9b4fbda5f79c.png)

**Comment by parkjohnston** [comment]
So the issue is when he clicks update and then tries to search....

I need disable the search then?

**Comment by altrdgenetics** [comment]
yes
