### ISSUE TITLE
(PROD052)  - (CMDS) -  Party Information Report for Multiple Case Numbers

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#414]
In CMDS, Diana would like the ability to print the Report > Party Information Sheet for multiple cases at once. She had this ability in the previous CMDS application.

When running in old system
![image](https://cloud.githubusercontent.com/assets/24595073/24616545/74e89ab6-185f-11e7-9877-a1aa361cce21.png)

When yes is pressed
![image](https://cloud.githubusercontent.com/assets/24595073/24616555/7c9cea64-185f-11e7-92a8-373014fe9a49.png)

![image](https://cloud.githubusercontent.com/assets/24595073/24616559/7f94e082-185f-11e7-997d-d348cc368d03.png)

**Comment by altrdgenetics** [comment]
This existed in the old system, Needs to exist here too. The old system just ran the report multiple times. We will end up building a new report most likely to accommodate it into a single document.

**Comment by anthonyperk** [comment]
Testing on live system.  closing ticket
