### ISSUE TITLE
MED section - Bug, on loading FF & concil panels 

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#420]
When loading a MED Case while on either the Fact Finder panel or the Conciliation panel the drop downs for "selection" and "replacement" do not always load the selected party.

Case with data:  2017-MED-03-0374

When i switched back and forth between this case and another while testing the CC of the letters it would not always select the party from the dropdown. 

tabbing over and coming back to said tab while in the case selects the parties correctly

**Comment by parkjohnston** [comment]
I can check this out...if needed

**Comment by altrdgenetics** [comment]
no one has dibs on it yet...

**Comment by parkjohnston** [comment]
this is a 3.1 issue with the tabs they asked to be implemented.  

the loading methods were NOT expecting someone to stay on the tab but would load that combo when it was navigated to.  

Updating the commands now

**Comment by parkjohnston** [comment]
Actually, I retract that previous comment...testing like crazy and we are handling it all properly.

When i am doing testing, I can't reproduce the issue.

**Comment by parkjohnston** [comment]
finally found the issue...when typing the case number it works 100% of the time...when using the combobox to scroll and select is when it fails.

**Comment by parkjohnston** [comment]
this issue is hard to track down...really really intermittent, but have found a few other tweaks in the process of fixing this.

**Comment by parkjohnston** [comment]
continued work on several findings that may all be related...not wanting to shotgun it

**Comment by parkjohnston** [comment]
Could not make progress on this XLN server was slow last night...continued issues

**Comment by parkjohnston** [comment]
IM DUMB...

**Comment by parkjohnston** [comment]
this should be good, but want to watch usage before closing it out...i put in a few tracking lines to see usage and such...we will see what happens before an "official" update

**Comment by parkjohnston** [comment]
did not see any issues fired today, but want to check one more edge case...will be good this weekend officially

**Comment by altrdgenetics** [comment]
nothing has popped up from SERB, and it appears to be solved without them even knowing. Closeing it out and next time if it gets opened it will be via official ticket number
