### ISSUE TITLE
(PROD057)  - (ORG) -  45 Day letter list does not match Noncompliance report

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#432]
See below. When comparing the Non Compliance report with the recipients of the 45 day letter we discovered a discrepancy of one extra org being sent a reminder.

What we discovered is that if the FY End date is 12/1 thru 12/14/2016 the org would still receive a reminder letter even though they were compliant. If the FY End date was 12/15 thru 12/31/2017 they would drop off of the report like they were suppose.

**Comment by anthonyperk** [comment]
not sure if this is a report issue or the 45 day letter issue

**Comment by altrdgenetics** [comment]
Anthony's Email: 

> Justin,
>  
> Could you ask Licia (whom I am assuming found this issue) which ORG is missing, and is it:
>  
> 1)      Missing From the Report but SHOULD be there
> 2)      Missing from the 45 Day Letter List but SHOULD be there
> 3)      An extra on the report that SHOULDN’T be there
> 4)      An extra on the 45 Day Letter list that SHOULDN’T be there

Justin's Response:

> Anthony,
>  
> ORG 1704 was an extra org showing on the All letters >> 45 days notice letter box. It should not have shown there because they did file there 2016 documents. There FY end date was 12/5/2016
>  
> I had Licia test to see what dates the notice letters would generate.
> Any date between 12/1/2016-12/14/2016 the org would show that a letter needed to be sent
> Any date after 12/15/2016-12/31/2016 and the org would not show stating they were in compliance.
>   
> Thank you,
> Justin Brown

**Comment by altrdgenetics** [comment]
**And..... Emailed Justin:**

> Justin,
> 
> We have looked into this and it appears to be another discrepancy  between what the rule set provided to us is and what it actually should be. When loading the "compliance list" We copied the exact code over from 2.0 that was used to backdate the calendar information. It has always set the date to the 15th, and that is most likely where your discrepancy comes from.
> 
> if (letter.startsWith("Tickler 45")) {
>     cal.set(Calendar.DAY_OF_MONTH, 15);
>     cal.add(Calendar.MONTH, 1);
>     cal.add(Calendar.MONTH, -5);
>     processOverdueNumbers(cal);
> } else if (letterstartsWith("Tickler 10")) {
>     cal.set(Calendar.DAY_OF_MONTH, 15);
>     cal.add(Calendar.MONTH, -5);
>     processOverdueNumbers(cal);
> } else if (letter.startsWith("Tickler 31")) {
>     cal.set(Calendar.DAY_OF_MONTH, 15);
>     cal.add(Calendar.MONTH, -5);
>     cal.add(Calendar.MONTH, -1);
>     processOverdueNumbers(cal);
> }
> 
> What should the correct date difference Be? Do I need to be at the end of the month, the beginning of the month, or something different all together?
>  
> - Andrew

**Comment by altrdgenetics** [comment]
FROM JUSTIN:

> Andrew,
>  
> The correct answer is the first day of the month. There are only a few oddball orgs that have an Fiscal Year end that is not at the end of the month. That is why this was not caught sooner.
>  
> Thank you,
> Justin Brown
