### ISSUE TITLE
(PROD058)  --  ORG Single Letter button issue

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#433]
The ORG Single Letter button only generates a letter to the ORG Rep.
This button should generate the letters just like the All Org letters button except it only generates it for the Org that you are in.
It uses the same ruleset as the All Org Letters. It could send to Org, Org Rep, or both.

**Comment by anthonyperk** [comment]
Andrew is looking at the rule set for the button

**Comment by altrdgenetics** [comment]
>  Andrew,
> 
> Looking at the frequency that these letters are generated using the single letter button, I would like to choose option one.
> 
> 1)      We can add a popup box after selection of the information on the letter generation window to trigger the bookmark logic saying something along the lines of:
> 
> a.       “Do you want to send this letter to the employee organization rep?”   Y/N box…. If no send to the employee organization.
> 
> b.       (this will however require the user to go through the generation process 2 times if they want to send it to both the ORG and the REP due to current bookmark logic)
> 
> Thank you,
> 
> Justin Brown

**Comment by altrdgenetics** [comment]
preformed the change to the single letter to accomidate this.

**Comment by altrdgenetics** [comment]
30min labor
