### ISSUE TITLE
(PROD062)  - (MED) -  Mail Log (report and panel) are not 'in order'

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#436]
On the mail log viewer and the printed pdf report version the mail log items appear out of date order.

![image](https://cloud.githubusercontent.com/assets/24595073/24724268/838bf260-1a18-11e7-8e32-c888627e6e1f.png)

**Comment by anthonyperk** [comment]
This also affects the other sections.  One change for all sections

**Comment by altrdgenetics** [comment]
Emailed Justin:

```
Justin,

We are currently following the ORDER BY clause as presented in 2.0

2.0: " ORDER BY CaseNumber DESC, HISTORYID DESC"
3.0: " ORDER BY Activity.CaseYear DESC, Activity.caseMonth DESC, Activity.caseNumber DESC, activity.id DESC"

If you would like this changed, please provide the correct ORDER BY and their order of importance.

- Andrew
```

**Comment by altrdgenetics** [comment]
> XLN Team,
>  
> Thank you for the clarification.  I was able to confirm that this issue has arisen because the Clerk’s office is a little behind on docketing. That is why this has not presented itself sooner.
>  
> Can we tweak the mail log header as shown below by adding the word “Received”? Once this tweak is completed this ticket can be closed out.

**Comment by altrdgenetics** [comment]
30min labor

**Comment by altrdgenetics** [comment]
> Hang on…. There has been some new discussion on this.. Let me get it finalized.
>  
> Thank you,
>  
> Justin Brown

**Comment by anthonyperk** [comment]
Upon further review of the mail log, We request the following enhancements. 
 
1)      The “Date” header should be changed to “Received Date”
2)      Add a new column called “Docket Date” This will help clarify when things are docketed a day or two after they were received. Also it will assist when using a date range that consists of several days. 
3)      Please add a drop down filter that allows the entries to be filtered by the staff they are assigned to. This drop down list should mirror the “To:” drop down list for each section in the docketing screen.  By default it should display “All” unless user selects a name from the drop down

![image](https://cloud.githubusercontent.com/assets/24595073/24809079/63d51648-1b8c-11e7-9b39-51a2e973bbcb.png)

**Comment by anthonyperk** [comment]
Andrew, 
 
I understand this change will affect all sections. Can you accommodate the “Assigned to:” drop down request?
 
Regarding the mail log printed version, please do not add the new column due to space limitations. Please make the two changes in red. 

![image](https://cloud.githubusercontent.com/assets/24595073/24809101/7153cbb6-1b8c-11e7-97bf-e97f97954ffc.png)

**Comment by altrdgenetics** [comment]
FROM JUSTIN:


> Yes this is what they are wanting. The “assigned to” should also be reflected on the printed mail log.
>  
> Thank you, 
> Justin Brown


So they want Assigned to on the Header and as an option within the maillog window.

**Comment by altrdgenetics** [comment]
Code is done for this, Only report changes needed.

**Comment by anthonyperk** [comment]
Report changed and tested.  Waiting on new release
