### ISSUE TITLE
(PROD063)  - (MED) -  Advanced Search missing Employer Name for some entries

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#439]
We are noticing some new entries in recent cases have a blank employer name and union name. When I open the cases they do show.
![image](https://cloud.githubusercontent.com/assets/24595073/24809165/b0a820fa-1b8c-11e7-8086-d752a8039964.png)

![image](https://cloud.githubusercontent.com/assets/24595073/24809171/b44d360a-1b8c-11e7-96b9-a211effee66c.png)

![image](https://cloud.githubusercontent.com/assets/24595073/24809176/b7b6f7a4-1b8c-11e7-9b57-9021f1314a45.png)

**Comment by anthonyperk** [comment]
Question to Justin:

Justin,

    I have looked over the ticket and tried to replicate the issue and with the tests I have preformed I was not able to recreate the issue. Even with the example case number provided in the ticket I see the information in the case search window from SERB DB. 

    Now one thing that had been mentioned in the past is that in order to keep the case search data persistent per Statement of Work we have to hold that data and never update it unless the "Refresh" button is pressed on the right side of the search textbox.  Could it be possible that the information for those cases were added between the initial load of the case search data and the screenshots provided? 

- Andrew

**Comment by altrdgenetics** [comment]
Sent Email To Justin Reminding him we have a outstanding question on this ticket.

**Comment by anthonyperk** [comment]
Email from Justin:

> PROD063 - Waiting on confirmation of non-issue/staff training problem
> Please close
