### ISSUE TITLE
(PROD064)  --  Opinion Date in Hearings tab should not be a date picker

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#440]
![image](https://cloud.githubusercontent.com/assets/24595073/24809265/f7295fd0-1b8c-11e7-938c-3f8995ae9bb4.png)

**Comment by parkjohnston** [comment]
Glad to see this was found in the 4 months of use so far....including testing.....

**Comment by parkjohnston** [comment]
ALTER TABLE HearingCase ALTER COLUMN opinion varchar(50);

**Comment by parkjohnston** [comment]
Also need to validate that no data loss will occur on current information....what is the status of the old data? Reimport that column maybe? 

The current data that is in the system is a date, so the above example of what he is trying to enter is not accurate to past data.  Attached is what they currently are storing.
![screen shot 2017-04-08 at 9 29 54 am](https://cloud.githubusercontent.com/assets/3246562/24829364/05c4bc9a-1c3e-11e7-94ba-30ef16c73618.png)

**Comment by parkjohnston** [comment]
This has been completed as requested, but we may see it again
