### ISSUE TITLE
(PROD067)  --  Hearing person in Board Status Tab should be the ALJ's

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#443]
BOARD STATUS TAB-Hearing Person Drop Down
Need the ALJ’s names for Hearing Person. It should show all users with a ALJ checkmark in users table.
![image](https://cloud.githubusercontent.com/assets/24595073/24809445/90086336-1b8d-11e7-9ca3-bdc20ab797c7.png)

**Comment by parkjohnston** [comment]
Again....this was NOT found in the last 103 releases we have done so far?
