### ISSUE TITLE
(PROD071)  --  ULP Docketing To: field not populating

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#447]
On the ULP Docketing Screen the To: field is not auto populating based upon who the case is assigned to.
I confirmed this issue in the email, scan, and media docket screens.
It should default to the investigator unless an ALJ is assigned to the case.
![image](https://cloud.githubusercontent.com/assets/24595073/24810008/b1dfef82-1b8e-11e7-9645-a8a5b9614ba6.png)

![image](https://cloud.githubusercontent.com/assets/24595073/24810014/b46761fe-1b8e-11e7-9836-d48956ddf10b.png)

![image](https://cloud.githubusercontent.com/assets/24595073/24810019/b85f3ba6-1b8e-11e7-91f0-04fd9f3cc710.png)

![image](https://cloud.githubusercontent.com/assets/24595073/24810022/bae1f6c0-1b8e-11e7-8726-2866241c7b2f.png)

**Comment by anthonyperk** [comment]
ULPCase:DocketTo (ln;985)
checked for ALJ but not for Investigator

**Comment by parkjohnston** [comment]
Did you follow what was provided on the initial list from Justin? This may not be a bug based on that list that has previously been uploaded

**Comment by altrdgenetics** [comment]
Ya, I checked the previous list that had been posted, the email from Justin that you had anthony get. It checked the first one properly but the fallback was not there in the resultset... their wishy washy definitely didnt help this . i got it added in and was real easy to spot. I did test and verify the fix.
