### ISSUE TITLE
(PROD074)  --  PC Case Tracking issues

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#450]
SERB PC Case Tracking Spelling correction and other party not appearing on the report.
See example below.

![image](https://cloud.githubusercontent.com/assets/24595073/24864559/8ee09a68-1dd2-11e7-9017-816f408ca793.png)

![image](https://cloud.githubusercontent.com/assets/24595073/24864564/936ae444-1dd2-11e7-9c74-1bafec97cce8.png)

**Comment by anthonyperk** [comment]
Some of these must be scanned in oddly, they dont show as pictures....

**Comment by altrdgenetics** [comment]
Email to Justin:

> Justin,
>  
> Seeing as REP has Employee Org, Rival Employee Org, and Incumbent Employee Org; what should be the hierarchy of party types.  So If I have an employee org, that’s what will be printed, however if there is not an employee org, then which party type (Rival or Incumbent) should be the one I look for to be printed, then if that doesn’t exist which after that?

**Comment by anthonyperk** [comment]
Changed 'Recomendation' to 'Recommendation'

**Comment by anthonyperk** [comment]
Email from Justin:

> Anthony, 
> 
> I spoke with Erin. There could be any combination of parties for REP. Please list all that appear in the case. There could be multiples listed

Anthony's Response:

> OK I can do that.  Would the Intervener, Conversion School, and Petitioner be included with the Employee Org, Rival Employee Org, and Incumbent Employee Orgs?  Or is it just the three types of ORGs?

Justins Response:

> Yes it would. All types other than employer.

**Comment by anthonyperk** [comment]
Added the following Parties:

Intervener
Conversion School
Petitioner
Employee Org
Rival Employee Org
Incumbent Employee Org
