### ISSUE TITLE
(PROD075)  --   Mediator Appointments Report sort issue

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#451]
Mediation Monthly Stats – Mediator Appointments Report.
Please keep the existing group by mediator, please add the sort by employer name A - Z

**Comment by altrdgenetics** [comment]
> Does Mary also want to keep the report sorted by Assigned Date as well?  Currently I have it by Mediator Name A-Z, Then Assigned Date Oldest to Newest

**Comment by anthonyperk** [comment]
> Anthony, 

She does not need it sorted by assigned date. 

Thank you,

**Comment by anthonyperk** [comment]
Removed sorting by Assigned Date and Added sorting by Employer Name
