### ISSUE TITLE
(PROD076)  --  Files not found while using Public Records

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#452]
Public Records Request:
Issue - Cannot located files.
Example: ORG 1188 – Docs filed on 4/7/2017 and I processed them this morning (4/11/2017). The AR and FS both open fine.
Using Public Records tab, I get the following error message:

![image](https://cloud.githubusercontent.com/assets/24595073/24916060/10fa083e-1ea7-11e7-80ed-4460be811602.png)

The actual documents (AR, FS and ebody) open fine within the system, I can view them:

![image](https://cloud.githubusercontent.com/assets/24595073/24916091/27da0c2a-1ea7-11e7-9e66-2a49d4698f6f.png)

![image](https://cloud.githubusercontent.com/assets/24595073/24916068/17fd15e0-1ea7-11e7-96cb-07385ac2cd7d.png)

**Comment by altrdgenetics** [comment]
missed the orgnumber on the file check.
