### ISSUE TITLE
(PROD078)  --  CMDS Bookmark questions

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#454]
I need a cheat sheet for what each of these items link to. I am questioning if some may be linked to multiple questions. I am struggling with getting them correct on the template.
I need assistance with getting the proper questions for the highlighted two bookmarks.

![image](https://cloud.githubusercontent.com/assets/24595073/24930970/7882ba64-1ed9-11e7-8c56-e197f37e5fb4.png)

![image](https://cloud.githubusercontent.com/assets/24595073/24930974/7bd76f52-1ed9-11e7-9320-721159b49277.png)

**Comment by altrdgenetics** [comment]
emailed Justin the cheat sheet
