### ISSUE TITLE
CMDS WebUpdater

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#456]
It was requested to us to changed and re code the PBR Web Updater to be compatible with W10. SERB left it out of the statement of work so it is 100% an enhancement.

**Comment by altrdgenetics** [comment]
I have completed the application and integrated it into the email server. We submitted a sample SEQ file for verification after XLN verified it internally. We received a response that Jim believes the activity entry SEQ file contains too much information and that the SQL statement needs to be modified and trim down the list available to the web. We were requested to send a list of activities in CMDS cases to SERB.

We are currently waiting on a blacklist or whitelist of items they want displayed in the web updater.

**Comment by anthonyperk** [comment]
Email from Justin:

> XLN Team, 
> 
> Regarding the SPBR website update file. I am struggling to come up with an on paper solution because of all the potential variables and changes from each version of CMDS. 
> 
> So here is what I can share so far. I am wondering if you can apply this to your existing code to remove the few “extra” entries. We can then add the other exclusions as we find them. 
> 
> 1)      All “Incoming” docketed document entries should appear on the web.  (CMDS Activity Types)
> 2)      Generated “document created” messages do not appear on the website.
> 3)      Generated messages like “Added Party” “changed Party” “Set ALJ” do not show on website.
> 4)      The system generated “Case was Filed and Started” should show on the website.
> 5)      The “Case Closed” entry should show on the website. 
> 6)      The following CMDS History Types should appear on the web (marked with an “X”) 
> a.       Note: When a document is officially sent from the office Diana enters one of the entry codes below the day it is mailed. 
> 
> Keep	entryType	Description
> x	A	Notices
> x	C	R and R
> x	D	Final Board Orders
> x	E	Procedural and Pre-Hearing Orders
> x	F	Obj Resp Ext of Time  R and R only
> x	G	Investigation letters and Responses
> x	H	Obj Resp Ext of Time  Non R and R
> 	I	Suppress From Docket Inventory
> x	J	Motions Memo Contra
> x	K	124.34 Order
> 	L	Maintain on Docket Inventory RPT
> x	M	Appealed to Court
> x	N	Clear Date
> x	O	Questionaires/Responses
> x	P	Hearings
> x	Q	Receipt Returned Certified Mail
> x	R	Case Closed
> x	S	Miscellaneous
> 	U	File in PBR Records
> x	V	Remailings
> 	W	Set ALJ or Mediator
> 	Z	System generated record
>

**Comment by altrdgenetics** [comment]
added in the changes requested

**Comment by altrdgenetics** [comment]
SEND LAST FRIDAY(4/21) AT 5pm:

> FYI… I am also planning on Monday to evaluate the CMDS web updater file.

**Comment by altrdgenetics** [comment]
this can be marked as Live....
