### ISSUE TITLE
(PROD080) - (ALL) - New Case Log Report

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#459]
Justin,
I’m trying to run the New Case Log Report for 4/3-4/7, but I get a blank report.
However, if I run 3/27-4/7 I get an accurate report (including the 4/3-4/7 cases). I can also run 3/27-3/31 without issue.

![image](https://cloud.githubusercontent.com/assets/8847344/25019022/20135990-2057-11e7-928e-6fa66e718775.png)

**Comment by anthonyperk** [comment]
Because there were not any ULP cases filed between 04/03/2017 and 04/07/2017, that part of the subreport would null out and then null out the entire report.  I have corrected this for MED, REP, and ULP parts.
