### ISSUE TITLE
(PROD082)  --  CMDS activites showing up on MED section

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#460]
Mary found a glitch in the system and the history entries do not correspond with the case number. The history entries are from CMDS and she is in the MED section. Closing out of the program and going back in resolved the issue. I am unable to recreate the issue.

![image](https://cloud.githubusercontent.com/assets/24595073/25022304/557ed2c4-2063-11e7-840d-e5c6576bc890.png)

**Comment by parkjohnston** [comment]
changed this as i can't reproduce it, but will continue to look....there was a LOT of network issues within serb yesterday, wondering it if caused a funny situation

**Comment by altrdgenetics** [comment]
The issue comes from imported data that does not have a case number tied to it.


![screenshot](https://cloud.githubusercontent.com/assets/8847344/25046834/9db533fa-2101-11e7-95c1-0907732960d3.png)

**Comment by altrdgenetics** [comment]
Emailed Justin asking if we should just delete these out.

**Comment by altrdgenetics** [comment]
justen finally got back to us about this ticket and opted to flag them as inactive.
