### ISSUE TITLE
(PROD084) - (CMDS) - Missing IN/OUT on activity during docket

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#462]
Brief Description: Please include what steps and button clicks led to the error. Add Screenshots if needed.
Issue:
CMDS:
The IN - and Out – are not appearing since we switched to the new system.

![image](https://cloud.githubusercontent.com/assets/8847344/25044948/a57fb196-20f7-11e7-8cb6-7fe0d8dc7721.png)

**Comment by parkjohnston** [comment]
this was working ....

**Comment by altrdgenetics** [comment]
just tested... it is non, issue

**Comment by altrdgenetics** [comment]
nevermind found the issue

**Comment by altrdgenetics** [comment]
missing from adding activity from scratch, worked perfectly fine during docket process.
