### ISSUE TITLE
(PROD086)  --  Procedure documents in HELP menu

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#465]
Please add the attached Employee Org “Procedures” PDF file to the Help Menu. Please put the word version in the same container folder.

Help > Procedures > ORG

Please add the following as well in the following order. Please have the PDF file look for the “Section_Name”.pdf. Please rename the attached PDF files accordingly. You can add a blank PDF filler page so that the link is not broken for the other sections.

Help > Procedures > Docketing
Help > Procedures > REP
Help > Procedures > ORG
Help > Procedures > ULP
Help > Procedures > Civil Service Commission
Help > Procedures > CMDS
Help > Procedures > Hearings

**Comment by altrdgenetics** [comment]
Closed out Documentation #61, after looking at the ticket and documents provided it appears Justin is taking over the handling of documents.

**Comment by altrdgenetics** [comment]
finishedthe coding and pushed up all of the changes
