### ISSUE TITLE
(PROD093)  --  Type of Action prompt missing in CMDS templates

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#472]
The “Type of Action” prompt does not display even though it is checkmarked with this letter is generated.

![image](https://cloud.githubusercontent.com/assets/24595073/25278412/d6761258-2670-11e7-89ba-fb62ff9732e5.png)

**Comment by anthonyperk** [comment]
Email to Justin:

> Justin,
> 
> This was overlooked due to the similarities of the wording on the panel as you can see from the attachments. The choices in the 'Action Appealed' and 'Type of Action' panels are also very similar;
> 
> ActionAppealed:
> suspension
> reduction
> reclassification
> other
> 
> TypeOfAction:
> suspension
> removal
> involuntary disability separation
> 
> 
> Looking at the database for 3.0 there is only two documents that are currently using 'Type of Action' and neither of them are using 'Action Appealed'. Should I add 'Type of Action' in or is it just technically a duplicate coming from bolt on enhancement bloat from 2.0 that needs to be removed (adding removal and IDS choices to Action Appealed dialog)?
> 
>  
> - Andrew

**Comment by altrdgenetics** [comment]
FROM JUSTIN:

> Andrew,
>  
> Great find!   After talking with Jim, we agree to proceed with your recommendation.
>  
> Please remove the “Type of Action” checkbox from the screen.
>  
> The “action appealed” drop down box should contain all of the following in lowercase (except for OSHA)
>  
> abolishment
> layoff
> transfer
> involuntary disability separation
> removal
> suspension (exists)
> reduction in pay or position (tweak)
> reclassification (exists)
> suspension
> fine
> whistleblower
> OSHA
> forced resignation
> investigation
> miscellaneous
>  
> That is the complete list of the type of appeals. I will fix the two templates to point to the “Action Appealed” prompt.
> Thank you,
>  
> Justin Brown

**Comment by altrdgenetics** [comment]
polished this off
