### ISSUE TITLE
(PROD094)  - (CMDS) -  3 Day Suspension template not generating correctly?

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#473]
When I generate the following letter, the template that generates is different than the one that is shown in the admin panel CMDS templates. I cannot figure this out.

![image](https://cloud.githubusercontent.com/assets/24595073/25278455/f98e4bca-2670-11e7-98f2-fcf91f118b50.png)
![image](https://cloud.githubusercontent.com/assets/24595073/25278458/fb8c1c72-2670-11e7-9559-afbff475a2aa.png)

![image](https://cloud.githubusercontent.com/assets/24595073/25278462/fef0c502-2670-11e7-8433-bfa1dbf8f12a.png)

**Comment by altrdgenetics** [comment]
Anthony send this To Justin Friday:


> Justin,
>  
> After looking over this ticket, I cant see anything wrong.  The template looks like it generates correctly (with the first and second paragraph having a bookmark at the end of them).  Can you give me some more information on what you see as incorrect?
>

**Comment by altrdgenetics** [comment]
Justin needs to check into this again, apparently he was way to tired when testing and needs to check again.

**Comment by altrdgenetics** [comment]
> XLN Team,
> 
> Prod 094 can be closed. The bookmarks were adding full sentences of text and that is what caused my confusion.
> 
> Thank you,
> Justin Brown
