### ISSUE TITLE
(PROD096)  - (ALL) -  'Include All' in Public Records Request

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#475]
Public Records Screen. Please add a “Include All” button to allow the user to select all documents to send via public records.

![image](https://cloud.githubusercontent.com/assets/24595073/25289917/a0ae8a6e-2699-11e7-9e23-8731ba7e0f58.png)

![image](https://cloud.githubusercontent.com/assets/24595073/25289920/a37ad7d4-2699-11e7-93d0-1b6fedda345e.png)

**Comment by anthonyperk** [comment]
Really?....

**Comment by anthonyperk** [comment]
Allen told us to put this on hold until later

**Comment by altrdgenetics** [comment]
they wanted allen does not know if this is a billed feature soo we will see
