### ISSUE TITLE
(PROD097)  --  Perticular Activity type not updating in MED

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#476]
MED Section
Unable to change docketing code entry for the following entry. We are able to change the entries around it.

![image](https://cloud.githubusercontent.com/assets/24595073/25292363/cb821a08-26a3-11e7-851e-a199ddbed78c.png)

**Comment by parkjohnston** [comment]
Looking at this issue...the text to replace is not found as they are in a huge mismatch of type and action.....something seems to be user error over actually being an XLN code error

**Comment by altrdgenetics** [comment]
Email Chain:

**TO JUSTIN:**
> Justin,
> 
> We will be unable to do anything with this ticket until we are provided with additional information. Without knowing how you got to where you are it will not be possible solve the problem that has led to this issue. The information that is currently displayed within the application is also displayed in the database, I have included a screenshot for that row entry.
> 
> - Andrew 

![screenshot](https://cloud.githubusercontent.com/assets/8847344/25337971/af9017a8-28cb-11e7-8214-d38214356ea5.png)


**FROM JUSTIN:**

> 
> Andrew,
>  
> To my knowledge the Clerks docketed this entry as a “Conciliation Award”. Mary was reviewing the files and discovered that the action was wrong. Then she attempted to change the document to a “Fact Finding Data Summary Sheet”.
>  
> I was able to update the two entries that were below this activity entry to the correct document description without any issues.
>  
> Is the system refusing to allow the change because the action no longer matches the filename and type?  I even attempted to change the type to something else at random and change it back and that would not work either.
>  
> Is it possible that the system wont allow a change if the “abbreviation” or “Description” contains a certain character?  I have seen “-“ and “/” and “,” characters in the Activity Type Maintenance screen.
>  
> At minimum can you manually make this change so that the document is labeled correctly while we continue to investigate?


**TO JUSTIN:**

> Justin,
> 
> The differences between the type and action are indeed the reason why it isn't updating properly anymore.
> 
> Why are are asking for the steps is because we have implemented some checks to make sure that all items would update properly. If the process you stated was the order it happened then our idea of possibly having a file open blocking something goes out the window, ours would only occur if the type choices were flipped. We also do not see any information in our error logs which might point to something related to this issue. Without the steps we will not be able to fix the cause of this issue, we can only change the rows as you tell us. And the "other" characters are not present in this specific example and the reason why the "type" column is used to show the exact type, we use it to aid in text replacement and shorthand lookup, so I doubt that is the issue either.
> 
> Are you going to investigate this more or should we make the single change to the Database and mark the ticket as complete?
> 
> - Andrew

**FROM JUSTIN:**

> Andrew,
>  
> I will follow up with Mary on this on Monday and see if I can get any additional details. It is possible that the file may have been open when she attempted the change. I hope to find out more on Monday.
>  
> Thank you,
>  
> Justin Brown

**TO JUSTIN:**

> Justin,
> 
>       That was our thought but it only works if it started as "Fact Finding Data Summary Sheet" since the extension on the filename column is "FFDSS". If it was open at the time, it would be unable to make it the short of "Conciliation Award".
> 
>       I do have a check that sees if the file is in use during the update and notifies the user, same if it can not find the file. It will not complete any aspect of the update during that time, consider those as "pre-flight" checks. The database change is 1 method (action & type) and the filename change is another one. So theoretically neither one of those can complete if it fails the checks.
> 
> - Andrew

**Comment by anthonyperk** [comment]
**FROM JUSTIN**

XLN Team, 

I followed up with Mary on this ticket. 

Mary stated that she opens the document to check what it is. Then she makes the change. I am fairly confident that the issue is that she leaves the document open when trying to make the document description change using the drop down. 
Can you do some double checks and tests in the test environment to confirm?

In case 2016-MED-10-1135
1)      Please manually fix the activity entry so that the action reads “In – Filed Fact Finding Data Summary Sheet”
![image](https://cloud.githubusercontent.com/assets/24595073/25401532/ec05f92a-29c3-11e7-90bc-7b1f5e870f1f.png)

In case 2017-MED-01-0062 
1)      Please manually fix the activity entry so that the action reads “In – Tentative Agreement” 
![image](https://cloud.githubusercontent.com/assets/24595073/25401539/f39b9686-29c3-11e7-98a6-521685d11ba6.png)

**Comment by anthonyperk** [comment]
**TO JUSTIN**

Justin,

Using our dev system (same build that is currently LIVE), I was unable to recreate Mary’s issue as you described 
(Activity Table -> Double click on Activity -> Open file in the Activity Detail  -> Keep the file open and attempt to change the type while the file is still open).  

I get an error saying that the file is currently in use and I will have to close the file to change the type.

 
![image](https://cloud.githubusercontent.com/assets/24595073/25401591/196e3fda-29c4-11e7-8227-60f05fc2ccce.png)


So she must be doing something else.

I have changed the two activity entries as well

**Comment by altrdgenetics** [comment]
> Anthony,
>  
> You are right. I was unable to recreate with the file open either.
>  
> I did find the bug… try the steps below and see if you get the same issue.
>  
> Please fix the history entry in the case below….
>  
> 1)      I opened the detail view. Clicked update. Made the change. Pressed Save (which worked).  Then I clicked update again (without closing detail view) changed it to another type and pressed save again.

**Comment by altrdgenetics** [comment]
Reloaded the panel after Saving.... this solved the issue, anthony tested it
