### ISSUE TITLE
(PROD102)  - (MED) -  duplicate STK Cases in MED Case Search

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#483]
The following case appears many times within the system.
Also, I noticed there are not any STK numbers that I can search prior to 2013.
![image](https://cloud.githubusercontent.com/assets/24595073/25389448/aa6422aa-299e-11e7-84b6-b9ed5f51e626.png)

**Comment by altrdgenetics** [comment]
So we imported the data correctly. Something happened between January and June of last year and overwrote all of the STK case data. Email sent out to Justin.

**Comment by altrdgenetics** [comment]
They want us to bring it in to their system from our system.

**Comment by altrdgenetics** [comment]
Got this added in, as it is DB changes it is live as of writing this.
