### ISSUE TITLE
(PROD107) - (MED) - MED Report Tweaks

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#488]
Two of the new reports that were recently released for the MED section need tweaked.
1) Mediator Assignment Report – By Case Number.
a. Please change “report drop down” and “template header text” to “Mediator Assignment Report – By Appointment Date”
b. Change the sort order to Mediator Appointment Date (oldest on top, newest on the bottom”
2) Mediator Assignment Report – By Employer Name
a. Please change the sort order to the following: Order by Employer

**Comment by altrdgenetics** [comment]
We were provided the exact text the wanted... Now we are provided with different text after completion of the report.

**Comment by anthonyperk** [comment]
All tweaks have been finished
