### ISSUE TITLE
(PROD109) - Bulk Closing 

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#490]
this is a huge draft ticket and Justin submitted it as T015 at one point i guess... but never officially submitted it. So we ignored it. Need to wait till we get an actual ticket from them.

Currently this is just a placeholder so we do not forget about it.

**Comment by altrdgenetics** [comment]
So we finally got a ticket but it is 13 pages. I ma not uploading all of it as it contains several different sections (though still all Bulk closing).


Item left to do is create or link in a report for MED close Cases.

FileName: "BulkCloseCasesList.jasper"

**Comment by anthonyperk** [comment]
BulkCloseCasesList.jasper has been created.  As it is in 2.0, the 3.0 report is a duplicate of MED Cases to be Closed by Board
