### ISSUE TITLE
(PROD110) - (MED) - Selection Due Date Issues

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#491]
Conciliation Selection Due Date field for panel 1 and panel 2 is calculation wrong. Please add 1 additional day to the count. (Five days, count starts day after order date).

![image](https://cloud.githubusercontent.com/assets/8847344/25590003/be1f1d6c-2e7c-11e7-83ae-c7042ea8a62a.png)

Please confirm the following process is working correctly:
Every field on the “primary” case on the Fact Finder Tab should be duplicated (updated) on the Fact Finder Tab of the Multi Case Number cases
Every field on the “primary” case on the Conciliation Tab should be duplicated (updated) on the Conciliation Tab of the Multi Case Number cases
Please test this in dev environment. I only have 1 test case number and do not want to make errors in other cases.

**Comment by parkjohnston** [comment]
This is two tickets in one....

**Comment by parkjohnston** [comment]
why are we confirming things when he should be the one to test them...before sending them to us

**Comment by parkjohnston** [comment]
The date part of this is fixed....will get to validation later, but would punt it back to Justin as he should validate before asking to waste time

**Comment by parkjohnston** [comment]
found that the "checking" we are supposed to do is in fact an issue and will be some time to do...will be working on this and freeing up another card since this will take time and is more important than a few other cards

**Comment by parkjohnston** [comment]
Question for Justin: 

As these are not primary cases, do the activity entries need to be made for the secondary cases? Or would only the primary case ever be referenced?

**Comment by parkjohnston** [comment]
If the answer to the above question is: 

No, the activity entries will not be needed, which is how it appears 2.0 works, then this can be closed, but if the answer is yes, I will just need to uncomment a wee bit as well as a few changes. 

No = close the ticket
Yes = mark as bug and will be a quick resolve

**Comment by parkjohnston** [comment]
Milestone may change if they want to activity entries to be done.

**Comment by altrdgenetics** [comment]
FROM JUSTIN:

> Andrew,
>  
> After speaking with Mary, we do want to copy all activity entries to the related cases.
>  
> So if a multi-unit case did not settle but the rest of them did, that one case would have an accurate history record for conciliation.
>  
> Thank you for finding and asking this important question. I don’t think we really thought about this in the past. You are right this was not in the old system.
>  
> Thank you for your help finding this!
> Justin Brown

**Comment by parkjohnston** [comment]
holy crap this is more work than I initially thought....lots of little updates in places to push out the activity to non global case number....work is still on going...will be done 5/3.

**Comment by parkjohnston** [comment]
Time to complete with test and release: 4.5 hours
