### ISSUE TITLE
(PROD111) - (CMDS) - CMDS Docket Inventory Report

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#492]
The Docket Inventory Report by Case Number is not displaying all of the Hearing Information. It seems to
only pull the first hearing date.

**Comment by altrdgenetics** [comment]
This report only has ever shown the "TOP ONE" Justin approved the more than one hearing as it was not in 2.0

**Comment by parkjohnston** [comment]
This was a debate that occurred in 2.0 and I remember it going for weeks of circles. 

It was one of those meetings that was at the end of the project that just went in circles.

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> Justin,
> 
> I am working on the Docket Inventory Report.  Could you ask CMDS how they would like the hearings to be listed (currently it is the earliest Hearing, I can give them all hearings but I need to know what order they want them to be in).
> 
> Thanks

**Comment by altrdgenetics** [comment]
**EMAIL TO JUSTIN (via Anthony):**


> Also, regarding ticket PROD111:
>  
> Could you ask CMDS how they would like the hearings to be listed (currently it is the earliest Hearing, I can give them all hearings but I need to know what order they want them to be in)

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

> Anthony, 
> 
> Please sort the hearings like in the example below.
> 
> 5/1/2016
> 5/2/2016
> 5/3/2016

**Comment by anthonyperk** [comment]
Report now shows all hearings for each case
