### ISSUE TITLE
(PROD112) - (ORG) - Header reloading Issue

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#493]
When the highlighted boxes are cleared it does not clear the values from the header.

![image](https://cloud.githubusercontent.com/assets/8847344/25589930/6f2e3e18-2e7c-11e7-9b0d-1053a37b5ea3.png)

**Comment by parkjohnston** [comment]
How is the parties tab highlighted when it is showing Org Information?

**Comment by parkjohnston** [comment]
found another issue where org number was throwing a null pointer crashing the whole section
