### ISSUE TITLE
(PROD113) - (ALL) - Media Docketing window missing data.

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#494]
Media Docketing for all sections. It does not provide user ability to change the date.

![image](https://cloud.githubusercontent.com/assets/8847344/25589954/9049958e-2e7c-11e7-81e8-662d838fadb5.png)

![image](https://cloud.githubusercontent.com/assets/8847344/25589955/929c266c-2e7c-11e7-9890-67683db5b99a.png)

**Comment by parkjohnston** [comment]
removing myself as the grouped cases is more work due to how it should operate

**Comment by altrdgenetics** [comment]
got SMDS and CMDS docketing media updated
