### ISSUE TITLE
(PROD115) - (MED) - Fact Finder Data, bad old data?

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#496]
Auto Removing Case information – update

Mary informed me that the case that I had fixed this morning no longer displayed the Fact Finder.
I went into SMDS 3.0, reviewed the Fact Finder Tab and discovered it was blank just like she said.
I pressed the update button, then pressed save (without changing anything) and it created the history entry below, which says I removed the Fact Finder. This tells me that the field is not displaying what is actually in the fact Finder field.

I switched sections and went back into the case and the field populated.
If I “Close” SMDS and go back into the case again the field is blank.

![image](https://cloud.githubusercontent.com/assets/8847344/25590093/0ed719bc-2e7d-11e7-8d97-aea09aba3667.png)

**Comment by parkjohnston** [comment]
we may need more steps than provided for this.

**Comment by parkjohnston** [comment]
Have tried this for 20 minutes and get it to fire...please have Justin request the steps that happened in more detail.

Was it recently selected? Selected in the past and now trying to get back to it? Fact Finder Selection Type, was it changed? New Selection? 

Lots of variables and they all could lead to different things.

**Comment by parkjohnston** [comment]
Another question: was this a part of a grouped case?

**Comment by parkjohnston** [comment]
I re-enabled my old checks in the application...we will see what they can also produce.

**Comment by altrdgenetics** [comment]
It appears that something is not loading correctly. I checked on our side and found this...


![screenshot 160s](https://cloud.githubusercontent.com/assets/8847344/25622640/05ede910-2f23-11e7-8541-8cb7680aa908.png)


![screenshot 160](https://cloud.githubusercontent.com/assets/8847344/25622641/074efd30-2f23-11e7-8390-db0024f64638.png)

**Comment by parkjohnston** [comment]
Think i found the source..will be looking into that this evening...it is super odd as to when it gets tossed. 

Should be a simple move, already have it in progress, was unable to get it 100% tested so did not want to release it due to other issues that could be released without a test

**Comment by parkjohnston** [comment]
Will be done 5/3

**Comment by parkjohnston** [comment]
was a super small mistake that would only happen on about one load when the app first started up.

**Comment by altrdgenetics** [comment]
can i get an estimated time spent on this, just for reference?

**Comment by parkjohnston** [comment]
1 hour total, research and such, found that the issue was also in Concil...fixed both
