### ISSUE TITLE
(PROD130) - (CSC) - New CSC Reports (5)

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#511]
Add the following new reports to Civil Service Commission.

**1) Active Civil Service Commissions Report**
a. Show all Civil Service Commissions where status = “active”
b. Sort by Civil Service Name “A to Z”
c. Display Civil Service “Name”, “Full Address”, “Phone Number”, “Email Address” and “Date Filed”
    i. Example
        1. Line 1: Name, Phone Number, Email Address, Date Filed
        2. Line 2: Full Address

**2) Inactive Civil Service Commissions Report**
a. Same as report above except status = “inactive”

**3) Non-Compliance Civil Service Commissions Report**
a. Same as report above but only shows Civil Service Commissions where Filed Date year does not match the calendar year when generated.
b. Add a third line to display all text in the Notes tab.

**4) Individual Civil Service Commission Detail Report**
a. Detailed Report showing all the fields on the CSC Information Tab, The Parties Tab, and the Notes Tab (at the bottom of the report).
b. Only shows for the Civil Service Commission user is in.
c. Header should display Civil Service Commission Name and Number

**5) Individual Civil Service Commission Documents Sent and Received Report**
a. Report displaying the date and history description of the documents sent and received.
b. Only shows for the Civil Service Commission user is in.
c. Header should display Civil Service Commission Name and Number

**Comment by altrdgenetics** [comment]
**TO JUSTIN (via anthony)**

> Justin,
>  
> Questions on the new reports:
>  
> 4) Individual Civil Service Commission Detail Report
>                 a. Do you want just the name of the Party, or the whole contact card?
>                 b. Do you want every party even if there are multiple of the same party type?
> 5) Individual Civil Service Commission Sent and Received Report
>                 a. Do you just want the activities starting with ‘IN-‘ and ‘OUT-‘?

**Comment by altrdgenetics** [comment]
**Reply from Justin**

> 
> Justin,
>  
> Questions on the new reports:
>  
> 4) Individual Civil Service Commission Detail Report
>                 a. Do you want just the name of the Party, or the whole contact card?
> **_# I want the entire contact card._**
>                 b. Do you want every party even if there are multiple of the same party type?
> **_# Yes, I want all parties listed for the Civil Service Commission. Phone Number and Email address._**
> 5) Individual Civil Service Commission Sent and Received Report
>                 a. Do you just want the activities starting with ‘IN-‘ and ‘OUT-‘?
> _**# Not all have “In” or “Out” can they be displayed if document link is not null or blank?**_

**Comment by anthonyperk** [comment]
SENT TO JUSTIN

> OK I got you on 4a and 4b, for 5, I can look for things that have a document link associated with it, however there could be the possibility where a document was generated for the CSC that wasn’t sent out (would have “Generated” in the activity), would you like those to be shown as well?

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

>Anthony, 
>Yes I will need the “Generated” items to show as well. All the memos and directives would fall under this. 


EMAIL TO JUSTIN

>OK then if it has a document link associated with it, then it will appear on the report

**Comment by anthonyperk** [comment]
These 5 reports will be ready for the next release
