### ISSUE TITLE
(PROD131) - (CSC)  Remove 'Agenda' from Reports box in CSC

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#512]
In the Civil Service Commission Tab -> Reports Please remove the following drop down.

![image](https://cloud.githubusercontent.com/assets/24595073/25669977/485dce2e-2ff9-11e7-90ed-8c88fabc0af2.png)

**Comment by altrdgenetics** [comment]
needed to add in CSC to the checklist.
