### ISSUE TITLE
(PROD132) - (CMDS) - Report Tweaks

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#513]
CMDS Report Tweaks.

**1) Docket Inventory Report – By Case Number**
a. Please add the ALJ that belongs to the case to the Header
b. When All ALJ is selected from report prompt, does the report group by ALJ?

**2) Docket Inventory Report – By Hearing Date**
a. Please add the ALJ that belongs to the case to the Header
b. When All ALJ is selected from report prompt, does the report group by ALJ?

**Example from CMDS 2.0**
![image](https://cloud.githubusercontent.com/assets/8847344/25670330/58640184-2ffa-11e7-8809-ab489cf96870.png)

**Comment by altrdgenetics** [comment]
TO Justin (via Anthony): 

> Justin, 
> Regarding B) from both tweaks:  Should they group by ALJ if ALL is selected?

**Comment by altrdgenetics** [comment]
**FROM JUSTIN:**

> If “All” is selected both reports should be grouped by ALJ.
> Thank you for the clarification.
>  
> Justin Brown

**Comment by anthonyperk** [comment]
These tweaks have been added
