### ISSUE TITLE
(PROD133) - (ALL) - Record Retention

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#514]
**Record Retention:
Note: Shane will be in charge of purging records.**

_(Details Grouped Below based on parts)_

> XLN Team,
> 
> Here is my final outstanding enhancement ticket for SMDS 3.0.
> Take a look and let me know what you think. I am open to suggested improvements to this process.
> 
> Thank you,
> Justin Brown

**Comment by altrdgenetics** [comment]
> **Create 2 Reports:**
> 
> **1) Cases that need Purged (Button on the Admin Purge Screen)**
> a. List of case numbers that need purged. (3 or 4 columns per page)
> b. Group by Section (MED, ULP, ORG)
> c. Sort Smallest to Largest
> 
> **2) Purged Documents Report**
> a. Header contains Purge Date.
> b. List of Activity Entries (that link to documents) that were purged from the system
> c. List Case Number and Activity Description Entry
> d. Sort by Case Number Smallest to Largest (Sort by Org Number for Org Section).
> e. This report should auto generate when Ok button is pressed on “Purge Complete” confirmation screen. (After files marked inactive).

**Comment by altrdgenetics** [comment]
> **Purge Selection Criteria:**
> 
> **MED Section**
> If [case status] = closed and Opinion field (hearing Tab) = null or blank and [board action pc date] (hearing
> tab) = null or blank and [board action pre-d date] (hearing tab) = null or blank and [Retention Tickler
> Date] is within user prompt date range
> Select all activity entry records except, NTN (notice to Negotiate), NTN AMD (Notice to Negotiate –
> Amended), NTN DUP (Notice to Negotiate – Duplicate), FF REPT (Fact Finding Report), CON AWAR
> (Conciliation Award), CON AWAR AMD (Conciliation Award Amended), CON AWAR DUP (Conciliation
> Award - Duplicate), DIR (Directive), DIR AMD (Directive – Amended), DIR DUP (Directive – Duplicate),
> NOT INT STK PKT (Notice of Intent to Strike or Picket), REQ for DET STK (Request for Determination of
> Unauthorized Strike), OPN (Opinion) and history entry description “Combined File Transfer from
> Intellivue”.
> Mark all other Activity entries INACTIVE (and flag somehow with a “Delete Date”)
> Create Activity Entry “Documents Purged per Retention Policy” with today’s date.
> After 6 months, purge INACTIVE entries and delete the linked files associated to them.
> REP Section
> All Case files remain as is. Digital files retained permanently.
> 
> 
> **ULP Section**
> If [Status] = closed and [Final Disposition] = closed and [Appeal Sent] = Null or Blank and [Appeal
> Received] = Null or Blank and [board action pc date] (hearing tab) = null or blank and [board action pre-d
> date] (hearing tab) = null or blank and Opinion field (hearing Tab) = null or blank and [board meeting
> date] + 1 year and 45 days falls within user prompt date range.
> Select all activity entry records except INIT CHRG (Initial Charge), INIT CHRG AMD (Initial Charge -
> Amended), INIT CHRG DUP (Initial Charge – Duplicate), INIT CHRG NOA (Initial Charge with Notice of
> Appearance), INV RPT (Investigator Report), INV RPT - AMD (Investigator Report - Amended), INV RPT –
> DUP (Investigator Report - Duplicate), DIR (Directive), DIR AMD (Directive - Amended), DIR DUP
> (Directive - Duplicate), and history entry description “Combined File Transfer from Intellivue”.
> Mark all other Activity entries INACTIVE (and flag somehow with a “Delete Date”)
> Create Activity Entry “Documents Purged per Retention Policy” with today’s date.
> After 6 months, purge INACTIVE entries and delete the linked files associated to them.
> 
> 
> **ORG Section**
> Select all Employee Org Activity entries older than [Due Date] minus 7 years except AR, FS, RR (Annual
> Report, Financial Statement, Registration Report) AR, FS, RR, CB (Annual Report, Financial Stmt,
> Registration, Const Bylaws), CB (Constitution and Bylaws), CB AMD (Constitution and Bylaws – Amended),
> CB DUP (Constitution and Bylaws – Duplicate), DIR (Directive), LocalList (Parent Org (Chapter) List), RR
> (Registration Report), RR AMD (Registration Report – Amended), RR DUP (Registration Report –
> Duplicate), RR, CB (Registration Report and Constitution and Bylaws), TR (Trustee), TR AMD (Trustee –
> Amended), TR DUP (Trustee – Duplicate)
> Mark all other Activity entries INACTIVE (and flag somehow with a “Delete Date”)
> Create Activity Entry “Documents Purged per Retention Policy” with today’s date.
> After 6 months, purge INACTIVE entries and delete the linked files associated to them.

**Comment by altrdgenetics** [comment]
> **Purge Records User Interface:**
> Below is a screenshot of the layout of the retention screen. This is accessible via the admin panel
> 
> • Display cases that match the purge criteria (from the query above) that have not yet been
> purged.
> • Sorts by case number order smallest to largest, then by history entry date.
> • The entries are auto check marked based upon the retention statements listed above. The user
> then verifies that the entry should be purged.
> • Each row can be click on to view the document (if doc exists)
> • When purge button is pressed, Confirmation box appears (Are you sure you want to purge these
> records?) Y/N
> • Then mark all selected records as inactive, and add a delete date to each activity entry.
> • Add all these entries to a new table called “Purged Records”
> o This table will be an archive of all the purged activity entry records. This will provide a
> fail-safe in case we need to undo a purge after the six-month period has past. The
> documents for a case could be recovered from our monthly backup.
> • Add a new history entry to each case stating “Records Purged per Retention Policy”
> • The “Delete Date” field will be used for the official purge up to 6 months later where the history
> entry and the linked file will be deleted from the system.


> **Below are the Header Options of the Purge Screen:**
> **Section Dropdown** = MED, ULP, ORG, CMDS (REP is excluded)
> **Date Range** = date range of possible cases that need purged.
> Start Date: End Date: =
> Note: If Blank Show all available to be purged?
> ![image](https://cloud.githubusercontent.com/assets/8847344/25679239/a2a2ba9a-301a-11e7-8d0c-f175dd26a09b.png)

**Comment by altrdgenetics** [comment]
end ticket data......

**Comment by parkjohnston** [comment]
i have several good talking points about this and think it would be super simple to implement.

**Comment by altrdgenetics** [comment]
This is a mess, it will take me a little bit of time to get the new processes that they are looking for straightened out and uploaded.

**Comment by altrdgenetics** [comment]
So far I have setup a few initial things for this ticket. 

1. I got the main panel setup and the menu item. I will not be adding this to the admin panel as Justin has asked for but instead adding it to the menu under the admin menu list. The item is currently hidden, it can be re-enabled from RootPanel on line  #123 (first item of the enableTabs() method).

2. I laid out all of the information and tables as I could figure with what was provided in the ticket. The table matches the layout that was asked for and we have a loading spinner on it when loading the table.

3. I have very basic SQL queries setup to handle the loading of the table (just top 50 for each section). I know these will need to be adjusted based off of the criteria that Justin has asked for later and possibly the whole date thing which we do not have a clue what he is trying to do. I just wanted to get the bones there and it setup for heavier duty SQL calls.

4. The double click on the row will allow you to open the file, that has been completed. 

5. Image renderer for files has been made into its own class instead of at the bottom as the activity panel has.

**Comment by altrdgenetics** [comment]
**STATUS UPDATE:**
Additional information has been added to the SQL Where statements and everything is setup for additions to the Exclusions list. All sections load properly now.

**LEFT TO COMPLETE:**
- Purged document reports
- Any modifications to the database
- The “Purge” process after checkmarks are verified.

**QUESTIONS:**
- For ULP SQL Query What is this user Prompted Date range?
- The supposed Date Range… date range of what? Case years, specific dates?
- CMDS is mentioned for the Dropdown but no criteria is mentioned
- What is supposed to be pre-check marked? We were told to exclude items in the list, not include them and just not checkmark them.
- Need a complete list of items to exclude in an actual usable list format.

**Comment by altrdgenetics** [comment]
Discussed this in the meeting and need to wait and see what they want to do, this is going to be done at a later point in time.

**Comment by altrdgenetics** [comment]
Last week we had a meeting and discussed tickets. We were informed by justin that this is the lowest priority ticket and it should be saved for last.

**Comment by altrdgenetics** [comment]
Justin has Green Light working on this ticket as of Monday's email

**Comment by altrdgenetics** [comment]
Put in 2hrs for the meeting we had yesterday and another 3hrs today working on prepping the display for demo-ability for Shane to see the UI. I have also submitted an email to Justin asking him to resubmit the ticket reflecting the updated changes from our meeting.

**Comment by altrdgenetics** [comment]
The Status of this ticket is that it still needs a meeting. SERB keeps requesting a PO however they have omitted PBR side yet still referencing details coming later. Allen is refusing to write the PO without knowing if they will be included or not. He has an email out to CMDS and CSC to get their input since Justin would not give us any details. We are waiting on a status for that. A meeting was requested for Oct 23-27

**Comment by altrdgenetics** [comment]
This is technically complete...

LIST TO DO AT SERB:

Add Reports to DB
Add Reports to shared drive
Create "RetentionExclusion" DB table

**Comment by altrdgenetics** [comment]
Updated information:

All items on SERB side have been properly created. Testing Phase begins now. 

Currently there is an issue with running needs purged report from the system

**Comment by altrdgenetics** [comment]
gave them the live working system
