### ISSUE TITLE
(PROD134) - (ULP) - Report Due Date reverted back to 4 months out

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#515]
In the Report Due Date field on the Status Tab, SMDS 3.0 has reverted back to calculating a 4-month due date (from the assigned date) instead of the 5-month Report Due date.

![image](https://cloud.githubusercontent.com/assets/24595073/25714653/b2cc9768-30c6-11e7-9d73-6a3737537845.png)

During the parallel testing, I submitted ticket PT 020 for the same issue and you advised me that the issue was resolved.
Beginning with Case No. 2017-ULP-03-0060 through 2017-ULP-05-0078, including the JWD case, the Clerk’s Office has been manually changing the Report Due date. The change is reflected in the Activity entry.
Cases filed prior to 0060 do not have an Activity record to show that any manual changes were done by the Clerk’s office to the Report Due date. The due date for those cases shows the correct 5-month out due date.
Please have XLN make the necessary adjustments in order that the new cases being filed do not require a manual adjustment by the Clerk’s office to correct what should automatically calculate as a 5-month due date.
I have only attached one example of the Activity entry and the Status Tab. As of today, this error has affected 20 cases.

![image](https://cloud.githubusercontent.com/assets/24595073/25714661/ba0031f2-30c6-11e7-9f8c-a0d6eb9cf314.png)

5-4-17 – See Activity entry for 3-13-17. Clerk’s office had to change the Report Due Date. Original date was 7/13/17 (4 months) was change to 8/13/17 (5 months). The system is back to calculating a 4 month report due date instead of the 5 month report due date. Original ticket was: PT020 submitted on 2/28/17 to correct this issue.

![image](https://cloud.githubusercontent.com/assets/24595073/25714668/c13f7d6a-30c6-11e7-940b-410309fc3026.png)
5-4-17 – The Report Due Date appears on the Status Tab.

**Comment by altrdgenetics** [comment]
(PT020) - Report Due Date in ULP auto-populate #205 

The switch to 5 months never happened....

initial code was created on Feb14 and no additional changes were made since.
