### ISSUE TITLE
(PROD135) - (CSC/ORG) - ORG/CSC information for Envelope Inserts

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#516]
Please add the information from the ORG Tab and the CSC tab to the “Envelope Inserts” list as an available party to the case that you can print an envelope insert for.
Note from Andrew:
As far as the envelope insert window on the party tab you did not specify that you would like to have the org information on either ORG or CSC tabs, so that was never put in as that information is not displayed on that tab or held within the caseParty table in the database. If you would like this added in please submit a new ticket with that as a request.

![image](https://cloud.githubusercontent.com/assets/24595073/25714702/d797763a-30c6-11e7-8740-852d6cc220d5.png)

**Comment by altrdgenetics** [comment]
got this finished up.
