### ISSUE TITLE
(PROD137) - (CMDS) - CMDSCCList not including all parties

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#518]
When the “CMDSCCList” bookmark is populated, It is not including all the parties in the case. Below is an example. It is also adding a leading comma if only the employer name field is populating. Please remove the leading comma in this instance.

![image](https://cloud.githubusercontent.com/assets/24595073/25717917/1d35d352-30d2-11e7-8528-ce7356258cac.png)

**Comment by altrdgenetics** [comment]
case sensitivity issue on creating parties.
