### ISSUE TITLE
(PROD138) - (REP) - Prof/NonProf Removed notification issues

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#519]
All of the “removed” history entries were created when I did the following steps.
1) Enter the case.
2) Click on Details Tab.
3) Click Update
4) Click the Professional/Non-Profesional Checkmark
5) Unclick the Professional/Non-Professional Checkmark
6) Press Save.
Once I did this one time in the case. I was unable to get these entries to appear again if I repeated these steps.

![image](https://cloud.githubusercontent.com/assets/24595073/25756413/b2201d16-3194-11e7-8e64-3d92382f1f2a.png)

Please note the entries below do not exist. I get these entries when I click the checkmark and press save.
Then update again remove the checkmark and press save.

![image](https://cloud.githubusercontent.com/assets/24595073/25756427/b92a124c-3194-11e7-83cb-d12a930f4b35.png)

**Comment by anthonyperk** [comment]
This may be a blank vs null issue

**Comment by parkjohnston** [comment]
it is 100% a blank/null issue....shown in screen shot below...data import issue? Just an idea.

The attached screenshot it on XLN server for 2012-0001

![screen shot 2017-05-07 at 8 49 16 am](https://cloud.githubusercontent.com/assets/3246562/25781134/4e94d1b8-3303-11e7-931f-7c67495198a6.png)

**Comment by parkjohnston** [comment]
trying to clean this up on SQL methods

**Comment by parkjohnston** [comment]
All old cases have this issue...

![screen shot 2017-05-07 at 10 23 48 am](https://cloud.githubusercontent.com/assets/3246562/25781978/53287c8c-330f-11e7-89c3-b7e3104d9ec9.png)

**Comment by parkjohnston** [comment]
This is fixed with changing REP Case ONLY for blank to null....should this continue in other places I have a script for the full DB
