### ISSUE TITLE
(PROD140) - (CSC) - Update issue in CSC Information tab

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#521]
XLN Team,
I need you to restore data to the CSC database. When we were going into each case and updating the
Date filed, a bug in the system was removing the address information. I discovered that the orgs that we
did not yet update the file date for have the correct address listed. We started this process last week so
we should still have a backup that we can use. We also need to find and fix the bug. We have stopped
with data entry in this section until this bug is fixed.

![image](https://cloud.githubusercontent.com/assets/24595073/25860195/d7e9098c-34ae-11e7-885c-796019aa2957.png)

**Comment by altrdgenetics** [comment]
I have completed the code for this and only need to keep it open to do the database transfer once the application has been updated tonight. The issue was that Address1 and Address2 had phone number formatting applied to it.

**Comment by altrdgenetics** [comment]
> Andrew,
>  
> I understand. Please proceed with bringing over the two fields from SMDS 2.0.
>  
> Thank you,
> Justin Brown

**Comment by altrdgenetics** [comment]
finished that out
