### ISSUE TITLE
(PROD141) - (CMDS) - Hearing dropdown addition

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#523]
CMDS and SERB Hearings Section.
I need a dropdown option for None (No hearing room needed) Please auto select when TC (Telephone Conference) is selected from the dropdown

![image](https://cloud.githubusercontent.com/assets/24595073/25868974/a25f56cc-34cc-11e7-92aa-624cb5914125.png)

**Comment by altrdgenetics** [comment]
Completed this
