### ISSUE TITLE
(PROD142) - (Hearing and CMDS) - Calendar Hearing Room invite tweak

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#524]
I am unable to confirm why the time is off. I am going to open a ticket with OIT to have them start investigating. When the invite ray received was forwarded to me it mad the changes shown below.
a.Can you increase the time block so that the calendar appointment is a 7 hour timeblock? That way the calendar invite blocks the entire day off in the Hearing Rooms andfor the ALJ. Then the ALJ can shorten the time block if needed.
i.Example: 10:00AM – 5:00PM
b.Currently Diana is manually blocking off the hearing rooms using her outlook. Shethought there was still a pending ticket to fix this.
Incident INC0983078

**Comment by altrdgenetics** [comment]
completed this, all of the hearings now go from 10AM to 5PM
