### ISSUE TITLE
(PROD143) - (ULP) - ULP Report Due Date history entry

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#525]
In ticket 134 you corrected the ULP Report Due Date calculation from 4 months to 5 months.
I have been informed that history entries are being made stating that users are updating the “Report Due Date” even though they are only updating the file date (which auto updates the report due date)
In the example below, we do not know why the highlighted history entry for the report due date was created because there is not a file date adjustment that goes with it.

![image](https://cloud.githubusercontent.com/assets/24595073/25869080/12fbee22-34cd-11e7-9f49-259ae85cb723.png)

**Comment by altrdgenetics** [comment]
TO JUSTIN:

> Justin,
> 
> Is this a question or an issue?
> 
> When creating new ULP cases the 'File Date' and 'Report Due Date' are automatically created when inserting the new case, that was the issue with PROD134. With the way the listeners are set up on the ULP information tab, chances are the 4 month issue on case creation was "self healing" due to the information panel always having the correct 5 month difference between the fileDate/reportduedate. So when a user would update the case information tab on one of those 'bad' 4 months cases it would change the 'report due date' field to the correct 5 month and you would get your activity entry. PROD134 was fixed on 5/4 and the dates on the screenshot in question was on 4/27, giving additional evidence to this being what occurred.
> 
> I tested it here with a 4 month case and an entry like your screenshot was created. On initial case creation we do not create entries for that first 'File Date' or 'Report Due Date' so we can not see what it was before it but it would explain why the change information shows a date increase of 1 month on the activity table.
> 
> 
> - Andrew

**Comment by anthonyperk** [comment]
> Andrew, 
> 
> Thank you for the update. Can you confirm if there are any other cases where the file date is not 5 months apart? Provide me a list and I can update them. 
> 
> I am trying to avoid finger pointing… on who updated what

**Comment by parkjohnston** [comment]
How has this tickets moved from a field creating an activity entry to use doing analytics on a date? 

I feel like this should be closed and another submitted

**Comment by altrdgenetics** [comment]
SENT an email with the list, and guess what... now we are updating them....


> XLN Team,
> 
> Angela has confirmed that she wants all of the ULP Cases (3,971) in the list you provided to be updated to a 5 month “report due date”
> 
> Thank you,
> 
> Justin Brown

**Comment by altrdgenetics** [comment]
manually did this in the server

```
UPDATE 
	ULPCase 
SET 
	ULPCase.reportDueDate = DATEADD(mm, 5, ULPCase.fileDate) 
WHERE 
    DATEADD(month, 5, ULPCase.fileDate) > ULPCase.reportDueDate
```
