### ISSUE TITLE
(PROD145) - (MED) - MED Bulk Case Closing additions

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#526]
MED Bulk Case Closing
Add select all checkbox option.
When processing (Closing Cases) please display spinnging wheel
When update is pressed add prompt “Did you print Cases to be closed list?” Yes = Continue No= return back to page so user can generate report.

![image](https://cloud.githubusercontent.com/assets/24595073/25869118/34e068ec-34cd-11e7-852f-5184cb20b463.png)

**Comment by altrdgenetics** [comment]
Need to ask allen if he wants us to start working on this.

**Comment by altrdgenetics** [comment]
This will be on hold till payment

**Comment by altrdgenetics** [comment]
Added in the select all checkbox

**Comment by altrdgenetics** [comment]
spinning wheel added in on processing the cases

**Comment by altrdgenetics** [comment]
user prompt was easy... this is now closed out.
