### ISSUE TITLE
(PROD146) - (Hearings/ORG) - File link missing after adding a comment

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#527]
When a comment is added in the SERB Hearings section to an entry with a document attached. The link to the file disappears.

![image](https://cloud.githubusercontent.com/assets/24595073/25903699/2f6dcb0e-356b-11e7-8346-777b5bbf7304.png)

**Comment by altrdgenetics** [comment]
Hearing, ORG, CSC seem to be the ones that do this.

**Comment by altrdgenetics** [comment]
The issue was on the file renaming, if it failed out on should be renaming then it would not put anything in for the updated activity entry, caught that and it is updating properly now.
