### ISSUE TITLE
(PROD147) - (Hearings) - Hearing Letter Queue showing just MED letters

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#528]
The SERB hearings letter queue shows only MED documents.

![image](https://cloud.githubusercontent.com/assets/24595073/25903754/4f09a352-356b-11e7-81fc-db43256f43e1.png)

**Comment by anthonyperk** [comment]
> Justin,
> 
> Since documents for a SERB hearing case could technically be generated in either the home section or the hearing section the Hearing Letter queue shows any MED, REP, or ULP cases. This was discussed when building out the letter generation process.
> 
> - Andrew

**Comment by altrdgenetics** [comment]
**FROM JUSTIN:**

> Andrew,
>  
> Thank you for the update. The reason that I asked is because Ray and I both generated letters “Proposed Orders” and used the letter queue, but they do not display in the queue.  Case 2017-ULP-01-0022 was the case I was in to do the test. I have since deleted the document from the live system.
>  
> Also, when I deleted the test document from the activity tab, the screen refreshed and it showed me all the entries for that case instead of the shortened list.
> Thank you,
>  
> Justin Brown


WOULD HAVE BEEN NICE TO HAVE THIS INFORMATION IN THE TICKET
