### ISSUE TITLE
(PROD148) - (MED) - New document to be auto attached to MED Initial Letters

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#529]
I added the new MED Letter with type Quest and it does not show in the lower right box of the letter queue process, only Fact Finders and Conciliator Bios are displayed.

Also, I want this template auto check marked when Initial Letter A, Initial Letter E – Multi Unit, and Initial Letter P – MAD are selected from the letter drop down list. This letter will be sent every time, unless the sender unchecks during this process.

![image](https://cloud.githubusercontent.com/assets/24595073/25906811/ae023f42-3573-11e7-8c01-b30a5a59174c.png)

![image](https://cloud.githubusercontent.com/assets/24595073/25906819/b27d2d8e-3573-11e7-8195-0bc536e23ca4.png)

**Comment by altrdgenetics** [comment]
SO looking into it all other sections use "Quest" This will not be as straight forward as I hoped. this will be 100% hard coded or something else. Will need to talk to Justin about it before continuing

**Comment by altrdgenetics** [comment]
**TO JUSTIN:**

> Justin,
> 
> Having looked into this ticket there is a few possible solutions.
> 
> As mentioned before the extra attachment table for the Med section lists all of the active fact finders and conciliators from the FactFinder table, opposed to using question templates from the SMDSDocuments table that every other SMDS section uses.
> 
> 1) We change out the "Additional Documents" table and have it show any questions you have, which would follow every other SMDS section. Going down this route we will hard code fact finder bios into the documents required it. Current ruleset is any document that contains "Panel" in the description.
> 
> 2) You append that document to the end of the initial letters mentioned in the ticket and no code changes are required, since the ticket reads that it will be sent every time except on rare occasions.
> 
> 3) We have both SMDSDocument "Quest" and Fact Finder Bios show. This will take the most work and require changing the table and retesting and checking every section on letter generation to ensure no other section was adversely affected. With ~70 rows already being created this table will just get that much larger. If this is the choice, it will take more than just a few billable hours to complete.
> 
> - Andrew

**Comment by altrdgenetics** [comment]
**FROM JUSTIN:**

> Andrew,
>  
> Thank you for looking into this. We have decided to go with option 2 and just add the text to a new page on each existing document.
>  
> Please close this ticket.
>  
> Thank you,
> Justin Brown
