### ISSUE TITLE
(PROD150) - (ALL) - Mail Log Loading Issue

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#531]
ORG, Civil Service, and Hearings Mail logs do not display any entries no matter what options or date range I pick.

![image](https://cloud.githubusercontent.com/assets/8847344/25952885/e107e2f4-362f-11e7-81db-1ce6e92b6bd6.png)

**Comment by altrdgenetics** [comment]
I have fixed the code for this but there is a report tweak that needs to be done, waiting on Anthony.

**Comment by altrdgenetics** [comment]
accidently closed with comment

**Comment by anthonyperk** [comment]
with a couple more tweaks to code and the report, the report runs as requested
