### ISSUE TITLE
(PROD151) - (Hearings) - Update bookmarks depending on what section it is in

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#532]
Please update the bookmarks as shown below in red.
1)“HearingParties” (See Exhibit 1)
a.“Complaintant” (State employment Relations Board) should be in all Caps. Add a commaat the end.

b.“Respondent” (Ohio Patrolmen’s Ben….) should be in all Caps. Add a comma at the end.

i.FYI… comma at the end of each party listed

c.For ULP Case “and” should be “v.”

d.For MED and REP Cases “and” is correct

e.For Rep Cases… (See Exhibit 2)

i.Display Conversion School (if available)

1.Followed by blank line, then “and”

ii.Display Employee Organization (if available)

1.Followed by blank line, then “and”

iii.Display Incumbent Employee Organization (if available)

1.Followed by blank line, then “and”

iv.Display Petitioner (if available)

1.Followed by blank line, then “and”

v.Display Rival Employee Organization (if available)

1.Followed by blank line, then “and”

vi.Display Intervener (if available)

1.Followed by blank line, then “and”

vii.Display Rival Employee Organization 2 (if available)

1.Followed by blank line, then “and”

viii.Display Rival Employee Organization 3 (if available)

1.Followed by blank line, then “and”

2)The “ALJAssigned” bookmark should be in all caps (both locations on the template)

3)The “CaseNumber” bookmark did not populate when in Hearing MED case. (2016-MED-02-0091)

Exhibit1
![image](https://cloud.githubusercontent.com/assets/24595073/26006070/22da4062-3709-11e7-8eca-894ea7e79586.png)

Exhibit2
![image](https://cloud.githubusercontent.com/assets/24595073/26006074/27653d08-3709-11e7-9a25-3681db95f757.png)

**Comment by altrdgenetics** [comment]
this is related to...

https://github.com/CurrentlyNotSet/SERB/issues/508

**Comment by altrdgenetics** [comment]
this was a mess... got it all sure'd up though. So many different things they wanted for that VS section. Also the Med bookmark was an issue because it was CaseNum and not CaseNumber in that section originally.
