### ISSUE TITLE
(PROD152) - (Hearings) - Incumbent Employee Org 'not showing up' (whatever that actually means)

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#533]
I created 3 new “Hearings” REP cases. All the parties populated correctly except the one below (no Employee Org).

I went back and looked at the original REP case for each. The two that populated correctly had an Employee Org in the original case. Case 17-REP-03-0033 had an Incumbent Employee Org….it did not come over to the Hearings tab.

![image](https://cloud.githubusercontent.com/assets/24595073/26006219/9f53b27c-3709-11e7-8e11-c79e5f3246d4.png)

**Comment by altrdgenetics** [comment]
XLNCMS 2.0 HEADER PANEL

```
if(CaseNumber.contains("REP")){
    //case related information
    REPDataData rcd = new REPDataData();
    rcd = rcd.getREPDataDataRecord(.......);
    CaseNum.setText(CaseNumber);
    Employer.setText(rcd.EName);
    EmployerIndiv.setText(rcd.EREPName);
    if(rcd.EOName.equals("")) {
        Union.setText(rcd.IEOName);
        UnionIndiv.setText(rcd.IEOREPName);
    } else {
        Union.setText(rcd.EOName);
        UnionIndiv.setText(rcd.EOREPName);
    }
}
```

**Comment by altrdgenetics** [comment]
Code should show IEO if EO is blank...

**Comment by altrdgenetics** [comment]
i adjusted the code to match 2.0
