### ISSUE TITLE
(PROD153) - (ORG) - Possible issue with AR and FS dates being deleted?

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#534]
XLN Team,
Can we confirm the issue below is not related to the Civil Service Section auto deletion of the addresses? We may need to reimport these from SMDS 2.0. This date field doesn’t usually change once it has been entered. Employee Orgs only need to file this form once when a new org is created.
JB
Just a head’s up if you get any ORG calls. Apparently when XLN did the data dump, some of the Registration Report Last filed dates either didn’t copy into the field or was never entered.
I’ve gotten about 5 calls like this in the past 2 days, they received the 10 day letter but had filed the AR and FS….the only reason they got the letter is b/c the field was blank. They are unions that have been around for years.
If you happen to get a call, look at that field and if blank, look to see if we have one on file already.

![image](https://cloud.githubusercontent.com/assets/24595073/26006318/fc833e9a-3709-11e7-94b8-c9f343e72571.png)

![image](https://cloud.githubusercontent.com/assets/24595073/26006322/ff4eb42e-3709-11e7-98be-6a3876ec3c4b.png)

**Comment by anthonyperk** [comment]
There are 79 ORGs from 2.0 with either a Registration Report last filed, a Annual Report last filed, or a Financial Statement last filed that is just a year (length != 10)

"OrgNumber"	"OrgName"	"RegistrationReportLastFiled"	"AnnualReportLastFiled"	"FinancialStatementLastFiled"
"11"	"Valley View Fire Dept Local 2634"	"1984"	""	""
"46"	"UFCW Local 880"	"1984"	"2000"	""
"68"	"North College Hill Police Assn"	"1984"	""	""
"110"	"Sandy Valley Education Assn"	"1991"	""	""
"111"	"Stark Area Vocational Education Assn"	"1992"	""	""
"113"	"Tuslaw Classroom Teachers Assn"	"1992"	""	""
"126"	"Strasburg Education Assn (Local 4733)"	"2012-04-24"	"2002"	""
"127"	"FOP Lodge 27"	"1984"	""	""
"130"	"Celina Municipal Employees Representative Committee"	"2002"	"2015-12-31"	"2015-12-31"
"133"	"FOP Lodge 36"	"2001"	"2015-12-31"	"2015-12-31"
"335"	"Delaware Public Works, Utilities, and Grounds Association"	""	"2000-01-20"	"2001"
"695"	"Wayne Co JVS Ed Assn"	"1984"	"2000"	""
"757"	"Mercer County Sheriffs Dept Employees Assn"	"1984"	""	""
"767"	"Jackson Twp Highway Dept Assn"	"1984"	""	""
"768"	"State Transportation Engineers Council of Ohio"	"1984"	"1990"	""
"769"	"Federation of United School Employees"	"1992"	""	""
"772"	"Cuyahoga Falls Patrolmans Benevolent Assn Local 96"	"1984"	"1990"	"1990"
"785"	"MARCA Education Assn"	"1991"	""	""
"797"	"IAFF Local 2938"	"1985"	"2015-12-31"	"2015-12-31"
"801"	"Cardington Lincoln School Support Assn"	"1985"	""	""
"802"	"Deepwood Employees Assn"	"1985"	""	""
"822"	"Whetstone Education Assn"	"1985"	""	""
"826"	"IAFF Local 702"	"1985"	""	""
"832"	"Celina Organized Police Sergeants (COPS) *File Closed"	"1985"	""	""
"843"	"Clark Co Command Officers Assn Inc"	""	"1983"	"1983"
"866"	"FOP Lodge 4"	"2001"	"2001"	"1988"
"874"	"Independent Union Care Center Workers"	"1985"	""	""
"886"	"AFSCME Local 2174"	"2002"	""	""
"891"	"Celina Radio Dispatchers  *File Closed; see comment"	"1985"	""	""
"918"	"Celina Patrol Officers Assn *File Closed; see comment"	"1985"	""	""
"928"	"AFSCME Local 0433"	""	"1984"	""
"932"	"AFSCME Local 0349"	"2004"	""	""
"945"	"IAFF Local 516"	"2001"	"2015-12-31"	"2015-12-31"
"958"	"FOP Lodge 71"	"1984"	"1984"	""
"965"	"North Central Local Employees Assn"	"1992"	""	""
"967"	"UAW Local 217"	"2001"	"2001"	"2001"
"972"	"Ansonia Local Support Personnel"	"1991"	""	""
"984"	"Teamsters Local 740"	"1986"	""	""
"986"	"Teamsters Local 450"	"1986"	""	""
"1006"	"Dublin Educators Assn"	"1985"	""	""
"1011"	"Williamsburg Local Support Personnel Assn"	"1985"	""	""
"1016"	"Springboro Classified Employees"	"1986"	""	""
"1028"	"UFCW Local 1059"	"1986"	""	""
"1083"	"FOP/OLC Ohio Brotherhood of Deputy Sheriffs  (Hancock Co)"	"1986"	"1986"	"1986"
"1084"	"AFSCME Local 0345"	""	"1985"	""
"1091"	"Celina Communication Operators Org"	"1986"	""	""
"1093"	"Akron University Police Patrolmens Assn"	""	"1991"	"1991"
"1096"	"Miamisburg Independent Employees Assn/Glenn E. Fortney Chapter"	"1985"	""	""
"1107"	"CWA Local 4524"	""	"1985"	""
"1122"	"FOP Lodge 28"	"1989"	"1988"	"1988"
"1139"	"CWA Local 4522"	""	"1990"	"1990"
"1180"	"Mansfield Police Patrol Officers Assn"	""	"1993"	"1993"
"1215"	"Rocky River Service Employees Assn"	""	""	"1989"
"1256"	"Unioto Support Assn"	"1989"	""	""
"1268"	"Bazetta Twp Road Dept Employees"	"1990"	""	""
"1308"	"UFCW Local 954"	""	"1987"	""
"1313"	"Barnesville Assn Classified Employees"	"1990"	""	""
"1320"	"Whitehall Tutor Assn"	"1990"	""	""
"1323"	"Teamsters Local 637"	"2002"	"2015-12-31"	"2015-12-31"
"1333"	"Independence Classified & Support Personnel"	"1991"	""	""
"1334"	"Cuyahoga Heights Assn of Support Employees"	"1991"	""	""
"1335"	"FOP Lodge 178 *File Closed; see comment"	"1991"	""	""
"1343"	"Maintenance Caucus"	"1991"	""	""
"1349"	"Command Officers of Fremont Police Dept"	"1992"	""	""
"1351"	"United Turnpike Workers Local 791 / UE"	"2001"	"2000"	"2000"
"1380"	"Oberlin Municipal Employees Corporation"	"2002"	"2002"	"2002"
"1381"	"FOP/OLC Office & Clerical Bargaining Unit"	"1993"	""	""
"1386"	"CWA Local 4390"	""	"1992"	"1992"
"1387"	"CWA Local 4401"	""	"1992"	"1992"
"1389"	"CWA Local 4315"	""	"1992"	"1992"
"1391"	"CWA Local 4354"	""	"1992"	"1992"
"1392"	"CWA Local 4311"	""	"1992"	"1992"
"1404"	"OPEIU Local 19   "	"1994"	"2016-01-31"	"2016-01-31"
"1407"	"OAPSE Local 0044 (Portage CBDD)"	"1994"	""	""
"1422"	"Electric Bridge Operators Assn"	"1994"	""	""
"1445"	"Employees of the City of Port Clinton"	"1995"	""	""
"1548"	"Lebanon City Schools Emps Assn"	"2003"	"2016-12-31"	"2016-12-31"
"1552B"	"AFSCME Local 3238B"	""	"2004"	"2004"
"1566"	"IAFF Local 3411"	"2003"	"2015-12-31"	"2015-12-31"

**Comment by altrdgenetics** [comment]
SQL statements that NEED re-imported, fields Just contain entries with YEAR only.

```
SELECT * from EmployeeOrg WHERE LEN(EmployeeOrg.FinancialStatementLastFiled) = 4
SELECT * from EmployeeOrg WHERE LEN(EmployeeOrg.AnnualReportLastFiled) = 4
SELECT * from EmployeeOrg WHERE LEN(EmployeeOrg.RegistrationReportLastFiled) = 4
SELECT * from EmployeeOrg WHERE LEN(EmployeeOrg.ConstitutionAndBylawsFiled) = 4
SELECT * from EmployeeOrg WHERE LEN(EmployeeOrg.filed) = 4
```

**Comment by anthonyperk** [comment]
licia is manually editing these
