### ISSUE TITLE
(PROD157) - (ALL) - Verification prompt when hitting the 'X'

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#538]
When the user clicks on the Red X to close the application, Please add a verification Prompt,
“Are you sure you want to close” Yes/No

![image](https://cloud.githubusercontent.com/assets/24595073/26073081/af2ad4cc-397b-11e7-9d50-924de3354915.png)

**Comment by parkjohnston** [comment]
30 minutes
