### ISSUE TITLE
(PROD159) - (MED) - Change fact finder panel original

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#540]
Please make the box below a drop down box showing all the available fact finders. That way Mary can update it when needed. There was an incorrect fact-finder listed. The existing code to populate this box does not need to change.

![image](https://cloud.githubusercontent.com/assets/8847344/26116450/330d846e-3a31-11e7-8871-23c521d4a165.png)

**Comment by altrdgenetics** [comment]
EMAIL CHAIN (oldest to newest):


> Chris
> 
> I may need clarification on PROD 159.
> 
> Said ticket is in regards to Mary (MED) having the ability to “over write” the field “Original Fact Finder”.  It was my understanding that this field, once populated by the system to indicate the original name of the fact finder, was not to be edited or modified by a user.  If it were to be modified, then why have the “Original Fact Finder” as a way to be sure MED does not pick and choose fact finders at their whim.
> 
> Or then again, perhaps I am mis-understanding the intent of PROD 159. 
> 
> In any event, I wanted to voice my concerns.
> 
> Thank You
> Allen Perk

-----------------------------------------------

> After gaining clarification on this from Justin, the request is valid in that there are apparently times that the field is not populated with the correct name and therefore needs to be edited. It is not an attempt to pick and /or choose fact finders at her whim. But, thanks for asking.
> 
> Thanks!
> Chris

-----------------------------------------------

> Oh.  That's a different item altogether.  We will look into as to why the field is not populating with the correct name and therefore needs to be edited.
> 
> I just wanted to be sure.
> 
> Thank You.
> Allen Perk

**Comment by altrdgenetics** [comment]
Uhhhh he was original Fact Finder. Mary removed him, she is trying to hide the fact that she is doing this.

![screenshot](https://cloud.githubusercontent.com/assets/8847344/26173002/4cb848a8-3b18-11e7-9558-0909d7236be5.png)

**Comment by altrdgenetics** [comment]
OUR BACKUP FROM ~4-18-2017


![screenshot 161](https://cloud.githubusercontent.com/assets/8847344/26173173/e689bda4-3b18-11e7-952b-9cf8e86051a5.png)

**Comment by anthonyperk** [comment]
From 2.0

![image](https://cloud.githubusercontent.com/assets/24595073/26173312/6093ed68-3b19-11e7-9fb9-10cb4976e701.png)

**Comment by altrdgenetics** [comment]
**FROM JUSTIN:**

> Allen,
> 
> I believe the Original Fact Finder field saves only the first fact finder selected. If the wrong fact finder was selected originally, then it gets stuck in the field and is unable to be edited. We had the same issue in SMDS 2.0.
> 
> Thank you,

Justin Brown

**Comment by altrdgenetics** [comment]
FROM ALLEN -> CHRIS:

> Chris
>  
> Additional data and information has come to my attention regarding this issue.  I feel it important that we sit down and address what we have found on this matter and then from that, what we (XLN & SERB) should do to address it.
>  
> Therefore I request a 30 minute meeting (let’s hold ourselves to that) to discuss this issue.  We are open from 10am to Noon tomorrow.  Will that work?  If so, let’s do it.  If not, let’s get to this early next week.
>  
> Thank You.
> Allen Perk

**Comment by altrdgenetics** [comment]
This was brought to their attention and Chris seemed to be very interested in the information we gave her. She was not told what really happened and now that she sees the data she is questioning it. 


HOWEVER...

They are still opting to go forward with this and also want the Conciliation panel to be the same.

They want the dropdown to be anyone active to be in the dropdown.

**Comment by parkjohnston** [comment]
I so don't think that this is a great idea at all...i know that we have been told to do it, but i see SEVERAL issues coming into play down the line that have me vastly worried about things being changed.  

Question for SERB:

Why are we allowing all FF/Concils to be loaded when it should only ever be picked from the generated list or depending on the type selection.  I think that regardless we should still follow the type selection rules.  I am worried that it would lead to other people being entered into the selected FF/Concil when they can't even follow the simple process that we have been told was what needed to be there in 2.0 and now 3.0.  Entering wrong information is NOT an application/XLN issue...it is an attention to detail issue that should be in place or more training. 

Again, I know that they have said green light it, but loading ALL of the options really brings into play that people that not even possible to be selected will be selected as they have shown they can't even pick from the list properly the first time.

Let me know how to proceed; as of now I have it as requested above, but just expressing my worries above and would like to make SERB aware of the issue and suggest another possible change to avoid "favorites" etc.

**Comment by altrdgenetics** [comment]
I didn't feel like writing that out, but it was brought to them during our meeting... Our concerns would have even been heard by deaf ears. We spent more than 30min in person discussing it with them and brought the screenshots shown in this tickets. Slapped them right in the face with proof and they acknowledged that she lied to them, and then proceed to tell us to do it anyways (Chris & Justin).

So doesn't matter how wrong they are, or how bad of an idea it is, they still want to pay us to do it.

**Comment by parkjohnston** [comment]
👍🏻

**Comment by parkjohnston** [comment]
This is completed, but will be changing functionality back to when the user saves FF/Concil the org is stated as it operates now.  

Had made a change to hold the information for MED section to update...this will revert to the old way

**Comment by parkjohnston** [comment]
4 hours
