### ISSUE TITLE
(PROD165) - (MED) - Fact-Finder and Conciliator Auto pick confirmation

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#547]
MED section Fact-Finder and Conciliator Auto Pick.
- Please confirm the auto pick is even. May need to tweak or build in a catch so that
a name does not go out more than 5x more than another name.

I have attached a report to review. We can discuss. This is not an urgent item.

My concern is the discrepancy in Year 2017 where one name was sent out 12 times while all others are
well under 12.

**Comment by parkjohnston** [comment]
This is a waste of space...RANDOM is random....

**Comment by altrdgenetics** [comment]
CODE FROM 3.0:

`int randomNumber = new Random().nextInt(randomFFList.size());`

**Comment by parkjohnston** [comment]
gets a random number within the size of the array...they are just now freaking out about us whistle blowing on some shady shit

**Comment by altrdgenetics** [comment]
CODE FROM 2.0:

```
int randomInt;
MEDCounterData MCD = new MEDCounterData();
MEDCounterData MCD2 = new MEDCounterData();
Random randomGenerator = new Random();
int number = atts.size();
```

**Comment by anthonyperk** [comment]
Talked to Justin on the Phone, he now understands that it is truly random, and that since FF and Concil. can be deactivated, the numbers COULD be skewed
