### ISSUE TITLE
(PROD166) - (Hearings) - Cases in advanced search are not displaying the correct information

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#548]
In the Hearings tab, the case name that displays in the search box is wrong. In the example below, case 17-ULP-01-0003 shows in the search box as City of Mayfield Heights, but is actually ATU and Toledo RTA.

![image](https://cloud.githubusercontent.com/assets/24595073/26318770/402ac162-3eea-11e7-8c34-7c94361bb54c.png)

**Comment by altrdgenetics** [comment]
There was an issue with pulling the case parties. it was doing it off of the global case number when a casenumber was provided.

**Comment by altrdgenetics** [comment]
changed out the case search table manually and added in the search for the case parties on the code
