### ISSUE TITLE
(PROD167) - (ULP) - Mediator Dropdown needs to also contain State Mediators

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#549]
In the ULP Section -> Mediator Assigned Drop Down, the SERB Mediator’s need added to the list. (Mediators Table where status = “State”)

![image](https://cloud.githubusercontent.com/assets/24595073/26318812/6ae72030-3eea-11e7-9082-b7fe6f9a2268.png)

**Comment by anthonyperk** [comment]
This had been fine, why the change now?

**Comment by altrdgenetics** [comment]
**TO JUSTIN:**

> Justin,
> 
> For this drop down are you asking for it to be State Mediator AND Caseworkers OR Just State Mediator? The ticket reads like you want both but I am wanting to confirm that I am reading that correctly. 
> 
> Based off of the information we received during meetings when building out the ULP section we store the drop-down information as an INT from the Users Table keyID in the database to the ULPCase table. The old system was a free-form text box. Currently this information comes from the Users table, since the column in the database is not a VARCHAR() the solution to make this work as described will become exponentially  more difficult and possibly result in a modification of the DB column from INT -> VARCHAR. 
> 
> The less complex solutions would be either to add the ULP workers to the Mediator table as State Mediators (code change still required) or Add the state Mediators as ULP CaseWorkers (no code change required at all). And do not forget that any reports using that drop-down will need to be modified as well.
> 
> 
> - Andrew

**Comment by altrdgenetics** [comment]
**FROM JUSTIN:**

> Andrew,
> 
> I am in need of this list to include both State Mediator AND Caseworkers.
> 
> I understand this is the more complicated approach and that it may affect reports (which ones I am not sure).
> 
> I apologize that this was not ironed out during the initial planning meetings.  
> 
> Thank you,
> Justin Brown

**Comment by altrdgenetics** [comment]
After having discussed this with Parker this ticket will have to be a single day change over. Where we fix it and release it same day/night. This probably will not make the cut for 3.2

**Comment by altrdgenetics** [comment]
Discussed this ticket in the meeting... This ticket is currently on hold, it is important but it is on hold till SERB gives the green light.... money issues as reason.

**Comment by parkjohnston** [comment]
This will be a huge change....first part completed.

Have the list sorted and loading into the dropdown.

Time: 90 minutes

**Comment by parkjohnston** [comment]
Working to convert everything to String now

**Comment by parkjohnston** [comment]
This will have an effect on ALL reports that are used in ULP. 

sorry @anthonyperk

**Comment by anthonyperk** [comment]
I will go over the ULP reports and make sure that I change those that need to be strings from ints

**Comment by parkjohnston** [comment]
This entire ticket is over this: 
<img width="460" alt="screen shot 2017-09-10 at 10 14 16 am" src="https://user-images.githubusercontent.com/3246562/30249769-eac7c764-9610-11e7-8254-c450e5a9eecc.png">

**Comment by parkjohnston** [comment]
My name was on countless other cases (from 2000-2004) I have removed that and set them back to null

**Comment by parkjohnston** [comment]
Data is very odd, shows my name for many of them.  Have updated the 0 value to be null as that is proper now that it is a string.

Need data to be imported for old cases.

**Comment by parkjohnston** [comment]
Time: 3 hours

Plus above 90 minutes

Total time (so far): 4.5 hours

**Comment by parkjohnston** [comment]
This is released, but needing @altrdgenetics to rerun data update.

If the data is not easy to reimport, kick this to Justin as a change in functionally made the data we were storing no longer viable

**Comment by altrdgenetics** [comment]
migrated everything over again. Raw import on the data since it is now strings
