### ISSUE TITLE
(PROD170) - (ORG) - ORG Mail Log column lables are incorrect

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#552]
The Org Mail Log, we are unable to expand the column header. It should read “Docketed”, the third Column should read Org Number, The fourth column Should read “Assigned To”

![image](https://cloud.githubusercontent.com/assets/24595073/26357483/666acc92-3f9d-11e7-9e96-7eb565537584.png)

**Comment by altrdgenetics** [comment]
when the columns were re-arranged a small if statement was missed in header label replacement.
