### ISSUE TITLE
(PROD171) - (Calendar Invites) - Notifications need tweaking

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#553]
When the Calendar invites are set for prehearings, record hearings, etc, for SERB and CMDS, the
notification needs a few tweaks.
The subject needs tweaked to display like it did in the previous system.
a. [Type Code] [ALJ Initials] [Appellant] [Case Number]
b. RH RMG Hageman 2016-REM-06-0113
c. For ULP cases [Appellant] field should be [Respondent] Party
d. For REP and MED cases [Appellant] field should be the [Employer] Party

![image](https://cloud.githubusercontent.com/assets/24595073/26357531/91f7608c-3f9d-11e7-85e7-350316d9edf8.png)

Example from 2.0
![image](https://cloud.githubusercontent.com/assets/24595073/26357540/96e1b854-3f9d-11e7-9130-52c62b1ba9d0.png)

**Comment by altrdgenetics** [comment]
Due to the complexity of the subject line we will need to go ahead and add the subject line column to the database Because of this changes will need to be made to the database, to the email server, and also to the application itself.

**Comment by altrdgenetics** [comment]
finally got everything squared away with the adding of the invites... lots of new information pulled in here

**Comment by altrdgenetics** [comment]
only thing left to do is wait on the next build to be released and update the database

**Comment by altrdgenetics** [comment]
since the release went out last night I have added the rest of the items required to setup. Nothing else needs to be done outside of the 3.2 release
