### ISSUE TITLE
(PROD172) - (MED) - System allowing things to be docketed to nonexistant cases

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#554]
When docketing into MED, the system allowed user to docket to a case number that does not exist.
These were docketed by email.

Case number 2016-MED-01-00027, 2016-MED-01-0028 exist
Case number 2016-MED-08-00027, 2016-MED-08-0028 do not exist 

We believe these were docketed to both cases at the same time.

![image](https://cloud.githubusercontent.com/assets/24595073/26357593/c6dead1e-3f9d-11e7-9aab-f80f8b38d9b4.png)

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN:

> Justin,
> 
> Were they docketed to multiple cases at the same time (entering multiple case numbers in the ‘File’ window separated by a comma)?
> 
> Any other information would be helpful.  From looking at the code, every docketing screen has a validation on casenumber to make sure it exists, so we are not sure how this happened.  Have you been able to reproduce this issue?

EMAIL FROM JUSTIN

> They believe these were docketed to the cases at the same time (more than one case number entered into the case field).

**Comment by parkjohnston** [comment]
The issue was that the cases were validated an error thrown but users (Mary) chose to continually ignore the countless warnings that appeared (about 8 dialogs).  However, the XLN issue fell on us at the point that even though the user ignored and interacted with ~8 dialogs, we still allowed them to file the document.  Change will be made to clear out the case number dialog when the case number is NOT valid to match all the other interactions.

**Comment by altrdgenetics** [comment]
**I had sent this to Justin Earlier today:

TO JUSTIN:**

> Justin,
> 
> We were finally able to recreate this issue on our own. The steps required to complete this involves users ignoring warnings and prompts. In every section we do verify case numbers against the SQL database splitting them on commas. If there is a case number that fails we notify the user with a prompt that there is an invalid case number and tell them specifically which one it is; the dialog box wording is (Case Number " + caseNumber + " is not valid). At that point in time a user should make note of that and remove or change it, however in this example the user ignored the message and proceeded to click the File Button anyways.
> 
> We will put in additional checks to make sure that the File Button is not enabled on partially invalid case number list.
> 
> - Andrew
