### ISSUE TITLE
(PROD174) - (MED) - Fact Finders not being CC'd on some outgoing letters

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#555]
The Fact Finder is not being CC’d on outgoing emails for the following four letters.

Confirmed CC is not working:
Accepted Fact Finder Report (Case 2015-MED-07-0648 Sent 5/22/2017)
Accepted and Deemed Accepted Fact Finder Report (Case 2016-MED-07-0701 Sent 5/18/2017)
Deemed Accepted Fact Finder Report (Case 2016-MED-08-0758 Sent 5/18/2017)
Rejection of Fact-Finding Report (Case 2016-MED-08-0827 Sent 5/22/2017)

No examples to confirm if CC is working: (Please double check)
Fact Finder Appointment Letter SERB (Discrectionary)
Fact Finder Extension
Conciliation Appointment SERB (Discretionary)
MAD Fact Finder Appointment
MAD Conciliation Appointment

Confirmed CC is working:
Fact Finder Appointment Letter
Conciliation Appointment Letter
Mediator Appointment State
Mediator Appointment FMCS

**Comment by altrdgenetics** [comment]
**TO JUSTIN:**

> Justin,
> 
> Not all of the items listed in the ticket were in your list of what needed to be CC'd for the MED section. We had discussed this in a meeting and came up with the following logic. If you remember I had concerns about hard-coding this information in as it was not easy to change at a later point in time. We had also discussed if they should be CC'd on all documents containing 'mediator', 'fact finder', etc; and you opted to not go down that route as you believed it would CC persons inappropriately.  Below is the [simplified] code that is in 3.0, any changes beyond what exists there will have to be an enhancement or change in functionality if you will.

**Comment by altrdgenetics** [comment]
**FROM JUSTIN:**

> Andrew,
>  
> Please add the seven items below that are not highlighted. All of them are for the fact finder except “Conciliation Appointment SERB (Discretionary), 
> Also, I did spell Discretionary wrong for the “Fact Finder Appointment Letter SERB (Discrectionary)”

**Comment by altrdgenetics** [comment]
I added these in, hard-coded to match the previous ticket on adding these persons to the CC list automatically behind the scenes.
