### ISSUE TITLE
(PROD173) - (ULP) - Check on note data in DB

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#556]
Can you run a query and tell me what cases contain the following two lines of text in the notes field?
Case closed by rsb
Paper destroy date 12-06-2015
I have found it in 2017-ULP-01-0015, 0016, 0017, 0025. It was there in the 2.0 system. I am not sure if it was just entered into the wrong cases or if there was a system glitch. The query results will hopefully tell me more.

![image](https://cloud.githubusercontent.com/assets/8847344/26365018/55b8b654-3fb4-11e7-8ac7-5e1d7804881a.png)

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> Justin,
> 
> The following cases from 3.0 and 2.0 have this note as part of its Notes tab:
> 
> 3.0 Case Number                             2.0 Case Number
> 2012-ULP-12-0305                            2012-ULP-12-0305
> 2013-ULP-01-0001                            2013-ULP-01-0001
> 2014-ULP-06-0096                            2014-ULP-06-0096
> 2014-ULP-06-0099                            2014-ULP-06-0099
> 2014-ULP-06-0102                            2014-ULP-06-0102
> 2014-ULP-07-0107                            2014-ULP-07-0107
> 2014-ULP-08-0128                            2014-ULP-08-0128
> 2014-ULP-08-0132                            2014-ULP-08-0132
> 2014-ULP-08-0133                            2014-ULP-08-0133
> 2014-ULP-08-0148                            2014-ULP-08-0148
> 2014-ULP-08-0149                            2014-ULP-08-0149
> 2014-ULP-09-0156                            2014-ULP-09-0156
> 2014-ULP-10-0195                            2014-ULP-10-0195
> 2016-ULP-08-0181                            2016-ULP-08-0181
> 2016-ULP-08-0182                            2016-ULP-08-0182
> 2016-ULP-09-0200                            2016-ULP-09-0200
> 2016-ULP-09-0216                            2016-ULP-09-0216
> 2016-ULP-09-0217                            2016-ULP-09-0217
> 2016-ULP-09-0218                            2016-ULP-09-0218
> 2016-ULP-09-0219                            2016-ULP-09-0219
> 2016-ULP-09-0220                            2016-ULP-09-0220
> 2016-ULP-10-0230                            2016-ULP-10-0230
> 2016-ULP-10-0231                            2016-ULP-10-0231
> 2016-ULP-10-0236                            2016-ULP-10-0236
> 2016-ULP-10-0237                            2016-ULP-10-0237
> 2016-ULP-12-0274                            2016-ULP-12-0274
> 2017-ULP-01-0012                            2017-ULP-01-0012
> 2017-ULP-01-0013                            2017-ULP-01-0013
> 2017-ULP-01-0015                            2017-ULP-01-0015
> 2017-ULP-01-0016                            2017-ULP-01-0016
> 2017-ULP-01-0017                            2017-ULP-01-0017
> 2017-ULP-01-0025                            2017-ULP-01-0025
> 2017-ULP-02-0048                            2017-ULP-02-0048
> 2017-ULP-02-0049                            2017-ULP-02-0049
> 2017-ULP-02-0050                            2017-ULP-02-0050
> 2017-ULP-02-0052                            2017-ULP-02-0052
> 2017-ULP-02-0053                            2017-ULP-02-0053
> 
> Looks like it’s a complete match


EMAIL FROM JUSTIN

> OK, 
> 
> We will manually remove those entries. Please close the ticket.
