### ISSUE TITLE
(PROD175) - (Hearings) - Report not showing correct information

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#557]
The Hearings report within the Hearings tab is not displaying the assigned mediator or the outcome of the mediation. Example below is case 2016-ULP-11-0260.
Thanks, Erin

![image](https://cloud.githubusercontent.com/assets/8847344/26410275/c7f6569c-4070-11e7-98cc-61fa0c90eef2.png)

**Comment by anthonyperk** [comment]
IN THE REPORT:

Changed the Nested SELECT to look at Mediator table not the Users table

CASE WHEN (HearingsMediation.mediator IS NOT NULL) THEN (SELECT (User.firstName + ' ' + User.lastName) FROM User WHERE User.id = HearingsMediation.mediator) ELSE 'NO MEDIATOR ASSIGNED' END AS Mediator,

CASE WHEN (HearingsMediation.mediator IS NOT NULL) THEN (SELECT (Mediator.firstName + ' ' + Mediator.lastName) FROM Mediator WHERE Mediator.id = HearingsMediation.mediator) ELSE 'NO MEDIATOR ASSIGNED' END AS Mediator,

**Comment by altrdgenetics** [comment]
adjusted the calls so it pulls the correct person now for the header

**Comment by anthonyperk** [comment]
Reopening this because I also missed the Mediation Outcome

**Comment by anthonyperk** [comment]
Changed the Outcome from HearingCase to HearingsMediation table

HearingsCase.Outcome AS Outcome   ->   HearingsMediation.Outcome AS Outcome
