### ISSUE TITLE
(PROD176) - (REP) - Eligibility label misspelled

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#558]
REP Election Tab… Spelling Error
Eligibility

![image](https://cloud.githubusercontent.com/assets/24595073/26420162/d0ab3338-408f-11e7-9089-4bccf82aae25.png)

**Comment by altrdgenetics** [comment]
fixed this and adjusted the alignment of some columns so they were straight with one another.
