### ISSUE TITLE
(PROD178) - (ORG) - ORG Letter bookmark additions

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#560]
ORG Letter Bookmark Request.
Create 3 new bookmarks
1) ORGAnnReptLF
a. Displays “Received” or “Missing” text if the date is not within the appropriate range
b. Criteria should be the same as is used to decide if they get a letter or not

2) ORGFSLF
a. Displays “Received” or “Missing” text if the date is not within the appropriate range
b. Criteria should be the same as is used to decide if they get a letter or not

3) ORGCONBYLAWSLF
a. Displays the date “02/02/2012”
We want to add the following paragraph to the existing reminder templates to better explain what documents we still need from them.

**Reporting Document Status**
Annual Report: Received
Financial Statement: Missing
Constitution and Bylaws Last Filed: 6/15/2013

**Comment by altrdgenetics** [comment]
**TO JUSTIN:**

> Justin,
> 
> Can i get some clarification on this ticket.
> 
> You keep saying "if the date is not within the appropriate range", but we do not have the user selecting any dates or even have any popup boxes for letter generation in the ORG section. So what are you trying to do?
> 
> You have also given me tickets in the past that have text with either an example or the exact wording you want used... what is it for #3? It says "displays the date "02/02/2012"  " but the example you provide below says "6/15/2012". Which even if you meant #3 as an example it is in a different format as the one shown (missing the 0 digit fill on single digit month). 
> 
> I am missing a lot of information required understand what you are trying to do with this ticket. ORG section bookmarks is by far the simplest section with amount of bookmarks and logic that currently exists. And as a reminder contains only these bookmarks.
> "OrgHeaderBlock"
> "RepName"
> "RepSalutation"
> "OrgAddress"
> "OrgName"
> "OrgNum"
> "CertifiedDate"
> "CCList"
> 
> 
> - Andrew

**Comment by altrdgenetics** [comment]
**FROM JUSTIN:**

> Andrew,
> 
> In the org section, when generating letters for all organizations, the user selects the desired letter. Based upon that letter, the system “auto” selects which orgs should be sent a letter. The ruleset to “auto”  select who should receive the letter is what I am interested in using to generate the two bookmarks for “ORGAnnReptLF” and “ORGFSLF” bookmarks to display the text of “Received” or “Missing”
> 
> I am not sure the best way to code this, but hopefully you can understand what we are trying to do with these bookmarks.
> 
> The “ORGCONBYLAWSLF” last filed can be displayed as 6/15/2013 (exclude zero in two digit month and day field). Sorry for the confusion.
> 
> Thank you,
> Justin Brown

**Comment by altrdgenetics** [comment]
Lack of understanding here, Justin is missing that there is not a link from all letters panel to bookmarks

**Comment by altrdgenetics** [comment]
**TO JUSTIN:**

> Justin,
> 
> I think I have an idea with what you are looking for, but the problem that we are running into is there is no actual link between building out the list for ALL-Letters and the individual bookmark placement as they are inserted into the document as the application iterates through that list. The bookmarks need to function if the document is generated though ALL document process or Singular document process. 
> 
> I am not sure if the rule-set for the date fields would even match what we are using to build the list out. To build out the All letters list we are comparing multiple columns to decide whether or not a single ORG (db row) would be shown. For we need to compare each column to a rule individually to determine what text is shown as the bookmark. I will need to be provided the rule set for each of the fields that you want to be "received" or "missing". I am pretty sure this will just be a "what is the cut off" for a time frame. But I will need to know the rule and the exact text you want displayed for each of the 3 new bookmarks (ex., you not list what you want 'ORGCONBYLAWSLF' to say if it is NULL in the db).
> 
> - Andrew

**Comment by altrdgenetics** [comment]
**FROM JUSTIN:**

> XLN Team,
>  
> Below is an alternative method using existing fields in the ORG section database. We should be able to use the “Fiscal Year Ending” field and do a little math. The year in yellow is the part that I am not sure how to calculate using coding since it varies depending on when the report is run throughout the calendar year.  I am open to suggestions.
>  
> If Fiscal Year Ending = “August”, Due date is January 15th. If Annual Report LF = 08/xx/2016 then “Received”, Else “Missing”
> If Fiscal Year Ending = “August”, Due date is January 15th. If Financial Statement LF = 08/xx/2016 then “Received”, Else “Missing”
>  
> If Fiscal Year Ending = “September”, Due date is February 15th. If Annual Report LF = 09/xx/2016 then “Received”, Else “Missing”
> If Fiscal Year Ending = “September”, Due date is February 15th. If Financial Statement LF = 09/xx/2016 then “Received”, Else “Missing”
>  
> If Fiscal Year Ending = “October”, Due date is March 15th. If Annual Report LF = 10/xx/2016 then “Received”, Else “Missing”
> If Fiscal Year Ending = “October”, Due date is March 15th. If Financial Statement LF = 10/xx/2016 then “Received”, Else “Missing”
>  
> If Fiscal Year Ending = “November”, Due date is April 15th. If Annual Report LF =11/xx/2016 then “Received”, Else “Missing”
> If Fiscal Year Ending = “November”, Due date is April 15th. If Financial Statement LF =11/xx/2016 then “Received”, Else “Missing”
>  
> If Fiscal Year Ending = “December”, Due date is May 15th. If Annual Report LF = 12/xx/2016 then “Received”, Else “Missing”
> If Fiscal Year Ending = “December”, Due date is May 15th. If Financial Statement LF = 12/xx/2016 then “Received”, Else “Missing”
>  
> If Fiscal Year Ending = “January”, Due date is June 15th. If Annual Report LF = 01/xx/2017 then “Received”, Else “Missing”
> If Fiscal Year Ending = “January”, Due date is June 15th. If Financial Statement LF = 01/xx/2017 then “Received”, Else “Missing”
>  
> If Fiscal Year Ending = “February”, Due date is July 15th. If Annual Report LF = 02/xx/2017 then “Received”, Else “Missing”
> If Fiscal Year Ending = “February”, Due date is July 15th. If Financial Statement LF = 02/xx/2017 then “Received”, Else “Missing”
>  
> If Fiscal Year Ending = “March”, Due date is August 15th. If Annual Report LF = 03/xx/2017 then “Received”, Else “Missing”
> If Fiscal Year Ending = “March”, Due date is August 15th. If Financial Statement LF = 03/xx/2017 then “Received”, Else “Missing”
>  
> If Fiscal Year Ending = “April”, Due date is September 15th. If Annual Report LF = 04/xx/2017 then “Received”, Else “Missing”
> If Fiscal Year Ending = “April”, Due date is September 15th. If Financial Statement LF = 04/xx/2017 then “Received”, Else “Missing”
>  
> If Fiscal Year Ending = “May”, Due date is October 15th. If Annual Report LF = 05/xx/2017 then “Received”, Else “Missing”
> If Fiscal Year Ending = “May”, Due date is October 15th. If Financial Statement LF = 05/xx/2017 then “Received”, Else “Missing”
>  
> If Fiscal Year Ending = “June”, Due date is November 15th. If Annual Report LF = 06/xx/2017 then “Received”, Else “Missing”
> If Fiscal Year Ending = “June”, Due date is November 15th. If Financial Statement LF = 06/xx/2017 then “Received”, Else “Missing”
>  
> If Fiscal Year Ending = “July”, Due date is December 15th. If Annual Report LF = 07/xx/2017 then “Received”, Else “Missing”
> If Fiscal Year Ending = “July”, Due date is December 15th. If Financial Statement LF = 07/xx/2017 then “Received”, Else “Missing”
>  
> Bookmarks:
> “ORGAnnReptLF”
> “ORGFSLF”
>  
> ORGCONBYLAWSLF
> If Constitution and Bylaws field is blank or null display “Missing” else display the date (Example: 1/22/2015)
> Thank you,
>  
> Justin Brown

**Comment by altrdgenetics** [comment]
**TO JUSTIN:**

> Justin,
> 
> This is the same kind of back and forth that we went through with the All Letters panel. We had many issues with it because we were not given exact information and the information we did have from 2.0 was not correct. It really looks like you are trying to make it more complicated than it is but I really cant tell. Here will be the logic and I will need you to fill in the blanks….
> 
>  
> 
>     Annual Report:
> 
>     IF [ARLF] IS OLDER THAN [DATE]
> 
>                     “Missing”
> 
>     ELSE
> 
>                     “Received”
> 
>      
> 
>     Financial Statement:
> 
>      
> 
>     IF [FSLF] IS OLDER THAN [DATE]
> 
>                     “Missing”
> 
>     ELSE
> 
>                     “Received”
> 
> I need to know what that [DATE] should be. From your email It appears that is is:
> 
> [DATE] =      [FYE-MONTH]    /    [WHICH DAY OF MONTH??]    /   [CURRENT YEAR MINUS ONE]
> 
> is this correct? I will need to know which day of the month you want it to fall on.
> 
> - Andrew

**Comment by altrdgenetics** [comment]
Showed Justin why his examples were bad and he will be submitting new examples soon for future addition. He will give proper examples so we can derive the logic.

**Comment by altrdgenetics** [comment]
Justin is lazy and does not feel like working on figuring out the logic. We will just put the straight dates in those fields for now and if it isn't enough then he will submit a new ticket to adjust for it later

**Comment by altrdgenetics** [comment]
finally finished this one out, made sure I did the null check on the date, there was not anything listed for the default text so I left it blank.
