### ISSUE TITLE
(PROD180) - (MED) - Send MED Cases to Board to Close not showing single dates

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#562]
All 342 cases have a settlement date of 5/1/2017
If I enter a start date of 5/1/2017 they do not show in the list.

![image](https://cloud.githubusercontent.com/assets/24595073/26462503/156b77c0-414f-11e7-80c2-5f96f23e2f79.png)

**Comment by anthonyperk** [comment]
I am very rich

**Comment by altrdgenetics** [comment]
so this was a bug with the way that the dates were calculated, it showed the date with the time all set to midnight so on a same day it would give the full day.
