### ISSUE TITLE
(PROD181) - (CMDS/Docketing) - Unable to docket to multiple cases

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#563]
I was attempting to docket a scanned document to several case numbers at once in CMDS. The item only filed to the first case number. XLN also received some sort of error notice.
Per Anthony’s request, I went back in and re-created the steps that I followed in order to get the screen shot below.
It was a scanned item I was trying to docket to multiple case numbers:
2016-ABL-05-0101, 2016-LAY-05-0102, 2016-ABL-05-0103, 2016-LAY-05-0104, 2016-ABL-05-0105, 2016-LAY-05-0106
It only filed to the first case.

EMAIL TO ERIN
> Erin,
> We noticed an issue with some CMDS things that were just entered. Were you entering things into CMDS? If so, can you give me what case number and what fields you were filling in?
> Anthony Perk

![image](https://cloud.githubusercontent.com/assets/24595073/26588614/c878d434-4523-11e7-95c6-c19885f36cf3.png)

**Comment by altrdgenetics** [comment]
got this fixed, issue was a leading space on the year number not getting trimmed starting at the second case number
