### ISSUE TITLE
(PROD182) - (MED) - FF CC is not listing the correct email for Van Pelt

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#564]
Case 2016-MED-11-1333 Fact Finder Appointment Letter > The CC email address shown below is not the one that is displayed in the Fact-Finder List for Gregory J. Van Pelt

Originally his last name was Van, Pelt I thought the comma was the problem. I fixed it in the panel and fixed it in the selection drop down. This still did not resolve the issue below. 

My next guess is that it is his two part last name

![image](https://cloud.githubusercontent.com/assets/24595073/26597425/eae867de-453f-11e7-9f4e-53199fd85e57.png)

**Comment by anthonyperk** [comment]
TO JUSTIN

> Justin,
> 
> Alright, let me know when you sort through all of your ideas. Once I know the outcome I will fix the issue.
> 
> - Andrew

FROM JUSTIN

> Andrew, 
> 
> I selected the other fact finders in the panel as the assigned fact finder and tested the letter. “Van Pelt” was the only one that is not using the correct CC. His name is the only one that is two parts. All the other fact Finders listed in FF Maintenance with two parts are “, Jr.”

**Comment by altrdgenetics** [comment]
switched the logic so it grabs length - 1 to grab FactFinder LIKE firstname/lastname
