### ISSUE TITLE
(PROD184) - (CSC) - CommissionAddressBlock bookmark change

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#566]
The Civil Service “commission address block” currently reads as follows:
Chairman
Municipal Civil Service Commission
[CommissionAddressBlock]

Upon further investigation with this section it was discovered that not all Civil Service Commissions across the state go by that name. So I need the address block to add the CSC Name to line one of the existing code.

Chairman
[CommissionAddressBlock]

![image](https://cloud.githubusercontent.com/assets/24595073/26830919/8825c9d0-4a98-11e7-86bd-dbc8f1019bd1.png)

**Comment by anthonyperk** [comment]
This is an addition to another enhancement (PROD126)

**Comment by anthonyperk** [comment]
(PROD126) - (CSC) - Add bookmarks #507

**Comment by altrdgenetics** [comment]
this is getting moved to the 3.2 release

**Comment by altrdgenetics** [comment]
finished this.
