### ISSUE TITLE
(PROD185) - (CMDS) - Issue with Jurisdiction PO letter

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#567]
In the CMDS Section,
Ray created the Jurisdiction PO letter. He attempted to use the letter queue. The letter appeared in the letter queue. Both email and Postal versions. When he attempted to send them they would blink across the screen.

Looking at the error log tonight, it seems to confirm the issue.

![image](https://user-images.githubusercontent.com/24595073/26879880-9f436c4e-4b60-11e7-8445-6eb73c515b9f.png)

**Comment by altrdgenetics** [comment]
we were not sanitizing the names of the files on conversion to PDF
