### ISSUE TITLE
(R3-002) - (ULP) - Report Sorting Issue

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#569]
The Assigned Date Report is not sorting the cases correctly. I have attached a few
pages of the report along with the cover sheet. It appears it is sorting the cases by the
MONTH filed and is disregarding the YEAR they were filed. The report should show the
cases in numerical order by YEAR.

The report was working correctly before today (6/16/2017).
The report should sort by: Newest cases filed to the oldest cases filed (depending on the
date range selected).

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> Justin,
> 
> The ORDER BY statement for this report is:
> 
> ORDER BY
>                 (Users.firstName + ' ' + Users.lastName), AssignedDate DESC, ULPCase.caseYear DESC, ULPCase.caseMonth DESC, ULPCase.caseNumber DESC
> 
> 
> This has not changed since 03/17/2017.  Should this be changed to just order by case number newest to oldest without regard to the Assigned Date?  If the assigned date needs to still be included, I can still fix this issue.


EMAIL FROM JUSTIN

> 
> Anthony, 
> 
> Please remove the “Assigned Date” text from the order by parameter.

**Comment by anthonyperk** [comment]
removed AssignedDate from the ORDER BY statement

.5 hours
