### ISSUE TITLE
(R3-005) - (ALL) - Annual Report generation issue

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#572]
SMDS Error Log
The error below appears when the Annual Report is generated. The report does generate.
com.microsoft.sqlserver.jdbc.SQLServerException: The column name COLUMN1 is not valid.

**Comment by altrdgenetics** [comment]
**TO JUSTIN:**

> Justin,
> 
> We are aware of the column that exists in the error log, XLN get notified of any issue that happens. This error occurred last week by Erin (several entries), however we did not receive any contact from SERB regarding this issue. I see that today before sending the email you have also caused the error twice, however in your ticket you did not provide us with the steps required to reproduce this error. We will be unable to work on this ticket without knowing the steps and user entered information.
> 
> - Andrew

**Comment by anthonyperk** [comment]
**FROM JUSTIN**

> Andrew, 
> 
> I was able to get the error by running the Annual Report from the File menu and putting in the date range of 7/1/2016 – 6/30/2017. I only ran the report once and it created two errors in the error log. 
>

**Comment by altrdgenetics** [comment]
Two SQL statements did not correctly alias the columns.... 31 ("threeone"), 93 ("ninethree"). Tested and no additional issues.
