### ISSUE TITLE
(R3-007) - (CMDS) - Activity Search issue

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#575]
In the CMDS Tab for case 2016-REM-09-0179 I type the word “Fred” and the search box only shows a “d” I believe this issue is only tied to this case… I tested in other sections and it worked fine. Once the issue occurs all cases after do not work or load correctly.

![image](https://user-images.githubusercontent.com/8847344/27401446-4901874e-5691-11e7-965c-10a380817cc8.png)

**Comment by parkjohnston** [comment]
this works with our dev data, so something between our last import and this ticket changed on their side...will be investigating what it was.  Seems to be a addition of a party

**Comment by parkjohnston** [comment]
after going through 98 records, i found the error....

![screen shot 2017-07-26 at 9 47 32 pm](https://user-images.githubusercontent.com/3246562/28650789-0ffa36ae-724c-11e7-8044-b14ee47f75ee.png)

The activity should NEVER be null, so someone appears to have mucked with this.

As the row has NO other values in it, I will be removing it from record upon payment of the PO

**Comment by parkjohnston** [comment]
Remove activity ID = 1125925

Time spent 90 minutes
