### ISSUE TITLE
(R3-008) - REP - Change of BCC in REP section

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#576]
When Angela sends the Registration Report Letter – Email from the REP Section the BCC should also include EOReport@serb.state.oh.us Below is the ebody. This is the only letter that should also be sent to the EOReport email address.

![image](https://user-images.githubusercontent.com/8847344/27435096-fce7dd0c-5728-11e7-8055-60972e181800.png)

**Comment by altrdgenetics** [comment]
![image](https://user-images.githubusercontent.com/8847344/27435376-0bdaae92-572a-11e7-98c9-f63841dfc097.png)


OLD Code shows this added in ONLY for registration report

**Comment by altrdgenetics** [comment]
![screenshot 10](https://user-images.githubusercontent.com/8847344/27435975-b47b4f74-572b-11e7-9779-855ad8b0186b.png)


THIS IS NOT A BUG ANYMORE

**Comment by altrdgenetics** [comment]
**TO JUSTIN:**

> Justin,
> 
>       You have previously sent us an email contradicting this ticket. March 9, 2017 you stated that ALL emails would BCC the specified box with no additional rules. The code was adjusted to meet the request in the email. Due to that this ticket should be considered a functionality change and marked as an enhancement, not a bug. I have attached a screenshot of the email for your reference, please adjust it accordingly.
> 
> - Andrew

**Comment by altrdgenetics** [comment]
updated the text in the top to reflect the revised ticket that Justin has submitted.

**Comment by parkjohnston** [comment]
updated

Time: 30 minutes

**Comment by altrdgenetics** [comment]
i had also spent 0.5hrs on this
