### ISSUE TITLE
(R3-009) - (CMDS) - Web updater changes

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#577]
Upon further investigation, I discovered that the error below only affects brand new cases that do not yet have any history entries to display on the PBR website. Can you check your query to make sure that the entry highlighted below appears on the PBR website? Also, Jim has requested that all history entries with “Ebody” should also be excluded from the website. We are getting customers calling and asking what that entry type is.

![image](https://user-images.githubusercontent.com/8847344/27548160-1c5cb56e-5a66-11e7-9a1d-f7ee7b19f7a2.png)

![image](https://user-images.githubusercontent.com/8847344/27548166-1fd23f3e-5a66-11e7-8119-a1e0f4d4c258.png)

![image](https://user-images.githubusercontent.com/8847344/27548169-22802462-5a66-11e7-8b50-806ca203f880.png)

![image](https://user-images.githubusercontent.com/8847344/27548172-25250994-5a66-11e7-95f7-6c64a8348203.png)

**Comment by parkjohnston** [comment]
Time spent 15 minutes

**Comment by altrdgenetics** [comment]
what did you do to this ticket?

this change is required for the Email Server

**Comment by parkjohnston** [comment]
i did do it in the email server
