### ISSUE TITLE
(R3-012) - (REP) - Bookmark Generation Issue

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#580]
In the REP Section. The “Registration Report Letter – Email” template. The bookmark “EOCONTACTEMAIL” displays as NULL in case 2017-REP-03-0040. I checked another case… 2017-REP-03-0034 which also has an Employee Organization REP and the bookmark populated correctly.
I removed the email address out of case 2017-REP-03-0040 and saved the record and reran the letter. I still get a NULL. I put the email address back in and tested again. I still get the error. Please assist.
I confirmed that the email address was entered correctly in the case.

![image](https://user-images.githubusercontent.com/8847344/27698816-36b622d0-5cc6-11e7-9e7f-2332de5855d7.png)

There are three bookmarks in a row so I put a number in front of them to confirm which bookmark was causing the problem.

![image](https://user-images.githubusercontent.com/8847344/27698826-3c203a8a-5cc6-11e7-9e6d-c0871c086994.png)

**Comment by parkjohnston** [comment]
This is ANOTHER serb is stupid issue...

EOCONTACT is for the NON REP party, which in this case is blank. Therefore, the email would never show up.  He is looking for EOCONTACTREP.

Waste of time

**Comment by parkjohnston** [comment]
It worked in the previous instance as the rep and non rep were the same person with the same email, so it appeared right with the REP, but it was just normal

**Comment by parkjohnston** [comment]
Just need to update a few calls to remove the null, but overall he is a mess with what he is looking at, compared to his expected result.

**Comment by parkjohnston** [comment]
This is completed, but also SERB/JUSTIN NEED to know that they may have the wrong expectation with the tag they have in place.  The reason that nothing is printing is the they are wanting the EOContact, but that contact has no email, however a REP does. 

The determination of what is proper, is outside of this ticket and also outside of our ability as we are not the users and he has FULL ability to change it.

Time Spent: 30 minutes
