### ISSUE TITLE
(R3-013) - (CMDS) - Report Issues

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#581]
In the CMDS Tab – Docket Inventory Report by case number ( I selected ALJ “All” and ALJ “James R. Sprague” ). The text on the notes tab does not appear on the report for every case.
They do not appear for cases 2016-IDS-09-0180, 2016-REM-10-0190
They do appear for cases 2016-INV-11-0198, 2016-REM-11-0201
NOTE: I ran the Docket Inventory Report by Hearing Date for comparison and the notes do appear for all of the cases.

![image](https://user-images.githubusercontent.com/8847344/27738572-afc48e74-5d79-11e7-82c5-38fb00666e48.png)

![image](https://user-images.githubusercontent.com/8847344/27738576-b1e5fcce-5d79-11e7-8303-d4658824b95b.png)

![image](https://user-images.githubusercontent.com/8847344/27738582-b483056c-5d79-11e7-9ce1-befd322a1a6f.png)

**Comment by anthonyperk** [comment]
Changed the way that the notes text box printed.  Also changed how the detail band grew/shrunk with null information.  Also moved the Hearing Info down a tad

**Comment by parkjohnston** [comment]
If this is completed, but waiting on payment please close...thanks!

**Comment by anthonyperk** [comment]
Time Spent: 1.25 hours
