### ISSUE TITLE
(R3-014) - (ORG) - Month MisSpelling

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#582]
In the ORG section on The ORG Information tab…

If Fiscal Year Ending “Febuary” is selected the Due date does not populate with July 15th. I double checked and all other months in the drop down work correctly.

I believe this issue will resolve itself if February is spelled correctly in the dropdown.

![image](https://user-images.githubusercontent.com/8847344/27750471-e3bf23e8-5da5-11e7-91cd-893e0efdfc5f.png)

**Comment by parkjohnston** [comment]
Fixed spelling in code..running SQL on prod to make sure no others are wrong

**Comment by parkjohnston** [comment]
select * from ORGCase where fiscalYearEnding like 'Feb%'

**Comment by parkjohnston** [comment]
this is completed just need to run the SQL in prod when time for the release

**Comment by parkjohnston** [comment]
.5 hour
