### ISSUE TITLE
(R3-015) - (REP) - Activity Button Issue

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#583]
I discovered two issues..
1)In the REP tab. If a user presses “Update” button while on the Activity Tab, User gets the “Addactivity” button.

![image](https://user-images.githubusercontent.com/8847344/27878609-cff64860-618c-11e7-96d0-78022735727e.png)

If user hits cancel. The user is unable to go to any other section. They are greyed out as shown in image on next page. If user goes to another REP tab, presses update, and save. They can then go to a different section. It gets them out of the loop.

2)Regarding the same button in the REP Section…- In the ULP section this button reads “Add Entry” on the Activity Tab, “Add Party” on the partytab, and “Update” on all remaining tabs.- In the REP section this button reads “Add Party” on the party tab, and “Update” on allremaining tabs.- Please tweak the text of the button to include the “Add Entry” text when on the activity tab inthe REP Section.
I discovered this while in case 2017-REP-04-0051

![image](https://user-images.githubusercontent.com/8847344/27878621-d9a036b4-618c-11e7-9b31-0be59d3e239c.png)

**Comment by parkjohnston** [comment]
Completed. 

Changing the button text, solved all issues...win/win

Time Spent: 15 minutes
