### ISSUE TITLE
(R3-017) - (REP) - Voter counts are off on Elections tab

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#585]
In the REP Section, the Election Total Ballots Cast field is not calculating correctly. Please calculate the blank boxes as “zeros” so the math works.

Example 1:
The election count is not auto adding. Total ballots cast should be 21 as reflected on the tally sheet
Case 2016-REP-06-0059
![image](https://user-images.githubusercontent.com/24595073/27971928-796c637a-6322-11e7-8885-121dcf845a33.png)

When I add the zero…
![image](https://user-images.githubusercontent.com/24595073/27971934-7d30ecba-6322-11e7-9d03-d5528c561c33.png)

Example 2:
Case 2016-REP-05-0050
The election count is not auto adding. Total ballots cast should be 49 as reflected on the tally sheet
The Total Column calculates correctly when I add a “0” in the EEO #2 box.
![image](https://user-images.githubusercontent.com/24595073/27971957-8d39ec9c-6322-11e7-9791-cb481d38fd46.png)

When I add the zero...
![image](https://user-images.githubusercontent.com/24595073/27971964-90b5c012-6322-11e7-9ee8-157184916d06.png)

**Comment by parkjohnston** [comment]
This is NOT something i can recreate...seems to be firing just fine for me.  Appears to be a data import issue.  Looking in the untouched case number in the screen shots the numbers are correct as displayed, but may have been imported incorrectly.  
![screen shot 2017-07-20 at 5 58 50 pm](https://user-images.githubusercontent.com/3246562/28440661-3792bc58-6d75-11e7-9664-e4d8b9949ed6.png)

Closing the ticket as it is NOT valid and will not be us fixing it.  The code is 100% solid.  Was an old data issue.  

Time spent 30 minutes
