### ISSUE TITLE
(R3-018) - (MED) - Mediators, FF, and Conciliator active/inactive issue

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#586]
In the MED section, we believe that when the mediators, FactFinders, and Conciliators are marked inactive in the admin panel, they no longer show in the actual case file, but they still appear in the database.

1) In case 2016-MED-01-0063 Inactive Fact-Finder William C. Heekin shows in the database, but does not display when viewed using SMDS 3.0.

2) We also believe that the same issue occurred in this case for Inactive Mediator Brian Eastman. When Mary went into update mode on the status Tab, we believe it auto removed Brian’s name from the case (since inactives do not show in the dropdown) and created a history entry stating she removed the name, even though she did not actually remove the name from the case when she pressed the save button.

3) I am guessing that this same issue may be occuring throughout the entire program as items are marked “inactive”, but I am not sure and would like you to double check these possibilities as well.

![image](https://user-images.githubusercontent.com/24595073/28216937-641acd2c-6881-11e7-8a70-03f832291d6d.png)

![image](https://user-images.githubusercontent.com/24595073/28216940-67366098-6881-11e7-97f8-569cb95267ee.png)

**Comment by parkjohnston** [comment]
The #1 above is NOT possible to happen has selected by parties load the items that are shown in the list, so this ticket is super fishy

**Comment by parkjohnston** [comment]
Time Spent 90 minutes
