### ISSUE TITLE
(R3-019) - (Hearings) - Letters are not being sent

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#587]
When attempting to send email out of the SERB Hearings section letter queue. They do not send from the queue when the send letter button is pressed. It did not send if both were check marked as shown below. They also do not send if selected individually. They just stay in the queue.

![image](https://user-images.githubusercontent.com/24595073/28275194-281fdf30-6ae1-11e7-85bb-39f98ad6312b.png)

**Comment by parkjohnston** [comment]
Issue was that the program was not properly handing Hearing case types....simple fix but hard to pin point on the information provided.

Time Spent 45 minutes
