### ISSUE TITLE
(R3-020) - (ULP) - Want the ability to highlight text to copy and paste

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#588]
Note: I would like to discuss before implementing…

The ULP section would like the ability to highlight the fields shown below so that they can copy and paste this information quickly into their label making program.

I believe there is another similar ticket regarding allowing this functionality. I would like to discuss what options we have with this and how technical this would be to implement. I am also interested in knowing what it would take to allow this capability for other fields and sections. I believe users would appreciate the ability to copy and paste data from SMDS while in read only mode. Typically this information would be pasted into an email or other document.

![image](https://user-images.githubusercontent.com/24595073/28321596-a457e5be-6ba1-11e7-8ced-6ee1d7dcc7f2.png)

**Comment by parkjohnston** [comment]
Time 30 minutes
