### ISSUE TITLE
(R3-021) - (MED) - Data not updating when switching between three particular cases

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#589]
Mary is updating the case information within the RED box for the following cases…
2017-MED-07-0818, 2017-MED-07-0819, 2017-MED-07-0820

When she is switching from case 0818 to 0819 the page refreshes with updated info… When she switches from 0819 to 0820 the info does not refresh. When I switch from 0820 back to 0818 The info does not refresh. If I close out and reopen SMDS it works when I go to case 0818. If I close out and go to case 0820 this info is blank.

I am hoping you can run this through your debugger to locate what the glitch is.

![image](https://user-images.githubusercontent.com/24595073/28321675-d7a3a7fa-6ba1-11e7-91b0-f63926e96829.png)

![image](https://user-images.githubusercontent.com/24595073/28321682-daf585a4-6ba1-11e7-9a44-0f790308ad77.png)

![image](https://user-images.githubusercontent.com/24595073/28321686-dda7a8e0-6ba1-11e7-85f5-302ef4fab696.png)

**Comment by anthonyperk** [comment]
When switching from 2017-MED-07-0819 to 2017-MED-07-0820, got this error output

> Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 1
>         at parker.serb.sql.BargainingUnit.getCertStatus(BargainingUnit.java:56)
>         at parker.serb.MED.MEDCaseStatusPanel.loadInformation(MEDCaseStatusPanel.java:280)
>         at parker.serb.MED.MEDRootPanel.loadInformation(MEDRootPanel.java:78)
>         at parker.serb.MED.MEDHeaderPanel.loadInformation(MEDHeaderPanel.java:74)
>         at parker.serb.MED.MEDHeaderPanel.lambda$addListeners$0(MEDHeaderPanel.java:61)
>         at javax.swing.JComboBox.fireActionEvent(Unknown Source)
>         at javax.swing.JComboBox.setSelectedItem(Unknown Source)
>         at parker.serb.MED.MEDCaseSearch$7.mouseClicked(MEDCaseSearch.java:157)
>         at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
>         at java.awt.Component.processMouseEvent(Unknown Source)
>         at javax.swing.JComponent.processMouseEvent(Unknown Source)
>         at java.awt.Component.processEvent(Unknown Source)
>         at java.awt.Container.processEvent(Unknown Source)
>         at java.awt.Component.dispatchEventImpl(Unknown Source)
>         at java.awt.Container.dispatchEventImpl(Unknown Source)
>         at java.awt.Component.dispatchEvent(Unknown Source)
>         at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
>         at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
>         at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
>         at java.awt.Container.dispatchEventImpl(Unknown Source)
>         at java.awt.Window.dispatchEventImpl(Unknown Source)
>         at java.awt.Component.dispatchEvent(Unknown Source)
>         at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
>         at java.awt.EventQueue.access$500(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.awt.EventQueue$4.run(Unknown Source)
>         at java.awt.EventQueue$4.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.awt.EventQueue.dispatchEvent(Unknown Source)
>         at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
>         at java.awt.WaitDispatchSupport$2.run(Unknown Source)
>         at java.awt.WaitDispatchSupport$4.run(Unknown Source)
>         at java.awt.WaitDispatchSupport$4.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.awt.WaitDispatchSupport.enter(Unknown Source)
>         at java.awt.Dialog.show(Unknown Source)
>         at java.awt.Component.show(Unknown Source)
>         at java.awt.Component.setVisible(Unknown Source)
>         at java.awt.Window.setVisible(Unknown Source)
>         at java.awt.Dialog.setVisible(Unknown Source)
>         at parker.serb.MED.MEDHeaderPanel.jLabel11MouseClicked(MEDHeaderPanel.java:402)
>         at parker.serb.MED.MEDHeaderPanel.access$000(MEDHeaderPanel.java:34)
>         at parker.serb.MED.MEDHeaderPanel$1.mouseClicked(MEDHeaderPanel.java:254)
>         at java.awt.Component.processMouseEvent(Unknown Source)
>         at javax.swing.JComponent.processMouseEvent(Unknown Source)
>         at java.awt.Component.processEvent(Unknown Source)
>         at java.awt.Container.processEvent(Unknown Source)
>         at java.awt.Component.dispatchEventImpl(Unknown Source)
>         at java.awt.Container.dispatchEventImpl(Unknown Source)
>         at java.awt.Component.dispatchEvent(Unknown Source)
>         at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
>         at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
>         at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
>         at java.awt.Container.dispatchEventImpl(Unknown Source)
>         at java.awt.Window.dispatchEventImpl(Unknown Source)
>         at java.awt.Component.dispatchEvent(Unknown Source)
>         at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
>         at java.awt.EventQueue.access$500(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.awt.EventQueue$4.run(Unknown Source)
>         at java.awt.EventQueue$4.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.awt.EventQueue.dispatchEvent(Unknown Source)
>         at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by anthonyperk** [comment]
1874 did not have a BUN associated with it.  With the BUN cleared out by Justin in this case, the issue was resolved.  I noticed that if I search for a BUN, and there isnt one, and the user 'x's'/cancels out of the BU Number table, the system places the employeeID number into the BUN Number field, which results in this exact issue.

**Comment by anthonyperk** [comment]
FROM JUSTIN

> Anthony, 
> 
> After talking with Staff at SERB… we would like to make sure that the MED section BUN number cannot be populated if it does not match something from the REP Section BUN table. Can you add that to your notes on this ticket. This is due to the issue of BUN numbers not existing in the REP section for grandfathered employers who have not had a REP case.

**Comment by anthonyperk** [comment]
Spent an hour on this so far

**Comment by parkjohnston** [comment]
this is a programing change to accommodate the move ask which will also result in the needed fix for the shit information they give / use

**Comment by parkjohnston** [comment]
The above mentioned request SHOULD be another ticket as they are vastly different issue. 

Please request another ticket be submitted to accommodate this request. 

Several tickets are again leaking over into several issues in a single ticket and are NOT helpful in getting things done

**Comment by parkjohnston** [comment]
@anthonyperk please have justin submit an enhancement ticket for the below...this is NOT what the initial issue was stated not the ticket and I want us to track real bug vs change request so we can prioritize work properly.

After talking with Staff at SERB… we would like to make sure that the MED section BUN number cannot be populated if it does not match something from the REP Section BUN table. Can you add that to your notes on this ticket. This is due to the issue of BUN numbers not existing in the REP section for grandfathered employers who have not had a REP case.

**Comment by parkjohnston** [comment]
The initial request is completed and will be awaiting for Justin to submit the new ticket before closing this one and working on that one.

**Comment by parkjohnston** [comment]
Closing this with an email to Justin about submitting a new ticket for the add on request in this ticket

**Comment by parkjohnston** [comment]
1.25 hours
