### ISSUE TITLE
(R3-022) - (Email Server) - Null Pointer exception 

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#590]
Null Pointer Exception error in email import program.
I closed and reran and it completed without issue.

7/20/2017 10:04am

I forwarded the email example to the following address for your inspection. It looks like it did docket correctly when it was processed after the application restart.

SERB.TestDocket@id.ohio.gov

![image](https://user-images.githubusercontent.com/24595073/28422967-9fdad22a-6d37-11e7-9395-743279ee09ad.png)

**Comment by altrdgenetics** [comment]
having seen this issue in the past, most likely a network hiccup. This has happened in the past and we have been requested to reboot the server. Upon rebooting the Email Server we have never heard anything again from the file not downloading.

The only thing I can think of that should be done is break apart the multi-catch to help narrow it down in the future.

**Comment by altrdgenetics** [comment]
this is a duplicate with less information closing it down
