### ISSUE TITLE
(R3-024) - (Email Server) - Attachment downloading slowness

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#592]
Attempting to further test the email importing issue of large PDF file sizes, I discovered that I can monitor the import progress of a file by looking in the EMAIL storage folder and monitoring the growth of the file size.
Note: I am also working with OIT and we were able to confirm that there is not a McAfee issue on the PC that the email import is being run from. We are now investigating the McAfee on the Fileserver to see if there are any issues there.

**Time Study (18MB PDF File):**
9.5MB in 14 minutes
10 MB in 15 minutes
11MB in 20 minutes (It seemed to get stuck at 11.2MB).
After 20 minutes I got the error below.

![image](https://user-images.githubusercontent.com/24595073/28575866-337050aa-7120-11e7-9087-0f098e72f3bd.png)

I retested the 18MB PDF file to see if It got stuck at the same spot.
This time it errored out at 14.7MB. When I restarted the email application it skipped trying to reimport this email.
![image](https://user-images.githubusercontent.com/24595073/28575872-3b5d4f52-7120-11e7-8ac2-ec1186800b3e.png)

Time Study Test 3 (14MB PDF file):
5.67MB in 5 Minutes 11.0MB in 10 Minutes
Completed successfully after about 13 minutes.
Time Study Test 4 (22MB PDF file):
9.14 MB in 20 Minutes 9.21 MB in 21 Minutes 9.28 MB in 22 Minutes 9.42 MB in 22 Minutes
…. Cancelled process
Testing of other smaller files also show between 1-1.5 Mb per minute download speeds.

![image](https://user-images.githubusercontent.com/24595073/28575887-458e2276-7120-11e7-8e53-8bb8c3a1318c.png)

**Comment by parkjohnston** [comment]
How is this an enhancement? it is NOT our software.

**Comment by altrdgenetics** [comment]
THIS IS A Duplicate, see R3-022 for any additional information:

FROM R3-022:

> 
> having seen this issue in the past, most likely a network hiccup. This has happened in the past and we have been requested to reboot the server. Upon rebooting the Email Server we have never heard anything again from the file not downloading.
> 
> The only thing I can think of that should be done is break apart the multi-catch to help narrow it down in the future.
> 
> METHOD: com.email.ReciveEmail.saveAttachment()
> LINE: 402

**Comment by altrdgenetics** [comment]
ive split the catches, not much else we can do at the moment without additional testing since this is not 100% replicatable and there is other factors at play here.
