### ISSUE TITLE
(R3-026) - (REP) - NULL pointer in Long/Short Agenda

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#594]
In the REP section I receive the following NULL pointer error when attempting to generate the Long and Short Agenda. Board Meeting Date is 8/3/2017

Cases Involved
2017:
0067
0072
0040
0057
0078
0031

2016:
0100

![image](https://user-images.githubusercontent.com/24595073/28786401-1f213a62-75e7-11e7-82b8-cc78f5163afe.png)

**Comment by anthonyperk** [comment]
FROM JUSTIN:

> XLN Team, 
> 
> Debra and I were able to find the missing “0” I updated the attached ticket. I would still like to explorer other solutions for this.

**Comment by parkjohnston** [comment]
Put a catch in that if it is null it will default to 0

**Comment by parkjohnston** [comment]
Time spit 30 minutes
