### ISSUE TITLE
(R3-030) - (Annual Report) - Multiple counts are incorrect

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#598]
SERB Annual Report Tweaks.
Below is the printout from SMDS 3.0. I have added red text were the staff has informed me of what the stat should be. Please tell me how you would like to proceed with correcting the queries.
1) If you can provide me with the current query, or at least the fields involved, that would help me identify the issue with the current queries.
2) It may also be helpful if the results of the query are provided to help determine which cases should or should not be included.
3) Please let me know how you would like to handle this.

**Comment by anthonyperk** [comment]
Annual Report Queries for R3-030
----------------------------------------------------------

NINE (Agency Activites: State Mediator Appointed)
----------------------------------------------------------------------------------------
SELECT MEDCase.caseYear + '-' + MEDCase.caseType + '-' + MEDCase.caseMonth + '-' + MEDCase.caseNumber AS COLUMN1 FROM MEDCase 
WHERE (MEDCase.mediatorAppointedDate BETWEEN '07/01/2016' AND '06/30/2017') AND (MEDCase.stateMediatorAppointedID IS NOT NULL) AND (MEDCase.mediatorAppointedDate IS NOT NULL)


TEN (Agency Activites: Federal Mediator Appointed)
----------------------------------------------------------------------------------------
SELECT MEDCase.caseYear + '-' + MEDCase.caseType + '-' + MEDCase.caseMonth + '-' + MEDCase.caseNumber AS COLUMN1 FROM MEDCase 
WHERE (MEDCase.fileDate BETWEEN '07/01/2016' AND '06/30/2017') AND (MEDCase.FMCSMediatorAppointedID IS NOT NULL) AND (MEDCase.mediatorAppointedDate IS NOT NULL)


ONEONE (Agency Activites: Fact Finder Appointed)
----------------------------------------------------------------------------------------
SELECT MEDCase.caseYear + '-' + MEDCase.caseType + '-' + MEDCase.caseMonth + '-' + MEDCase.caseNumber AS COLUMN1 FROM MEDCase 
WHERE (MEDCase.FFOriginalFactFinderDate BETWEEN '07/01/2016' AND '06/30/2017') OR (MEDCase.FFAppointmentDate BETWEEN '07/01/2016' AND '06/30/2017')


ONETWO (Agency Activites: Conciliator Appointed)
----------------------------------------------------------------------------------------
SELECT MEDCase.caseYear + '-' + MEDCase.caseType + '-' + MEDCase.caseMonth + '-' + MEDCase.caseNumber AS COLUMN1 FROM MEDCase 
WHERE (MEDCase.concilOriginalConcilDate BETWEEN '07/01/2016' AND '06/30/2017') OR (MEDCase.concilAppointmentDate BETWEEN '07/01/2016' AND '06/30/2017')


ONEFOUR (Agency Activites: Elections Held)
----------------------------------------------------------------------------------------
SELECT REPCase.caseYear + '-' + REPCase.caseType + '-' + REPCase.caseMonth + '-' + REPCase.caseNumber  AS COLUMN1 FROM REPCase 
WHERE (REPCase.pollingEndDate BETWEEN '07/01/2016' AND '06/30/2017')


ONEFIVE (Agency Activites: Complaints Issued)
----------------------------------------------------------------------------------------
SELECT HearingCase.caseYear + '-' + HearingCase.caseType + '-' + HearingCase.caseMonth + '-' + HearingCase.caseNumber  AS COLUMN1 FROM HearingCase 
WHERE (HearingCase.complaintIssuedDate BETWEEN '07/01/2016' AND '06/30/2017')


ONENINE (Mediations Conducted: Complaints Issued)
----------------------------------------------------------------------------------------
SELECT HearingsMediation.caseYear + '-' + HearingsMediation.caseType + '-' + HearingsMediation.caseMonth + '-' + HearingsMediation.caseNumber AS COLUMN1 FROM HearingsMediation 
WHERE (HearingsMediation.MediationDate BETWEEN '07/01/2016' AND '06/30/2017') AND (HearingsMediation.PCPreD = 'Pre-D' OR HearingsMediation.PCPreD = 'PreD') AND (HearingsMediation.caseType = 'ULP')

***NOTE*** This query was looking for the wrong string in HearingsMediation.PCPreD (PreD [OLD] vs Pre-D [NEW]).  However, when runing this query, I get 11.  There were 6 cases that had a Mediation date of 06/28/2017


TWOTHREE (Mediations Conducted: Total Non-Contract Mediations)
----------------------------------------------------------------------------------------
This is a total count of 19 - 22


TWOSIX (Final Dispositions: Election Results Certified)
----------------------------------------------------------------------------------------
SELECT REPCase.caseYear + '-' + REPCase.caseType + '-' + REPCase.caseMonth + '-' + REPCase.caseNumber AS COLUMN1 FROM REPCase 
WHERE (REPCase.boardActionDate BETWEEN '07/01/2016' AND '06/30/2017') AND (REPCase.boardActionType LIKE '%cert results%')


TWOEIGHT (Final Dispositions: Recognission Requests/election petitions dismissed)
----------------------------------------------------------------------------------------
SELECT DISTINCT (BoardMeeting.caseYear + '-' + BoardMeeting.caseType + '-' + BoardMeeting.caseMonth + '-' + BoardMeeting.caseNumber) AS COLUMN1 
FROM BoardMeeting LEFT JOIN REPCase ON (BoardMeeting.caseYear = REPCase.caseYear AND BoardMeeting.caseType = REPCase.caseType AND BoardMeeting.caseMonth = REPCase.caseMonth AND BoardMeeting.caseNumber = REPCase.caseNumber) 
WHERE (BoardMeeting.boardMeetingDate BETWEEN '07/01/2016' AND '06/30/2017') AND (REPCase.boardActionType LIKE '%cert vr%' OR REPCase.boardActionType LIKE '%cert opt-in vr%')

***NOTE*** While testing this, I found that the number has been reduvced to 9, meaning someone has changed some of the info in the cases that should be counted


THREEFOUR  (Final Dispositions: ULP complaints settled)
----------------------------------------------------------------------------------------
SELECT HearingCase.caseYear + '-' + HearingCase.caseType + '-' + HearingCase.caseMonth + '-' + HearingCase.caseNumber AS COLUMN1 FROM HearingCase 
WHERE (HearingCase.boardActionDate BETWEEN '07/01/2016' AND '06/30/2017') AND (HearingCase.caseType = 'ULP') AND (HearingCase.finalResult = 'Settled') AND (HearingCase.complaintIssuedDate IS NOT NULL)


THREEEIGHT (Fillings and Appointments: Noticed of Intent to Strike)
----------------------------------------------------------------------------------------
This can be changed to use the same query as the first page (THREE)


THREENINE (Fillings and Appointments: Mediator Appointments)
----------------------------------------------------------------------------------------
SELECT MEDCase.caseYear + '-' + MEDCase.caseType + '-' + MEDCase.caseMonth + '-' + MEDCase.caseNumber AS COLUMN1 FROM MEDCase WHERE (MEDCase.mediatorAppointedDate BETWEEN '07/01/2016' AND '06/30/2017') AND (MEDCase.stateMediatorAppointedID IS NOT NULL OR MEDCase.FMCSMediatorAppointedID IS NOT NULL)

***NOTE*** This looks like it should be the total of NINE and TEN

FOURZERO (Fillings and Appointments: Fact Finder Appointments)
----------------------------------------------------------------------------------------
This looks like it should be ONEONE


FOURONE (Fillings and Appointments: Fact Finder Appointments)
----------------------------------------------------------------------------------------
This looks like it should be ONETWO


FOURFOUR (FY Year Notices to Negotiate: Successor - Statutory)
----------------------------------------------------------------------------------------
SELECT MEDCase.caseYear + '-' + MEDCase.caseType + '-' + MEDCase.caseMonth + '-' + MEDCase.caseNumber AS COLUMN1 FROM MEDCase 
WHERE (MEDCase.fileDate BETWEEN '07/01/2016' AND '06/30/2017') AND (MEDCase.negotiationType LIKE 'SE%')


FOURFIVE (FY Year Notices to Negotiate: Total - Statutory)
----------------------------------------------------------------------------------------
This is a total of FOURTWO-FOURFOUR, so once FOURFOUR is fixed, then FOURFIVE will be correct


FOUREIGHT (FY Year Notices to Negotiate: Successor - MADs)
----------------------------------------------------------------------------------------
SELECT MEDCase.caseYear + '-' + MEDCase.caseType + '-' + MEDCase.caseMonth + '-' + MEDCase.caseNumber AS COLUMN1 FROM MEDCase 
WHERE (MEDCase.fileDate BETWEEN '07/01/2016' AND '06/30/2017') AND (MEDCase.negotiationType LIKE 'ZE%')


FOURNINE (FY Year Notices to Negotiate: Total - MADs)
----------------------------------------------------------------------------------------
This is a total of FOURSIX-FOUREIGHT, so once FOURFOUR is fixed, then FOUREIGHT will be correct


***********SEVENTHREE and SEVENFOUR have been swapped in the past, we can swap them again if need be


EIGHTZERO (Public Sector Strikes: Education)
----------------------------------------------------------------------------------------
SELECT MEDCase.caseYear + '-' + MEDCase.caseType + '-' + MEDCase.caseMonth + '-' + MEDCase.caseNumber AS COLUMN1 FROM MEDCase 
WHERE (MEDCase.strikeBegan BETWEEN '07/01/2016' AND '06/30/2017') AND (MEDCase.strikeOccured = 'Yes') AND (MEDCase.FFEmployerType = 'School Dist%')

***NOTE*** This is due to 2016-STK-10-0004 NOT having a "Fact Finder Employer Type" at all (should be School District)


EIGHTFOUR (Public Sector Strikes: Other)
----------------------------------------------------------------------------------------
SELECT MEDCase.caseYear + '-' + MEDCase.caseType + '-' + MEDCase.caseMonth + '-' + MEDCase.caseNumber AS COLUMN1 FROM MEDCase 
WHERE (MEDCase.strikeBegan BETWEEN '07/01/2016' AND '06/30/2017') AND (MEDCase.strikeOccured = 'Yes') AND (MEDCase.FFEmployerType = 'Other')

***NOTE*** This is due to 2016-STK-12-0005 NOT having a "Fact Finder Employer Type" at all (should be Other)



EIGHTFIVE (Public Sector Strikes: Total) is a total of EIGHTZERO - EIGHTFOUR



EIGHTSIX (Representation Summary of Activity: Elections Held)
----------------------------------------------------------------------------------------
SELECT REPCase.caseYear + '-' + REPCase.caseType + '-' + REPCase.caseMonth + '-' + REPCase.caseNumber AS COLUMN1 FROM REPCase 
WHERE (REPCase.pollingEndDate BETWEEN '07/01/2016' AND '06/30/2017')


EIGHTEIGHT (Representation Summary of Activity: Choices for Representation)
----------------------------------------------------------------------------------------
SELECT REPCase.caseYear + '-' + REPCase.caseType + '-' + REPCase.caseMonth + '-' + REPCase.caseNumber AS COLUMN1 FROM REPCase 
WHERE (REPCase.pollingEndDate BETWEEN  '07/01/2016' AND '06/30/2017') AND (REPCase.pollingStartDate IS NOT NULL) AND (REPCase.pollingEndDate IS NOT NULL) AND (REPCase.resultWhoPrevailed != 0 AND REPCase.resultWhoPrevailed IS NOT NULL)


EIGHTNINE (Representation Summary of Activity: Approximate number of eligable voters)
----------------------------------------------------------------------------------------
SELECT (SUM(REPCase.combinedApproxNumberEligible) + SUM(REPCase.professionalApproxNumberEligible) + SUM(REPCase.nonprofessionalApproxNumberEligible) + SUM(REPCase.resultApproxNumberEligibleVoters)) AS COLUMN1 FROM REPCase 
WHERE (REPCase.pollingEndDate BETWEEN '07/01/2016' AND '06/30/2017')

***NOTE*** This query results in a NULL (which is defaulted to 0 for this process).  We can add NULL checks for the 4 catagories so the statement looks like the following:

SELECT (SUM(CASE WHEN REPCase.combinedApproxNumberEligible IS NULL THEN 0 ELSE REPCase.combinedApproxNumberEligible END) + SUM(CASE WHEN REPCase.professionalApproxNumberEligible IS NULL THEN 0 ELSE REPCase.professionalApproxNumberEligible END) + SUM(CASE WHEN REPCase.nonprofessionalApproxNumberEligible IS NULL THEN 0 ELSE REPCase.nonprofessionalApproxNumberEligible END) + SUM(CASE WHEN REPCase.resultApproxNumberEligibleVoters IS NULL THEN 0 ELSE REPCase.resultApproxNumberEligibleVoters END)) AS COLUMN1 FROM REPCase 
WHERE (REPCase.pollingEndDate BETWEEN '07/01/2016' AND '06/30/2017')

However this results in a sum of 1196, so we are still missing some counts somewhere.  here is a query that lists all 4 catagories plus the case number:

SELECT (REPCase.caseYear + '-' + REPCase.caseType + '-' + REPCase.caseMonth + '-' + REPCase.caseNumber), REPCase.combinedApproxNumberEligible, REPCase.professionalApproxNumberEligible, REPCase.nonprofessionalApproxNumberEligible, REPCase.resultApproxNumberEligibleVoters FROM REPCase 
WHERE (REPCase.pollingEndDate BETWEEN '07/01/2016' AND '06/30/2017')


NINEZERO (Representation Summary of Activity: Voter Turnout)
----------------------------------------------------------------------------------------
SELECT (SUM(REPCase.combinedTotalVotes) + SUM(REPCase.professionalTotalVotes) + SUM(REPCase.nonprofessionalTotalVotes) + SUM(REPCase.resultTotalBallotsCast)) AS COLUMN1 FROM REPCase WHERE (REPCase.pollingEndDate BETWEEN '07/01/2016' AND '06/30/2017')

***NOTE*** This is similar to EIGHTNINE where we need to add in NULL checks.  However the number with NULL checks is 957.

SELECT (SUM(CASE WHEN REPCase.combinedTotalVotes IS NULL THEN 0 ELSE REPCase.combinedTotalVotes END) + SUM(CASE WHEN REPCase.professionalTotalVotes IS NULL THEN 0 ELSE REPCase.professionalTotalVotes END ) + SUM(CASE WHEN REPCase.nonprofessionalTotalVotes IS NULL THEN 0 ELSE REPCase.nonprofessionalTotalVotes END) + SUM(CASE WHEN REPCase.resultTotalBallotsCast IS NULL THEN 0 ELSE REPCase.resultTotalBallotsCast END)) AS COLUMN1 FROM REPCase WHERE (REPCase.pollingEndDate BETWEEN '07/01/2016' AND '06/30/2017')


NINETWO (Unfair Labor Practice Summary of Activity: ULP Charges Filed)
----------------------------------------------------------------------------------------
SELECT ULPCase.caseYear + '-' + ULPCase.caseType + '-' + ULPCase.caseMonth + '-' + ULPCase.caseNumber AS COLUMN1 FROM ULPCase 
WHERE (ULPCase.fileDate BETWEEN '07/01/2016' AND '06/30/2017') AND (ULPCase.caseType = 'ULP')


NINESEVEN (Unfair Labor Practice Summary of Activity: Complaints Settled)
----------------------------------------------------------------------------------------
SELECT HearingCase.caseYear + '-' + HearingCase.caseType + '-' + HearingCase.caseMonth + '-' + HearingCase.caseNumber AS COLUMN1 FROM HearingCase WHERE (HearingCase.boardActionDate BETWEEN '07/01/2016' AND '06/30/2017') AND (HearingCase.finalResult = 'Settled') AND (HearingCase.complaintIssuedDate IS NOT NULL)


ONEZEROFIVE (Hearings Section Summary of Activity: Hearings Held)
----------------------------------------------------------------------------------------
SELECT HearingCase.caseYear + '-' + HearingCase.caseType + '-' + HearingCase.caseMonth + '-' + HearingCase.caseNumber AS COLUMN1 FROM HearingCase WHERE (HearingCase.HearingDate BETWEEN 	'07/01/2016' AND '06/30/2017')


ONEZEROSIX (Hearings Section Summary of Activity: Settlements)
----------------------------------------------------------------------------------------
SELECT HearingCase.caseYear + '-' + HearingCase.caseType + '-' + HearingCase.caseMonth + '-' + HearingCase.caseNumber AS COLUMN1 FROM HearingCase WHERE (HearingCase.boardActionDate BETWEEN '07/01/2016' AND '06/30/2017') AND (HearingCase.finalResult = 'Settled') AND (HearingCase.complaintIssuedDate IS NOT NULL)

**Comment by altrdgenetics** [comment]
updated teh queries that I was given from anthony 30min

**Comment by altrdgenetics** [comment]
two additional queries have been updated, only 4 outstanding at the moment.

**- OneFour
- TwoSix
- TwoEight
- EightEight**

**Comment by altrdgenetics** [comment]
ONEFOUR - Is good now

TWO SIX AND TWO EIGHT - maybe good, code is there if SERB concurs

EIGHTEIGHT - No Idea.

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

> ONEFOUR – 
> You got it
> Justin – Thanks!
> ---
> TWOSIX – 
> 2016-REP-02-0013   AND   2016-REP-03-0024  are still not on my count due to the Ballots Count Date (Tally Date) being outside of the Annual Report timeframe of 07/01/2016 – 06-30-2017
> Justin – I understand… Correct as is. 
> ---
> TWOEIGHT – 
> When I adjust the query to also look for “DISM” as well, I get the 20 cases below
> 
> 2016-REP-01-0006 (Not on your list.  DISM and Board Meeting Date of 12/15/2016)
> 2016-REP-05-0055
> 2016-REP-05-0056
> 2016-REP-06-0063
> 2016-REP-07-0070
> 2016-REP-08-0075
> 2016-REP-08-0077
> 2016-REP-09-0084
> 2016-REP-09-0095
> 2016-REP-10-0101 (Not on your list.  DISM and Board Meeting Date of 12/15/2016)
> 2016-REP-11-0109 (Not on your list.  DISM RD and Board Meeting Date of 03/21/2017)
> 2016-REP-11-0115
> 2016-REP-12-0118
> 2017-REP-01-0006
> 2017-REP-01-0010
> 2017-REP-02-0022 (Not on your list.  DISM and Board Meeting Date of 03/21/2017) 
> 2017-REP-03-0045
> 2017-REP-04-0050
> 2017-REP-05-0064
> 2017-REP-06-0068
> 
> 
> Just want to make sure I am getting the correct count
> 
> Justin – Your counts are correct.

**Comment by anthonyperk** [comment]
Total Hours: 10.5
