### ISSUE TITLE
(R3-032) - (MED) - MED report additions

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#600]
MED Section

When the following 5 reports are generated from the MED section, please add a dropdown box so that Mary can select either “All” or “only one name from the dropdown box” before generating the report. This is for filtering the records. These reports are rather long depending on the date range and in many cases she only needs to generate the report for one name. Previously I gave her access to MS Access which gave her this capability. She no longer has this access in SMDS 3.0.

1) Conciliator Appointments – By Conciliator
2) Fact Finder Appointments – By Fact Finder
3) Conciliation Panels Sent
4) Fact Finder Panels Sent
5) Monthly Stats – Mediator Appointments

![image](https://user-images.githubusercontent.com/24595073/29043203-2435501e-7b88-11e7-9a88-f7d33c179574.png)

**Comment by altrdgenetics** [comment]
The bullet list does not match what is in the database, there is over 500 entries in the SMDSDocuments table. We need the exact wording in the dropdown to be able to continue.

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> Justin,
> 
> Looks like the report names provided in the ticket don’t match any reports in the dropdown exactly (its those pesky Unicode dashes again).  Is the list below correct?
> 
> 1.	Conciliator Appointments – By Conciliator  ->      Conciliation Appointments - By Conciliator  
> 2.	Fact Finder Appointments – By Fact Finder ->     Fact Finder Appointments - By Fact Finder
> 3.	Conciliation Panels Sent ->                                           Conciliator Panels Sent
> 4.	Fact Finder Panels Sent ->                                            Fact Finder Panels Sent
> 5.	Monthly Stats – Mediator Appointments ->        Monthly Stats - Mediator Appointments
> 
> 
> Also we want to make sure that we are displaying the correct fact finders/conciliators/mediators so we need to know what exactly each of the below reports needs to have in the dropdown list (ex: which mediators should be in the dropdown for #5)


EMAIL FROM JUSTIN

> 
> Anthony, 
> 
> Your list of five reports are correct. MS Word auto converts to the Unicode dash. 
> Items 1-4 should list all active Fact Finders & Conciliators by name. The “All” dropdown option would include active/inactive for the date range specified. 
> Item 5 should list all active Mediators (State and Fed) by name. The “All” drop down option would include active/inactive for the date range specified. 
> 
> In summary the all option would run the report as it is currently programmed. If an individual name is selected the report would only generate for that one name. 
> 
> Note: I know that you are considering changing the programming of how the Mediator names are saved in the database. Currently it uses their Number. I believe this may be changed to a name per another open ticket. I just wanted to remind you of this before the programming is completed.

**Comment by altrdgenetics** [comment]
Got the code ready for Anthony, next up is the reports to test against.

SPENT: 1HR

**Comment by anthonyperk** [comment]
2 hours

**Comment by altrdgenetics** [comment]
another 30min testing. this ticket is now complete.
