### ISSUE TITLE
(R3-033) - (MED) - Replace second "Intended Date" with 2 dropdowns

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#601]
1) On the MED Strike tab, please remove the filed marked below. Any values stored in it can be placed in the box above it. Let me know if there are any instances where both boxes are populated.

2) The 5 checkboxes will utilize this one "Intended Date" field
Please add the two drop down fields below. These are identical to the fields displayed on the Fact-Finder Tab. They should be linked to the same database fields so the information is displayed in both tabs. These fields were not being populated because they were not on this tab. This information is used to populate strike information on the annual report.

![image](https://user-images.githubusercontent.com/24595073/29125367-92ae967e-7ce9-11e7-802c-f81cbfcef674.png)

**Comment by parkjohnston** [comment]
update MEDCase set intendedDateStrike = intendedDatePicket where intendedDatePicket is not null

**Comment by parkjohnston** [comment]
Removing and updating data: 30 minutes

**Comment by parkjohnston** [comment]
Added Combos
Updated to pull from fields
Add detailed history entries 

Time: 1 hour

**Comment by parkjohnston** [comment]
Total time: 1.5 hour
