### ISSUE TITLE
(R3-034) - (Hearings) - Case loading issue (possilby because of duplicate case number)

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#602]
In the SMDS 3.0 Hearings Section, Ray accidentally created a second copy of the case.
Case 2017-ULP-01-0021. Can you remove the newest entry? Also, please tweak the code on the “New Hearing” button to not permit the ability to create duplicate cases?

Finally, in the example below… when you click on one of the entries the case will load, but the activity entries will not load unless the user clicks on and then cancels the add entry button… I believe this is related to it being a duplicate case… but I wanted to mention it as well in case it is not related.

![image](https://user-images.githubusercontent.com/24595073/29474583-493eb47c-842a-11e7-973f-27bcdb13d2ad.png)

**Comment by parkjohnston** [comment]
Delete from HearingCase where id = '626'
Delete from HearingCaseSearch where id = '1231'

Time here: 30 minutes

**Comment by parkjohnston** [comment]
Created Text for already made case.

Time Spent: 30 minutes

**Comment by parkjohnston** [comment]
This is also to many things in a single ticket...we need to get back to one issue a ticket...

**Comment by parkjohnston** [comment]
Total time: 1 hour
