### ISSUE TITLE
(R3-035) - (ORG) - 'February' misspelled in report dropdown

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#603]
Thank you for fixing the spelling error of February on the Org Information Tab > Fiscal Year ending: drop down box.

I was informed today that this same spelling error exists on two report drop down items shown below for the Org Section. Org 735 is the only one due in February.

Report 1
![image](https://user-images.githubusercontent.com/24595073/29569063-5e3a435c-8720-11e7-8300-746babfb5e91.png)

![image](https://user-images.githubusercontent.com/24595073/29569071-628cb8b8-8720-11e7-9993-56482c310243.png)

![image](https://user-images.githubusercontent.com/24595073/29569074-65371978-8720-11e7-9de9-6b55d630b61c.png)

![image](https://user-images.githubusercontent.com/24595073/29569078-68302bb0-8720-11e7-9da8-de2c281d78a0.png)

**Comment by altrdgenetics** [comment]
this uses the Global Month List. modified that and changed the one on the main ORG panel to use the same list

**Comment by anthonyperk** [comment]
Update to the ticket, doesnt affect anything:

Check these four reports....
The ORG reports with the drop down month in the generate
report box are:
-All Active Organizations Listing Only Order by Fiscal Year and Month
-All Organizations Noncompliance Report All Months
-Employee Organization Non-Compliance Report – Detail
-Single Month Employee Organizations Noncompliance Report

In the Generate Report box, for the above named reports, when
it prompts with the “required report information” box, the
MONTH drop down will need to be changed so that February is
spelled correctly.
