### ISSUE TITLE
(R3-036) - (MED) - Bulk MED Close Cases doesn't work

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#604]
MED Close cases
(File > Batch Handle Cases > MED Section) Close Cases

When user selects one or more cases and presses the update button, the process completes without updating the cases. 

This is the first time this has been used since going live.

![image](https://user-images.githubusercontent.com/24595073/29575172-b32e3db2-8731-11e7-8e4a-3e82404ad587.png)

**Comment by altrdgenetics** [comment]
so ill get to this in a bit, but im an idiot... i cleared the table before processing it.

**Comment by altrdgenetics** [comment]
Removal of that single line is the only thing that needed to be accomplished.
