### ISSUE TITLE
(R3-039) - (Hearing) - Documents not sending through letter queue

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#605]
SERB Hearing Section > Unable to send out documents using the letter queue.

Ray informed me of the issue.
I am in the test case 2012-REP-01-9999 and I generate the Proposed Order. It appears in the letter queue. I checkmark and press the send button, it was marked to send to my gmail email account. (I am a party in this test case). The message disappears but the email does not get sent. The email application is running.

In Ray’s example for a different case one letter was marked to be sent via email, and the other via postal.
When I attempt to send the postal letter I get the extra prompt to send. I click yes and then it goes back to the letter queue and the letter is still in the list.

![image](https://user-images.githubusercontent.com/24595073/29668990-04a23d68-88b0-11e7-8487-7ec7bc17d33e.png)

**Comment by altrdgenetics** [comment]
This was a mess, so Hearings was not account for in the file paths and there was nothing there to flag it otherwise. this was for both postal and email 4hrs of labor
