### ISSUE TITLE
(R3-037) - (CMDS) - Add button to CMDS Activity to set Inventory Status Line

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#606]
CMDS Activity Entry Detail Screen. Please add a button called “Set Inventory Status Line” which would update the inventory Status Line with the text displayed in the Action field.

In the example below, the status line would read “Created a RH on 9/15/2017 0930 AM in HR3”

![image](https://user-images.githubusercontent.com/24595073/29669653-249d7874-88b2-11e7-82cd-4cdb8e82d79a.png)

**Comment by parkjohnston** [comment]
Well this is an interesting request...allows for people to hide mess ups, but they are asking sooo..

This button will appear when the UPDATE button is clicked, would not be best for people to click it by not 110% meaning to

**Comment by parkjohnston** [comment]
Completed. 

Time Spent: 2 hours

Users must click update to see the button, once the button is visible, clicking it will update the status and reset the box to a non update status.  No confirmation box is asked about updating the status as it is required they show intent by clicking the update button first.
