### ISSUE TITLE
(R3-038) - (CMDS) - add aditional prompt to "Add Hearing" Button functionality

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#607]
CMDS > Add Hearing Button. When saved please add prompt asking if you wish to update the Inventory Status Line. If yes is chosen, the status line would read as shown in image 2 below.

![image](https://user-images.githubusercontent.com/24595073/29669704-510e4d8e-88b2-11e7-864e-e9178ee364ba.png)

![image](https://user-images.githubusercontent.com/24595073/29669709-5333a51e-88b2-11e7-9105-0e8e4256d9de.png)

**Comment by parkjohnston** [comment]
The status lines in the images are the same? 

Confused...think I know what he wants, but these tickets MUST be more clear.

**Comment by parkjohnston** [comment]
Completed... 

Time: 1 hour
