### ISSUE TITLE
(R3-040) - (Hearings) - Can not create new hearings

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#608]
SERB Hearings Section > Staff are unable to create new SERB Hearing Case numbers. They receive the error “Case Already Created”. This case number exists in the ULP Section, but not in the SERB Hearings Section. I believe the verification check needs tweaked. Possible utilizing some of the query results used to generate the SERB Hearings advanced case search.

Please tell me if you would like me to use the previous build 3.3 to create these two cases so that Erin can proceed with her work on them.

We are using the "New Hearing" button in the SERB Hearings Section.

![image](https://user-images.githubusercontent.com/24595073/29716455-8577acd8-8979-11e7-83a5-17a2b16e0fc8.png)

![image](https://user-images.githubusercontent.com/24595073/29716462-88043494-8979-11e7-9a5a-dfe82d062d5b.png)

**Comment by parkjohnston** [comment]
They cant use that old build as DB changes happened. 

He should have tested. Put this one to my name and it will be in 3.4.1 released this weekend

**Comment by parkjohnston** [comment]
Time Spent: 15 minutes
