### ISSUE TITLE
(R3-041) - (Email Server) - Jericho issues with an email

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#609]
Regarding the error below, I believe it was caused by the email shown in the example below. I have forwarded the email to the test docket email account for your review.

Email from Partick J. Schmitz (pat@scottscrivenlaw.com)
Date 8/30/2017 2:32 PM

Notice in the side-by-side graphic on page 2 the <![if !supportLists]>1. <![endif]> tags.

![image](https://user-images.githubusercontent.com/24595073/29890799-d3135c96-8d96-11e7-99ec-ff10a00b5079.png)

![image](https://user-images.githubusercontent.com/24595073/29890803-d6f47d90-8d96-11e7-8007-f012b40a00a3.png)

**Comment by anthonyperk** [comment]
this may just be an FYI ticket

**Comment by altrdgenetics** [comment]
This is fixable, the tags are coming from M$ Office. It is an issue with list generation, using similar looking HTML tags but not... they are Office tags.

**Comment by altrdgenetics** [comment]
Justin wanted a quote on time before proceeding, stated 2hrs and then subsequent ones would be less.

**Comment by altrdgenetics** [comment]
Reference to K-9 mobile email having same issue

https://github.com/k9mail/k-9/issues/2559

**Comment by altrdgenetics** [comment]
got this squared away.
