### ISSUE TITLE
(R3-046) - (ALL) - Report for All Sections 2 Reports Name/Address Search

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#614]
**[OLD TICKET DATA NO LONGER VALID]**

I received a request via a public records request “to locate all of the cases that the following union was
associated with within the last 5 years.”
International Union of Operating Engineer Local 18

Please add the following 2 reports to all sections (MED, REP, ULP, Hearings, CMDS, CIVITAS, ORG)

**Report 1**
Party Name Lookup Report
The search would look at the following fields:
“like” Party Name (First Name + Last Name) or “like” (Company Name)
Include the following fields on the report:
Case Number
Case Status (Open/Close)
Party Name (First Name + Last Name) or (Company Name)
Party Type
Address 1,
Address 2,
Address 3,
City,
State
Zip
Phone
Sorting:
Group the report by section, then sort the records by case number descending (newest on top, oldest on
the bottom)

**Report 2**
Party Address Lookup Report
The search would look at the following fields:
“like” Address 1, Address 2, Address 3
Include the following fields on the report:
Case Number
Case Status (Open/Close)
Party Name (First Name + Last Name) or (Company Name)
Party Type
Address 1,
Address 2,
Address 3,
City,
State
Zip
Phone
Sorting:
Group the report by section, then sort the records by case number descending (newest on top, oldest on
the bottom)

**Comment by altrdgenetics** [comment]
We have looked at this and it is a mess and will require database change and backfill of data, def tearing up concrete. We have informed Justin of this and offered to come up with a report as an alternative solution that would be able to pull from ALL sections. He now realizes that this is crazy and would take a substantial amount of hours as well as the party types not displayed here being used infrequently. 

With all of the discussion he is going to think about it more and get back with us.

**Comment by altrdgenetics** [comment]
Discussed this with Justin again. Told him about the report and this ticket will completely change into a report based request. We will create 2 reports, one to search on name, and the other to search for address. He will submit the specs for the reports he wants shortly.

**Comment by anthonyperk** [comment]
3 Hours

**Comment by altrdgenetics** [comment]
Added in the code for the new types, will still need DB entries 1hr
