### ISSUE TITLE
(R3-048) - (MED) - Add 'Checkmark All' option in Send to Board Panel

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#616]
In the Mediation Section
File > Batch Handle Cases > MED
Select Send to Board. Select date Ranges below.
Press Print Board to Close List
Populate Board Date Prompt of 10/12/2017

Please add the checkmark All button. I just manually clicked all 1,043 entries.
Also, add a spinning circle while it is processing. (took 12-15 seconds to complete)

![image](https://user-images.githubusercontent.com/24595073/30915135-ce796382-a363-11e7-9cd2-211800bfbc02.png)

**Comment by altrdgenetics** [comment]
Added in the check all box, it is similar to the other bulk panel for med.
