### ISSUE TITLE
(R3-049) - (EMAIL) - Incoming email subject with 'long dash' issue

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#617]
Received an email that would not migrate into SMDS. I sent a copy to the testdocket email box.
(From Wendy Colon Rosa). Is it possible to add a catch for this?

I discovered the filename of the attachment was as follows.

SERB - Tuscarawas Co. Sheriff – FOP - NOA - 2017-MED-09-1148.pdf

Below is the error code from the import application.

Attachment "26409_01_=?Windows-1252?Q?SERB_-_Tuscarawas_Co._Sheriff_=96_FOP_-_NOA_-_2017-MED-0?= =?Windows-1252?Q?9-1148.pdf?=" could not be saved: IOException

![image](https://user-images.githubusercontent.com/24595073/30931648-487ed53e-a393-11e7-890f-4f684cca513a.png)

**Comment by altrdgenetics** [comment]
> Justin,
> 
> I checked the email and the attachment that was sent. In the information that you provided the "=?Windows-1252?Q?" tags spotted in the print out can be seen in other locations other than the long dash, I do not see anything out of the ordinary with the attachment or the email itself. Since this occurred before the outlook server migration and that there was several errors with connections surrounding that print out we believe that other factors out of our control are at play here. That text is usually related to an encoding issue with the email itself, usually as an error decoding during receiving of the message.
> 
> We already strip out non windows supported characters for filenames as we pull down the attachments so any "catch" that could be put in already has. Since this does not occur on every single pdf attachment and this happened during the same time you were having additional email server related issues there is nothing that can be done at this time. We will close out this ticket and if the error becomes more permanent and found more often than just isolated incidents please submit a new ticket.
> 
> - Andrew
