### ISSUE TITLE
(R3-050) - (MED) - MED bulk sending of letters wont send after initial run-through

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#618]
XLN Team,

Mary runs into an issue each time she sends her bulk letters… Below is a theory….

1) Mary has over 50 items in the queue. Primarily all are email. There may be a few that are postal.
2) The type box is marked “both” She presses send.
3) The first 50 are sent and disappear from the list.
4) Issue… when she sends the next group of emails they do not send when she presses the send button. If she closes out and goes back in they will send. I had her run it with the black command box and no errors are logged. It seems the system does not reset and refresh the list to allow the sending again. I changed the type and tried to send and that did not make a difference either.

![image](https://user-images.githubusercontent.com/24595073/31134894-6e882062-a831-11e7-9711-413c3c7d9a1b.png)

**Comment by altrdgenetics** [comment]
> Justin,
> 
> After our discussion in the meeting about how this process was handled to receive the error we came back to the office to test the workflow. We were unable to preform a process that would replicate the error that was experienced as described. Our process was as follows.
> 
> # We generated 147 letters to email, generated 4 letters to postal.
> 1. Opening up the letter queue we left the Type Dropdown on the defaulted "Both" option.
> 2. We checked the "Select Top 50" checkbox and watched it fill the first 50 items in the list
> 3. We used the scroll bar to verify 50 were checked and then hit the Send button.
> 4. Once the process occurred with the spinner dialog the window refreshed and the select all checkbox was unmarked, no items were marked in the table.
> 5. We preformed step 2 and 3 (ensuring 50 new items were checked), when we hit the Send button it processed all of the items as it should have and we verified the count change in the database.
> 
> 
> We were able to preform these steps on email only and also email and postal in the same batch, both first and second batch... doing multiple batches to clear out the entire queue. We have so far been unable to reproduce the error that you said you are experiencing. I have confirmed my results by redoing the test structure with Anthony watching to ensure I was not overlooking anything. As far as postal is concerned everything is getting converted to PDF and merged so there is no hang-up from Word being open within the application itself.
> 
> In order to proceed with a fix we will need a detailed step by step that we can replicate. I know that Mary is really the only one that uses a bulk process to handle their workload but you have not made any mention of this issue from any other users or if you were able to replicate it on your machine, could there be an issue with the her specific process or how she is using her machine?
> 
> - Andrew

**Comment by altrdgenetics** [comment]
Justin emailed us and said Mary is working on trying to reproduce it but was unable to do so on first try.

**Comment by altrdgenetics** [comment]
Got This Gem:

> Andrew,
>  
> The next batch of Mary’s letters will not be sent out until November 16th. I do not have any way of easily testing this scenario. I would like to release the latest update when it is available. And group Mary’s ticket with future new tickets.
>  
> Thank you,
>  
> Justin Brown

**Comment by altrdgenetics** [comment]
**TO JUSTIN:**

> Justin,
> 
> Since Mary's next set of letters are not due to be sent out till Nov 16th, that will be almost 2 months since our initial analysis. With no guarantee that the exact issue will be found as additional testing will occur at a monthly cycle we are going to close this ticket out as not reproducible. If you are able to recreate this issue and provide us with reproducible steps that will cause the issue described please submit that as a new ticket number with reference R3-050. 
> 
> Within the next few days we will have a release build available and will notify you at that point so you can test and distribute it at your leisure.
> 
> - Andrew
>
