### ISSUE TITLE
(R3-053) - (CMDS) - CMDS Bulk Closing

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#621]
**SPBR Bulk Closing** (Last section with cases that does not have a bulk closing process).
Please add the following Bulk closing process.
1) Add “CMDS” to the Batch Handle Cases List

![image](https://user-images.githubusercontent.com/8847344/32110890-d53679e8-bb06-11e7-8fbf-097e2cb7eedb.png)

2) Show all open cases with a “final board order mail date” older than 90 days from today’s date. A list of cases for that criteria would appear in Case number order ascending.

3) Query: Where Final Board Order mail date older and Case status = “O”
         a. Note: Cases with the following entry types would display in the list. User would skip them during procesing since unable to exclude. Activity Entry “Case Type C:” Description: “Stayed, Returned – Unclaimed, Returned – Undeliverable, Remanded to ALJ” 

![image](https://user-images.githubusercontent.com/8847344/32110913-e76b0a0c-bb06-11e7-98c0-29d06df21661.png)

4) Need ability to print the list that appears. “Print Case Listing” Button
         a. Order the Report by Case Number in ascending order.

![image](https://user-images.githubusercontent.com/8847344/32110924-f1a39f2a-bb06-11e7-8fda-fafbfa0422dc.png)

Note: User would use this list to verify cases to close and box them up. Noting the box number on this report. Once all cases are boxed… User would return to the application to Close the digital case records.

5) Checkmark the cases that you want to “Close” by box number. Press “Update” Button to process.
        a. Prompt User for a File Stored Box Number [Numeric only]. Save this number to the cases.
        b. Case Status is changed to “C”
        c. Populate “Close Date” field with Today’s Date.
        d. Populate “PBR Box Number” field with the box number
        e. Create 2 history entries in each case.
                i. Date, Action =“Case Closed”, By Who
                ii. File Stored Box [Box Number]
                iii. Repeat for each case that was checkmarked.
        f. Close Cases Process Completes

6) User can then print the “Storage Box List” in step 7 or proceed with closing the next batch of cases using the next box number.

7) Need ability to print the “Storage Box List”. This report will be attached onto the storage box for identification of the cases stored within the box. It can be printed at any time. This report will prompt user for the box number.

![image](https://user-images.githubusercontent.com/8847344/32111087-7ba86c8c-bb07-11e7-9bec-253c42b98597.png)

Note: The destruction date field is 2 years after the Close Date. Sort by Case Number Ascending order.

![image](https://user-images.githubusercontent.com/8847344/32111094-81ae9732-bb07-11e7-95cf-43d3302ff1f7.png)

8) Then user has the option to print the “Closed Case List” Report via button. This report will display all the closed cases for a specific date range. Example below.
        a. Sort Report by Case Number Ascending

![image](https://user-images.githubusercontent.com/8847344/32111104-88e5e848-bb07-11e7-9eea-afed844a8fdb.png)

![image](https://user-images.githubusercontent.com/8847344/32111110-8adc301c-bb07-11e7-8929-594399395bcd.png)

**Comment by altrdgenetics** [comment]
FIX: need to ask for report boxnumber (string) on print box number report

**Comment by altrdgenetics** [comment]
add PBR Box Number to CMDS report Parameter (FIX is done from above)

**Comment by altrdgenetics** [comment]
fixed this too. Anthony is now testing on his machine

**Comment by anthonyperk** [comment]
Tested as Working.  Closing ticket
