### ISSUE TITLE
(R3-058) - (ULP) - ULP Report Changes

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#626]
I have confirmed that ERC and JWD cases are currently being excluded from the following ULP Reports:
    Annual Case A Filings
        Annual Case B Filings
        Annual Case DFARB Filings
        Annual Case Dismissals
        Annual Case Filings Tracking Charging and Charged Party
        Annual Case Probable Cause
        Annual Case RR Filings
        Annual Case Withdrawals

Please modify these reports by removing the exclusion so that the reports list ULP, ERC, and JWD case types.

![image](https://user-images.githubusercontent.com/8847344/32120512-e28854f2-bb26-11e7-8dda-a7ffbd166077.png)

Below is an example of a where statement from one of the reports. All 8 reports are currently using this exclusion for ERC and JWD cases.

        WHERE
        ULPCase.caseType NOT LIKE '%ERC%' AND
        ULPCase.caseType NOT LIKE '%JWD%' AND
        ULPCase.finalDispositionStatus LIKE '%W%' AND
        ULPCase.dismissalDate BETWEEN $P{begin date} AND $P{end date}

**Comment by anthonyperk** [comment]
These reports exclude JWD and ERC because the 2.0 reports also excluded them.

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN:

> Justin,
> 
> Looking at the 2.0 reports, all of the ones you have listed in this ticket exclude ERC and JWD cases (which is why they are excluded in the 3.0 reports).  Just wanted to give you a heads up on that.
> 
> Anthony 


EMAIL FROM JUSTIN:

> Anthony, 
> 
> Agree with your statement. This is a new tweak to the 8 reports and not an error in your programming

**Comment by anthonyperk** [comment]
live on their system

.75 hours
