### ISSUE TITLE
(R3-060) - (EMAIL) - NULL pointer error

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#628]
I received the following error message when attempting to import an email into SMDS MED section. A
copy of the email has been sent to the test email account.
Date: 11/1/2017 12:59 PM
From: Local 1099 union@mail.visn.net
Subject: City of Parma Heights – Intent to Negotiate

![image](https://user-images.githubusercontent.com/24595073/32293824-bd5dca7a-bf1a-11e7-94a2-400ca1ff8d92.png)

I have attached the printed Ebody and the attachment for reference.

I noticed the message was marked as Importance "High" I am not
sure if that has anything to do with the error.

**Comment by altrdgenetics** [comment]
easy issue to fix...

Problem was there is no text in the email message. It is just an attachment.

**Comment by altrdgenetics** [comment]
changed to enhancement... that is how justin flagged it.
