### ISSUE TITLE
(R3-061) - (MED) - Report Sort Order Change

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#629]
MED Section
Please sort the following report by Appointment Date ASC, Full Case Number ASC Currently it is only sorted by Appointment Date.

![image](https://user-images.githubusercontent.com/8847344/32842405-00d2e698-c9eb-11e7-9822-e190fb3e6493.png)

**Comment by anthonyperk** [comment]
Report sort order changed from Appointment Date ASC to Appointment Date ASC, Full Case Number ASC

**Comment by anthonyperk** [comment]
15 minutes
