### ISSUE TITLE
(R3-064) - (REP) - Report Sort Issues

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#631]
**REP Section Reports**

For the following three REP Reports; remove ElectionType3 from the “Where” statement. It is excluding
needed case numbers.

Single Organization Election Report (RD).jasper
Single Organization Election Report (RC-1 and Opt-Ins).jasper
Multiple Organization Election Report (RC-2).jasper

**Comment by altrdgenetics** [comment]
Verified with Justin, there is no R3-063

**Comment by altrdgenetics** [comment]
**TO JUSTIN:**


> Justin,
>  
> While researching why these reports are wrong, I noticed the following:
>  
>  
> Single Organization Election Report (RC-1 and Opt-Ins):  I noticed that the missing case (2016-REP-09-0082) has an election type 3 as ‘Standard’ instead of NULL.  When removing the election type 3 from the query all together, the report count grows to 24 (from the 3 + 1 listed in the example).  It seems like the missing case needs to have the election type 3 nulled out.  This brings up another issue entirely.  In 3.0, the election type 3 dropdown shows ‘Standard’ and ‘Professional/Nonprofessional’, where as 2.0 shows <BLANK> and ‘Professional/Nonprofessional’.  We recall that Standard being introduced as part of the ‘no shorthand’ request, which is where this may have originated from. 
> Multiple Organization Election Report (RC-2): Same ‘Standard’ issue as above.  However, 2016-REP-09-0087 is labeled as an RC-1, not RC-2
> 
> Single Organization Election Report (RD): When I ran the report again, the report shows all 3.  Looking at the dev database (about a week old), the case in question (2016-REP-10-0104) didn’t have an election type 2 selected at all, which is why it wasn’t on the report.  Looks like someone realized this and updated it today.
>  
>  
> So removing the electiontype3 from the list will net the user more on the report, but that MAY not be what they are looking for in the report.  We may have to add a BLANK/NULL option to the electiontype3 to make the reports work correctly.  The ‘Standard’ and “Professional/Nonprofessional’ choices are linked to what the Elections panel shows or hides.

**Comment by altrdgenetics** [comment]
**FROM JUSTIN:**


> Anthony,
>  
> The RC-1 report growth to 24 sounds accurate.
>  
> Please proceed with removing the references to Election Type 3 in the three reports.
>  
> The number of cases on the three reports should add up to the number of cases on the inactive election report.
>  
> I provided Angela with a copy of the Inactive Election Type report. I did identify a few errors that she was going to correct.
>  
> Thank you,
> Justin Brown

**Comment by anthonyperk** [comment]
FROM JUSTIN

> XLN Team, 
> 
> Angela confirmed that she wants to keep the 3 REP reports in their currently revised state.
> 
> Thank you for your help!

**Comment by anthonyperk** [comment]
3 hours
