### ISSUE TITLE
(R3-068) - (CSC) - Can't generate letters

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#634]
In the CSC Section Generating “Single Letter” I select the Annual Report – 60 Day Notice” letter.

I select the following settings.

![image](https://user-images.githubusercontent.com/8847344/35287316-12194ea8-0030-11e8-9177-b481082232ea.png)

Then I get the error below. The document does show as an activity entry that I can open.

![image](https://user-images.githubusercontent.com/8847344/35287322-16d69234-0030-11e8-95ff-5c26054e2278.png)

**Comment by altrdgenetics** [comment]
Postal Never worked. copy paste error from org to csc switch statement.

orgCase.orgName => cscCase.name

**Comment by anthonyperk** [comment]
Letter generated, no error.  Closing ticket
