### ISSUE TITLE
(R3-069) - (CSC) - All Letters Window

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#635]
In the CSC Section Generating “All Letters” I select the Annual Report – 60 Day Notice” letter.

Can the query be adjusted to remove commissions that have a “Date Filed” of the current year? We have had 4 commission file early. I would like them to be excluded from the list base upon date filed.

![image](https://user-images.githubusercontent.com/8847344/35287381-395bf286-0030-11e8-8889-0d2b9a914861.png)

**Comment by altrdgenetics** [comment]
**TO JUSTIN:**

> Justin,
> 
> I have a question about the change to the letter selection criteria. The way the logic flows at the moment may be different than how you intend to use the system as you add more letters to it. We did not have much information to go on when creating this section other than "make it like ORG" so this is the logic that we have.
> 
> 
> IF selected letter contains the text "past due"
>    
>         SQL = "SELECT * FROM CSCCase WHERE Active = 1 AND (filed < DATEADD(yy, DATEDIFF(yy, 0, GETDATE()), 0) OR filed IS NULL)"
> 
> ELSE
> 
>        SQL = "SELECT * FROM CSCCase WHERE Active = 1"
> 
> 
> So if we replace the query that is currently used it potentially could mess up other letters further down the road as you add to them since the letter in question is in the catch all section of the IF/ELSE statement. What is the correct IF/ELSE to fit the workflow of the letters?
> 
> 
> - Andrew

**Comment by altrdgenetics** [comment]
this technically could be added to past due

**Comment by altrdgenetics** [comment]
Justin stated he would be out till next week, just forgot to update this. He should be in 01/29/2018

**Comment by altrdgenetics** [comment]
**Sent another Reminder email:**

> You can reference the email sent on Mon 1/22/2018 in the "R3-069 CSC "All Letters" query tweak" email chain for more information if needed. What we are still looking for what letter groupings should be when displaying the CSCs. In the email I have given you the IF/ELSE statement with the SQL calls. I personally believe that based on the text given in the ticket that we could place this letter with the letters that contain the text "past due" and it will achieve the desired results since the date math is showing filed older than 01/01/[CURRENT YEAR]. However if there is anything more specific needed then I will need to expand the IF/ELSE and create a new SQL to account for the correct criteria, but if so I will need the rules in order to build the new query.

**Comment by altrdgenetics** [comment]
**FROM JUSTIN:**

> Andrew,
>  
> I believe we can use the past due query for both letters. The only difference between the two letters is the date they are sent and that the Past Due letter is “technically” a reminder to file letter.
>  
> At this time there is no plans for future letters to be added so tweaking the IF statement should work.
>  
> IF selected letter contains the text "past due" or “60 Day Notice”

**Comment by anthonyperk** [comment]
No CSC's were listed with a 'Date Filed' with the current year (2018).  Closing ticket
