### ISSUE TITLE
(R3-070) - (Hearings) - Activity Detail Hearings Section

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#636]
In the SMDS Hearings Section. When user Ray Geis attempts to edit an activity entry to correct a labeling error he gets the message below. I tested from my PC with my account and receive the same error.

Also, there is nothing showing in the “Type” Dropdown. It is blank.

Case 2017-ULP-01-0021

![image](https://user-images.githubusercontent.com/8847344/35287450-5c80cd4a-0030-11e8-9047-05060c1cc743.png)

**Comment by altrdgenetics** [comment]
Two issues with this. For the hearing section the dropdown for TYPE is never loaded and the oktorename for filepath was missing for hearing section

**Comment by anthonyperk** [comment]
Was able to access file and change the type dropdown.  Closing ticket.
