### ISSUE TITLE
(R3-071) - (CMDS) - Activity Entries Disappearing

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#637]
When Ray or myself go into an activity entry in case 2016-REM-04-0067… open the detail view. Then click the update button and add a comment… When we press save the activity entry disappears from the screen. I looked in at the backend thinking maybe it was changed “from active to inactive” but the entry does not exist. In the example below, I did not press save to avoid losing another entry.

We are missing “Day 2 of Hearing Completed” this is one that I was testing on when I realized it was deleting the entries. I was adding a comment of “Test” The entry user was flagged as System.

I tested the previous build as well and found this issue was present then too.

![image](https://user-images.githubusercontent.com/8847344/35688088-5cdd44c0-073e-11e8-8420-c8e911fcfd1b.png)

The entry below was deleted when testing in the previous build.

![image](https://user-images.githubusercontent.com/8847344/35688103-63c3f022-073e-11e8-96d9-403617dd8f5d.png)

**Comment by altrdgenetics** [comment]
**TO JUSTIN:**

> 
>     Having done my investigation on this issue and I questioned if the data actually got deleted since there should be no code to do that from the activity detail panel. I have found that the information was not actually deleted at all, it is still in the database however the information has been changed in a way that it will not show properly to the user in the application. There was 4 modified entries, 3 have a comment of "test" and the 4th has "P.O - Decision Classified".
> 
> 
>     There are two important things that was not mentioned in the ticket that are critical to why the activity "disappears". First the items that staff have been trying to modify are generated by the system automatically or at least show the created by as "SYSTEM". The second is that all of the activities that have been modified in this case are old enough that they were created in the 2.0 system. If you notice in the screenshots of the detail panel provided the Category and Description are blank and nothing is selected BECAUSE OF THIS... the action is blanked out since the system can not build the text from blank choices and the activity disappears in the application. This is because the text do not match any of the language that the current CMDS activity information drop-downs contain.
> 
> 
>     Now the question to all of this is what should happen when the user attempts to edit an activity that does not have a Category/Description that matches up to the list as available in the current 3.0 lists?

**Comment by altrdgenetics** [comment]
**FROM JUSTIN:**

> Thank you for confirming what is happening, I found it hard to believe that these entries were actually deleted. But I was unable to see them when viewing using HeidiSQL as well.
> I have two proposals…
>  
> 
>     Preferred Option… I believe the users should be able to tweak and fix invalid entries if needed… or to add a comment to better explain what the entry item is.  What suggestions do you have to make this work? If any?
>     Option 2… At a minimum if option 1 does not have a good solution… I suggest that a message box display when attempting to edit the old entries Informing the user that this entry cannot be tweaked. This should also prevent any errors from occurring.

**Comment by anthonyperk** [comment]
Was able to update the comment on a SYSTEM generated entry without it disappearing from the activity table.  Closing ticket.
