### ISSUE TITLE
(R3-073) - (ALL) - Frequent user lock outs

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#639]
I am submitting this ticket to address the SMDS issue where users get “Locked Out”. This happens at least twice per week. Sometimes more frequently. It is usually one of three repeat offenders.
There are two primary causes:

1) They do not log out overnight.
2) SMDS freezes (usually due to integration with MS Word; when this occurs).

I would really like to address item number 1.

I would like to see what kind of possible solutions you may have to address this.

1) Add an unlock option to the lock screen shown below.
![image](https://user-images.githubusercontent.com/24595073/36562045-afaf9c24-17e3-11e8-9860-64b4a6ba8bdd.png)

2) Somehow force a logoff.
3) Simply run a script overnight to clear the login checkmark.

When I have checked users’ PCs who are logged in after 5pm I have found that the PC is either off, or at the login screen.

Any assistance with this would be helpful. Currently, the users are reporting the lockout to myself, Tammy, or Erin. Then we go in and Unlock the account. Due to this process… It would make more sense for the user to be able to unlock their own account.

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> Justin,
>  
>         I can understand the frustration of having the users constantly coming to you to get their account unlocked. If you remember from back when we were building this application we created the single sign in as a solution to a few different scenarios. One of which was due to the unknown changes with the ID domain but another one was to create more accurate tracking and auditing of the users by making sure the user could only be signed in at one place at one time. This was in addition to allowing us to test specific user accounts from any logged in machine on the network. One of the non-mentioned features of the single sign in would limit the potential of locking files and supporting applications that plagued SMDS 2.0 from having multiple applications running on a single machine. 
>  
>         The largest concern that we have with this ticket at the moment is that you mention SERB3.0 freezes due to MS Word integration. If this is indeed an application error and not a user issue then that needs to be addressed.
>  
>         We have talked over this issue a little bit this morning and for addressing the first item on your list (They do not log out overnight) is making sure that the users follow proper end of day procedure and get them into the habit of it as it will be the most reliable solution when done correctly. This seems to be the least heavy handed solution since you said it is usually only one of three users.
>  
>         If we perform any of the solutions that you have provided this will open up the potential for additional consequences. The most glaring consequence that we see arising from these solutions is the user will have the potential for having multiple copies of the application open at once. This can add to confusion of which application is currently active and that the link between our app and MS Word or Japsersoft/Adobe PDF is not disconnected between the locked up app and the newly launched one. This problem along with correct and proper audit tracking was some of the issues that we listed when Angela submitted the ticket about a year ago to bypass the login screen when she requested the ability to run two copies of the application on one computer.
>  
>         We believe that the introduced risks with any of the solutions provided in the ticket outweigh the benefit provided for a small amount of problem users and the cleanest is to make sure the users follow the proper procedure. If you still wish to pursue other options and introduce an "auto log out" feature we will favor solution #3 the most. We discussed potential options and that one in particular seems to be the most reliable and secure out of any provided or any that we came up with ourselves. In order to make sure that potentially introduced issues are as minimal as possible and keep the posterity the audit trail there are a few additional things that will need to be done. The workflow for solution #3 should be as follows:
>  
> 1.	End of day occurs; all users should exit the application as previously instructed.
> 2.	Scheduled Task created by SERB or OIT kills any java application in use on all SERB/SPBR staff machines @ specific time for example 10pm. (This will be related to the Active Directory and will run via admin privs.)
> 3.	Email Server runs the normal daily error log now with new information of who is still signed in and where (now delayed till after the created Scheduled Task is run)
> 4.	Email Server Application then runs the new command that clears the login check mark after crash email is sent.
>  
>         Obviously the newly created Scheduled Task that exits java applications on the user’s machine will interfere and adversely affect any user that does not have these issues and likes to leave their application open overnight. But they shouldn't be leaving it open anyways per policy. This new Scheduled Task will need to be put on through the AD/DS which you may not have access to and require OIT assistance. The depending on how OIT implements the task a major downside to this is that the Email Server is also running java and could be force exited as well. Forcing the computer to turn off would be an alternative; we just need to make sure any open SERB3.0 applications have pending updates committed. This also would have the same consequences that the other task has. Either task would result in the daily email being delayed till after whenever that new Scheduled Task is ran, we have no issue in changing the time that the crash log email is sent.
>  
>         Let us know what you think 
>  
> - Andrew

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

> Andrew, 
>  
> I am still thinking on this email below… I spoke with Christine. 
>  
> Please give me two weeks to further investigate users not logging off at night.  
>  
> Thank you,

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> Justin,
> 
> We completely understand, you can see from our lengthy email that we could not come up with a good solution that solved the issue without potentially introducing additional work for someone else. We will make note in the ticket and if we have not gotten additional information from you check for a status update at that later point in time. 
> 
> - Andrew

**Comment by altrdgenetics** [comment]
At the meeting we had on 2/26 we talked to justin about it and the users are getting better about logging off. He is leaning towards closing out the ticket but he wanted some more time to see what happens

**Comment by altrdgenetics** [comment]
Emailed Justin reminding him that he has this ticket open

**Comment by altrdgenetics** [comment]
Talked to Justin about it today and he said the users still sometimes have issues but he has been constantly reminding them when he checks at the end of day.

Told him about if we implement an idle timeout for the users that it may have adverse effects if they are in an "update" mode.

At this point in time Justin has said to close out the ticket.

**Comment by anthonyperk** [comment]
6 hours
