### ISSUE TITLE
(R3-075) - (EMAIL SERVER) - Callendar Invite time change request

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#641]
The calendar invites that appear in Outlook when scheduled in SMDS are 5 hours behind. Please modify the code in application to “Add 5 hours” to the current formula so that they appear correct in Outlook.
I understand this modification may need to be tweaked if the true cause is resolved by OIT or Microsoft.

![image](https://user-images.githubusercontent.com/24595073/36688758-69a1a978-1afb-11e8-9e79-468dca12a1b4.png)

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> Justin since we are in production and you currently are in possession of the email server can you give me a test set parameters to use for testing purposes. A screenshot of all of the information required for a hearing from either Hearings or CMDS section would be great. Things like a case number and a user, etc. That way I could test it using your exact environment and you could let me know if the date is coming through correctly. I have an idea of how we can complete this with a change done from within the user application. 
> 
> Thanks,
> Andrew

EMAIL FROM JUSTIN

> I would like to use the following case and highlighted Hearing for testing. 
> 
> ![image](https://user-images.githubusercontent.com/24595073/36853025-49dc12f8-1d3b-11e8-9335-2d061368a4f0.png)
> 
> Below is the info that Diana manually put on the calendar. I noticed that it involves three cases. 
> 
> ![image](https://user-images.githubusercontent.com/24595073/36853024-47f35ffa-1d3b-11e8-8ccf-b452a8368e78.png)

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> 
> Justin,
> 
> I will have to create new hearings for the invites for testing. I see here that the ALJ is "James Sprague", if I create invites for this case he will receive multiple emails for the invites that I am testing. If this is acceptable I will go ahead and test against it when I am ready or else I would recommend temporary setting the ALJ to yourself so you get the emails directly. I think I might be able to start testing this tomorrow depending on my research that I am doing today.
> 
> - Andrew

EMAIL FROM JUSTIN

> Andrew, 
> 
> I will let Jim know that you will use that case for testing.

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> Justin,
> 
> Once we got all of the information together and started to do some internal testing here we found that the position in the client application is not the best spot for what we are trying to accomplish. We have moved the code change over to the email server application and have done the initial testing and believe that it will give correct information now. This change should be more complete and account for daylight savings time changes as well. 
> 
> I have placed the application in the test folder labelled as "ServerEmailControl - v2.2.27.jar". The only code that was changed in this build relates to the Calendar Invites, nothing else will be affected. If you could, please test this when you can. We have not created any hearings, we are leaving that up to your availability to do so. Once we know that it is functioning properly I will respond with an email that explains exactly what I think the root causes are so we have that for future reference.
> 
> NOTE: as a reminder do not run 2 copies of the email server at the same time, shut down the existing one before starting the test copy.
> 
> - Andrew


EMAIL FROM JUSTIN

> Andrew, 
> 
> I closed out of the Email program… then
> 
> When I click on the ServerEmailControl -v2.2.27 to run (I see a Java icon in task manager start running at 86.4MB of memory, but it does not display a message box like the old program did. 
> 
> Also, It did not send the calendar invite… so I don’t think it is working. 
> 
> I closed using task manager and restarted the original email program. 
> 
> I added three test hearings and now none of them are showing on the HR2 calendar. The 10am was sent while the new import program was running… the other two were sent after the new import program was closed and the original import program was running. The original import program has cycled through several times.   I am heading to lunch… Be back at 12:30
> 
> ![image](https://user-images.githubusercontent.com/24595073/36853182-c2122f5a-1d3b-11e8-9d2e-7d3836777ff2.png)


EMAIL TO JUSTIN

> Justin,
> 
> if you clicked on the application or the bat file I created for you without renaming the file to match the filename "EmailServer.jar" it will not show a console print out. The .bat file I created specifically opens a command line window for easy restarting of the application. In order to run the file with the version specific name you will need to open a command line window at that location and type in the following...
> 
> start java -jar [FILENAME]
> 
> or with the name I provided to you...
> 
> start java -jar ServerEmailControl - v2.2.27.jar
> 
> 
> then you will be able to have your commandline window. You may not have seen the calendar invites get sent yet because the order of operations within the application is as follows...
> 
> incoming emails
> calendar invites emails
> notifications emails
> outgoing emails
> 
> The application could have still been processing the incoming emails when you closed it out from task manager.
> 
> 
> Let us know if you need any additional assistance in testing the application
> 
> -  Andrew

**Comment by altrdgenetics** [comment]
**FROM JUSTIN:**

> 
> Andrew,
> 
> The new email server is working. The dates and times all match.

**Comment by altrdgenetics** [comment]
reopened this issue because now there the time is off, specifically 1hr ahead. I think someone changed for DST already. I emailed Justin and am waiting on him to get back to us about what we are going to do. He is supposed to check all of his date time settings.

**Comment by altrdgenetics** [comment]
Emailed Justin reminding him about testing after the DST time change

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

> Andrew, 
> 
> My test this morning confirmed that you were correct. As a result of Daylight Savings, the calendar invites are now 100% accurate. 
> 
> This ticket can be closed.
