### ISSUE TITLE
(R3-077) - (Calendar Invites) - Invite updates overwriting older invite versions

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#643]
I did discover one issue… when scheduling two hearings for the same case on different days. The second invite updates the original invite. See below.

I swapped back to the previous email application and tested and found that this issue existed there as well. It was just not reported to you because I did not know about it.

![image](https://user-images.githubusercontent.com/24595073/36851537-6ec782a4-1d37-11e8-80fa-ec7d8adee2de.png)

Issue:
When you schedule two hearings for the same case. The second calendar invite overwrites (updates) the first invite.

![image](https://user-images.githubusercontent.com/24595073/36851551-76f77d6c-1d37-11e8-978a-bbe9ee8c3d39.png)

![image](https://user-images.githubusercontent.com/24595073/36851557-7a2c1fec-1d37-11e8-98e0-1566b9c7029f.png)

Before…. Second hearing scheduled.

![image](https://user-images.githubusercontent.com/24595073/36851578-8056db14-1d37-11e8-95e3-7a82f137ab6e.png)

After second hearing scheduled. It erased the one on 2/3/18

![image](https://user-images.githubusercontent.com/24595073/36851586-869d40a8-1d37-11e8-93ea-2ec4f51cccae.png)

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> Justin,
> 
> I believe that you mentioned this in the R3-075 email chain before I got a chance to respond to it. Once the invite leaves our application what happens afterwards is beyond our control. When you were setting up the mailboxes on the new emails server I think I remember that you had problems getting the invites to even come through and in the end had to tell the mailboxes to auto accept invites. Auto accepting invites may have this issue as a side affect. We are just the messenger at this point, what ever happens after Exchange receives the iCal is going to be controlled by the mailbox settings itself. We do not have bidirectional communication with Exchange calendars. I do not believe this is something we can fix on our end.
> 
> - Andrew


EMAIL FROM JUSTIN

> Andrew, 
> 
> The Recipient email program thinks that it is an update, which makes me think that somehow the iCal needs to be unique in order to send more than 1.  
> 
> The ALJ also receives an “update” to the original so it is not the auto accept feature. Can you investigate further to see what needs to happen to make each invite separate so that two can be sent from the same case. (Possibly have a unique subject using the “created date/time” to test my theory?)

**Comment by altrdgenetics** [comment]
**TO JUSTIN:**
> Justin,
> 
> I am glad that the additional change has finally caused the calendar to NOT overwrite the existing invites that were already there. Unfortunately I do not believe that the last change I have made was 100% the root cause. I believe that it was part of the problem but not the sole issue, I would recommend that we leave the date/time in the subject to ensure that changes to the servers outside of your control (i.e. updates) will not cause any issues with the calendar invites in the future.
> 
> Is there a reason why you do not want that information to be displayed in the subject also?
> 
> 
> - Andrew


**FROM JUSTIN:**
> Andrew,
>  
> We can leave it for now. The calendar gets printed and displayed on the front window.
>  
> Thank you,
> Justin Brown
