### ISSUE TITLE
(R3-081) - (ALL) - Date limitation in Record retention panel

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#646]
Record Retention Screen. Do not allow the end date to be earlier than the begin date.

![image](https://user-images.githubusercontent.com/24595073/37419766-91f85844-278b-11e8-8299-01fe4c7ffb6f.png)

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> Justin,
> 
> This is something relatively easy to implement but I do have one question surrounding what you are asking us to do. I do not believe this check/feature is available anywhere else in the application. Is this something you only want implemented at this location or do you want us to edit every start/end date box within the application to have the same check/feature?
> 
> If you would like it to be done system wide then please send a revised ticket stating so.
> 
> - Andrew


EMAIL FROM JUSTIN

> Andrew, 
> 
> Please only implement this tweak on the retention screen.

**Comment by altrdgenetics** [comment]
I have completed this ticket, I added in a few extra QoL items for labels and the such when the date pickers are cleared out.

(1.5hr Spent)
