### ISSUE TITLE
(R3-083) - (ALL) - Tweek time requirement for ORG Record Retention

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#648]
Records Retention ORG Section & Civil Service Section. Please tweak the code to keep 7.5 years of activity instead of 7 years of activity. Upon review, the timing of a few things were being purged sooner than we would like.

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

> Correct answers are bolded:
> 
> In the ORG section we have the date difference set to 7 years from the "Filing Due Date". Is this going to be 7.5 years from TODAY, **or will it be 7.5 years from "Filing Due Date"**?
> 
> For the CSC section it is 7 years from April 30, [CURRENT YEAR]. The same question for this section as well. Is this going to be from TODAY or **following the April 30th**?

**Comment by altrdgenetics** [comment]
DATEADD(month, -6, @d) 
        |->@d = date

**Comment by altrdgenetics** [comment]
(1hr spent)
