### ISSUE TITLE
(R3-084) - (ALL) - Needs Purged Report redo

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#649]
Needs Purged Report.
Please tweak the report to only print the items for the section that you are in. We do not want all sections printed at the same time.

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> Justin,
> 
> Just so we are on the same page: PROD133 asked for the Needs Purged Report to show all cases that need activities purged and order them by board meeting date, then be section.  You would now like it broken out to be run section by section.


EMAIL FROM JUSTIN

> Anthony, 
> 
> After seeing the report, the end users are asking that it be run section by section.

**Comment by anthonyperk** [comment]
Changed the report to only print the section that is asked for.

1.5 hours

**Comment by altrdgenetics** [comment]
has not been completed, not pushed to SERB

**Comment by anthonyperk** [comment]
Files transferred to G drive.  Tested using the 3.8.1 test build.  All reports generate as expected.
