### ISSUE TITLE
Auto-Retention of Documents

### ISSUE THREAD

**Issue by parkjohnston** [CurrentlyNotSet/SERB#65]
Provide the ability to move documents to a "inactive state" that would allow for serb review and then a final removal state "of deleted from disk" x number of days after the inactive state.  This will allow for SERB to triple check documents and ensure they are correct removing themselves.

Also would like a way to whitelist a certain case to NEVER be removed.

This is including history entries and documents.  The rules are very odd, need more information

NOT IN SOW, but has been discussed internally....just monitor.

**Comment by parkjohnston** [comment]
Any movement on this? 

Have a really easy solution! :)

**Comment by altrdgenetics** [comment]
Justin Had snuk this in with PROD109 but i told him to separate it out, he has not submitted the new ticket.

**Comment by altrdgenetics** [comment]
They finally Submitted a ticket on this...

(PROD133) - (ALL) - Record Retention #514
