### ISSUE TITLE
(R3-085) - (ORG) - Updating activites in ORG

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#650]
Please see the included CSV file. Please use the “ID” Column and the “Action NEW” Column to update the 2,611 records in the file. This update will properly name the files. This corrects errors in the system that were created from programming bugs in the version 1.0 program. Your assistance is appreciated.

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

> Correct answers are bolded:
> 
> In the ORG section we have the date difference set to 7 years from the "Filing Due Date". Is this going to be 7.5 years from TODAY, **or will it be 7.5 years from "Filing Due Date"**?
> 
> For the CSC section it is 7 years from April 30, [CURRENT YEAR]. The same question for this section as well. Is this going to be from TODAY or **following the April 30th**?

**Comment by altrdgenetics** [comment]
I have completed this ticket. and verified the data in the database

Total Time: 4hrs
