### ISSUE TITLE
(R3-088) - (ALL) - Change of CMDS Record Retention process

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#653]
SMDS 3.0 Records Retention – Modification to CMDS Tab Record Purge Criteria.
Please modify the code for the CMDS Tab Only. All other sections have been confirmed to stay as is.

Criteria:
If Status = “C” and [close date] + 731 days (2 years + 1 day) falls within user prompt date range… then select all active/inactive activity records with documents attached for purging except the following activity entry types with documents attached:

- Archive Board Order
- Common Pleas
- Court of Appeals
- Public Records Request
- R & R

Notes:
All activity entries without a document attached would be excluded by default. Only activity entries with a document attached would be displayed in the purge screen.

The exclusion list would exclude activity entries with documents attached.

Upon purge, the new records would be created in the purge table, however only the link to the document would be deleted from the activity table. The activity entry is

Please clear the other CMDS Purge Exclusion items.

**Comment by altrdgenetics** [comment]
8hr spent
