### ISSUE TITLE
(R3-089) - (CMDS) - Dy mis labelled a CMDS Case

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#654]
CMDS Section:

Please change the following case number.
**18-ABL-03-0051**

Change to:
**18-WHB-03-0051**

Would it be possible to have the change case feature added back into SMDS? It was in the previous SMDS 2.0 build? Sections: CMDS, REP, ULP, MED

**Comment by altrdgenetics** [comment]
**RELATED ISSUE NUMBERS:**

> (R3-059) - (CMDS) - Case Number Change #627
> 
> (PROD158) - (CMDS) - Update Case type #539

**Comment by anthonyperk** [comment]
Changed the database to reflect the change.  At this time, SERB has declined the option to create a way for them to change the case numbers on their own.

1.5 hours
