### ISSUE TITLE
(N/A) - (ALL) - Locked out users

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#656]
It appears Justin is out and they lost internet and everyone was locked out.

**FROM LICIA:** (TO: Allen, Andrew, Timothea)
>
> Hi Allen and Andrew,
>  
> Our internet went down and everyone got locked out of SMDS. Would you please unlock Tammy Johnson so that she can unlock the rest of us? 
>  
> Thanks!
> Licia Sapp

-----------------------------------------

**FROM ALLEN:**

> Oh Boy.
>  
> Andrew has left the company & Anthony is out of town.
>  
> I am trying to contact Anthony to get this done.  Please stand By.
>  
> Thanks
>  
> PS
>  
> Damn OIT Internet!
>  
> Allen Perk

> I’m told that in 35 minutes, everyone who is locked will be unlocked.
>  
> Will that work?
>  
> Allen Perk

-----------------------------------------

**FROM TAMMY:**

> Yes that will work.   I will let everyone know.
>  
> Thanks      
> Tammy Johnson

**Comment by altrdgenetics** [comment]
List of users needing unlocked

![untitled-1](https://user-images.githubusercontent.com/8847344/38144655-b8aca7bc-3413-11e8-986c-ee000e76e4c8.jpg)

**Comment by altrdgenetics** [comment]
No information was received back, I can only assume they were able to get back to work without issue.

**TIME SPENT: 0.5HR**

**Comment by anthonyperk** [comment]
Added to SOW per Allens request
