### ISSUE TITLE
(R3-090) - (CMDS) - Limit 'Group Number' to 8 digits AND CMDS Web Updater

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#659]
CMDS Section:
Please tweak the field below to only allow numeric values with a min and max value of 8 digits. This is causing an issue with our SPBR Website.

Also, fix the SPBR Website updater to look for 8 digits instead of 6 digits.

Note: Please confirm that I have enough pool of hours to resolve this. I need Christine to confirm if this can be billed this FY or after July 1

20180015 (correct)

![image](https://user-images.githubusercontent.com/24595073/42697112-30df466a-8688-11e8-811e-3e8751eb8937.png)

NOTE: Diana fixed the invalid group numbers in CMDS on 5/22/2018

**Comment by anthonyperk** [comment]
Looks like we dont have to retro-actively change the group numbers as Di has already done that

**Comment by anthonyperk** [comment]
It looks like we may need SERB to contact the person on OIT's side that deals with the website itself to change the group number to 8 on their end as well

**Comment by altrdgenetics** [comment]
I know we talked about this before, what is the final say? Are they going to change the way the their web propagator on their end to support the additional characters.

RECAP: their current parser does it based on character index and NOT delimited by specific character.

**Comment by anthonyperk** [comment]
After a couple emails back and forth, Justin said that the website does not have any limitation on that quantity of characters in each field, so changing the code on our end from 6 to 8 should work without anything on OIT's end.

It looks like if we go with what he says, then all we have to do is change the code in CMDSwebUpdater.java:

line += String.format("%-6s", item.getGroupNumber().equals("") ? "      " : item.getGroupNumber());

to 

line += String.format("%-8s", item.getGroupNumber().equals("") ? "      " : item.getGroupNumber());

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN
> Anthony, 
> 
> After an hour of investigating, I think I found a very easy solution. 
> 
> 1)	The website does not limit the quantity of characters. It simply points to the MS Access database and displays whatever is in the designated field. 
> 2)	After looking at the MS Access database, I discovered that the field length is set for each field. So, I changed the group size field width from 6 to 8 characters in the spbr-template file located in G:\CMDS\CMDSWeb. When the template database is opened it runs a script to populate the database. I will take a look after it runs tonight to see if this resolves the issue. 

EMAIL FROM JUSTIN

> Anthony, 
> 
> I double checked the new MS Access file that was uploaded to the web last night. I still have the issue with the group number. 
> I did confirm however that the group number is formatted for 8 characters so I did update the correct template file.  Next we should look at the G:\CMDS\CMDSWeb\spbr-case.txt file that is created from SMDS that populates this MS Access database table.  I will need your assistance with this step since it only runs once per day and deletes itself once the upload is completed. 

So justin has changed the groupnumber field in the template to 8 characters (not sure if this needed to happen, probably did).  Is the change in my above comment the only thing that needs to be changed?

**Comment by anthonyperk** [comment]
Wellllllllllllllllllllll it didnt work.  According to Justin, now everything is off by 2 spaces if there isnt a group number, and if there IS a group number, nothing has changed.  This points to the parser on the website side (at least for the 'if a group number exists' portion').

**Comment by anthonyperk** [comment]
TO JUSTIN:

> Well it looks like it didn’t work.  This leads me to believe it’s a parser issue on the websites side.  I am assuming that it is looking for 6 characters starting at a specific spot within the file, then after that 6th digit cutting it off and starting the next field regardless of what is next.
> 
> Justin, can you look at the destination and see what the database or file looks like?


FROM JUSTIN:

> Anthony, 
> 
> I disagree… The change you implemented made things worse. 
> 
> Before yesterday, all entries were correct except for when there was a group. 
> 
> Today, All entries are now off by at least 2 characters.  See the example below. It added two spaces in front of the ALJ only if there was no group number. 

![image](https://user-images.githubusercontent.com/24595073/43962721-64268de4-9c86-11e8-8705-40317a086af3.png)

![image](https://user-images.githubusercontent.com/24595073/43962725-672ea42c-9c86-11e8-8e75-5778f052ce4b.png)

**Comment by anthonyperk** [comment]
I may have found the fix.  This will be in two parts:

1) The padding for the group number within the EmailServer will need to be changed.  While I did change the number from 6 to 8 in the string.format portion of the code, I did NOT then increase the padding on the if statement portion from 6 to 8:

`item.getGroupNumber().equals("") ? "      " : item.getGroupNumber());`

to

'item.getGroupNumber().equals("") ? "        " : item.getGroupNumber());'


2) Within the Access database, there is a macro that imports the information from the INTERNET-Case-EXTRACT.SEQ/spbr-case.txt file into the Access Database.  This macro uses a "specification" called the "Case Import Specification", which apparently instructs the macro on how exactly to import the information (Table column name, **length of the entry into the column**, and **starting character within the imported file**, etc).  EVERY column after the group number will have to then have its starting character number increased by 2 in order to align correctly.

I will see if I cant get this done before this evening so it can be tested for over the weekend.

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> Justin,
> 
> While looking this over again, I notice that in this email, you say this field should be 9 characters (####-####), but the ticket says 8 characters (I assume ######## without the dash).  Allowing the dash in the field will disrupt the CMDSWebUpdater program (without changing code on the webupdater side).
> 
> Which way would you like to go with this?


EMAIL FROM JUSTIN

> Anthony, 
> 
> Great catch. It should be 8 characters, numeric only. No dashes allowed.

**Comment by anthonyperk** [comment]
8 digit Group Number limitation on CMDS Tab moved to #690
