### ISSUE TITLE
(R3-091) - (CMDS) - Outgoing documents to be saved to the group if it exists

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#660]
When sending a document out via the letter queue (email or postal) check to see if the case is part of a group. If the case is part of a group provide a prompt to the user asking if the outgoing document should be saved into all cases within the group.

Prompt: Should this outgoing message and attachments be docketed into all cases within the group?
Y/N

Notes:
Incoming Documents will docket to all cases within the group.

Other Notes/Questions…
Thank you for the response below. Currently, the docketing of incoming documents does not give you the option to pick which cases in a group receive the incoming files; The system auto dockets the files into all cases in the group. The only way to stop this is to remove a case from the group once the case has been resolved. Question: is this an issue?

I will create a new ticket (R3-091) to address the outgoing documents issue when in a group. I will also ensure that there is a prompt when sending out via the CMDS letter queue to ask if the file should be docketed into all cases within the group when sending.

Question: Do I need the ability to allow user to pick which cases within the group should receive the files or do an All or None option?

Question: Do I need to be able to update the status line in all cases during this process? Seeking further clarification on how this should work.

**Comment by anthonyperk** [comment]
Justin responded, didnt get rid of the 'waiting for response' tag

**Comment by altrdgenetics** [comment]
Depending on the response from Justin this may be digging up concrete, might even find Hoffa.

So the way the letters are processed they are just verified that everything is in order when going through the letter queue on the front end. The only action that happens within the main app is the modification to the flag for okToSend on the emails/postal. 

What happens to the outgoing emails on the server side is that the email server will just loop through any that have okToSend set to true and handle the heavy lifting with file conversions, sending the emails, and adding the activities. Now you may be thinking that there is something with multicases already there and you would be correct that would be MED section and it AUTO adds activities to any that have multicase information. 

So if SERB wants this functionality there will need to be changes to the threading of java for the desktop app in addition to the extra display windows, a new database table or changes to an existing one, and changes to the email server for how the processing occurs to utilize the previous mentioned changes after all supporting changes have been made.

If they do wish to do this change still I would like to discuss a game plan with you before accurately estimating hours but I can go ahead and say more than 3hrs.

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

```

> Anthony, 
> Currently I see 7 groups affecting 21 PBR cases for the past year. Can you provide a quote for what this would cost to “dig up concrete” per the proposal in the ticket? I need to see the pro/cons of proceeding. The current system has worked flawlessly and I don’t want to break it. I also need to be cautious with how many hours I burn this early in the year. 
> Backup Plan…
> Worst case scenario… the user could email to clerks office to docket into the other cases since there are so few. Then this could be addressed in a future build or release.

**Comment by anthonyperk** [comment]
Justin also updated the ticket:

> When sending a document out via the letter queue (email or postal) check to see if the case is part of a group. If the case is part of a group provide a prompt to the user asking if the outgoing document should be saved into all cases within the group.
>
> Question: Do I need to be able to update the status line in all cases during this process? When sending outgoing message that includes a group of cases, a prompt will display.
>
> "Docket into the following Group Cases:" Note: All will be checkmarked by default
> Checkbox Case 1
> Checkbox Case 2
> Checkbox Case 3
>
> User can remove checkmark as needed. Outgoing items will be docketed into the
> checkmarked cases.
>
> The inventory status line will be updated if updated in the master case.
>
> We identified several instances where this is needed. This was not an issue before; but now that we are
> sending things out via the letter queue this change is needed.

**Comment by altrdgenetics** [comment]
Current game plan for getting this in the system. I think that we can do this with a new table and not a new column. This should allow for flexibility when delivering the new version. This will still require a pair release of the email server and desktop application.

![20181224_162557](https://user-images.githubusercontent.com/8847344/50406775-c4d18680-0798-11e9-9f55-a8978f5416cd.jpg)

**Comment by altrdgenetics** [comment]
I overlooked things, We will need to have a postalOutRelated and an emailOutRelated table in the DB. Email server will of course only need to contain the email one.

**Comment by altrdgenetics** [comment]
I have finished this ticket up and it is awaiting review... 

One thing to note is that the multicase selection during letter generation is currently setup to be in the middle requiring action from the user ALWAYS. There will be some additional work but we can move this to a button like on the letter queue panel and assume the case will be docketed into ALL cases unless otherwise acted upon (to reduce clicks). This is stated in case there is questions regarding the flow we have presented. 


Justin mentioned this:

> The inventory status line will be updated if updated in the master case.

The code for adding the multi-case Activities utilize the same code as those as what currently exists, if there is any deviation on that. Inventory Status Line does not update on generation or sending of documents from what I can tell, No change has been made during this ticket to that functionality. It only happens on incoming documents, not on outgoing.

**Comment by anthonyperk** [comment]
TEST RESULTS
-----------------------------------
Cases:
2018-OSH-04-0087
2018-OSH-04-0086
2018-OSH-04-0085
2018-OSH-04-0084

Group Number: 20180084


Postal
-------------
Postal's process went as smooth as I could have hoped.  Used 2018-OSH-04-0085.  The letter (BO Settlement) generated without issue and was waiting in the queue for me to send out.  Once sent out from the queue, every case in the group got an activity for each copy of the letter to each recipient (5 recipients, 5 different activities in each of the 4 cases in the group).  Not sure if this is how its supposed to work, but thats the result I got.


Email
----------
Email's process also went smooth, like Postal's, until sending it.  I do have the Email server running, but it can NOT connect to the email server itself (and I have set okToSendEmail to FALSE in the code).  Since I can not send out the emails, the application does not update the actives in the cases.  I am sure I am doing it wrong.

Other Observations
--------------------------
1) While sending the postal letters, it did NOT update the inventory status line, but I am not sure if the BO Settlement is supposed to update the Inventory Status line.

2) Backspacing in the group number still throws a warning box (implemented in R3-090).  Can't remember if you had gotten to that yet.

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> Justin,
> 
> I am in the final testing phase of ticket R3-091, but I have a couple final questions (NOTE: all testing is being done at our office and not on your live system.  No emails are actually being sent out during testing):
> 
> 1.	For the postal sending, the way we currently have it set up is that when you have multiple recipients of a letter (say BO Settlement for example), if you docket it to 1, multiple, or all cases within the group, each case gets an activity entry for each recipient/letter generated.  Is this what you are looking for, or are you looking for just 1 activity for each case?  Example below (note, this selection was from 1 Letter generation process, not 5 different ones.  The letter was selected to be sent out through postal for all 5 parties within the case I chose as an example, 2018-OSH-04-0085.  All cases within the group have the same 5 activity entries as this):
>  
> 2.	For the inventory status line: From what we can tell, the inventory status line has never been updated with any outgoing letter (email or postal).  Your ticket asks for the Inventory Status Line (ISL) to be updated if updated within the master case.  Is this request completely separate from the outgoing letter part of this ticket?  That may be where the confusion lies.

**Comment by altrdgenetics** [comment]
for "1." Postal sending

I went back and tested it from the development branch and this is the way it has always functioned. The generated only contained a single copy, the postal out (for all sections BTW) had a copy for each person you sent it to due to it having the foldable insert in the saved document. This was "proof" that you did indeed send it to the person and could easily print it back out at a later point in time if you need to resend it without having to regenerate the insert as it was saved as a singular PDF. I did notice that the activity escription could be a little more useful as it currently does not reflect which person it was sent to, but they have not complained about it or asked us to change it as of yet.

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

> Anthony, 
> 
> I had a meeting with Ray and Jim this morning regarding your questions below. Here are the responses. 
> 
> 1) Please create only one activity entry for mailed PBR cases. If group has both email and mail; two activity entries would be created. 
>
> In other sections, where an activity entry is created for each postal recipient, can you append the recipients name to the end of the activity entry? Otherwise, user would need to click on each postal entry to determine who it is to. 
> 
>2) Thank you for bringing this up. I was unaware that this was the current process. Please do not update the inventory status line when generating letters.

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> The consolidation of the postal outs is a lot more complex than we originally thought, but is possible.  If you wanted this functionality, could you please submit a ticket for that so we can spin this out into its own ticket and not have to wait for it to be completed in order to roll out the rest of R3-091.  HOWEVER, your request to amend the activity entry to have the recipient’s name at the end of the activity is pretty straight forward and can be completed a lot faster.


EMAIL FROM JUSTIN

> We would like to wait until all of R3-091 is ready before rolling it out. Can you confirm what additional costs are associated to make the system combine the files? Can it be completed prior to June? Once I have the answers to these two questions we can decide how to proceed.

**Comment by anthonyperk** [comment]
Didnt mean to close the ticket

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> After talking with Andrew last night, he indicated ~15-20 hours to complete the consolidation of Postal out files, as he will have it mostly rewrite the entire process for generation as well as outgoing postal for CMDS.
> 
> That being said, he would like clarification on how you would like the process to go.
> 
> Currently, when you generate a postal out:
> 1.	user chooses the letter to generate, choose the recipients
> 2.	add any additional attachments/documents
> 3.	the ‘creation’ activity entry is created for that case, and x amount of documents are sent to the letter queue
> 4.	when the user brings up the letter queue and selects the postal to be sent out (printed and mailed), the PDF is created for each recipient with the Cover page, original document, any attachments combined into 1 PDF/file to be printed.  
> 
> The way I understand your request is that you want the PDF that is created and then printed to be a combination of all pages to all recipients into 1 document and in 1 activity entry INSTEAD OF 3 separate documents and associated activity entries.    Example:
> 
> 3 recipients of a Board Order document
> Current:
> 1 document containing
> Cover letter/mailing insert to recipient A with name and address
> Board Order document
> Any extra attachments from the case/questionnaires/etc.
> Within 1 activity entry, recipients name amended to the end of the activity entry
> 
> 1 document containing
> Cover letter/mailing insert to recipient B with name and address
> Board Order document
> Any extra attachments from the case/questionnaires/etc.
> Within 1 activity entry, recipients name amended to the end of the activity entry
> 
> 1 document containing
> Cover letter/mailing insert to recipient C with name and address
> Board Order document
> Any extra attachments from the case/questionnaires/etc.
> Within 1 activity entry, recipients name amended to the end of the activity entry
> 
> 
> 
> Proposed:
> 1 document containing
> Cover letter/mailing insert to recipient A with name and address
> Board Order document
> Any extra attachments from the case/questionnaires/etc.
> Cover letter/mailing insert to recipient B with name and address
> Board Order document
> Any extra attachments from the case/questionnaires/etc.
> Cover letter/mailing insert to recipient C with name and address
> Board Order document
> Any extra attachments from the case/questionnaires/etc.
> Within 1 activity entry, all recipients name amended to the end of the activity entry



EMAIL FROM JUSTIN

> I discussed this with Jim and Jeannette. We would like to proceed with the consolidation of Postal Out files for the 15-20 additional hours of work. All my notes and confirmations are in red below. 
> 
> Currently, when you generate a postal out:
> 1.	user chooses the letter to generate, choose the recipients **(correct)**
> 2.	add any additional attachments/documents **(correct)**
> 3.	the ‘creation’ activity entry is created for that case, and x amount of documents are sent to the letter queue **(correct)**
> 4.	when the user brings up the letter queue and selects the postal to be sent out (printed and mailed), the PDF is created for each recipient with the Cover page, original document, any attachments combined into 1 PDF/file to be printed.   **(correct)**
> 
> The way I understand your request is that you want the PDF that is created and then printed to be a combination of all pages to all recipients (in the selected case) into 1 document and in 1 activity entry INSTEAD OF 3 separate documents and associated activity entries.   **(correct)**
> 
>  Example:
> 
> 3 recipients of a Board Order document
> Current: **(This is correct)**
> 1 document containing
> Cover letter/mailing insert to recipient A with name and address
> Board Order document
> Any extra attachments from the case/questionnaires/etc.
> Within 1 activity entry, recipients name amended to the end of the activity entry
> 
> 1 document containing
> Cover letter/mailing insert to recipient B with name and address
> Board Order document
> Any extra attachments from the case/questionnaires/etc.
> Within 1 activity entry, recipients name amended to the end of the activity entry
> 
> 1 document containing
> Cover letter/mailing insert to recipient C with name and address
> Board Order document
> Any extra attachments from the case/questionnaires/etc.
> Within 1 activity entry, recipients name amended to the end of the activity entry
> 
> 
> 
> Proposed: **(Correct with tweak below)**
> 1 document containing
> Cover letter/mailing insert to recipient A with name and address
> Board Order document
> Any extra attachments from the case/questionnaires/etc.
> Cover letter/mailing insert to recipient B with name and address
> Board Order document
> Any extra attachments from the case/questionnaires/etc.
> Cover letter/mailing insert to recipient C with name and address
> Board Order document
> Any extra attachments from the case/questionnaires/etc.
> Within 1 activity entry, **all recipients name amended to the end of the activity entry (remove)**
> 
> If in a group, add the one activity entry into the selected case numbers. 
> 
> Change:
> For the group combination PDF, do not append the recipient names. It will make the activity entry too long. The recipient names were suggested if we proceeded with having 3 activity entries instead of 1 to better inform the user. I also confirmed the appended name is not needed in the other sections. 
> 
> Please proceed per your proposal stated above with the two tweaks. Let me know if you have any questions.

**Comment by anthonyperk** [comment]
Call with Justin
-----------------------
Justin clarified that the ENTIRE "recipient names amended to the activity entry" request is no longer wanted.  Apparently that was suggested IF they had stayed with the multiple-activity-entries-for-postal route.  But since they want the combined activity entry, "recipient names amended to the activity entry" is no longer wanted.  SO, that part is now scrapped, but they had originally asked for it so we are still going to keep that in the bill.

Everything else about the ticket remains the same.  Combination of all postal out files into one giant file, and one activity entry.  That activity entry and giant file will also be copied to the cases in the group that have been selected in your new selection panel.

**Comment by anthonyperk** [comment]
Everything in this ticket that ISN'T addressed in R3-091 part 2 is finished.  I am closing this part of the ticket.
