### ISSUE TITLE
(R3-094) - (Admin) - SERB System Information panel not saving changes

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#663]
SERB System Information Screen in Admin Panel

The save button does not seem to work. I attempted to update the URL. It won’t save changes.

I manually updated the URL using SQL until issue can be resolved.

![image](https://user-images.githubusercontent.com/24595073/42697779-0dc23140-868a-11e8-9308-7acf1afa5749.png)

**Comment by anthonyperk** [comment]
I confirmed this on our side and their side (added something to "Address 2').

Stepping through the code, it doesnt skip over any of the trims, nor any part of the information gathering or sql writing.  the "saveInformation();" method IS being called, not sure what is going on

**Comment by altrdgenetics** [comment]
I have figured out the issue with this, when you are ready to go over it let me know and we can schedule time to do so.
