### ISSUE TITLE
(R3-099) - (MED) - Mediators marked as inactive do not show up on their previously assigned cases

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#666]
If a State Mediator or FMCS Mediator is marked “inactive” the name no longer shows in the case. If you make them active again they show up in the case. Note: It does not affect the annual report stats.

Is it possible for the name to stay visible in the dropdown if it has already been selected?

I believe this is probably an issue in other dropdown boxes as well. Please investigate.

![image](https://user-images.githubusercontent.com/24595073/42766176-bf20c1ae-88e7-11e8-868a-51140985806b.png)

**Comment by parkjohnston** [comment]
Do you need me to work on these? 

Super easy fixes just unsure what the game plan is

**Comment by altrdgenetics** [comment]
So when we load the mediators anyone that will not load will not show. So after it loads we attempt to select the mediator for the case but they aren't there. So after that occurs we just check to see if the dropdown is still blank and if so we add the case mediator in and then select them.
