### ISSUE TITLE
Letter Queue

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#68]
- create table that contains all of the letters ready to send out with a date column for suggested send date
- Thread this to live reload the number on the home page (for number count on the root panel button)

**Comment by altrdgenetics** [comment]
completed all but thread the button on main tab

**Comment by parkjohnston** [comment]
@altrdgenetics this seems completed?

**Comment by altrdgenetics** [comment]
completed the letter queue some time ago.
