### ISSUE TITLE
(R3-106) - (ORG) - Record Retention will not load for ORG

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#681]
The Employee Org Record Retention program does not allow the use of the date range fields (which I don’t think are needed for this section) or provide a listing of the records that need to be purged. I confirmed via the database that the system has no purged the activity entries yet.

![image](https://user-images.githubusercontent.com/24595073/46758674-6f0e3780-cc9b-11e8-80ee-7300dac4f7dd.png)

**Comment by anthonyperk** [comment]
First Issue:  Within the database, February is misspelled for in the ORGCase.filingduedate column (missing the first r).  This causes the SQL statement to fail since it is looking for the correct spelling of February.  This leads into the next issue.....

Second Issue: Within the code for ORG (ORGInformationPanel.java), if 'September' is selected for the 'Fiscal Year Ending' dropdown, then 'February 15' is supposed to be entered into the Due Date field.  February is misspelled in the code, which is then inserted into the database, which causes the SQL statement for the ORG Record Retention to fail.

Third Issue: There are 162 entries for 'Febuary' in the live database, these will be changed.

**Comment by altrdgenetics** [comment]
It was asked of us that we do not have a date range selection for the ORG section. So for that panel it is disabled. See PROD133 #514 

"Select all Employee Org Activity entries older than [Due Date] minus 7 years except..."

**Comment by anthonyperk** [comment]
Nothing else needs to be done to this ticket:

EMAIL TO JUSTIN:

> Justin,
> 
> Question on this ticket:
> 
> Now that the SQL query runs correctly (due to February being spelled correctly in the database), the list of eligible ORG documents to be purged now populates as requested.  In your ticket, the first issue is that the date fields are grayed out and can not be used.  This is due to the request made for PROD133 for the ORG section:
> 
> Select all Employee Org Activity entries older than [Due Date] minus 7 years except AR, FS, RR (Annual
> Report, Financial Statement, Registration Report) AR, FS, RR, CB (Annual Report, Financial Stmt,
> Registration, Const Bylaws), CB (Constitution and Bylaws), CB AMD (Constitution and Bylaws – Amended),
> CB DUP (Constitution and Bylaws – Duplicate), DIR (Directive), LocalList (Parent Org (Chapter) List), RR
> (Registration Report), RR AMD (Registration Report – Amended), RR DUP (Registration Report –
> Duplicate), RR, CB (Registration Report and Constitution and Bylaws), TR (Trustee), TR AMD (Trustee –
> Amended), TR DUP (Trustee – Duplicate)
> Mark all other Activity entries INACTIVE (and flag somehow with a “Delete Date”)
> Create Activity Entry “Documents Purged per Retention Policy” with today’s date.
> After 6 months, purge INACTIVE entries and delete the linked files associated to them.
> 
> I know that you had indicated in the ticket that you don’t think the date fields are necessary for ORG section, but I just wanted to make sure that this list of criteria still valid AND that you agree that the date fields SHOULD NOT be used for the ORG section. 


EMAIL FROM JUSTIN

> The removal purge process should work just like the other sections. The date range can remain greyed out since we do not need to use it for this section. I believe this ticket can be closed since the records are now displaying correctly on the purge screen.

**Comment by anthonyperk** [comment]
I think this ticket can be closed with a merge request for the spelling correction of 'February'
