### ISSUE TITLE
(R3-109) - (Docket) - Issue with docketing a file with special characters in the title

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#688]
XLN Team,

I forwarded an email to the test mailbox for you to analyze. The attachment shown below does not docket into SMDS. I assume the issue is caused by the apostrophe in the filename or one of the other special characters.

Can you add a check into the system to convert the special character to a blank space so that it can be docketed?

![image](https://user-images.githubusercontent.com/24595073/49704933-33cead00-fbe7-11e8-8641-189554410d8d.png)

**Comment by anthonyperk** [comment]
This may be due to an apostrophe ('), percent (%), or dash (-)

**Comment by altrdgenetics** [comment]
I request more detail on this, does it make it to the docket screen? or does the email system not even import it in?

The title of the document provided in the screenshot it does not match the standard format that the email server creates. And on top of that the %2c is encoding for a 'comma' which is not a valid system file character. 

I don't see anything that stands out in the SECException SQL Table

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> Justin,
> 
> When trying to docket this file, does it make it to the docket screen? or does the email system not even import it in to be docketed?
> The title of the document provided in the screenshot it does not match the standard format that the email server creates. And on top of that the “%2c” is encoding for a 'comma' which is not a valid system file character.
> I don't really see anything that stands out in the SECException SQL Table at all.

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

> Anthony, 
> 
> The email system skips it during import as if it was never there.

**Comment by altrdgenetics** [comment]
From the Screenshots we might need to see about what is going on. I tracked it down now that I know the actual filenames. Looks like it is not the only file that has the same issue. As you can see we are renaming the file soooo it doesn't appear to be the issue. The last image is the method is actually craps out on and we already have the file renamed at that point so best guess is that there is some sort of temp location it is writing to and crapping out on. All of this is in the EmailServer

![screenshot 67](https://user-images.githubusercontent.com/8847344/49771175-ebca8b80-fcb5-11e8-8ae6-d6eee5905766.png)


![screenshot 68](https://user-images.githubusercontent.com/8847344/49771177-ecfbb880-fcb5-11e8-960f-5d3c9324f62c.png)

![screenshot 69](https://user-images.githubusercontent.com/8847344/49771323-904ccd80-fcb6-11e8-811c-ef41f17f9930.png)
