### ISSUE TITLE
(R3-112) - (MED) - Fact Finder not CC'ed on letter

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#692]
XLN Team,

In the mediation section, when the Fact Finder Appointment Extension letter is selected, and sent out of the letter queue, the Fact Finder Selected does not get CC’d on the outgoing email.

I just looked back at a year of outgoing extension letters and the selected Fact Finder is not CC’d on any of them. We do not send this letter very often and I believe we just did not catch it.

![image](https://user-images.githubusercontent.com/24595073/49896779-63b5c480-fe22-11e8-8987-69ba8edfdf89.png)

**Comment by anthonyperk** [comment]
This looks like it was addressed in PROD174 #555 

EMAIL TO JUSTIN:

> Justin,
> 
> Can you check to see if the other letters that are supposed to CC the Fact Finder are in fact working?  The list we have programmed is:
> 
> fact finder appointment letter
> accepted fact finder report
> accepted and deemed accepted fact finder report
> deemed accepted fact finder report
> rejection of fact-finding report
> fact finder appointment serb (discrectionary)
> fact finder appointment serb (discretionary)
> fact finder extension

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

> 
> Anthony, 
> 
> They are all working correctly except for the extension letter. 
> 
> fact finder appointment letter  (YES)
> accepted fact finder report (YES)
> accepted and deemed accepted fact finder report (YES)
> deemed accepted fact finder report (YES)
> rejection of fact-finding report (YES)
> fact finder appointment serb (discrectionary) (Yes)
> fact finder appointment serb (discretionary) (Duplicate)
> fact finder extension (NO)

**Comment by anthonyperk** [comment]
May have Found the issue:

Code is looking at the 'description' field of the database, the description for the letter in the DB does not match the description in the code (I know that upper/lower case doesnt matter).

DB:  Fact Finder Appointment Extension
Code:  fact finder extension

**Comment by altrdgenetics** [comment]
![screenshot 70](https://user-images.githubusercontent.com/8847344/50060564-7eaa7080-0163-11e9-8971-916c63974a32.png)
