### ISSUE TITLE
(PLACEHOLDER) - (EMAIL) - Breakout Email Threads via ARGs

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#698]
Email Server needs to be broken up so that way the application can be run in multiple ways. There are 4 methods found in the MainClass.java within the emailThreads() method as follows:

```java
//Incoming
incomingEmails();

//Outgoing
calInvites();
notificationEmails();
outgoingEmail();
```

To break them out we can put if statements in place to determine which methods will be run with which command-line arguments.

**Proposal 1:**

NONE PROVIDED (runs all of them)
-all (runs all of them)
-incoming (only runs top method)
-outgoing (only runs bottom method)

pros: we maintain and deliver a single executable 
cons: Justin has to remember the command-line arguments, more on our end to setup work

**Proposal 2:**

We set a global variable and let it handle everything within the code, following Proposal 1 variations.

pros: less work, no need for Justin to remember command-line arguments when starting the application
cons: multiple deliverable executables we need to maintain distribute when sending updated applications.

**Proposal 3:**

We just comment out the lines for each variation and handle it all within that method, following Proposal 1 variations.

pros: basically no upfront work, no need for Justin to remember command-line arguments when starting the application
cons: multiple deliverable executables we need to maintain distribute when sending updated applications.

**Comment by altrdgenetics** [comment]
When doing the Java jar emailserver.jar to run it from commandline append one of these if you wanna get picky on what it will do, doing nothing will be = to the all command.

"-incoming"
"-outgoing"
"-all"

**Comment by anthonyperk** [comment]
Testing results

```
C:\Users\XLNsystems\Documents\NetBeansProjects\SERBEmailControl\target>java -jar test.jar -incoming

Starting SERB Email Server - v2.8.8

Incoming Email Process: true
Outgoing Email Process: false


C:\Users\XLNsystems\Documents\NetBeansProjects\SERBEmailControl\target>java -jar test.jar -outgoing

Starting SERB Email Server - v2.8.8

Incoming Email Process: false
Outgoing Email Process: true
```


However the application did NOT actually start.  I suspect that's on purpose.

**Comment by altrdgenetics** [comment]
good catch... if you look I forgot to comment out the main thread from running. if you pull down the updated version now it should be fine. 

I had commented it out so i could quickly run it without having it get hung on trying to connect to the email server

**Comment by anthonyperk** [comment]
From my testing, this ticket can be closed.
