### ISSUE TITLE
(R3-090 Part 3: The Reconing) - (CMDS) - Invalid Character warning diolog when backspacing/delete in a Group Number

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#700]
When updating a group number within the Case Information tab, if you hit backspace or the delete key to clear a character from the Group Number field, it DOES delete the character, but also brings up a Warning dialog about an invalid character.  This happens regardless of if there is a valid group number already or if there is a blank group number

![image](https://user-images.githubusercontent.com/24595073/55487254-c3b3bf00-55fb-11e9-93c0-8584efc22ad9.png)

**Comment by altrdgenetics** [comment]
This should be good to go. I added the proper regex character for the non standard keys.
