### ISSUE TITLE
(R3-115) - (Postal) - Outgoing Letter Queue Performance when Sending Postal

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#702]
Is there anything that can be done to increase the speed at which outgoing letters that are sent via postal are created? Where are these files being temporarily stored/generated? Is all the document creation/saving happening on the G: drive or are they created on a local machine and then moved to the G: drive?

The postal generation process takes a really long time to complete, even if there are only a few postal items in the queue. Anything that could be done to improve the speed and performance of this process is appreciated. This has been an ongoing performance issue that I would like to revisit.

**Comment by anthonyperk** [comment]
Creation with attachments?
McAfee scanning the documents?
G Drive slowness?

Ask justin if this is the generation of the letters or printing items out of the letter queue

PDF Box update?

Try on Justin's 7 machine?

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> When in the process are the users seeing this slowness (creation or letter queue process)?

While talking with Andrew, he mentioned the fact that McAfee scans any file being opened.  Since the creation of these letters requires quite a few opens and save-then-open of files (depending on if there are attachments or extras being tacked onto the end of the file).  If you still have access to a Windows 7 machine (like one of the ones that XLN teamviewer’s into), you can test to see if generation is any faster.  Since the Windows 7 machine’s used Norton instead of McAfee, better speeds on the 7 machines could point more to McAfee.

The files are ultimately being saved to the G drive, so possible G: Drive slow transfer speeds may also be an issue.


EMAIL FROM JUSTIN

> Thank you for the confirmation and extra info. We are in the process of removing McAfee from our network environment. OIT is going to be utilizing Windows Defender along with Tanium as the replacement to McAfee. OIT confirmed that this new environment would provide them with added benefits and less CPU utilization. The replacement should be completed prior to June 30. 

The letter generation process seems to be OK. The performance issue occurs in the letter queue when it converts from MS Word to PDF (When the send button is pressed). We only notice it for the Postal items. The emailed items are processed via the email program. 

Which computer is performing this covert to PDf action? It is the SQL Server correct?  
The PC in my office runs the email server, I can see it processing the emailed items and converting them to PDF.

**Comment by altrdgenetics** [comment]
Ok so when the send button is hit, a few things happen...

Postal Insert generation (SQL call + Jasper generation)
Convert DOCX -> PDF
Combine PDF files
Create activities & copy file to respective case folders on G:\
Clean Temp files
Present collated File to user.

All of this happens on the individual end users machines. Also the more attachments they have and the more cases it is getting docketed to the longer it will take,.. naturally. 

As far as speeding things up I am not sure what we could do except for maybe update PDFBox and see what that gets us. It is a few versions old now but on the same major version so I doubt there will be any breaking changes but I have not looked into it. Other than that it is left up to file transfers pulling the files from the G drive and then copying the final product back as well as A/V software.

**Comment by anthonyperk** [comment]
Call with Justin
----------------------
Justin is going to try and get OIT to disable his McAfee so that he can test the creation of postal outs.  This will at least eliminate OR point to McAfee being the culprit.

Justin says that ORG and Civitas have the biggest issues, as it could take 15-20 minutes to create one of the large postal out's (as it has to combine 50ish pages together).  Hopefully its McAfee's fault, but then we dont know what Windows Defender and Tanium will do with the files.

**Comment by altrdgenetics** [comment]
50ish pages or files and what is the size of the final document?

There could be a lot of overhead regardless and testing doing a manual combine as far as how long it takes would be another test to see how it fairs.

**Comment by altrdgenetics** [comment]
No additional complaints ticket closed due to inactivity
