### ISSUE TITLE
(R3-116) - (CMDS) - Adding latest Inventory Status line activity comment to the ISL

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#703]
CMDS Inventory Status Line

I am inquiring to see if it is possible for the Inventory Status Line to be updated so that it appends the action & comment field together, so that if I add a comment it would be included in the Inventory Status Line? The ultimate goal is to include both items on the two reports on the following pages.

![image](https://user-images.githubusercontent.com/24595073/55833902-a5136380-5ae6-11e9-8f1f-f6311b9ca183.png)

We would like the additional information in the inventory status line to show on the following reports:
Docket Inventory by Case Number
Docket Inventory – by Hearing Date

![image](https://user-images.githubusercontent.com/24595073/55833914-ac3a7180-5ae6-11e9-8597-9039b45d69fe.png)

![image](https://user-images.githubusercontent.com/24595073/55833919-ae9ccb80-5ae6-11e9-8b18-0cb92017f993.png)

**Comment by anthonyperk** [comment]
Call with Justin
------------------------
Justin is REALLY looking for the combination of the ISL and the Comment for the REPORTS, and doesnt seem to care about that combination for the actual application.

**Comment by anthonyperk** [comment]
It looks like some ISL's already have the comment added to the end, and some do not

**Comment by anthonyperk** [comment]
EMAIL TO JUSTIN

> The ISL field within the application is just a set size depending on the size of the application window itself.  Any text that ‘spills over’ if its too long for the field is just not shown.  So theoretically if the ISL + Comment is longer than the field, there may be part of the comment that is cut off from showing on the ISL on the top right hand side.  You had said that the comments are not very long anyway, so there’s a good chance that everything would fit, especially with the application window maximized.
>  
> Depending on how Andrew and I implement the addition of the comment to the ISL, there wouldn’t be any change to the reports other than making sure that the ISL field in the reports are correctly configured to expand depending on the size of the combined ISL and comment.
>  
> Also to answer your question, Yes the text that may be cut off from the ISL within the application WILL BE SHOWN in the report, no worries about the report also being cut off as long as I make the ISL field in the report a variable length and it doesn’t push the remaining fields out of place.


EMAIL FROM JUSTIN

> This is what we are seeking. Please proceed.

**Comment by altrdgenetics** [comment]
CMDSDetailedActivityDialog 
ln.459 
is missing the comment addition, all of the incoming docking has it.

**Comment by altrdgenetics** [comment]
Two options available here; need clarification on which route SERB wants to go:

1) it appears that adding the comment to the ISL from the detailed activity panel is the only thing that is missing, they may just be having issue with this one aspect and it is technically a bug ticket and not an actual enhancement. (est: 1hr labor)

2) they want us to dynamically update the ISL with both information which would require new DB field or some finagling of the logic to get it to translate properly as we would be going from a string only version to an keyID based loading of the information. (est: lots hr labor)

What is their actual problem here, sounds like solutioning without understanding the issue.

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

> The Activity Description and newly added comment appear appended together on the activity tab (Activity entries). The Inventory Status Line should only be updated when the “Update Inventory Status Line button is pressed.  If a user clicks update, adds a comment, then presses update inventory status line, I would want the changes saved, then update the ISL. 
> 
> If only the save button is pressed, changes would be saved and screen would close, with no changes to ISL.

**Comment by anthonyperk** [comment]
ISL field in the application is updated with the new comment.

Both reports changed to allow the expansion of the ISL field.
