### ISSUE TITLE
(R3-091 part 2) - (CMDS) - Consolidation of Group Postal Out files into 1 file and activity entry

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#704]
Consolidation of Postal Out files for the 15-20 additional hours of work. 

Currently, when you generate a postal out:

   1) user chooses the letter to generate, choose the recipients 
   2) add any additional attachments/documents 
   3) the ‘creation’ activity entry is created for that case, and x amount of documents are sent to the letter queue 
    4) when the user brings up the letter queue and selects the postal to be sent out (printed and mailed), the PDF is created for each recipient with the Cover page, original document, any attachments combined into 1 PDF/file to be printed. 

The Request is that CMDS wants the PDF that is created and then printed to be a combination of all pages to all recipients (in the selected case) into 1 document and in 1 activity entry INSTEAD OF 3 separate documents and associated activity entries.  This consolidated file and corresponding activity entry will be copied to the cases that have been selected in the new Group Number Panel implemented in R3-091

Example:   3 recipients of a Board Order document

------------------------------------------------------
Current: 
1 document containing
Cover letter/mailing insert to recipient A with name and address
Board Order document
Any extra attachments from the case/questionnaires/etc.
Within 1 activity entry, recipients name amended to the end of the activity entry

1 document containing
Cover letter/mailing insert to recipient B with name and address
Board Order document
Any extra attachments from the case/questionnaires/etc.
Within 1 activity entry, recipients name amended to the end of the activity entry

1 document containing
Cover letter/mailing insert to recipient C with name and address
Board Order document
Any extra attachments from the case/questionnaires/etc.
Within 1 activity entry, recipients name amended to the end of the activity entry

----------------------------------------------------------------
Proposed: 
1 document containing
Cover letter/mailing insert to recipient A with name and address
Board Order document
Any extra attachments from the case/questionnaires/etc.
Cover letter/mailing insert to recipient B with name and address
Board Order document
Any extra attachments from the case/questionnaires/etc.
Cover letter/mailing insert to recipient C with name and address
Board Order document
Any extra attachments from the case/questionnaires/etc.
Within 1 activity entry.  This consolidated file and corresponding activity entry will be copied to the cases that have been selected in the new Group Number Panel implemented in R3-091.

**Comment by anthonyperk** [comment]
Process ran correctly:

Case: 2018-OSH-04-0086

- Created BO Settlement
- Postal selected to All Parties
- Application asked if I wanted to file this to all in the group (and it did file it to the group)
- Word Document Was created
- Combined document was placed in Letter Queue
- Once 'sent' from letter queue, the PDF appeared on the screen, all parties got a copy and a letter insert
- 'Creation' activity was added into the case I had created the document from
- All cases in group got the combined parties PDF

"Issues" I found:

- In the combined PDF, the recipients were 'out of order', but they were all contained within the PDF (this is more of an observation than anything)
- After sending/printing out the combined PDF from the letter queue, the case I was on did NOT show the "OUT - BO Settlement" combined PDF activity in the original case UNTIL I went to another case and then back to the original case OR to another tab within the original case then back to the activity tab.  I am sure that the panel needs to be refreshed for the combined PDF activity to show up, maybe this can be added easily?

**Comment by altrdgenetics** [comment]
1. it was in order for alphabetical but was actually reversed (Z->A) I have flipped it to A->Z but since the name field is a single line it will be keyed off the first name first letter. Nothing can be done beyond that.

1. added it in for the updating the activity window

**Comment by anthonyperk** [comment]
2 issues when testing:

1) Error when creating the postal out:

> Exception in thread "Thread-5" java.lang.NoClassDefFoundError: parker/serb/sql/PostalOutBulk
> 	at parker.serb.letterGeneration.LetterGenerationPanel.insertPostalOutBulk(LetterGenerationPanel.java:967)
> 	at parker.serb.letterGeneration.LetterGenerationPanel.generateLetter(LetterGenerationPanel.java:621)
> 	at parker.serb.letterGeneration.LetterGenerationPanel.lambda$processThread$3(LetterGenerationPanel.java:1209)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.ClassNotFoundException: parker.serb.sql.PostalOutBulk
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)


Documents Button -> Choose Document -> Generate Letter Panel -> Chose the recipients (I chose all 5 as postal, as I have been doing) -> Generate Button Clicked - > Multi-Case Docketing Panel -> Accept Button Clicked.

The document was STILL generated, but the application crashed.  The second time I tried it, it worked fine.

2) Activity Tab did NOT update until I went to another tab and came back to the Activity tab (did not change section tab or case)
