### ISSUE TITLE
(R3-117) - (Hearings) - Add permissions for Adding/Removing Hearings

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#705]
SERB & CMDS Hearings

Add/Remove Hearing Permissions

We are seeking to add the following security permissions to the SERB Hearings and CMDS Hearings tabs. Please grey out the “Add Hearing” and “Delete” button from both the SERB Hearings Tab and CMDS Hearings Tab, unless the user has a checkmark in user maintenance for the new option Add/Remove Hearing. See third image below as an example. We seek to grey out these two buttons for all users except Erin and Diana.

CMDS > Hearings Tab
![image](https://user-images.githubusercontent.com/24595073/56668641-df036e80-667d-11e9-9095-6a98d82c89b6.png)

SERB Hearings > Hearings Tab
![image](https://user-images.githubusercontent.com/24595073/56668650-e4f94f80-667d-11e9-803e-45e095ba247e.png)

SMDS User Maintenance
Add the new item below. It would control if the two buttons in the two sections above are enabled or greyed out. Buttons should be greyed out unless they have the checkmark below.
![image](https://user-images.githubusercontent.com/24595073/56668668-ec205d80-667d-11e9-810b-264c303561f0.png)

**Comment by altrdgenetics** [comment]
Since this is related to security concerns for the hearings is this looking to be exclusive or in combination with their respective section.

For example a user that only has CMDS Worker permissions are they able to add/remove HEARING section hearings or vise versa?


logic would be

```
if (global.section == hearings && hearingsWorkers && addRemoveHearings ){
    ....
}
```

or 

```
if (global.section == hearings &&  addRemoveHearings ){
    ....
}
```

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

> 
> Please make the following requirements
> CMDS Section
> CMDS Worker Checkbox + Add/Remove Hearing Checkbox
> 
> SERB Hearings Section
> Hearings Worker + Add/Remove Hearing Checkbox

**Comment by altrdgenetics** [comment]
CODE FOR DB TABLE ADD:

`ALTER TABLE Users
  ADD HearingAdmin BIT NOT NULL
  CONSTRAINT D_Users_HearingAdmin DEFAULT 0
  WITH VALUES`

**Comment by altrdgenetics** [comment]
I have not run the code on SERB side it seems like I can not connect to the DB anymore from the W7 machine and I forget the domain/user combo for the W10 machine. 

The SQL command from above is all that is needed. I have checked and verified the code and even though it is on an existing table the SQL calls have ALL been constructed in a way that it will have no effect on the current application.

**Comment by anthonyperk** [comment]
SMDS Hearings
-------------------------------------
- Delete button still shown AND works even if you are not a hearing worker + Add/Rem. Hearings

CMDS Hearings
-------------------------------------
- Add Hearing button still active when **NOT** CMDS Worker Checkbox + Add/Remove Hearing Checkbox, should be grayed out.

**Comment by anthonyperk** [comment]
SMDS Hearings issue still exists: Delete button is shown and is active even if you are not a hearing worker + Add/Rem. Hearings
