### ISSUE TITLE
(R3-119) - (SMDS) - Update application dependancies

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#715]
Update SMDS Application Dependencies

It looks like many of the dependencies within the SMDS application and the Email Server application are not up-to-date. Please update/integrate the following dependencies: 
PDFbox
JasperReports plugin
Maven
Sunfire
Office Integration
Jacob
Slack plugin 

Also, are we on the latest version of Java? My PC has version 8 update 144.

**Comment by altrdgenetics** [comment]
Email Server took the updates without issue. The application will take a little more work. Looks like there was a lot of updates and I cant find any of the updated information for WebLAF

**Comment by parkjohnston** [comment]
just a quick input on this: it has to be custom built from another server at this point. 

If you need help let me know!

**Comment by altrdgenetics** [comment]
They have been updating it on MVN but that Russian dude has not updated his site. it is a Major version release and it break some of the objects like the calendar. Need to track down to see if it is worth the upgrade/hassle to figure out.

**Comment by anthonyperk** [comment]
Is it worth Updating from Java 8.144?  Justin has to touch all of the machines soon anyway for another software update and wants to know if he should/needs to update java at all
