### ISSUE TITLE
(R3-123) - (SMDS) - Application Code Optimization

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#719]
SERB would like XLN to comb through the code and optimize any method(s) that can be rewritten, combine/merge any code that is able to be combined, change/update the applications to work more smoothly. This is in an attempt to shrink down the size of the applications in order for them to launch quicker.

**Comment by anthonyperk** [comment]
SERB requests that we don't spend too much time on this.  Justin is in the mind of 'if it aint broke, dont fix it', and is worried that the code optimization may actually break something instead.

If you know of a method that can easily be rewritten without major risk, then go for it.  Otherwise, leave it be.

**Comment by altrdgenetics** [comment]
same as R3-122 #718 duplicate
