### ISSUE TITLE
(R3-124) - (NONE) - Cyber Security Training & Outlook Functionality

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#720]
SERB would like XLN to conduct cyber security training for the SERB/PBR staff. This can include best practices for both at work and at home. SERB suggests that XLN hit on the following:
• How to spot email fishing
• Password/passphrase complexity
• Training on outlook functionality (junk folder use, filtering, etc.)
• Information on phone call phishing
• Issues with automatically saving passwords on websites
• Phone call scams
o Paying someone via Gift Cards – iTunes, Green Money Cards, pre-paid cards
o Credit Card Companies
o IRS
o Helping a stranded ‘family member’

**Comment by altrdgenetics** [comment]
Here ya go... Show them videos from This due messing with scammers

https://www.youtube.com/channel/UCm22FAXZMw1BaWeFszZxUKw

**Comment by anthonyperk** [comment]
Not wanted.  Closed
