### ISSUE TITLE
(R3-2020-002) - (SMDS) - Outgoing Calendar Invite issues

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#728]
Outlook “not supported calendar message.ics” error when sending hearing calendar invites.
We checked PC Logs, Event Logs, Tanium/Defender Logs on Sending PC (Email Application) and receiving PC (my PC). We do not see any messages regarding events or blocks that could be causing this issue. Outlook to Outlook calendar invites are not having any issues. It is only SMDS outgoing calendar invites that are the problem. After having no luck I also updated Outlook on my PC to the latest version 1902 and tested again. No luck. The issue is also present when the email is viewed via the webmail browser view.

OIT is questioning if a Microsoft update somewhere in the environment (possibly even the exchange server) may be the cause of this issue and if the JAVA application code may need to be updated to resolve the issue.

My guess is between the JAVA application and Exchange Server where the exchange server receives and encodes the message to be sent to the applications.

![image](https://user-images.githubusercontent.com/24595073/61138022-af058380-a494-11e9-976d-a67b60dd7b2a.png)

**Comment by anthonyperk** [comment]
Justin asked OIT about this, their response:

> Justin – so after you sent us the calendar invite I attempted to open up the invite in my outlook at received the same error. Upon research of the error I found out it was a change in how outlook receives and reads the format in ICS which causes it to fail to import. Currently the ICS is sent a METHOD:REQUEST this leads to the failure of the import and the display of the error, upon changing it to METHOD:PUBLISH I was able to open the file without error. I am attaching the new test.ics that I made the below change on that allowed me to send the calendar invite, please verify you are able to open and send without error as I was able to test on my machine and Ians and it was successful. A change in the Java script will more than likely need to be made to reflect the change to METHOD:PUBLISH as currently it is being sent as a request.
> 
> ![image](https://user-images.githubusercontent.com/24595073/61138141-df4d2200-a494-11e9-8b13-c99d8c102af5.png)
> 
> ![image](https://user-images.githubusercontent.com/24595073/61138145-e2481280-a494-11e9-9c4f-69c0ab8276ac.png)
> 

I am looking at the code now to see if this 'easy fix' can be implemented

**Comment by anthonyperk** [comment]
Looks like the iCAL code is in SendEmailCalInvite.java in the SERBEmailControl project.

Change lines 146 and 196 from 

+ "METHOD:REQUEST\n"

to

+ "METHOD:PUBLISH\n"

is whats being suggested as a fix

**Comment by anthonyperk** [comment]
Changed in the EmailServer application and pushed out

**Comment by anthonyperk** [comment]
According to Justin, the fix didn't work:

> Anthony, 
> 
> We are still getting the Not Supported Calendar Message. Attached is an example for reference. 
> 
> We are rolling back the update at 12pm


![image](https://user-images.githubusercontent.com/24595073/62063318-9e753d00-b1f8-11e9-8ec4-ec22af49abad.png)

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

> When I submit the ICAL to the validator on the following website. I still get the warning below. I am not sure if this has anything to do with why we are getting the error but I wanted to point it out again. 
> 
> https://icalendar.org/validator.html
> 
> ![image](https://user-images.githubusercontent.com/24595073/62068059-4263e600-b203-11e9-833c-9af4b7067c5c.png)
>

**Comment by altrdgenetics** [comment]
Can I get the sample iCal file to test with... and based on what it is below... there is a warning but nothing else. hard to troubleshoot that one. without an actual file, and makes me wonder if OIT has blocked external ICS files for some reason.

Also with the bad ical file can I get one that SERB generated and sent internally. So that way we can compare a ICS generated from the application and one from outlook itself

**Comment by altrdgenetics** [comment]
https://stackoverflow.com/questions/41890741/java-ics-not-read-in-outlook

**Comment by altrdgenetics** [comment]
I updated the application. Could pull it down and test with on their local machine for when Justin is up for it, but again.... cant connect to the W10 machine to access it.

**Comment by anthonyperk** [comment]
According to Justin's email from 9/6/2019, the fixes that Andrew implemented worked:

> Outbound:
> Using the outbound command… The calendar invite feature is now working; as shown below. I also sent some test outgoing messages. The outbound messages work and the calendar invite works again.
> 
> ![image](https://user-images.githubusercontent.com/24595073/64643216-e84b6880-d3dd-11e9-9756-08da72651957.png)
