### ISSUE TITLE
(R3-2020-003) - (EMAIL) - Email Server erroring at REP section

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#730]
Email Docketing Error.
When we run the program using the In Command. It skips over the REP section. It also provided an error for the MED section. Once it ran the first time the black box closed.

Then I ran it from my office using the All command. I get the error below for the REP section.

I think it is kicking an error whenever it finds a message to docket.

![image](https://user-images.githubusercontent.com/24595073/62052681-f35a8880-b1e3-11e9-93b3-b6b3d89b6c85.png)

**Comment by altrdgenetics** [comment]
Do you remember how to breakpoint and debug?

This is something that there is an issue with the email being read in and the HTML parser barfing on it.

Need access to the REP email box and also need to debug to see which email it gets to, They have had this problem before in the past Justin had always just shuffled emails around and then did a manual import on the offending one.

**Comment by anthonyperk** [comment]
According to the email from Justin on 9/6/2019, this is still an issue AND from the looks of it, errored on MED during his testing

> Inbound: 
> I sent a test email to all the inboxes. Then attempted to import. I received the following error. I removed the test file to let it skip to the next box… I still got the following error.  I tested using inbound and all command.
> 
> ![image](https://user-images.githubusercontent.com/24595073/64643298-17fa7080-d3de-11e9-8cc1-73609951ecfa.png)

**Comment by altrdgenetics** [comment]
Question going through all of these inboxes it says to "all of the inboxes" so the same email passed on every single section EXCEPT for "MED"? or that was the first one it failed on? 

because I can see the first email is "testdocket" which gets no email. The reason I ask is because if this issue is the same for each of the mail boxes it changes my opinion... plus can we get a copy of that email he sent to those boxes. as an .eml attachment file. It makes me think that if there is an issue with ALL boxes then I should roll back one of the dependencies that I updated.

**Comment by altrdgenetics** [comment]
We will reverse the Jericho Dependency to start and see where that gets us. The reference PR for rolling back these changes can be found here

https://github.com/CurrentlyNotSet/SERBEmailControl/pull/8/files

**Comment by anthonyperk** [comment]
UPDATE FROM JUSTIN

According to Justin, the new Email Server jar worked great with the old and newest version of SMDS.  He has deployed both today (Monday 11/4/19)

**Comment by anthonyperk** [comment]
Reopening due to error from Justin.  After restarting the email server, the error didnt come back.

![image](https://user-images.githubusercontent.com/24595073/68142575-b64a1480-fefd-11e9-86c4-c0f3f3183d69.png)

**Comment by anthonyperk** [comment]
This error has not come back, and Justin asks for the ticket to be closed
