### ISSUE TITLE
(R3-2020-005) - (Letter Queue) - Mary signature on MED Outgoing Letters

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#732]
When Mary sends her letters in the MED section only, we need to add a line break into the code as noted with the red line below. I discovered all her letters have been sent with the signature as shown below.

![image](https://user-images.githubusercontent.com/24595073/62711404-febd6900-b9c6-11e9-95f3-5cce6eb6632e.png)

**Comment by anthonyperk** [comment]
After searching through the code, I don't think this is hard coded.\

May just be on her outlook

**Comment by anthonyperk** [comment]
I'm guessing this would be in the StringUtilities.java generateDepartmentAddressBlock() line 323

**Comment by altrdgenetics** [comment]
incorrect, it is in....

parker.serb.letterGeneration.LetterGenerationLanel.java

insertEmail() : 838

**Comment by altrdgenetics** [comment]
As long as she has a job title it will give a new line, it is all of the same newlines that we use for everything else. 

The user can edit the email body before sending the message so I do not know if she is doing it on her own or if there is an issue with her "jobTitle" in the Users database.

All of the SERB machines are showing as offline so I can not check that.

**Comment by anthonyperk** [comment]
Perhaps the job title was too long and/or the "-" screwed something up.

Email from Justin

> Anthony, 
> 
> I confirmed the issue with Mary’s signature was the “-“. We have resolved the issue by changing her signature to the following:
> 
> Mary E. Laurent
> Bureau of Mediation
> State Employment Relations Board
> 65 East State Street, 12th Floor
> Columbus, OH 43215-4213
> Telephone: (614) 644-8716
