### ISSUE TITLE
2020-007 - Creation of CSV file for Board Orders in CMDSWebUpdater

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#735]
I am seeking a CMDS data export to a text file (CSV) feature (added to the existing website updater program) with the data arranged in the file as indicated below. This file will be manually uploaded to the PBR website to populate the tables. The PDF files will automatically upload to the appropriate location on a different server. 

The file would be created each evening and placed in the following location: G:\CMDS\CMDSWeb\
Row 1 – Show Hide the field on website (Static – doesn’t change)
Row 2 – Column Headers (Static – doesn’t change)
Row 3+ data (1 row per case)

- Only extracting cases with Board Order Date Issued
- 5 year lookback, cases added and drop off daily.

Excel view of .csv file
![image](https://user-images.githubusercontent.com/24595073/71375780-5bdc4480-258d-11ea-9ed7-785f2f9f59af.png)

Same info in notepad view.
![image](https://user-images.githubusercontent.com/24595073/71375795-6991ca00-258d-11ea-8934-c0c143bd7603.png)

Column Details:
Case Number – Case Number of the Case (19-ABL-02-0020) View – Will always be the word “View” URL – This is the custom URL path to the location of the PDF file stored on the other server.

- We believe the URL will be as follows: 

- https://spbr.ohio.gov/static/PDF/Reports/2019/19-ABL-02-0020.pdf
- https://spbr.ohio.gov/static/PDF/Reports/[CaseYear]/[CaseNumber].pdf

Appellant –
Appellee –
Open Date –
Board Order Date –
Result – Note: We may want the code spelled out in the export file.

![image](https://user-images.githubusercontent.com/24595073/71375849-934af100-258d-11ea-85d4-462328913db5.png)

![image](https://user-images.githubusercontent.com/24595073/71375852-9645e180-258d-11ea-918b-0a0e46a8cd9c.png)

**Comment by anthonyperk** [comment]
SQL Statement:

`SELECT (RIGHT (CMDSCase.caseYear, 2) + '-' + CMDSCase.caseType + '-' + CMDSCase.caseMonth + '-' + CMDSCase.caseNumber) AS CMDSCaseNumber,
('View') AS "View",
('https://spbr.ohio.gov/static/PDF/Reports/' + CMDSCase.caseYear + '/' + (RIGHT (CMDSCase.caseYear, 2) + '-' + CMDSCase.caseType + '-' + CMDSCase.caseMonth + '-' + CMDSCase.caseNumber) + '.pdf') AS URL,
(SELECT CaseParty.firstName + ' ' + CaseParty.lastName FROM CaseParty WHERE (CaseParty.caseYear = CMDSCase.caseYear AND CaseParty.caseType = CMDSCase.caseType AND CaseParty.caseMonth = CMDSCase.caseMonth AND CaseParty.caseNumber = CMDSCase.caseNumber) AND CaseParty.caseRelation = 'Appellant' ) AS AppellantName,
((SELECT TOP 1 CASE WHEN CaseParty.companyName IS NOT NULL THEN CaseParty.companyName ELSE (CaseParty.firstName + ' ' + CaseParty.lastName) END  FROM CaseParty WHERE (CaseParty.caseYear = CMDSCase.caseYear AND CaseParty.caseType = CMDSCase.caseType AND CaseParty.caseMonth = CMDSCase.caseMonth AND CaseParty.caseNumber = CMDSCase.caseNumber) AND CaseParty.caseRelation = 'Appellee' )) AS AppelleeName,
CONVERT(VARCHAR, CMDSCase.openDate, 101) AS OpenDate,
CONVERT(VARCHAR, CMDSCase.mailedBO, 101) AS BoardOrderDate,
CMDSCase.result AS Result


FROM CMDSCase


WHERE
CMDSCase.mailedBO >= DATEADD(yy, -5, GETDATE())

ORDER BY
CMDSCase.caseYear ASC, CMDSCase.caseMonth ASC, CMDSCase.caseNumber ASC`

**Comment by altrdgenetics** [comment]
2 Questions:

1. What should the output CSV filename be called? Static name with a file replace or a unique date driven name for history.

2. For the SQL statement would it be better suited that we create an SQL "view" table in their database instead. We have some information hard-coded such as the BASE_URL path. This way any URL changes that need to be performed will not require a redeploy of the application as all of the information is gathered before hand.

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

"Anthony, 

I would like it to overwrite the static file each time it is run. We will know it was updated by the creation date. "

**Comment by anthonyperk** [comment]
As for the view idea, Views can not contain an 'order by' statement in their queries so I dont think that is going to work

**Comment by anthonyperk** [comment]
UPDATED VERSION OF THE TICKET.  CHANGES IN **BOLD**

XLN Team, Please quote and make recommendation on solution. I am seeking a CMDS data export to a text file (CSV) feature (added to the existing website updater program) with the data arranged in the file as indicated below. This file will be manually uploaded to the PBR website to populate the tables. The PDF files will automatically upload to the appropriate location on a different server. The file would be created each evening and placed in the following location: 
**(Update) I:\Board_Orders_SPBR_Website_Upload_Folder\SPBR_Board_Orders_Web_Listing.csv**

Row 1 – Show Hide the field on website (Static – doesn’t change)
Row 2 – Column Headers (Static – doesn’t change)
Row 3+ data (1 row per case)

Only extracting cases with Board Order Date Issued. 5 year lookback, cases added and drop off daily.

**(UPDATE) Below is an updated version of what should be in the export file with proper URL.**
S,S,H,S,S,H,S,S
Case Number,View,URL,Appellant,Appellee,Open Date,Board Order Date,Result
2000-ABL-01-0016,View,https://spbr.ohio.gov/static/PDF/Board_Orders/2000/00-ABL-01-0016.pdf,Dominic D'Emilio,University of Toledo,01/11/00,10/27/17,RET
2000-FRN-02-0070,View,https://spbr.ohio.gov/static/PDF/Board_Orders/2000/00-FRN-02-0070.pdf,Michael Phillians,Ohio State University,02/18/00,10/27/17,AAA


Column Details:
Case Number – Case Number of the Case (19-ABL-02-0020) View – Will always be the word “View” URL – This is the custom URL path to the location of the PDF file stored on the other server.
We believe the URL will be as follows: 
**https://spbr.ohio.gov/static/PDF/Board_Orders**/2019/19-ABL-02-0020.pdf
**https://spbr.ohio.gov/static/PDF/Board_Orders**/[CaseYear]/[CaseNumber].pdf
Appellant – Appellee – Open Date – Board Order Date – Result – Note: We may want the code spelled out in the export file.

[SPBR Board Orders Web Listing.txt](https://github.com/CurrentlyNotSet/SERB/files/4109501/SPBR.Board.Orders.Web.Listing.txt)

**Comment by anthonyperk** [comment]
I have changed my query to reflect the changes to the URL.  Please note that I have attached a sample of what they are currently using now at the bottom of the updated ticket post above.

**Comment by altrdgenetics** [comment]
MR can be found here, all done.

https://github.com/CurrentlyNotSet/SERBEmailControl/pull/12

**Comment by anthonyperk** [comment]
UPDATE FROM JUSTIN

> Anthony, 
> 
> Upon Review of the exported file I found the following three tweaks, plus changing the location as previously discussed.  
> 
> Line 1 –The fifth “S” should be an “H”.
> S,S,H,S,S,**H**,S,S, 
> S,S,H,S,S,S,S,S, 
> 
> Line 2 – Should be Board Order Date
> Case Number,View,URL,Appellant,Appellee,Open Date,**Board Order Date,**Result,
> Case Number,View,URL,Appellant,Appellee,Open Date,Board Order,Result,
> 
> Line 3 – end of file  - Remove the “s” in spbr
> 2000-ABL-01-0016,View,https://**pbr**.ohio.gov/static/PDF/Board_Orders/2000/00-ABL-01-0016.pdf,Dominic D'Emilio,University of Toledo,2000-01-11,2017-10-27,RET,
> 2000-ABL-01-0016,View,https://spbr.ohio.gov/static/PDF/Board_Orders/2000/00-ABL-01-0016.pdf,Dominic D'Emilio,University of Toledo,2000-01-11,2017-10-27,RET,

**Comment by anthonyperk** [comment]
I updated the items above, and commited the changes to Sourcetree

**Comment by anthonyperk** [comment]
For Reference: 
Total Anthony time is 2 hours
Total Andrew Time is XXXX

**Comment by anthonyperk** [comment]
Justin confirms that this is working as intended.

Closing ticket
