### ISSUE TITLE
2020-012 - CMDS - Bookmark math Update

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#741]
CMDS Section

Please make an update on the PBR Appeal notice.

In CMDS, I generate an Appeal Notice and then enter the length of the hearing in minutes. The number of minutes is automatically multiplied by $1.50 to determine the transcript costs which appears on the Appeal Notice via bookmark. I need to update the rate to $3.00 per minute. This change was approved by the SPBR Board.

![image](https://user-images.githubusercontent.com/24595073/78905697-63e0c700-7a4c-11ea-97cf-658300edbba1.png)

![image](https://user-images.githubusercontent.com/24595073/78905717-693e1180-7a4c-11ea-983c-703cd9d47395.png)

**Comment by anthonyperk** [comment]
I suspect that all that is needed is a change from 1.5 to 3 on line 538 of processCMDSBookmarks.java

`double precost = Double.parseDouble(cleanedNumber) * 1.5;`
-to-
'double precost = Double.parseDouble(cleanedNumber) * 3;'

**Comment by altrdgenetics** [comment]
https://github.com/CurrentlyNotSet/SERB/blob/develop/src/main/java/parker/serb/bookmarkProcessing/processCMDSbookmarks.java#L538
