### ISSUE TITLE
2021-002 - CMDS - Adding additional column in CMDS Case Search windows

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#749]
CMDS Section

Add the Case Group Number field to the Case Search/Lookup screen so that grouped cases are easy to find. Currently, grouped cases only get documents added to them during creation process, so user must enter each grouped case to update status line, enter info into notes, and populate hearing tab. Since grouped cases could be linked /unlinked at any time, and could contain different parties, we do not wish to change the existing configuration of how grouped cases work. Just to add the ability to find grouped cases quicker.

![image](https://user-images.githubusercontent.com/24595073/91584877-493abc00-e921-11ea-8464-c13819f5e71a.png)

**Comment by altrdgenetics** [comment]
This work would amount to 8 hrs of labor.

The work involves adding a database field to the CMDS Search Table

Creating a script and front loading the information to that new field

updating the SQL call to update that field when necessary

Add to UI and search query for CMDS Case Search

**Comment by anthonyperk** [comment]
A little more detail from Justin.

>Sorry for delayed response. Inserting a new column in the far right column will be fine for the group number. Adjusting the widths of the other columns will be fine to make it fit in the existing window. 
>
![image](https://user-images.githubusercontent.com/24595073/93386041-1d7e6800-f835-11ea-9dff-4018d2fee48e.png)

**Comment by altrdgenetics** [comment]
I can insert the column where-ever they want. We have a little bit of play room with the Case Number, Open Date, and ALJ since those are pretty standard char lengths. The appellant columns are also probably pretty standard as well

**Comment by altrdgenetics** [comment]
I have been able to concoct an SQL update script for this once the extra field is added to the database. No need to run an extra bit of code or anything. This will grab and copy the information over. Running it on the local XLN DB it took 500ms to complete.

New Field:
`SERB.CMDSCaseSearch.groupNumber`  set this to `VARCHAR(15)`

Update Database Script:
```sql
UPDATE 
	CMDSCaseSearch 
SET 
	CMDSCaseSearch.groupNumber = CMDSCase.groupNumber
FROM   
	CMDSCaseSearch
INNER JOIN CMDSCase
	  ON  CMDSCase.caseYear   = CMDSCaseSearch.caseYear
     AND CMDSCase.caseType   = CMDSCaseSearch.caseType
     AND CMDSCase.caseMonth  = CMDSCaseSearch.caseMonth
     AND CMDSCase.caseNumber = CMDSCaseSearch.caseNumber
WHERE 
	CMDSCase.groupNumber IS NOT NULL
 ````

**Comment by anthonyperk** [comment]
Tested and Merged

**Comment by anthonyperk** [comment]
Tested on SERB machine
