### ISSUE TITLE
2021-010  -  ULP Processing Time and Reporting

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#757]
Below are my notes about the ULP Board Management Report. I wanted to bring the “processing time” stat to your attention as I have found some discrepancies in its accuracy. I have not talked with Robert about this yet as I want to find out from you if you agree this is worth pursuing/fixing in the future. I know Craig keeps an eye on this stat so I want to make sure we are providing an accurate metric. I have several other proposed enhancement tickets to discuss in the future and I want to find out if this should be another one to add to the list.

While researching some stats and creating queries for the Annual Report, I stumbled across the Board Management Report for the ULP section. I have been working with Judy to understand how the Processing Time is calculated. I have confirmed that the processing time listed is coded to list the amount of days that the investigator is assigned to actively work on the case (investigator actual processing time). The math formula to get this stat is the difference between the board meeting date and the investigator assigned date (not the file date).

My issue with the calculation is that the assigned date (and turn in date) is updated each time the board directs the investigator to work on the case a second or third time (this doesn’t happen frequently; Pre-D is an example). When this happens SMDS is unable to provide or track an accurate stat since the original assign and turn in dates are replaced with new dates. Image 1 below shows the difference in the processing time depending on if the file date or assigned date is used. The investigators are very proud of their processing time stats; which are fewer than when the file date stat is used. Judy keeps two stats… one for investigator processing time, and a second for entire duration, this report does not match either of Judy’s stats.

There are three possible solutions (if you agree this is worth fixing) for this problem and the best solution depends on what metrics or tracking is most important. I think both stats are of value, but only if they are
accurate. The number of days the case is open (since file date) stat would be most important (to me), followed by how long it took the investigator to work the case (investigator processing time).

1) Investigator Processing Time (Clock Starts when assigned, stops when report turned in & if sent to Pre-D, Restarts when assigned back to investigator)(Note: From report turn in time to board meeting date would not be counted, but currently on this report it is counted). This is the stat most valued by investigators. Implement an enhancement and update the report coding so that this report (and others) can calculate accurately the number of days the investigator is working on the case. Judy currently tracks this manually in an excel spreadsheet.
a. I think adding four more date fields to SMDS would solve this problem. Then math can calculate the difference between all these start/stop dates to come up with a total number of days the investigator works on the case
i. Assign Date (existing)
ii. Turn-In Date (existing)
iii. Assign Date 2
iv. Turn-In Date 2
v. Assign Date 3
vi. Turn-In Date 3

2) How Many Days Since Case was Filed Change the Board Management report to focus on the file date instead of the assigned date. The file date does not change and it would provide the correct number of days the case has been open.
a. No new fields needed, just update on the report template.

3) Update the Report to show Both stats.

Image 1 – The first two listed are examples where the case was assigned back to the investigator a second time
![image](https://user-images.githubusercontent.com/24595073/108229395-c7785e00-710d-11eb-8029-43defd3bfcad.png)

Cases 2018-ULP-11-0190 and 0194 are exceptions for the 7-18-19 Board meeting. They were originally assigned on 11-27-18, went before the board as a withdrawal on 3-14-19, the cases were not actually withdrawn – so on 7-18-19, the board remanded the charges back to the investigator so they got “reassigned” to the investigator on 7-26-19 and on 1-30-20, the board found probable cause.

This type of scenario is rare. This is why Judy keeps the actual processing time manually.

**Comment by altrdgenetics** [comment]
Discussion needed to understand the full scope of the problem

**Comment by anthonyperk** [comment]
SERB would like the second and third set of Assign Date/Turn-In Dates to be added to SMDS, and the reports to be tweaked.  I can handle the reports, but the new dates need to be added to the application.

**Comment by anthonyperk** [comment]
QUESTION TO JUSTIN

> 2021-010:  So all you are looking for is the addition of 4 date fields in the ULP section (2 sets of Assign Date/Turn-In Date) and a couple updates to the Board management Report? 


ANSWER FROM JUSTIN

> This is correct. It needs to be able to count the start and end date for the mgmt. report. If end date is blank the count should use report run date to calculate number of days to date. 
> Not sure if adding a few date fields is easier or if putting it in a table to add an unlimited number of start/end dates is easier/better.

**Comment by anthonyperk** [comment]
UPDATE FROM JUSTIN

Please update the Board Management Report by adding one new column called Investigator Processing Time. The value equals the number of days between assigned date and turn in date.
Also, change the date selector to a date range.
![image](https://user-images.githubusercontent.com/24595073/132408110-ca32c287-c009-4b6f-8d94-72aaca8417f8.png)

At the bottom of the report should be an average investigator processing time.

![image](https://user-images.githubusercontent.com/24595073/132408127-f7210220-8515-4574-9a4a-12634f0aad66.png)

![image](https://user-images.githubusercontent.com/24595073/132408139-3d577f9f-0e99-4abe-b6f1-8e8171d2df73.png)

**Comment by anthonyperk** [comment]
Quote: 1.25 hours

**Comment by altrdgenetics** [comment]
![Screenshot (272)](https://user-images.githubusercontent.com/8847344/147796968-e11de3db-e27c-4cf4-a636-ee620dc3ca5d.png)

**Comment by anthonyperk** [comment]
Install 6.8.1, compile report and test

**Comment by anthonyperk** [comment]
This seems to have been resolved by installing Jaspersoft Studio 6.8.0 and recompiling the report.
