### ISSUE TITLE
2021-011  -  CSC Valid and Letter send (their words)

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#758]
The Civil Service Commission Tab sends out the annual reminder letters even if the Valid Checkmark is not marked.

I found in the database that there are two CSC Active Columns.

Active =Yes/No

Valid = Yes/No

When creating a new CSC the Active = Yes does not get populated.

When sending letters, it should use the Valid = Yes

I believe we can condense this to only have one Active/Valid prompt.

The Active=Yes/No cannot be accessed via the data entry screen

![image](https://user-images.githubusercontent.com/24595073/108229787-1d4d0600-710e-11eb-8e9e-f9cdd2c9bd2c.png)

**Comment by anthonyperk** [comment]
Anthony: Add a flow to the letter generation

**Comment by anthonyperk** [comment]
Civil Service Tab > All Letters > “Annual Report – 60 day Notice” letter & “Annual Report – Past Due Notice” Letter

**Comment by altrdgenetics** [comment]
As we both know the active field is to hide from the users and we can't condense the two fields in the database. I have added the extra piece in the WHERE clause for loading the files which has rectified the issue with invalid CSCs being populated in the list.

**Comment by anthonyperk** [comment]
During testing, I found that if a new CSC was added within the application, the 'active' field was not populated with a 1/True (left as NULL).  This will need to be fixed.

**Comment by anthonyperk** [comment]
Will be changing the database during the release

**Comment by anthonyperk** [comment]
Database changed on SERB site (had to go into SQL Server Management Studio on the server to do this change as HeidiSQL gave errors).  Tested through the application.
