### ISSUE TITLE
2021-012  -  CSC  -  Add 3 Date Fields

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#759]
Please add the following three date fields to the CSC Information Tab. Under the Activities Last Filed Date Field.

![image](https://user-images.githubusercontent.com/24595073/108230834-2b4f5680-710f-11eb-8ac7-4505d11ed3ab.png)

If possible during the docketing screen… add a prompt during docketing that if a specified activity entry is selected a box will pop up asking if user wants to update a corresponding date field.

Examples:
AR (Annual Report) = Activities Last Filed Date
ORD (Ordinance) = Ordinance Last Filed Date
RULES (Rules) = Rules Last Filed Date
CHA (Charter) = Charter Last Filed Date

**Comment by altrdgenetics** [comment]
Confirmation on which docket panels this is needed for? (email, scan, media)

**Comment by anthonyperk** [comment]
All three

Docketing Tab > CSC Section > Type = Email, Scan, & Media

**Comment by altrdgenetics** [comment]
New Database Fields that Need to be Created with the Datatype of `DATE`

`ordinanceLastFiled`
`rulesLastFiled`
`charterLastFiled`

**Comment by anthonyperk** [comment]
Tested and Merged

**Comment by anthonyperk** [comment]
Will have Justin test since its production data
