### ISSUE TITLE
2021-018  -  ORG  -  File not found error when file does exist

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#770]
ORG Section:
I am troubleshooting why we received a file not found error for the following file. It appears the filename
does not match the activity entry.

![image](https://user-images.githubusercontent.com/24595073/122074304-189c1400-cdc7-11eb-8509-2d699d2177b7.png)

**Comment by anthonyperk** [comment]
Justin also requests that there be a check for irregularities in the file path.  Not sure how feasible that is

**Comment by altrdgenetics** [comment]
I request a "flow" to recreate this issue.

**Comment by altrdgenetics** [comment]
Nevermind... I no longer request a flow. It appears that there are illegal characters within the filename that is generated. How would Justin like these changed for compliance with filesystem namespacing?

It also would be possible to potentially check one by one for each of the ones provided in the screenshot and compare the activity table with the shorthand to see how it compares. And also look for the comma in the database. Could do a mass replace on those filenames as well. 

![Screenshot (96)](https://user-images.githubusercontent.com/8847344/122503158-f3292900-cfc5-11eb-89f9-0016306104d0.png)

**Comment by anthonyperk** [comment]
QUESTION TO JUSTIN

>2021-018:  Does ‘hard copy’ mean it was scanned into the system rather than an email into the system?  Does this happen for all AR,_FS documents or just some of them?

ANSWER FROM JUSTIN

>Hard copy means scanned, I found both emailed and scanned examples.  There is not a code that ends in AR,_FS in the document type screen. So I do not know why the _ is getting added. There are a bunch of “AR, FS” codes that work fine. But the document type saved to G: is not AR, FS.

**Comment by altrdgenetics** [comment]
Quote: 1.5hr

> Since Justin is fixing the ones already in the system then there is much less work that we need to worry about. Spending more time looking into it I think it actually occurring on the activity details screen. But I will just remove the replace on the spots found and that should fix it going forward.

**Comment by altrdgenetics** [comment]
Another issue was found and resolved when testing this.

ORG case was using file related stuff for CSC during the docketing process causing a hidden null pointer exception. This also prevented the User from docketing if they used a TYPE found in the CSC playbook, as an example AR for annual report.

A window would show up and it would attempt to update the CSC number and one may not be found. This has been rectified and no additional popups will show up for ORG.

**Comment by anthonyperk** [comment]
Confirmed that the file, when docketed, no longer has an underscore between AR,  and   FS.
