### ISSUE TITLE
2021-020  -  MED  -  New Tab in MED Section

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#774]
MED Section

Please add the following enhancement to the Mediation Section.

Add a new tab called Mediation. This tab design is a mirror of the Mediation Tab in the REP section.

![image](https://user-images.githubusercontent.com/24595073/130634781-f2eacb7e-2695-4f2d-a7a9-7341989c8db4.png)

**The Type Field** would include: 
CBA Mediation (Default)
Strike Mediation
Other Mediation

**Mediator field** would include the following:
List of State and FMCS Mediators 
Default to the State or FMCS Mediator listed on the Status tab (if populated)
If status tab not populated use Mediator Appointed (Strike Tab)

**Outcome drop down** includes:
Settled 
Not Settled 
Rescheduled 
Canceled 
Ongoing

**Report:**
We would also need to be able to run a report showing those mediations and the outcomes (settled, not settled, etc.) for a date range. Include text from the MED Notes Tab. Grouped by Mediator.

**Comment by altrdgenetics** [comment]
Quote: 10hr 


Work As Described:
> Add New Tab to section Root Panel
> Add New Table To Database
> Add/Remove Mediation windows

**Comment by altrdgenetics** [comment]
Create Code:

```
CREATE TABLE "MEDMediation" (
	"id" BIGINT IDENTITY(1,1) PRIMARY KEY,
	"caseYear" VARCHAR(4) NOT NULL,
	"caseType" VARCHAR(3) NOT NULL,
	"caseMonth" VARCHAR(2) NOT NULL,
	"caseNumber" VARCHAR(4) NOT NULL,
	"mediationEntryDate" DATE NULL DEFAULT NULL,
	"mediationDate" DATETIME NULL DEFAULT NULL,
	"mediationType" VARCHAR(100) NULL DEFAULT NULL,
	"mediatorID" VARCHAR(5) NULL DEFAULT NULL,
	"mediationOutcome" VARCHAR(100) NULL DEFAULT NULL,
);
```

**Comment by anthonyperk** [comment]
Issues:

1) New Mediation Window -> Type Drop down:  The 'blank' entry is at the bottom instead of the top
2) New Mediation Window -> Outcome Drop down:  The 'blank' entry is at the bottom instead of the top

**Comment by anthonyperk** [comment]
Report is live and waiting for Admin panel addition and table creation

**Comment by altrdgenetics** [comment]
Updated

**Comment by altrdgenetics** [comment]
Updated the order of the drop downs

**Comment by anthonyperk** [comment]
"Type" dropdown is fixed, "Outcome" dropdown is not
