### ISSUE TITLE
2021-021  -  ULP  -  New tab for ULP

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#775]
ULP Section

Please add the following enhancement to the ULP Section.

Add a new tab called Mediation. This tab design is a mirror of the Mediation Tab in the REP section.

![image](https://user-images.githubusercontent.com/24595073/130635330-a3ee1576-d7fc-4616-86f5-4f0b7aed3446.png)

**The Type Field** would include: 
Voluntary Mediation 

**Mediator field** would include the following: 
The same list as in the Mediator Assigned drop down on the status tab. Default to the Mediator Selected on the Status Tab.

**Outcome drop down** includes: 
Settled
Not Settled 
Rescheduled 
Canceled 
Ongoing

**Report:**
We would also need to be able to run a report showing those mediations and the outcomes (settled, not settled, etc.) for a date range. Include text from the ULP Notes Tab. Grouped by Mediator.

**Comment by altrdgenetics** [comment]
Quote: 10hr 


Work As Described:
> Add New Tab to section Root Panel
> Add New Table To Database
> Add/Remove Mediation windows

**Comment by altrdgenetics** [comment]
Create Code for the Database Table

```
CREATE TABLE "ULPMediation" (
	"id" BIGINT NOT NULL,
	"caseYear" VARCHAR(4) NOT NULL,
	"caseType" VARCHAR(3) NOT NULL,
	"caseMonth" VARCHAR(2) NOT NULL,
	"caseNumber" VARCHAR(4) NOT NULL,
	"mediationEntryDate" DATE NULL DEFAULT NULL,
	"mediationDate" DATETIME NULL DEFAULT NULL,
	"mediationType" VARCHAR(100) NULL DEFAULT NULL,
	"mediatorID" VARCHAR(5) NULL DEFAULT NULL,
	"mediationOutcome" VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY ("id")
)
;
```

**Comment by anthonyperk** [comment]
When trying to pull this feature, I only get the 'ULPUpdateMediationDialog.java' file and not the rest of the necessary files.  When I try to checkout the commit that has all of the file, I get a warning about SourceTree making a detached head, so I cancel out of that.

**Comment by anthonyperk** [comment]
Issues:

1) New Mediation Window -> Type Drop down:  The 'blank' entry is at the bottom instead of the top
2) New Mediation Window -> Outcome Drop down:  The 'blank' entry is at the bottom instead of the top

**Comment by anthonyperk** [comment]
Report is live and waiting for Admin panel addition and table creation

**Comment by altrdgenetics** [comment]
updated the order of the dropdowns

**Comment by anthonyperk** [comment]
"Type" dropdown is fixed, "Outcome" dropdown is not

**Comment by anthonyperk** [comment]
Confirmed as working
