### ISSUE TITLE
2021-022  -  REP  -  Changes to Mediation tab in REP

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#776]
REP Section

The Rep Section already has the Mediation Tab.

![image](https://user-images.githubusercontent.com/24595073/130635663-6ae6f724-9226-4099-ab1c-2ae334472bf2.png)

**Outcome drop down** includes: 
Add Ongoing 

**Report:**
Tweak the existing Mediation report showing the REP mediations and the outcomes (settled, not settled, etc.) for a date range. Include text from the REP Notes Tab. Grouped by Mediator.

**Comment by altrdgenetics** [comment]
Quote: 0.25hr

Work As Described:

> Add another field in the dropdown, hardcoded
> NOTE: this only covers the UI side, not the report side

**Comment by altrdgenetics** [comment]
I merged this one in order to work in the other ones

**Comment by anthonyperk** [comment]
Report is tweeked and live
