### ISSUE TITLE
2021-023  -  MED  -  MED Records Retention

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#787]
1) Please add the following “Appealed” Checkbox to the Mediation Status Tab. This is needed to exclude MED cases from the Records Retention Purge process.

![image](https://user-images.githubusercontent.com/24595073/151572486-5e09643f-46ed-4203-bffc-cabc2ac26c7f.png)

2) Update the Record Retention Select Statement to exclude all activity entries that have the “Appealed” checkmark marked. The existing select statement should be reviewed. Please send it to us to verify.

**Comment by altrdgenetics** [comment]
Can we get a confirmation on the record retention requirements. The existing one has a bunch of "Catches" to it. I want to ensure we got it correct and are not accidentally including/omitting something we shouldn't.

Link to Statement:

https://github.com/CurrentlyNotSet/SERB/blob/37e40d41124f162a37f29ee8a61647b0ad6fc9b9/src/main/java/parker/serb/sql/PurgedActivity.java#L348

**Comment by anthonyperk** [comment]
EMAIL FROM JUSTIN

The addition of the one line in 2021-023 is perfect. 

                AND MEDCase.appealed = 0

**Comment by altrdgenetics** [comment]
the PR has been updated

**Comment by anthonyperk** [comment]
Error is gone

**Comment by anthonyperk** [comment]
Further testing reveals that the Appealed check mark box does not update.  Furthermore, adding a bit to the 'appealed' column in the database manually results in the entire row zeroing out

**Comment by anthonyperk** [comment]
Probably my fault for not testing fully

**Comment by altrdgenetics** [comment]
flipped the logic. PR is here

https://github.com/CurrentlyNotSet/SERB/pull/815

**Comment by anthonyperk** [comment]
Merged and deployed
