### ISSUE TITLE
2021-024  -  Admin  -  Non-Active parties still showing up when trying to add new parties to a case

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#788]
Party Information Lookup Screen

1) Non-Active parties shown below are still showing up when trying to add new parties to a case.

![image](https://user-images.githubusercontent.com/24595073/151572706-452b5d05-f2f2-4261-be60-edd65c443e7e.png)

![image](https://user-images.githubusercontent.com/24595073/151572729-852b56ec-7934-4f7b-a541-999db05982e6.png)

Note: We are trying to remove duplicate entries. In this example a lawyer who has been at three different law firms.

**Comment by altrdgenetics** [comment]
Quote: 0.5hr

> Fix the party search to show active only
