### ISSUE TITLE
2021-025  -  PBR Web Update  -  Tweak to knock cases off website sooner

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#789]
Email From Anthony regarding current code.

It looks like the webupdater and webhistory looks for cases where the case year is greater than 5 years from the current year:

`WHERE (CMDSCase.caseYear > YEAR(GETDATE()) - 5)`

The BoardOrdersWebUpdater looks for the MailedBoardOrder Date greater than 5 years from the current year

`CMDSCase.mailedBO >= DATEADD(yy, -5, GETDATE())`

Add the following exclusion:
Remove from website list 1 year after [closedate].

**Comment by anthonyperk** [comment]
Is this for both the webhistory AND BoardOrders?

**Comment by anthonyperk** [comment]
This request is ONLY FOR webhistory.  Show all cases until 1 year after CMDSCase.CloseDate.

**Comment by altrdgenetics** [comment]
QUOTE: 0.25hrs

> Swapping out 5 with 1 for WebHistory Only

**Comment by altrdgenetics** [comment]
ok soooo this is more complicated than just adjusting time.

Are they are looking to show all cases where case is open or BO is within a year?

**Comment by anthonyperk** [comment]
I wrote up a whole reply before I understood what you were asking.  I will quote 5 to be on the safe side

**Comment by anthonyperk** [comment]
This has not been confirmed yet, just keeping records:

```
String sql = "SELECT "
                    + "RIGHT(Activity.CaseYear, 2) AS caseYear, "
                    + "LEFT(Activity.CaseMonth, 2) AS caseMonth, "
                    + "Activity.CaseNumber, "
                    + "LEFT(Activity.caseType, 3) AS caseType, "
                    + "CONVERT(char(10), Activity.date,126) as date, "
                    + "LEFT((" + subSQL + "), 39) AS Appellant, "
                    + "CMDSCase.closeDate, "
                    + "LEFT(Activity.action + ' ' + ISNULL(Activity.comment,''), 54) AS action "
                    + "FROM "
                    + "Activity INNER JOIN CaseType ON "
                    + "Activity.caseType = CaseType.caseType "
                    + "Activity INNER JOIN CMDSCase ON "
                    + "Activity.caseYear = CMDSCase.caseYear AND "
                    + "Activity.caseType = CMDSCase.caseType AND "
                    + "Activity.caseMonth = CMDSCase.caseMonth AND "
                    + "Activity.caseNumber = CMDSCase.caseNumber "
                    + "WHERE "
                    + "((Activity.action NOT LIKE '%CREATED ON%' "
                    + "AND Activity.action NOT LIKE '%Generated%' "
                    //+ "AND Activity.action NOT LIKE '%Case was Filed and Started%' " <-- removed at JB request R3-009
                    + "AND Activity.action NOT LIKE 'Added %' "
                    + "AND Activity.action NOT LIKE 'Set %' "
                    + "AND Activity.action NOT LIKE 'Changed %' "
                    + "AND Activity.action NOT LIKE 'Ebody %' "
                    + "AND Activity.action NOT LIKE 'Removed %' "
                    + "AND Activity.type != 'I' "
                    + "AND Activity.type != 'L' "
                    + "AND Activity.type != 'U' "
                    + "AND Activity.type != 'W') "
                    + "OR (Activity.type = 'A'   AND Activity.action LIKE '%initial case preparation%') "
                    + "OR (Activity.type = 'Z'   AND Activity.action LIKE '%initial case preparation%') "
                    + "OR (Activity.type = 'E'   AND Activity.action LIKE '%Procedural Order & Questionnaire Mailed%') "
                    + "OR (Activity.type = 'O'   AND Activity.action LIKE '%Procedural Order & Questionnaire Mailed%') "
                    + "OR (Activity.type = 'Z'   AND Activity.action LIKE '%Pre Hearing Scheduled%') "
                    + "OR (Activity.type = 'Z'   AND Activity.action LIKE '%Record Hearing Scheduled%') "
                    + "OR (Activity.type = 'E'   AND Activity.action LIKE '%Procedural Order Mailed%') "
                    + "OR (Activity.type = 'Z'   AND Activity.action LIKE '%Status Conference Scheduled%') "
                    + "OR (Activity.type = 'Z'   AND Activity.action LIKE '%Notice Of Appeal Filed%') "
                    + "OR (Activity.type = 'A'   AND Activity.action LIKE '%Notice of Appearance%') "
                    + "OR (Activity.type = 'E'   AND Activity.action LIKE '%Procedural Order Mailed%') "
                    + "OR (Activity.type = 'A'   AND Activity.action LIKE '%Notice of Withdrawal Of Counsel%') "
                    + "OR (Activity.type = 'Z'   AND Activity.action LIKE '%Miscellaneous Witness And Documents List%')"
                    + "OR (Activity.type IS NULL AND Activity.action LIKE '%Case was Filed and Started%')) "
                    + "AND (Activity.caseYear > YEAR(GETDATE()) - 5) "
                    + "AND Activity.active = 1 "
                    + "AND CaseType.section = 'CMDS' "
                    + "AND (CMDSCase.closeDate > (dateadd(year, -1, GETDATE())) OR CMDSCase.closeDate IS NULL) "
                    + "ORDER BY Activity.caseyear, Activity.caseNumber";
```

**Comment by anthonyperk** [comment]
I am assuming we will also need to update WebCase since WebCase and WebHistory go hand in hand.  If so:

`String sql = "SELECT"
                    + " CMDSCase.CaseYear,"
                    + " CMDSCase.caseNumber,"
                    + " CMDSCase.casemonth,"
                    + " CMDSCase.casetype,"
                    + " Users.initials AS ALJ,"
                    + " CMDSCase.groupNumber"
                    + " FROM CMDSCase "
                    + " LEFT JOIN Users ON"
                    + " CMDSCase.aljID = Users.id"
                    + " WHERE WHERE (CMDSCase.closeDate > (dateadd(year, -1, GETDATE())) OR CMDSCase.closeDate IS NULL) "
                    + " ORDER BY CMDSCase.caseyear, CMDSCase.caseNumber";`

**Comment by altrdgenetics** [comment]
PR can be found here

https://github.com/CurrentlyNotSet/SERBEmailControl/pull/17

**Comment by anthonyperk** [comment]
Justin gets this error when the WebUpdate runs:

Jul 15, 2022 10:03:35 PM com.sql.WebHistory getWebHistoryList
SEVERE: null
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'Activity'.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:297)
        at com.sql.WebHistory.getWebHistoryList(WebHistory.java:92)
        at com.CMDSWebUpdater.CMDSwebUpdater.processWebHistoryList(CMDSwebUpdater.java:164)
        at com.MainClass$dailyCMDSWebupdater.run(MainClass.java:132)
        at java.util.TimerThread.mainLoop(Unknown Source)
        at java.util.TimerThread.run(Unknown Source)

**Comment by anthonyperk** [comment]
After looking at the query again, the FROM portion of the select statement will need to be rewritten as:

                    + "FROM "
                    + "Activity " 
                    + "INNER JOIN CaseType ON "
                    + "Activity.caseType = CaseType.caseType "
                    + "INNER JOIN CMDSCase ON "
                    + "Activity.caseYear = CMDSCase.caseYear AND "
                    + "Activity.caseType = CMDSCase.caseType AND "
                    + "Activity.caseMonth = CMDSCase.caseMonth AND "
                    + "Activity.caseNumber = CMDSCase.caseNumber "

**Comment by altrdgenetics** [comment]
PR for this can be found here

https://github.com/CurrentlyNotSet/SERBEmailControl/pull/18

**Comment by anthonyperk** [comment]
Merged and Deployed
