### ISSUE TITLE
Fact Finder Selection due date auto-fill

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#79]
MED -> Fact Finder Tab:  When the user picks a selection date in the fact finder tab, the selection due date should be auto filled to 7 days (which includes weekends).  This functionality DOES exist in their current system.

ORIGINAL REQUEST
------------------------------
On the MED > Fact Finder Tab. Please have the Selection Due Date for panels 1 and 2 auto fill when the selection date is populated. The math should be 7 days (includes weekends). The user should be able to edit the selection due date and change if the date falls on a holiday.

**Comment by parkjohnston** [comment]
@anthonyperk this is a mix of what they currently have/dont have.  The current system does NOT allow for them to change the auto generated date.  Should this be included?

**Comment by anthonyperk** [comment]
yes, please give it to them

**Comment by parkjohnston** [comment]
thanks for the follow up.

will be in the upcoming release
