### ISSUE TITLE
2021-027  -  SMDS  -  Add email address to sender’s contact block bookmark

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#791]
Letter Queue – Outbound Emails – Add email address to sender’s contact block bookmark (not MS word Templates).

Please add code to the system so that the letter senders email address will show in the outbound emails.

![image](https://user-images.githubusercontent.com/24595073/151573552-a228be22-5042-40ff-b524-87b8201ac9a1.png)

**Comment by altrdgenetics** [comment]
QUOTE: 1.0 hr

> Add Email to "signature block" to all outgoing email bodies
