### ISSUE TITLE
2022-001  -  Public Records  -  public records screen description column does not include the user comments.

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#792]
The public records screen description column does not include the user comments. Please update the code to append this important info.

In the case below the comment states to stricken the docs from the record, but this info does not show on the public records screen.

![image](https://user-images.githubusercontent.com/24595073/151573730-d8dab6b2-4963-4c48-a973-e838b1a2bfa0.png)

**Comment by anthonyperk** [comment]
How would they like this info displayed?  Amended to the description?  In its own column?  In its own box at the bottom of the screen?

**Comment by anthonyperk** [comment]
Please append to the existing description.

**Comment by altrdgenetics** [comment]
Quote: 0.5hrs

> Adding comment field to the description column with separation matching Activity table of SPACE

**Comment by anthonyperk** [comment]
During testing, the comment would not show up on the Public Records window.

![image](https://user-images.githubusercontent.com/24595073/171464594-8a87315a-bff4-4bc6-af43-2502b909bba3.png)

**Comment by altrdgenetics** [comment]
The PR is updated

**Comment by anthonyperk** [comment]
Comments are now showing in the Public Records window
