### ISSUE TITLE
2022-002  -  Public Records  -  Search for Representative Names

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#793]
The public records screen description column does not include the user comments. Please update the
code to append this important info.

On the Right Click > case number search feature, please add the ability to search by the Representative
names on the party tab for MED, REP, ULP, ORG, and Civil Service.

This would be helpful for a variety of reasons including mass email address changes, address changes,
etc. Currently a query needs to be run against the data in the backend to get this info.

**Comment by altrdgenetics** [comment]
second piece for searching most likely if it mirrors the following ticket it will be 8hr per section outlined

 2021-002 - CMDS - Adding additional column in CMDS Case Search windows #749

**Comment by anthonyperk** [comment]
First Part (Public Records):  - Sorry this is a carry over note from 2022-001

Second Part (Representative in Party Search  -  This part of the ticket is breaking concrete, may be 40+ hours):
- I thought this might be the case. I am inquiring with Erin, we may just want to create a report instead. The purpose is to find cases that a REP has for address and email address changes, etc.

**Comment by anthonyperk** [comment]
Ticket Revised

Please create a report for ticket 2022-002.

This report would be available in all SMDS/CMDS sections, pointing to the same report file. 

The cases would be sorted by case type first, then by case year, then by case number.
Since CMDS uses a variety of case types, the case numbers would not be cleanly grouped by section. 


Report Name: Party Search Report – All Case Types

Prompt:
Enter the following:
First Name = [Case Party.FirstName] ‘Matt%’  Add a wildcard so it finds both Matt and ‘Matthew’
Last Name = [CaseParty.LastName] ‘Baker’

Example query with correct sort. 
SELECT * FROM CaseParty WHERE lastname = 'baker' and firstname= 'matt' ORDER BY firstname, CaseType asc, caseyear desc, casenumber desc

Display the following fields on Report.

 
![image](https://user-images.githubusercontent.com/24595073/152602418-6125ac03-fa49-4e89-8304-f5bdf18e5b70.png)

**Comment by anthonyperk** [comment]
Quote: 3 hours

**Comment by anthonyperk** [comment]
Report completed.  I will need a parameter created to ask for a First and Last name

**Comment by altrdgenetics** [comment]
Dialog box is in the system now and available for selection in the admin panel. The choice is:

"First Name, Last Name"

**Comment by anthonyperk** [comment]
Further testing reveals that NULLs are passed to the report.  Testing with the other two string possibility (Charging Party, Charged Party) results in the same thing.  Wondering if the entire 'two string' method doesn't work at all.

**Comment by anthonyperk** [comment]
I am dumb
