### ISSUE TITLE
2022-004  -  ORG  -  require the Org Name field before allowing it to save

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#795]
When creating a new ORG.

Please require the Org Name field before allowing it to save. If this does not happen the ORG gets locked and I have to enter it in the backend to allow the Clerks office to access.

Also, please mark new ORGs as Valid by default.

![image](https://user-images.githubusercontent.com/24595073/154283216-2f013ca5-f7c0-49bb-b644-770e7daa2d9f.png)

**Comment by altrdgenetics** [comment]
1hr work.... PR ready and in queue, since SERB is in a rush

**Comment by anthonyperk** [comment]
Confirmed working
