### ISSUE TITLE
Two label changes in the Party Information Panel

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#80]
Party Information window -> View and Edit:  On the panel itself, SERB would like the label for Name Title to be changed to 'Prof. Designation' and Prof. Designation changed to 'Job Title'.  This needs to be done in 5 separate places according to Andrew.

*******THIS IS TO BE CHARGED FOR, KEEP TIME RECORD

**Comment by parkjohnston** [comment]
@anthonyperk should this be done now or wait?

**Comment by anthonyperk** [comment]
Allen asks to do it whenever you are bored to tears, just as long as you keep track of your time

**Comment by parkjohnston** [comment]
Only had to be updated in 3 places that I was able to find.

Started 8:15 am 1/14/17
Finished 8:30 am 1/14/17

**Comment by parkjohnston** [comment]
@anthonyperk 

To reiterate...do the text boxes need changes also or just changing the text?  

Changing just the text does not solve the initial ask, but that is what is asked above.  Dont want to mess it up and deliver just a text change without recording the actual columns.

**Comment by anthonyperk** [comment]
Only the labels need to be changed, the actual text boxes and DB dont need to be touched

**Comment by parkjohnston** [comment]
ok, just wanted to make sure!

Thanks

**Comment by parkjohnston** [comment]
Confirmed that we will need to change the text boxes as well, so that we are not putting trash data into the DB.

**Comment by parkjohnston** [comment]
Start 1/15/17 @ 8:30am
Finished 1/15/17 @ 9:00am

Total Time: 45 minutes
