### ISSUE TITLE
Total Number of Strike Days tweek

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#81]
In MED -> Strike Tab -> Total Number of Days text box:  The total number of days should include the first and last day in the count.  Example: Strike Began - 01/03/2017, Strike Ended - 01/06/2017, Total Number of Days should be 4, not 3.

NOTE: This was NOT how it was originally told to us by Justin

NOTE:  This will not be billable to SERB, but is for Parker

**Comment by parkjohnston** [comment]
32048491da58d1e91cb419319aa3d27d939bebe6
