### ISSUE TITLE
Null pointer exception while generating a letter

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#84]
Justin got this error when generating 'AC Filed By EEO - Letter to ER'

parker.serb.util.StringUtilities.buildFullName(StringUtilities.java:24)

![image](https://cloud.githubusercontent.com/assets/24595073/22121907/cbbf0492-de53-11e6-84bb-bf1984606297.png)

**Comment by altrdgenetics** [comment]
on joining name together there was not a null check to see if the string was filled, only checked for BLANK
