### ISSUE TITLE
File Names

### ISSUE THREAD

**Issue by parkjohnston** [CurrentlyNotSet/SERB#85]
Files created in the system are appearing to lack the shortened names that are in the current system.  

Looking the activity table shows that long file times are getting creating, reducing the desired obfuscation of the document, allowing back door usage.  Another concern is the longer file names with "," and such causing Windows file explore issues.

![screen shot 2017-01-22 at 10 38 41 am](https://cloud.githubusercontent.com/assets/3246562/22188957/56ee0a6e-e0e7-11e6-8bca-ea0fb24bc0bd.png)

**Comment by altrdgenetics** [comment]
added a stringLeft trim to the two filename lines to limit it to 50 characters of text plus  the timestamp in the beginning. There was already a check for "historyFilename" in the DB.
