### ISSUE TITLE
Header Bookmark "HeaderPersonnelBlock" not generating correctly

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#86]
When the letter templates populate, the “HeaderPersonnelBlock” does not populate correctly. It is missing names and the line breaks. Also, The address is not correct, and the phone and fax numbers are not formatted correctly.

![image](https://cloud.githubusercontent.com/assets/24595073/22252857/8e5d37ea-e21d-11e6-8331-a30513f455a6.png)

![image](https://cloud.githubusercontent.com/assets/24595073/22252861/91a9759e-e21d-11e6-98cd-3d11639ce6b9.png)

**Comment by altrdgenetics** [comment]
misplaced the new line and double processing phone numbers
