### ISSUE TITLE
CHDREPADDRESSBLOCK not generating correctly

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#87]
The CHDREPADDRESSBLOCK bookmark (Address block) is not formatting correctly. See example below. It is also not formatting the phone number correctly.  Please confirm the other address block bookmarks are also formatting correctly. 

![image](https://cloud.githubusercontent.com/assets/24595073/22252932/cca0bd06-e21d-11e6-9180-4ce69cca3af0.png)

**Comment by altrdgenetics** [comment]
misplaced the new line and double processing phone numbers
