### ISSUE TITLE
Dates between Strike begin and end should count the start date

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#88]
REP -> Elections Tab: The polling end date should be 14 calendar days after the polling start date, which INCLUDES the start date.  Ex: Start Date - 12/13/2016  End Date - 12/27/2016.  I would suspect that we can subtract 1 from our current formula.

**Comment by altrdgenetics** [comment]
This issue turned out to be not tracked properly and it had already been resolved on January 4th looking at this git-history (a62cb34). This issue comes from T004 ticket email. This changed had been preformed by Parker and is getting marked as completed.
