### ISSUE TITLE
CMDS Add History Entry Date not used for the Activity tab date

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#90]
CMDS -> Activity Tab -> Add Entry Button -> Add History Entry box:

The entry date selected on the Add History Entry box should populate the date field in the Activity table in the Activity Tab.  In CMDS, users may send mail in the past, and update the system later.

On Ticket T009

**Comment by parkjohnston** [comment]
Not sure this is how it is in the current system

**Comment by parkjohnston** [comment]
4c06851519b92e1cd24335b2016f72591a949c9a
