### ISSUE TITLE
Miscellaneous Letters dropdown missing from REP section

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#92]
**Ticket T011 - 1**

REP Tab -> Letters Button

Missing Miscellaneous Letters Drop Down. Please add it under the letters drop down. All of the misc. letters also need added to the drop down (SMDSDocuments Table -> type = Misc).

**Comment by altrdgenetics** [comment]
added in the dropdown beneath the agenda combobox. It is unknown how these files generate as i do not have them on my system. But the drop down works as intended and notifies me the document could not be located.
